/* Sault Newcomer Skills Survey 2026 questionnaire definition. */

const SKILLS = [
  ["critical_thinking", "Critical Thinking", ""],
  ["problem_solving", "Problem Solving", ""],
  ["systems_analysis", "Systems Analysis", ""],
  ["oral_comprehension", "Oral Communication: Oral Comprehension", ""],
  ["oral_expression", "Oral Communication: Oral Expression", ""],
  ["learning_strategies", "Learning and Strategies", ""],
  ["quality_control", "Quality Control Testing", ""],
  ["decision_making", "Decision Making", ""],
  ["writing", "Writing", ""],
];

const EMPLOYED_STATUSES = [
  "Self-employed",
  "Employed casual (less than 10 hours/week)",
  "Employed part-time (10–33 hours/week)",
  "Employed full-time (34+ hours/week)",
];

const NATURAL_SCIENCE_SECTORS = [
  "Natural and Applied Sciences and Related Occupations",
  "Natural and applied sciences and related occupations (e.g., Software Developer, Civil Engineer)",
];

const QUESTIONS = [
  {
    id: "consent",
    section: "Consent",
    type: "single",
    text: "Please confirm that you are at least 18 years of age and voluntarily agree to participate in this survey.",
    options: ["I agree", "I disagree"],
  },
  {
    id: "eligible",
    section: "Eligibility Check",
    type: "eligibility",
    text: "Did you move to Northern Ontario after December 2021 to live?",
    options: ["Yes", "No"],
  },
  {
    id: "moved_from",
    section: "Eligibility Check",
    type: "single",
    text: "Where have you moved from?",
    options: [
      "Other parts of Ontario",
      "Outside of Ontario but within Canada",
      "Outside of Canada with an immigration status",
      "Outside of Canada with non-immigration status",
    ],
  },
  {
    id: "province",
    section: "Eligibility Check",
    type: "select",
    text: "Please select the province you moved from",
    visible: (a) => a.moved_from === "Outside of Ontario but within Canada",
    options: [
      "Quebec",
      "British Columbia",
      "Alberta",
      "Manitoba",
      "Saskatchewan",
      "Nova Scotia",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Prince Edward Island",
      "Yukon",
      "Northwest Territories",
      "Nunavut",
    ],
  },
  {
    id: "gender",
    section: "Section A: Demographics",
    type: "single",
    text: "What is your gender?",
    options: ["Woman", "Man", "Non-binary person or other gender"],
  },
  {
    id: "age_group",
    section: "Section A: Demographics",
    type: "select",
    text: "What is your age group?",
    options: ["18–24", "25–34", "35–44", "45–54", "55–64", "65–74", "75–84", "85 or older"],
  },
  {
    id: "identity_groups",
    section: "Section A: Demographics",
    type: "multi",
    text: "Do you identify with any of the following groups? (Select all that apply)",
    options: [
      "Indigenous (First Nations, Métis, Inuit/Inuk)",
      "Visible minority (e.g., South Asian, Chinese, Black)",
      "Immigrant (permanent resident)",
      "Non-permanent resident (e.g., work permit, study permit, refugee claimant)",
      "None of the above (do not select any other options)",
    ],
    exclusiveOption: "None of the above (do not select any other options)",
  },
  {
    id: "non_permanent_category",
    section: "Section A: Demographics",
    type: "single",
    text: "Select non-permanent resident category",
    visible: (a) => (a.identity_groups || []).includes("Non-permanent resident (e.g., work permit, study permit, refugee claimant)"),
    options: [
      "Temporary Foreign Worker",
      "International Student",
      "Refugee Claimant",
      "Protected Person",
      "Temporary Resident Permit Holder",
      "Other",
    ],
  },
  {
    id: "recent_credential",
    section: "Section B: Education",
    type: "select",
    text: "What is the most recent educational credential you have completed?",
    options: [
      "Primary school",
      "High school diploma or equivalent",
      "Apprenticeship",
      "College certificate",
      "Diploma",
      "Advanced Diploma",
      "Undergraduate degree",
      "Post-graduate degree (e.g., Master's, PhD, MD)",
    ],
  },
  {
    id: "program_name",
    section: "Section B: Education",
    type: "textarea",
    text: "What is the FULL NAME of the program you completed for your most recent credential?",
    help: "Example: BA in Psychology, Project Management Certificate",
  },
  {
    id: "program_location",
    section: "Section B: Education",
    type: "single",
    text: "Where did you complete this program?",
    options: ["In Canada", "Outside Canada"],
  },
  {
    id: "institution_name",
    section: "Section B: Education",
    type: "textarea",
    text: "Name of the institution (e.g., University/College/School)",
  },
  {
    id: "program_completion_year",
    section: "Section B: Education",
    type: "select",
    text: "When did you complete this program?",
    options: [
      "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019",
      "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011",
      "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003",
      "2002", "2001", "2000", "Before 2000",
    ],
  },
  {
    id: "highest_education",
    section: "Section B: Education",
    type: "single",
    text: "Is this program your highest level of education?",
    options: ["Yes", "No"],
  },
  {
    id: "employed_before",
    section: "Section C: Employment",
    type: "single",
    text: "Were you employed before moving to Sault Ste. Marie?",
    options: ["Yes", "No"],
  },
  {
    id: "previous_job_title",
    section: "Section C: Employment",
    type: "textarea",
    text: "What was the title of your most recent job before moving here?",
    visible: (a) => a.employed_before === "Yes",
  },
  {
    id: "previous_job_duties",
    section: "Section C: Employment",
    type: "textarea",
    text: "What were your main duties in this job?",
    visible: (a) => a.employed_before === "Yes",
  },
  {
    id: "employment_status",
    section: "Section C: Employment",
    type: "single",
    text: "Which of the following best describes your current employment status?",
    options: [
      "Self-employed",
      "Employed casual (less than 10 hours/week)",
      "Employed part-time (10–33 hours/week)",
      "Employed full-time (34+ hours/week)",
      "Unemployed and not looking for work",
      "Unemployed and looking for work",
      "Social assistance recipient",
      "Unable to work / on disability",
      "Student or recent graduate",
      "Retired",
      "Homemaker / caregiver",
      "Prefer not to answer",
    ],
  },
  {
    id: "individual_income",
    section: "Section C: Employment",
    type: "select",
    text: "What was your total individual income in the past 12 months? (before tax and deductions)",
    options: [
      "No income",
      "Under $15,000",
      "$15,000 to $24,999",
      "$25,000 to $34,999",
      "$35,000 to $49,999",
      "$50,000 to $59,999",
      "$60,000 to $74,999",
      "$75,000 to $99,999",
      "$100,000 to $124,999",
      "$125,000 or more",
      "Prefer not to answer",
    ],
  },
  {
    id: "current_job_title",
    section: "Section C: Employment",
    type: "textarea",
    text: "What is the title of your current job?",
    visible: (a) => EMPLOYED_STATUSES.includes(a.employment_status),
  },
  {
    id: "occupation_sector",
    section: "Section C: Employment",
    type: "select",
    text: "Which sector best describes your occupation?",
    visible: (a) => EMPLOYED_STATUSES.includes(a.employment_status),
    options: [
      "Business, Finance and Administration",
      "Administrative occupations (e.g., Mayor, CEO)",
      "Business, finance and administration occupations (e.g., Accountant)",
      "Natural and Applied Sciences and Related Occupations",
      "Natural and applied sciences and related occupations (e.g., Software Developer, Civil Engineer)",
      "Health Occupations",
      "Health occupations (e.g., Nurse Practitioner)",
      "Occupations in Education, Law and Social, Community and Government Services",
      "Education, law and social services (e.g., Teacher, Social Worker)",
      "Art, Culture, Recreation and Sport",
      "Arts and recreation occupations (e.g., Graphic Designer, Photographer)",
      "Sales and Service Occupations",
      "Sales and service occupations (e.g., Sales Associate, Customer Service Representative)",
      "Trades, Transport and Equipment Operators",
      "Trades and transport occupations (e.g., Electrician, Truck Driver)",
      "Natural Resources, Agriculture and Production",
      "Natural resources and agriculture (e.g., General Farm Worker, Forestry Labourer)",
      "Manufacturing and Utilities",
      "Production worker / warehouse worker",
    ],
  },
  {
    id: "occupation_group",
    section: "Section C: Employment",
    type: "single",
    text: "Which occupation group best describes your work?",
    visible: (a) => NATURAL_SCIENCE_SECTORS.includes(a.occupation_sector),
    options: [
      "Specialized middle management – engineering and science",
      "Professional occupations in natural and applied sciences",
      "Technical occupations",
    ],
  },
  {
    id: "first_job_search_time",
    section: "Section C: Employment",
    type: "single",
    text: "How many months did it take you to find your first job after arriving?",
    visible: (a) => EMPLOYED_STATUSES.includes(a.employment_status),
    options: [
      "Less than 3 months",
      "3–6 months",
      "6–12 months",
      "More than 1 year",
      "More than 2 years",
      "More than 3 years",
    ],
  },
  {
    id: "job_search_help",
    section: "Section C: Employment",
    type: "multi",
    text: "What helped you the most in your job search?",
    visible: (a) => EMPLOYED_STATUSES.includes(a.employment_status),
    options: [
      "Personal connections",
      "Networking events",
      "Recruitment or employment agency",
      "Recognition of experience",
      "Training or certification",
      "Referral",
      "Social media",
      "Communication skills",
    ],
  },
  {
    id: "intended_job",
    section: "Section C: Employment",
    type: "single",
    text: "Is your current job the one you intended to do?",
    visible: (a) => EMPLOYED_STATUSES.includes(a.employment_status),
    options: ["Yes", "No"],
  },
  {
    id: "skills",
    section: "Section D: Skills",
    type: "rating",
    text: "How would you rate your level for each of the following skills?",
    help: "1 = Lowest, 2 = Low, 3 = Moderate, 4 = High, 5 = Highest",
    legend: ["1 · Lowest", "5 · Highest"],
    skills: SKILLS,
  },
  {
    id: "local_job_knowledge",
    section: "Section D: Skills",
    type: "single",
    text: "How would you rate your knowledge of local job opportunities?",
    options: ["Very low", "Low", "Moderate", "High", "Very high"],
  },
  {
    id: "local_training_knowledge",
    section: "Section D: Skills",
    type: "single",
    text: "How would you rate your knowledge of local training opportunities related to your intended job?",
    options: ["Very low", "Low", "Moderate", "High", "Very high"],
  },
  {
    id: "employment_barriers",
    section: "Section E: Barriers and Challenges",
    type: "multi",
    text: "What do you think about the main barriers for newcomers to find a job in Sault Ste. Marie? (Select all that apply)",
    options: [
      "Lack of Canadian experience",
      "Lack of jobs",
      "Language barriers",
      "Limited network",
      "Credentials not recognized",
      "Lack of job information",
      "Discrimination",
      "Transportation issues",
      "Childcare responsibilities",
      "Other",
    ],
  },
  {
    id: "helpful_support",
    section: "Section E: Barriers and Challenges",
    type: "multi",
    text: "What type of support would help newcomers most to improve their employment opportunities? (Select all that apply)",
    options: [
      "Credential recognition",
      "Training or certification",
      "Language training",
      "Resume/interview support",
      "Job matching",
      "Training matching",
      "Networking",
      "Mentorship",
      "Childcare support",
      "Local job market information",
      "Other",
    ],
  },
  {
    id: "application_challenges",
    section: "Section E: Barriers and Challenges",
    type: "multi",
    text: "What challenges have you experienced when applying for jobs in Sault Ste. Marie? (Select all that apply)",
    options: [
      "No interviews",
      "Resume not effective",
      "Finding jobs",
      "Long job search",
      "Lack of interview skills",
      "Online application difficulty",
      "No Canadian references",
      "Language barriers",
      "No difficulties",
      "Other",
    ],
  },
  {
    id: "accessed_support_services",
    section: "Section E: Barriers and Challenges",
    type: "single",
    text: "Have you tried to access any job search, training or employment support services?",
    options: ["Yes", "No"],
  },
  {
    id: "gift_card_draw",
    section: "Gift Card Draw",
    type: "single",
    text: "Do you want to participate in the gift card draw? (For prize purposes only)",
    options: ["Yes", "No"],
  },
];

const SECTIONS = [
  "Consent",
  "Eligibility Check",
  "Section A: Demographics",
  "Section B: Education",
  "Section C: Employment",
  "Section D: Skills",
  "Section E: Barriers and Challenges",
  "Gift Card Draw",
];

window.SURVEY = { QUESTIONS, SECTIONS, SKILLS };
