// DRAFT Arabic (ar) — ⚠ MACHINE-QUALITY DRAFT. Requires native-speaker review
// before release. RTL language — see the dir=rtl wiring in app.js.
module.exports = {
  q: {
    language: "اختر لغة للمتابعة",
    consent: "يرجى التأكيد بأن عمرك 18 عامًا على الأقل وأنك توافق طوعًا على المشاركة في هذا الاستطلاع.",
    eligible: "هل انتقلت إلى شمال أونتاريو للعيش بعد سبتمبر 2021؟",
    moved_from: "من أين انتقلت؟",
    province: "يرجى اختيار المقاطعة التي انتقلت منها",
    country_moved_from: "يرجى اختيار البلد الذي انتقلت منه",
    gender: "ما هو جنسك؟",
    age_group: "ما هي فئتك العمرية؟",
    identity_groups: "هل تنتمي إلى أي من المجموعات التالية؟ اختر كل ما ينطبق.",
    immigration_category: "اختر فئة الهجرة",
    non_permanent_category: "اختر فئة المقيم غير الدائم",
    non_permanent_other: "يرجى التحديد",
    recent_credential: "ما هو آخر مؤهل تعليمي أكملته؟",
    program_name: "ما كان مجال دراستك الرئيسي؟",
    program_name_other: "اكتب مجال دراستك الرئيسي",
    program_location: "أين أكملت هذا البرنامج؟",
    highest_education: "هل هذا البرنامج هو أعلى مستوى تعليمي لديك؟",
    highest_credential: "ما هو أعلى مستوى تعليمي لديك؟",
    highest_program_name: "بالنسبة لأعلى مستوى تعليمي لديك، ما كان مجال دراستك الرئيسي؟",
    highest_program_name_other: "اكتب مجال دراستك الرئيسي لأعلى مستوى تعليمي لديك",
    current_program: "ما هو برنامج دراستك الحالي؟",
    current_program_name: "ما هو مجال دراستك الرئيسي؟",
    current_program_name_other: "اكتب مجال دراستك الرئيسي",
    employed_before: "هل كنت تعمل في كندا قبل الانتقال إلى سو سانت ماري؟",
    previous_job_title: "ما كانت آخر مهنة لك قبل الانتقال إلى سو سانت ماري؟",
    home_emp_before: "هل كنت تعمل في بلدك الأصلي قبل القدوم إلى كندا؟",
    home_country_job: "ما كانت آخر مهنة لك في بلدك الأصلي؟",
    employment_status: "أي مما يلي يصف حالتك الوظيفية الحالية بشكل أفضل؟",
    current_job_title: "ما هو المسمى الوظيفي لعملك الحالي؟",
    intended_job: "هل عملك الحالي هو العمل الذي كنت تنوي القيام به؟",
    intended_job_title: "ما هو المسمى الوظيفي للعمل الذي تنوي القيام به؟",
    job_search_help: "أي مما يلي كان مفيدًا في بحثك عن عمل في شمال أونتاريو / سو سانت ماري؟ اختر كل ما ينطبق.",
    job_search_other: "يرجى التحديد",
    work_barriers: "اختر كل العوائق التي تنطبق",
    work_barriers_other: "يرجى التحديد",
    work_support: "ما نوع الدعم الذي سيساعدك في الحصول على العمل الذي تريده؟ اختر كل ما ينطبق.",
    work_support_other: "يرجى التحديد",
    unemployed_intended_job: "ما هو المسمى الوظيفي للعمل الذي تنوي القيام به؟",
    unemployed_barrier_gate: "هل واجهت أي عوائق أثناء البحث عن عمل في سو سانت ماري؟",
    unemployment_reasons: "اختر كل العوائق التي تنطبق",
    unemployment_reasons_other: "يرجى التحديد",
    not_looking_reasons: "لماذا لا تبحث عن عمل؟",
    not_looking_other: "يرجى التحديد",
    student_working: "هل تعمل حاليًا؟",
    student_current_job: "ما هو المسمى الوظيفي لعملك الحالي؟",
    student_job_relevant: "هل عملك الحالي ذو صلة ببرنامج دراستك الحالي؟",
    student_job_help: "أي مما يلي كان مفيدًا في بحثك عن عمل في شمال أونتاريو / سو سانت ماري؟ اختر كل ما ينطبق.",
    student_job_help_other: "يرجى التحديد",
    student_barrier_gate: "هل واجهت أي عوائق أثناء البحث عن عمل في سو سانت ماري؟",
    student_barriers: "اختر كل العوائق التي تنطبق",
    student_barriers_other: "يرجى التحديد",
    student_support: "ما نوع الدعم الذي سيساعدك في الحصول على العمل الذي تريده؟ اختر كل ما ينطبق.",
    student_support_other: "يرجى التحديد",
    planned_intended_job: "ما هو المسمى الوظيفي للعمل الذي تنوي القيام به بعد التخرج؟",
    skills: "كيف تقيّم مستواك في كل من المهارات التالية؟",
    gift_card_draw: "هل ترغب في المشاركة في سحب بطاقات الهدايا؟ (لأغراض الجائزة فقط)",
    "work_barrier.a": "هل هناك عائق يمنعك من العمل بدوام كامل؟",
    "work_barrier.b": "هل هناك عائق يمنعك من الحصول على العمل الذي تريده؟",
    "work_barrier.c": "هل هناك عائق يمنعك من العمل بدوام كامل ومن ممارسة العمل الذي تريده؟",
    "work_barrier.d": "هل هناك عائق يمنعك من الحصول على عمل بدوام كامل؟",
    "work_barrier.e": "هل هناك عائق يمنعك من ممارسة العمل الذي تريده؟",
  },
  help: {
    skills: "1 = الأدنى، 2 = منخفض، 3 = متوسط، 4 = مرتفع، 5 = الأعلى، 0 = غير متأكد",
  },
  o: {
    "85 or older": "85 أو أكثر",
    "Advanced Diploma": "دبلوم متقدم",
    "Alberta": "ألبرتا",
    "Apprenticeship": "تدريب مهني",
    "British Columbia": "كولومبيا البريطانية",
    "Canadian degree or training": "شهادة أو تدريب كندي",
    "Canadian work experience": "خبرة عمل كندية",
    "Caregiving responsibilities": "مسؤوليات الرعاية",
    "Childcare support": "دعم رعاية الأطفال",
    "College certificate": "شهادة كلية",
    "Credential recognition support": "دعم الاعتراف بالمؤهلات",
    "Credentials not recognized": "المؤهلات غير معترف بها",
    "Diploma": "دبلوم",
    "Discrimination of any kind": "التمييز بأي شكل",
    "Doesn’t need employment income": "لا يحتاج إلى دخل من العمل",
    "Economic Immigrant": "مهاجر اقتصادي",
    "Employed casual (less than 10 hours/week)": "عمل عرضي (أقل من 10 ساعات/أسبوع)",
    "Employed full time (30+ hours/week)": "عمل بدوام كامل (30 ساعة فأكثر/أسبوع)",
    "Employed part time (10-30 hours/week)": "عمل بدوام جزئي (10-30 ساعة/أسبوع)",
    "Employment or settlement centre": "مركز التوظيف أو الاستقرار",
    "Family Sponsored": "برعاية عائلية",
    "Health issues": "مشاكل صحية",
    "Health reasons": "أسباب صحية",
    "High school diploma or equivalent": "شهادة الثانوية العامة أو ما يعادلها",
    "Household responsibilities": "المسؤوليات المنزلية",
    "Household work / Caregiver": "العمل المنزلي / مقدم رعاية",
    "I agree": "أوافق",
    "I didn't have a work permit": "لم يكن لدي تصريح عمل",
    "I directly moved to Sault": "انتقلت مباشرة إلى سو",
    "I disagree": "لا أوافق",
    "Immigrant (permanent resident)": "مهاجر (مقيم دائم)",
    "Immigration issues": "مشاكل الهجرة",
    "In Canada": "في كندا",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "من السكان الأصليين (الأمم الأولى، الميتيس، الإنويت)",
    "International Student": "طالب دولي",
    "Internship / volunteer experience": "تدريب / خبرة تطوعية",
    "Lack of Canadian work experience": "نقص الخبرة العملية الكندية",
    "Lack of skills for available jobs": "نقص المهارات للوظائف المتاحة",
    "Language barriers": "الحواجز اللغوية",
    "Language support": "الدعم اللغوي",
    "Limited job opportunities in preferred sector": "فرص عمل محدودة في القطاع المفضل",
    "Limited knowledge of local job market": "معرفة محدودة بسوق العمل المحلي",
    "Limited mentorship and job-matching support": "دعم محدود في الإرشاد ومطابقة الوظائف",
    "Limited professional network": "شبكة مهنية محدودة",
    "Limited suitable jobs": "وظائف مناسبة محدودة",
    "Local job boards": "لوحات الوظائف المحلية",
    "Local job market information": "معلومات سوق العمل المحلي",
    "Local training or certification": "تدريب أو شهادة محلية",
    "Low wages": "أجور منخفضة",
    "Man": "رجل",
    "Manitoba": "مانيتوبا",
    "Mentorship support": "دعم الإرشاد",
    "Networking support": "دعم بناء العلاقات",
    "New Brunswick": "نيو برونزويك",
    "Newfoundland and Labrador": "نيوفاوندلاند ولابرادور",
    "No": "لا",
    "Non-Canadian work experience not recognized": "الخبرة العملية غير الكندية غير معترف بها",
    "Non-binary person or other gender": "شخص غير ثنائي الجنس أو جنس آخر",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "مقيم غير دائم (مثل تصريح عمل، تصريح دراسة، طالب لجوء)",
    "None of the above (do not select any other options)": "لا شيء مما سبق (لا تختر أي خيارات أخرى)",
    "Northwest Territories": "الأقاليم الشمالية الغربية",
    "Not qualified for available jobs": "غير مؤهل للوظائف المتاحة",
    "Nova Scotia": "نوفا سكوشا",
    "Nunavut": "نونافوت",
    "On temporary leave from a job (e.g., maternity/parental leave)": "في إجازة مؤقتة من العمل (مثل إجازة الأمومة/الوالدية)",
    "Other": "أخرى",
    "Other parts of Ontario": "أجزاء أخرى من أونتاريو",
    "Outside Canada": "خارج كندا",
    "Outside of Canada": "خارج كندا",
    "Outside of Ontario but within Canada": "خارج أونتاريو ولكن داخل كندا",
    "Personal contacts": "معارف شخصية",
    "Post-graduate degree (e.g., Master's)": "شهادة دراسات عليا (مثل الماجستير)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "شهادة دراسات عليا (مثل الماجستير، الدكتوراه، دكتوراه في الطب)",
    "Primary school": "المدرسة الابتدائية",
    "Prince Edward Island": "جزيرة الأمير إدوارد",
    "Professional network": "شبكة مهنية",
    "Protected Person": "شخص محمي",
    "Quebec": "كيبيك",
    "Recognition of non-Canadian work experience": "الاعتراف بالخبرة العملية غير الكندية",
    "Refugee": "لاجئ",
    "Refugee Claimant": "طالب لجوء",
    "Resume/interview support": "دعم السيرة الذاتية والمقابلات",
    "Retired": "متقاعد",
    "Saskatchewan": "ساسكاتشوان",
    "Self-employed": "يعمل لحسابه الخاص",
    "Skills-to-job matching platform": "منصة مطابقة المهارات بالوظائف",
    "Social media (e.g., LinkedIn)": "وسائل التواصل الاجتماعي (مثل لينكد إن)",
    "Student or recent graduate": "طالب أو خريج حديث",
    "Temporary Foreign Worker": "عامل أجنبي مؤقت",
    "Temporary Resident Permit Holder": "حامل تصريح إقامة مؤقتة",
    "Training recommendations": "توصيات التدريب",
    "Unable to work": "غير قادر على العمل",
    "Undergraduate degree": "درجة البكالوريوس",
    "Unemployed and actively looking for work": "عاطل عن العمل ويبحث بنشاط عن عمل",
    "Unemployed and not looking for work": "عاطل عن العمل ولا يبحث عن عمل",
    "Visible minority (e.g., South Asian, Chinese, Black)": "أقلية مرئية (مثل جنوب آسيوي، صيني، أسود)",
    "Woman": "امرأة",
    "Yes": "نعم",
    "Yukon": "يوكون",
  },
  def: {
    "Family Sponsored": "هاجرت لأن أحد أفراد عائلتك الموجودين بالفعل في كندا قام برعايتك.",
    "Economic Immigrant": "هاجرت عبر برنامج للعمال المهرة أو الأعمال (مثل Express Entry، برنامج ترشيح المقاطعات).",
    "Refugee": "جئت إلى كندا للحماية من خطر في بلدك الأصلي.",
    "Temporary Foreign Worker": "في كندا بتصريح عمل مرتبط بصاحب عمل أو تصريح عمل مفتوح.",
    "Refugee Claimant": "طلبت من كندا حماية اللاجئين وتنتظر القرار.",
    "Protected Person": "أقرت كندا بالفعل بأنك بحاجة إلى حماية (وضع لاجئ/شخص محمي معتمد).",
    "Temporary Resident Permit Holder": "لديك تصريح خاص للبقاء مؤقتًا في حالات لا يُسمح بها عادة.",
    "Canadian degree or training": "أكملت شهادة أو برنامج تدريب في كندا.",
    "Canadian work experience": "عملت لدى صاحب عمل في كندا.",
    "Employment or settlement centre": "تلقيت مساعدة من منظمة تدعم الباحثين عن عمل أو القادمين الجدد (مثل Sault Community Career Center).",
    "Internship / volunteer experience": "اكتسبت خبرة عملية من خلال تدريب غير مدفوع الأجر أو عمل قصير الأمد أو تطوع.",
    "Local job boards": "استخدمت مواقع إلكترونية أو إعلانات تنشر وظائف في منطقتك (مثل لوحة وظائف AWIC).",
    "Personal contacts": "حصلت على مساعدة أو معلومات عن وظائف من العائلة أو الأصدقاء أو أشخاص تعرفهم شخصيًا.",
    "Professional network": "استخدمت علاقات من مجال عملك، مثل الزملاء أو الموجهين.",
    "Recognition of non-Canadian work experience": "تم قبول خبرتك العملية المكتسبة خارج كندا.",
    "Caregiving responsibilities": "عليك رعاية أطفال أو أفراد عائلة مسنين يعتمدون عليك.",
    "Credentials not recognized": "تعليمك أو شهادتك أو رخصتك من خارج كندا غير مقبولة لدى أصحاب العمل الكنديين.",
    "Discrimination of any kind": "عوملت بشكل غير عادل بسبب عرقك أو أصلك أو دينك أو جنسك أو لهجتك أو عمرك أو خصائص شخصية أخرى.",
    "Health issues": "لديك حالات صحية جسدية أو نفسية تجعل العثور على عمل أو الاحتفاظ به أصعب.",
    "Household responsibilities": "عليك إدارة الأعمال المنزلية (الطبخ، التنظيف، إدارة المنزل).",
    "Lack of Canadian work experience": "يطلب أصحاب العمل خبرة عملية في كندا، وهي ليست لديك بعد.",
    "Lack of skills for available jobs": "الوظائف المتاحة في منطقتك تتطلب مهارات أو تدريبًا لا تملكه حاليًا.",
    "Language barriers": "مهاراتك في الإنجليزية (أو الفرنسية) تجعل العثور على عمل أو اجتياز المقابلات أصعب.",
    "Limited job opportunities in preferred sector": "هناك وظائف قليلة في مجالك أو قطاعك في منطقتك.",
    "Limited knowledge of local job market": "لست متأكدًا من كيفية العثور على وظائف، أو من هم أصحاب العمل الذين يوظفون، أو كيف يتم التوظيف في منطقتك.",
    "Limited mentorship and job-matching support": "ليس لديك وصول إلى موجهين أو خدمات تربطك بوظائف مناسبة.",
    "Limited professional network": "تعرف عددًا قليلًا من الأشخاص في مجالك يمكنهم مشاركة فرص العمل أو التزكيات أو النصائح.",
    "Non-Canadian work experience not recognized": "خبرتك العملية المكتسبة خارج كندا غير مقبولة ولا مقدَّرة لدى أصحاب العمل الكنديين.",
    "Childcare support": "تحتاج إلى مساعدة في رعاية أطفالك حتى تتمكن من العمل.",
    "Credential recognition support": "تحتاج إلى مساعدة في قبول تعليمك أو مؤهلاتك المهنية المكتسبة خارج كندا.",
    "Language support": "تحتاج إلى مساعدة لتحسين مهاراتك في الإنجليزية (أو الفرنسية).",
    "Local job market information": "تحتاج إلى معلومات عن أصحاب العمل الذين يوظفون، والوظائف المتاحة، والمهارات المطلوبة في منطقتك.",
    "Local training or certification": "تحتاج إلى تدريب أو شهادة تُقدَّم في منطقتك لتأهيلك للوظائف المتاحة.",
    "Mentorship support": "تحتاج إلى التواصل مع أشخاص ذوي خبرة في مجالك.",
    "Networking support": "تحتاج إلى مساعدة في مقابلة أصحاب العمل والمهنيين.",
    "Resume/interview support": "تحتاج إلى مساعدة في إعداد سيرتك الذاتية أو رسالة التقديم أو التدرب على المقابلات.",
    "Skills-to-job matching platform": "تحتاج إلى خدمة أو أداة تطابق مهاراتك مع الوظائف الشاغرة المناسبة.",
    "Training recommendations": "تحتاج إلى اقتراحات حول التدريب أو الدورات التي تأخذها لتحسين فرصك في الحصول على عمل.",
    "Doesn’t need employment income": "لا تحتاج إلى العمل لأن لديك مصادر دخل أخرى أو دعمًا ماليًا.",
    "Health reasons": "لديك حالات صحية جسدية أو نفسية تجعل العثور على عمل أو الاحتفاظ به أصعب.",
    "Immigration issues": "وضعك أو وثائقك المتعلقة بالهجرة (مثل تصريح العمل، معاملة الإقامة الدائمة) تمنعك من العمل.",
    "Limited suitable jobs": "هناك وظائف قليلة في منطقتك تتناسب مع مهاراتك أو خبرتك أو تفضيلاتك.",
    "Low wages": "الوظائف المتاحة تدفع أجرًا منخفضًا جدًا بحيث لا يستحق العمل العناء بالنسبة لك.",
    "Not qualified for available jobs": "الوظائف المتاحة في منطقتك تتطلب تعليمًا أو مهارات أو شهادات لا تملكها حاليًا.",
  },
  ui: {
    "% complete": "٪ مكتمل",
    "Back to home": "العودة إلى الصفحة الرئيسية",
    "Back": "رجوع",
    "Consent is required to continue": "الموافقة مطلوبة للمتابعة",
    "Definition:": "التعريف:",
    "Email address": "عنوان البريد الإلكتروني",
    "Finish to become a Survey Champion": "أكمل لتصبح بطل الاستطلاع",
    "Five $50 local gift cards drawn monthly": "يتم سحب خمس بطاقات هدايا محلية بقيمة 50 دولارًا شهريًا",
    "Go back": "رجوع",
    "Go home": "الصفحة الرئيسية",
    "Home": "الرئيسية",
    "Next 5 skills": "المهارات الخمس التالية",
    "Next question": "السؤال التالي",
    "No matches": "لا توجد نتائج",
    "Not sure": "غير متأكد",
    "One moment.": "لحظة واحدة.",
    "Previous question": "السؤال السابق",
    "Saving your response…": "جارٍ حفظ إجابتك…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "حدثت مشكلة في الاتصال بالخادم. إجاباتك ما زالت محفوظة على هذا الجهاز — يرجى المحاولة مرة أخرى.",
    "Submit": "إرسال",
    "Thank you for your time and response": "شكرًا على وقتك وإجابتك",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "شكرًا على وقتك وإجابتك. لقد قدمت مساهمة كبيرة في تطوير المجتمع.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "شكرًا — تم تسجيل إجابتك. لا حاجة لتعبئتها مرة أخرى.",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "للمشاركة، يجب أن يكون عمرك 18 عامًا على الأقل وأن توافق على المشاركة. إذا كنت ترغب في المتابعة، يمكنك الرجوع وتغيير إجابتك.",
    "Try again": "حاول مرة أخرى",
    "We couldn't save your response": "لم نتمكن من حفظ إجابتك",
    "Yes, enter me in the gift-card draw": "نعم، أدخلني في سحب بطاقات الهدايا",
    "You made a great contribution to the development of the community": "لقد قدمت مساهمة كبيرة في تطوير المجتمع",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "لقد فتحت رابط دعوة شخصي، لذا قد يتم تسجيل إكمالك لأغراض التذكير. تبقى إجاباتك سرية ويتم تحليلها بشكل مجهول الهوية.",
    "You're a Survey Champion": "أنت بطل الاستطلاع",
    "You've already completed this survey": "لقد أكملت هذا الاستطلاع بالفعل",
    "Your responses are anonymous.": "إجاباتك مجهولة الهوية.",
    "more — keep typing to narrow": "المزيد — استمر في الكتابة للتضييق",
    "Search or select a language": "ابحث أو اختر لغة",
    "Type to search countries…": "اكتب للبحث عن بلد…",
    "Type to search areas of study…": "اكتب للبحث عن مجال دراسة…",
    "Type to search occupations…": "اكتب للبحث عن مهنة…",
    "Type to search…": "اكتب للبحث…",
    "Select one…": "اختر واحدًا…",
    "1 · Lowest": "1 · الأدنى",
    "5 · Highest": "5 · الأعلى",
  },
};
