// DRAFT Bengali (bn) — ⚠ MACHINE-QUALITY DRAFT. Requires native-speaker review
// before release. Keyed to exact source strings.
module.exports = {
  q: {
    language: "চালিয়ে যেতে একটি ভাষা নির্বাচন করুন",
    consent: "অনুগ্রহ করে নিশ্চিত করুন যে আপনার বয়স কমপক্ষে ১৮ বছর এবং আপনি স্বেচ্ছায় এই জরিপে অংশগ্রহণ করতে সম্মত।",
    eligible: "আপনি কি ২০২১ সালের সেপ্টেম্বরের পরে বসবাসের জন্য উত্তর অন্টারিওতে এসেছেন?",
    moved_from: "আপনি কোথা থেকে এসেছেন?",
    province: "আপনি যে প্রদেশ থেকে এসেছেন তা নির্বাচন করুন",
    country_moved_from: "আপনি যে দেশ থেকে এসেছেন তা নির্বাচন করুন",
    gender: "আপনার লিঙ্গ কী?",
    age_group: "আপনার বয়সের গোষ্ঠী কী?",
    identity_groups: "আপনি কি নিম্নলিখিত কোনো গোষ্ঠীর সঙ্গে নিজেকে চিহ্নিত করেন? প্রযোজ্য সবগুলি নির্বাচন করুন।",
    immigration_category: "অভিবাসন শ্রেণি নির্বাচন করুন",
    non_permanent_category: "অস্থায়ী বাসিন্দার শ্রেণি নির্বাচন করুন",
    non_permanent_other: "অনুগ্রহ করে উল্লেখ করুন",
    recent_credential: "আপনি সবচেয়ে সম্প্রতি কোন শিক্ষাগত যোগ্যতা সম্পন্ন করেছেন?",
    program_name: "আপনার পড়াশোনার মূল ক্ষেত্র কী ছিল?",
    program_name_other: "আপনার পড়াশোনার মূল ক্ষেত্র লিখুন",
    program_location: "আপনি এই প্রোগ্রামটি কোথায় সম্পন্ন করেছেন?",
    highest_education: "এই প্রোগ্রামটি কি আপনার শিক্ষার সর্বোচ্চ স্তর?",
    highest_credential: "আপনার শিক্ষার সর্বোচ্চ স্তর কী?",
    highest_program_name: "আপনার শিক্ষার সর্বোচ্চ স্তরের জন্য, আপনার পড়াশোনার মূল ক্ষেত্র কী ছিল?",
    highest_program_name_other: "আপনার শিক্ষার সর্বোচ্চ স্তরের জন্য পড়াশোনার মূল ক্ষেত্র লিখুন",
    current_program: "আপনার বর্তমান পড়াশোনার প্রোগ্রাম কী?",
    current_program_name: "আপনার পড়াশোনার মূল ক্ষেত্র কী?",
    current_program_name_other: "আপনার পড়াশোনার মূল ক্ষেত্র লিখুন",
    employed_before: "সল্ট স্ট. মেরিতে আসার আগে আপনি কি কানাডায় কর্মরত ছিলেন?",
    previous_job_title: "সল্ট স্ট. মেরিতে আসার আগে আপনার সর্বশেষ পেশা কী ছিল?",
    home_emp_before: "কানাডায় আসার আগে আপনি কি আপনার নিজ দেশে কর্মরত ছিলেন?",
    home_country_job: "আপনার নিজ দেশে আপনার সর্বশেষ পেশা কী ছিল?",
    employment_status: "নিম্নলিখিত কোনটি আপনার বর্তমান কর্মসংস্থানের অবস্থা সবচেয়ে ভালোভাবে বর্ণনা করে?",
    current_job_title: "আপনার বর্তমান চাকরির পদবি কী?",
    intended_job: "আপনার বর্তমান চাকরিটি কি সেটাই যা আপনি করতে চেয়েছিলেন?",
    intended_job_title: "আপনি যে চাকরিটি করতে চান তার পদবি কী?",
    job_search_help: "উত্তর অন্টারিও / সল্ট স্ট. মেরিতে আপনার চাকরি খোঁজায় নিম্নলিখিত কোনগুলি সহায়ক ছিল? প্রযোজ্য সবগুলি নির্বাচন করুন।",
    job_search_other: "অনুগ্রহ করে উল্লেখ করুন",
    work_barriers: "প্রযোজ্য সব বাধা নির্বাচন করুন",
    work_barriers_other: "অনুগ্রহ করে উল্লেখ করুন",
    work_support: "কোন ধরনের সহায়তা আপনাকে কাঙ্ক্ষিত চাকরি পেতে সাহায্য করবে? প্রযোজ্য সবগুলি নির্বাচন করুন।",
    work_support_other: "অনুগ্রহ করে উল্লেখ করুন",
    unemployed_intended_job: "আপনি যে চাকরিটি করতে চান তার পদবি কী?",
    unemployed_barrier_gate: "সল্ট স্ট. মেরিতে কাজ খোঁজার সময় আপনি কি কোনো বাধার সম্মুখীন হয়েছেন?",
    unemployment_reasons: "প্রযোজ্য সব বাধা নির্বাচন করুন",
    unemployment_reasons_other: "অনুগ্রহ করে উল্লেখ করুন",
    not_looking_reasons: "আপনি কেন কাজ খুঁজছেন না?",
    not_looking_other: "অনুগ্রহ করে উল্লেখ করুন",
    student_working: "আপনি কি বর্তমানে কাজ করছেন?",
    student_current_job: "আপনার বর্তমান চাকরির পদবি কী?",
    student_job_relevant: "আপনার বর্তমান চাকরি কি আপনার বর্তমান পড়াশোনার প্রোগ্রামের সঙ্গে সম্পর্কিত?",
    student_job_help: "উত্তর অন্টারিও / সল্ট স্ট. মেরিতে আপনার চাকরি খোঁজায় নিম্নলিখিত কোনগুলি সহায়ক ছিল? প্রযোজ্য সবগুলি নির্বাচন করুন।",
    student_job_help_other: "অনুগ্রহ করে উল্লেখ করুন",
    student_barrier_gate: "সল্ট স্ট. মেরিতে চাকরি খোঁজার সময় আপনি কি কোনো বাধার সম্মুখীন হয়েছেন?",
    student_barriers: "প্রযোজ্য সব বাধা নির্বাচন করুন",
    student_barriers_other: "অনুগ্রহ করে উল্লেখ করুন",
    student_support: "কোন ধরনের সহায়তা আপনাকে কাঙ্ক্ষিত চাকরি পেতে সাহায্য করবে? প্রযোজ্য সবগুলি নির্বাচন করুন।",
    student_support_other: "অনুগ্রহ করে উল্লেখ করুন",
    planned_intended_job: "স্নাতক হওয়ার পরে আপনি যে চাকরিটি করতে চান তার পদবি কী?",
    skills: "নিম্নলিখিত প্রতিটি দক্ষতার জন্য আপনি আপনার স্তর কীভাবে মূল্যায়ন করবেন?",
    gift_card_draw: "আপনি কি গিফট কার্ড ড্রয়ে অংশগ্রহণ করতে চান? (শুধুমাত্র পুরস্কারের উদ্দেশ্যে)",
    "work_barrier.a": "এমন কোনো বাধা আছে যা আপনাকে পূর্ণকালীন কাজ করতে বাধা দেয়?",
    "work_barrier.b": "এমন কোনো বাধা আছে যা আপনাকে কাঙ্ক্ষিত চাকরি পেতে বাধা দেয়?",
    "work_barrier.c": "এমন কোনো বাধা আছে যা আপনাকে পূর্ণকালীন কাজ করতে এবং কাঙ্ক্ষিত চাকরি করতে বাধা দেয়?",
    "work_barrier.d": "এমন কোনো বাধা আছে যা আপনাকে পূর্ণকালীন চাকরি পেতে বাধা দেয়?",
    "work_barrier.e": "এমন কোনো বাধা আছে যা আপনাকে কাঙ্ক্ষিত চাকরি করতে বাধা দেয়?",
  },
  help: {
    skills: "১ = সর্বনিম্ন, ২ = নিম্ন, ৩ = মাঝারি, ৪ = উচ্চ, ৫ = সর্বোচ্চ, ০ = নিশ্চিত নই",
  },
  o: {
    "85 or older": "৮৫ বা তার বেশি",
    "Advanced Diploma": "উন্নত ডিপ্লোমা",
    "Alberta": "আলবার্টা",
    "Apprenticeship": "শিক্ষানবিশি",
    "British Columbia": "ব্রিটিশ কলাম্বিয়া",
    "Canadian degree or training": "কানাডীয় ডিগ্রি বা প্রশিক্ষণ",
    "Canadian work experience": "কানাডীয় কাজের অভিজ্ঞতা",
    "Caregiving responsibilities": "যত্ন নেওয়ার দায়িত্ব",
    "Childcare support": "শিশু যত্ন সহায়তা",
    "College certificate": "কলেজ সার্টিফিকেট",
    "Credential recognition support": "যোগ্যতা স্বীকৃতি সহায়তা",
    "Credentials not recognized": "যোগ্যতা স্বীকৃত নয়",
    "Diploma": "ডিপ্লোমা",
    "Discrimination of any kind": "যেকোনো ধরনের বৈষম্য",
    "Doesn’t need employment income": "কর্মসংস্থানের আয়ের প্রয়োজন নেই",
    "Economic Immigrant": "অর্থনৈতিক অভিবাসী",
    "Employed casual (less than 10 hours/week)": "অনিয়মিত কর্মসংস্থান (সপ্তাহে ১০ ঘণ্টার কম)",
    "Employed full time (30+ hours/week)": "পূর্ণকালীন কর্মসংস্থান (সপ্তাহে ৩০+ ঘণ্টা)",
    "Employed part time (10-30 hours/week)": "খণ্ডকালীন কর্মসংস্থান (সপ্তাহে ১০-৩০ ঘণ্টা)",
    "Employment or settlement centre": "কর্মসংস্থান বা বসতি কেন্দ্র",
    "Family Sponsored": "পরিবার কর্তৃক স্পনসরকৃত",
    "Health issues": "স্বাস্থ্য সমস্যা",
    "Health reasons": "স্বাস্থ্যগত কারণ",
    "High school diploma or equivalent": "উচ্চ বিদ্যালয়ের ডিপ্লোমা বা সমতুল্য",
    "Household responsibilities": "গৃহস্থালির দায়িত্ব",
    "Household work / Caregiver": "গৃহস্থালির কাজ / যত্নকারী",
    "I agree": "আমি সম্মত",
    "I didn't have a work permit": "আমার কাজের অনুমতি ছিল না",
    "I directly moved to Sault": "আমি সরাসরি সল্টে এসেছি",
    "I disagree": "আমি সম্মত নই",
    "Immigrant (permanent resident)": "অভিবাসী (স্থায়ী বাসিন্দা)",
    "Immigration issues": "অভিবাসন সংক্রান্ত সমস্যা",
    "In Canada": "কানাডায়",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "আদিবাসী (ফার্স্ট নেশনস, মেটিস, ইনুইট/ইনুক)",
    "International Student": "আন্তর্জাতিক শিক্ষার্থী",
    "Internship / volunteer experience": "ইন্টার্নশিপ / স্বেচ্ছাসেবী অভিজ্ঞতা",
    "Lack of Canadian work experience": "কানাডীয় কাজের অভিজ্ঞতার অভাব",
    "Lack of skills for available jobs": "উপলব্ধ চাকরির জন্য দক্ষতার অভাব",
    "Language barriers": "ভাষাগত বাধা",
    "Language support": "ভাষা সহায়তা",
    "Limited job opportunities in preferred sector": "পছন্দের খাতে সীমিত চাকরির সুযোগ",
    "Limited knowledge of local job market": "স্থানীয় চাকরির বাজার সম্পর্কে সীমিত জ্ঞান",
    "Limited mentorship and job-matching support": "সীমিত পরামর্শ ও চাকরি-মিলকরণ সহায়তা",
    "Limited professional network": "সীমিত পেশাদার নেটওয়ার্ক",
    "Limited suitable jobs": "সীমিত উপযুক্ত চাকরি",
    "Local job boards": "স্থানীয় চাকরির বোর্ড",
    "Local job market information": "স্থানীয় চাকরির বাজারের তথ্য",
    "Local training or certification": "স্থানীয় প্রশিক্ষণ বা সার্টিফিকেশন",
    "Low wages": "কম মজুরি",
    "Man": "পুরুষ",
    "Manitoba": "ম্যানিটোবা",
    "Mentorship support": "পরামর্শ সহায়তা",
    "Networking support": "নেটওয়ার্কিং সহায়তা",
    "New Brunswick": "নিউ ব্রান্সউইক",
    "Newfoundland and Labrador": "নিউফাউন্ডল্যান্ড ও ল্যাব্রাডর",
    "No": "না",
    "Non-Canadian work experience not recognized": "অ-কানাডীয় কাজের অভিজ্ঞতা স্বীকৃত নয়",
    "Non-binary person or other gender": "নন-বাইনারি ব্যক্তি বা অন্য লিঙ্গ",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "অস্থায়ী বাসিন্দা (যেমন, কাজের অনুমতি, অধ্যয়নের অনুমতি, শরণার্থী আবেদনকারী)",
    "None of the above (do not select any other options)": "উপরের কোনোটিই নয় (অন্য কোনো বিকল্প নির্বাচন করবেন না)",
    "Northwest Territories": "নর্থওয়েস্ট টেরিটরিজ",
    "Not qualified for available jobs": "উপলব্ধ চাকরির জন্য যোগ্য নয়",
    "Nova Scotia": "নোভা স্কোশিয়া",
    "Nunavut": "নুনাভুত",
    "On temporary leave from a job (e.g., maternity/parental leave)": "চাকরি থেকে অস্থায়ী ছুটিতে (যেমন, মাতৃত্ব/পিতৃত্বকালীন ছুটি)",
    "Other": "অন্যান্য",
    "Other parts of Ontario": "অন্টারিওর অন্যান্য অংশ",
    "Outside Canada": "কানাডার বাইরে",
    "Outside of Canada": "কানাডার বাইরে",
    "Outside of Ontario but within Canada": "অন্টারিওর বাইরে কিন্তু কানাডার মধ্যে",
    "Personal contacts": "ব্যক্তিগত যোগাযোগ",
    "Post-graduate degree (e.g., Master's)": "স্নাতকোত্তর ডিগ্রি (যেমন, মাস্টার্স)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "স্নাতকোত্তর ডিগ্রি (যেমন, মাস্টার্স, পিএইচডি, এমডি)",
    "Primary school": "প্রাথমিক বিদ্যালয়",
    "Prince Edward Island": "প্রিন্স এডওয়ার্ড আইল্যান্ড",
    "Professional network": "পেশাদার নেটওয়ার্ক",
    "Protected Person": "সুরক্ষিত ব্যক্তি",
    "Quebec": "কুইবেক",
    "Recognition of non-Canadian work experience": "অ-কানাডীয় কাজের অভিজ্ঞতার স্বীকৃতি",
    "Refugee": "শরণার্থী",
    "Refugee Claimant": "শরণার্থী আবেদনকারী",
    "Resume/interview support": "জীবনবৃত্তান্ত/সাক্ষাৎকার সহায়তা",
    "Retired": "অবসরপ্রাপ্ত",
    "Saskatchewan": "সাসকাচোয়ান",
    "Self-employed": "স্ব-নিযুক্ত",
    "Skills-to-job matching platform": "দক্ষতা-থেকে-চাকরি মিলকরণ প্ল্যাটফর্ম",
    "Social media (e.g., LinkedIn)": "সামাজিক মাধ্যম (যেমন, লিংকডইন)",
    "Student or recent graduate": "শিক্ষার্থী বা সদ্য স্নাতক",
    "Temporary Foreign Worker": "অস্থায়ী বিদেশি কর্মী",
    "Temporary Resident Permit Holder": "অস্থায়ী বাসিন্দা অনুমতিপত্রধারী",
    "Training recommendations": "প্রশিক্ষণ সুপারিশ",
    "Unable to work": "কাজ করতে অক্ষম",
    "Undergraduate degree": "স্নাতক ডিগ্রি",
    "Unemployed and actively looking for work": "বেকার এবং সক্রিয়ভাবে কাজ খুঁজছেন",
    "Unemployed and not looking for work": "বেকার এবং কাজ খুঁজছেন না",
    "Visible minority (e.g., South Asian, Chinese, Black)": "দৃশ্যমান সংখ্যালঘু (যেমন, দক্ষিণ এশীয়, চীনা, কৃষ্ণাঙ্গ)",
    "Woman": "নারী",
    "Yes": "হ্যাঁ",
    "Yukon": "ইউকন",
  },
  def: {
    "Family Sponsored": "আপনি অভিবাসন করেছেন কারণ কানাডায় ইতিমধ্যে থাকা একজন পরিবারের সদস্য আপনাকে স্পনসর করেছেন।",
    "Economic Immigrant": "আপনি দক্ষ-কর্মী বা ব্যবসায়িক প্রোগ্রামের মাধ্যমে অভিবাসন করেছেন (যেমন, এক্সপ্রেস এন্ট্রি, প্রাদেশিক মনোনীত প্রোগ্রাম)।",
    "Refugee": "আপনি নিজ দেশে বিপদ থেকে সুরক্ষার জন্য কানাডায় এসেছেন।",
    "Temporary Foreign Worker": "একজন নিয়োগকর্তার সঙ্গে যুক্ত কাজের অনুমতি বা উন্মুক্ত কাজের অনুমতি নিয়ে কানাডায়।",
    "Refugee Claimant": "আপনি কানাডার কাছে শরণার্থী সুরক্ষা চেয়েছেন এবং সিদ্ধান্তের অপেক্ষায় আছেন।",
    "Protected Person": "কানাডা ইতিমধ্যে স্বীকার করেছে যে আপনার সুরক্ষা প্রয়োজন (অনুমোদিত শরণার্থী/সুরক্ষিত মর্যাদা)।",
    "Temporary Resident Permit Holder": "সাধারণত অনুমোদিত না হলেও অস্থায়ীভাবে থাকার জন্য আপনার একটি বিশেষ অনুমতি আছে।",
    "Employment or settlement agency": "একটি সংস্থা যা মানুষকে কাজ খুঁজে পেতে সাহায্য করে, বা নতুন আগতদের কানাডায় বসতি স্থাপনে সাহায্য করে।",
    "Recognition of experience": "একজন নিয়োগকর্তা যিনি আপনার আগে অর্জিত কাজের অভিজ্ঞতা গ্রহণ ও মূল্যায়ন করেন।",
    "Networking events": "এমন অনুষ্ঠান যেখানে আপনি চাকরির সংযোগ গড়তে আপনার ক্ষেত্রের মানুষের সঙ্গে দেখা করেন।",
    "Lack of local experience": "আপনি এখনও কানাডায় বা এই এলাকায় কাজ করেননি, যা নিয়োগকর্তারা প্রায়ই চান।",
    "Lack of Canadian experience": "আপনি এখনও কানাডায় বা এই এলাকায় কাজ করেননি, যা নিয়োগকর্তারা প্রায়ই চান।",
    "Qualifications not recognized": "অন্য দেশ থেকে আপনার শিক্ষা, লাইসেন্স বা অভিজ্ঞতা এখানে গৃহীত হয় না।",
    "Credential recognition issue": "অন্য দেশ থেকে আপনার শিক্ষা, লাইসেন্স বা অভিজ্ঞতা এখানে গৃহীত হয় না।",
    "Experience not recognized": "অন্য দেশ থেকে আপনার শিক্ষা, লাইসেন্স বা অভিজ্ঞতা এখানে গৃহীত হয় না।",
    "Immigration restrictions": "আপনার অনুমতি বা মর্যাদার শর্ত আপনি যে কাজ বা ঘণ্টা করতে পারেন তা সীমিত করে।",
    "Immigration status": "আপনার অনুমতি বা মর্যাদার শর্ত আপনি যে কাজ বা ঘণ্টা করতে পারেন তা সীমিত করে।",
    "Skills mismatch": "আপনার দক্ষতা স্থানীয়ভাবে উপলব্ধ চাকরির সঙ্গে মেলে না।",
    "Limited network": "আপনি এমন অনেক মানুষকে চেনেন না যারা আপনাকে চাকরির সঙ্গে সংযুক্ত করতে পারে।",
    "Credential recognition": "কানাডায় আপনার বিদেশি শিক্ষা বা লাইসেন্স স্বীকৃত করাতে সহায়তা।",
    "Job matching": "একটি সেবা যা আপনাকে উপযুক্ত চাকরির সুযোগের সঙ্গে সংযুক্ত করে।",
    "Training matching": "একটি সেবা যা আপনাকে উপযুক্ত প্রশিক্ষণ প্রোগ্রামের সঙ্গে সংযুক্ত করে।",
  },
  ui: {
    "% complete": "% সম্পন্ন",
    "Back to home": "হোমে ফিরে যান",
    "Back": "পিছনে",
    "Consent is required to continue": "চালিয়ে যেতে সম্মতি প্রয়োজন",
    "Definition:": "সংজ্ঞা:",
    "Email address": "ইমেল ঠিকানা",
    "Finish to become a Survey Champion": "জরিপ চ্যাম্পিয়ন হতে সম্পন্ন করুন",
    "Five $50 local gift cards drawn monthly": "প্রতি মাসে $৫০ মূল্যের পাঁচটি স্থানীয় গিফট কার্ড ড্র করা হয়",
    "Go back": "পিছনে যান",
    "Go home": "হোমে যান",
    "Halfway there": "অর্ধেক পথ",
    "Home": "হোম",
    "Next 5 skills": "পরবর্তী ৫টি দক্ষতা",
    "Next question": "পরবর্তী প্রশ্ন",
    "No matches": "কোনো মিল নেই",
    "Not sure": "নিশ্চিত নই",
    "One moment.": "এক মুহূর্ত।",
    "Previous question": "পূর্ববর্তী প্রশ্ন",
    "Saving your response…": "আপনার উত্তর সংরক্ষণ করা হচ্ছে…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "সার্ভারে পৌঁছাতে সমস্যা হয়েছে। আপনার উত্তরগুলি এখনও এই ডিভাইসে সংরক্ষিত আছে — অনুগ্রহ করে আবার চেষ্টা করুন।",
    "Submit": "জমা দিন",
    "Thank you for sharing your experience.": "আপনার অভিজ্ঞতা শেয়ার করার জন্য ধন্যবাদ।",
    "Thank you for your time and response": "আপনার সময় ও উত্তরের জন্য ধন্যবাদ",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "আপনার সময় ও উত্তরের জন্য ধন্যবাদ। আপনি সম্প্রদায়ের উন্নয়নে দারুণ অবদান রেখেছেন।",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "ধন্যবাদ — আপনার উত্তর রেকর্ড করা হয়েছে। এটি আবার পূরণ করার প্রয়োজন নেই।",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "অংশগ্রহণ করতে, আপনার বয়স কমপক্ষে ১৮ বছর হতে হবে এবং অংশগ্রহণে সম্মত হতে হবে। আপনি যদি চালিয়ে যেতে চান, আপনি পিছনে গিয়ে আপনার উত্তর পরিবর্তন করতে পারেন।",
    "Try again": "আবার চেষ্টা করুন",
    "We couldn't save your response": "আমরা আপনার উত্তর সংরক্ষণ করতে পারিনি",
    "Yes, enter me in the gift-card draw": "হ্যাঁ, আমাকে গিফট কার্ড ড্রয়ে অন্তর্ভুক্ত করুন",
    "You made a great contribution to the development of the community": "আপনি সম্প্রদায়ের উন্নয়নে দারুণ অবদান রেখেছেন",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "আপনি একটি ব্যক্তিগত আমন্ত্রণ লিঙ্ক খুলেছেন, তাই অনুস্মারকের উদ্দেশ্যে আপনার সম্পন্ন হওয়া রেকর্ড করা হতে পারে। আপনার উত্তরগুলি গোপন রাখা হয় এবং পরিচয়-বিহীন আকারে বিশ্লেষণ করা হয়।",
    "You're a Survey Champion": "আপনি একজন জরিপ চ্যাম্পিয়ন",
    "You've already completed this survey": "আপনি ইতিমধ্যে এই জরিপটি সম্পন্ন করেছেন",
    "Your responses are anonymous.": "আপনার উত্তরগুলি বেনামী।",
    "more — keep typing to narrow": "আরও — সংকুচিত করতে টাইপ করতে থাকুন",
    "Search or select a language": "একটি ভাষা খুঁজুন বা নির্বাচন করুন",
    "Type to search countries…": "দেশ খুঁজতে টাইপ করুন…",
    "Type to search areas of study…": "পড়াশোনার ক্ষেত্র খুঁজতে টাইপ করুন…",
    "Type to search occupations…": "পেশা খুঁজতে টাইপ করুন…",
    "Type to search…": "খুঁজতে টাইপ করুন…",
    "Select one…": "একটি নির্বাচন করুন…",
    "1 · Lowest": "১ · সর্বনিম্ন",
    "5 · Highest": "৫ · সর্বোচ্চ",
  },
};
