// DRAFT Spanish (es) — pending fluent review. Keyed to exact source strings.
module.exports = {
  q: {
    language: "Seleccione un idioma para continuar",
    consent: "Confirme que tiene al menos 18 años y que acepta participar voluntariamente en esta encuesta.",
    eligible: "¿Se mudó al norte de Ontario después de septiembre de 2021 para vivir?",
    moved_from: "¿De dónde se mudó?",
    province: "Seleccione la provincia de la que se mudó",
    country_moved_from: "Seleccione el país del que se mudó",
    gender: "¿Cuál es su género?",
    age_group: "¿Cuál es su grupo de edad?",
    identity_groups: "¿Se identifica con alguno de los siguientes grupos? Seleccione todas las opciones que correspondan.",
    immigration_category: "Seleccione la categoría de inmigración",
    non_permanent_category: "Seleccione la categoría de residente no permanente",
    non_permanent_other: "Especifique",
    recent_credential: "¿Cuál es la credencial educativa más reciente que ha completado?",
    program_name: "¿Cuál fue su principal área de estudio?",
    program_name_other: "Escriba su principal área de estudio",
    program_location: "¿Dónde completó este programa?",
    highest_education: "¿Es este programa su nivel más alto de educación?",
    highest_credential: "¿Cuál es su nivel más alto de educación?",
    highest_program_name: "Para su nivel más alto de educación, ¿cuál fue su principal área de estudio?",
    highest_program_name_other: "Escriba su principal área de estudio para su nivel más alto de educación",
    current_program: "¿Cuál es su programa de estudios actual?",
    current_program_name: "¿Cuál es su principal área de estudio?",
    current_program_name_other: "Escriba su principal área de estudio",
    employed_before: "¿Tenía empleo en Canadá antes de mudarse a Sault Ste. Marie?",
    previous_job_title: "¿Cuál era su última ocupación antes de mudarse a Sault Ste. Marie?",
    home_emp_before: "¿Tenía empleo en su país de origen antes de venir a Canadá?",
    home_country_job: "¿Cuál era su última ocupación en su país de origen?",
    employment_status: "¿Cuál de las siguientes opciones describe mejor su situación laboral actual?",
    current_job_title: "¿Cuál es el título de su empleo actual?",
    intended_job: "¿Es su empleo actual el que deseaba tener?",
    intended_job_title: "¿Cuál es el título del empleo que desea tener?",
    job_search_help: "¿Cuáles de los siguientes le resultaron útiles en su búsqueda de empleo en el norte de Ontario / Sault Ste. Marie? Seleccione todas las opciones que correspondan.",
    job_search_other: "Especifique",
    work_barriers: "Seleccione todas las barreras que correspondan",
    work_barriers_other: "Especifique",
    work_support: "¿Qué tipo de apoyo le ayudaría a conseguir el empleo que desea? Seleccione todas las opciones que correspondan.",
    work_support_other: "Especifique",
    unemployed_intended_job: "¿Cuál es el título del empleo que desea tener?",
    unemployed_barrier_gate: "¿Ha enfrentado alguna barrera al buscar trabajo en Sault Ste. Marie?",
    unemployment_reasons: "Seleccione todas las barreras que correspondan",
    unemployment_reasons_other: "Especifique",
    not_looking_reasons: "¿Por qué no está buscando trabajo?",
    not_looking_other: "Especifique",
    student_working: "¿Está trabajando actualmente?",
    student_current_job: "¿Cuál es el título de su empleo actual?",
    student_job_relevant: "¿Su empleo actual está relacionado con su programa de estudios actual?",
    student_job_help: "¿Cuáles de los siguientes le resultaron útiles en su búsqueda de empleo en el norte de Ontario / Sault Ste. Marie? Seleccione todas las opciones que correspondan.",
    student_job_help_other: "Especifique",
    student_barrier_gate: "¿Ha enfrentado alguna barrera al buscar empleo en Sault Ste. Marie?",
    student_barriers: "Seleccione todas las barreras que correspondan",
    student_barriers_other: "Especifique",
    student_support: "¿Qué tipo de apoyo le ayudaría a conseguir el empleo que desea? Seleccione todas las opciones que correspondan.",
    student_support_other: "Especifique",
    planned_intended_job: "¿Cuál es el título del empleo que desea tener después de graduarse?",
    skills: "¿Cómo calificaría su nivel en cada una de las siguientes habilidades?",
    gift_card_draw: "¿Desea participar en el sorteo de tarjetas de regalo? (Solo para fines del premio)",
    "work_barrier.a": "¿Hay alguna barrera que le impida trabajar a tiempo completo?",
    "work_barrier.b": "¿Hay alguna barrera que le impida conseguir el empleo que desea?",
    "work_barrier.c": "¿Hay alguna barrera que le impida trabajar a tiempo completo y desempeñar el empleo que desea?",
    "work_barrier.d": "¿Hay alguna barrera que le impida conseguir un empleo a tiempo completo?",
    "work_barrier.e": "¿Hay alguna barrera que le impida desempeñar el empleo que desea?",
    "unemployed_support": "¿Qué tipo de apoyo le ayudaría a conseguir el empleo que desea? Seleccione todas las opciones que correspondan.",
    "not_looking_intended_job": "¿Cuál es el título del empleo que desea tener?",
    "not_looking_barrier_gate": "¿Ha enfrentado alguna barrera al buscar trabajo en Sault Ste. Marie?",
    "not_looking_barriers": "Seleccione todas las barreras que correspondan",
    "not_looking_barriers_other": "Especifique",
    "not_looking_support": "¿Qué tipo de apoyo le ayudaría a conseguir el empleo que desea? Seleccione todas las opciones que correspondan.",
    "not_looking_support_other": "Especifique",
    "not_looking_expect_look": "¿Espera comenzar a buscar trabajo en los próximos 12 meses?",
  },
  help: {
    skills: "1 = más bajo, 2 = bajo, 3 = moderado, 4 = alto, 5 = más alto, 0 = no estoy seguro",
  },
  o: {
    "85 or older": "85 o más",
    "Advanced Diploma": "Diploma avanzado",
    "Alberta": "Alberta",
    "Apprenticeship": "Aprendizaje",
    "British Columbia": "Columbia Británica",
    "Canadian degree or training": "Título o formación canadiense",
    "Canadian work experience": "Experiencia laboral canadiense",
    "Caregiving responsibilities": "Responsabilidades de cuidado",
    "Childcare support": "Apoyo para el cuidado de niños",
    "College certificate": "Certificado universitario (college)",
    "Credential recognition support": "Apoyo para el reconocimiento de credenciales",
    "Credentials not recognized": "Credenciales no reconocidas",
    "Diploma": "Diploma",
    "Discrimination of any kind": "Discriminación de cualquier tipo",
    "Doesn’t need employment income": "No necesita ingresos laborales",
    "Economic Immigrant": "Inmigrante económico",
    "Employed casual (less than 10 hours/week)": "Empleo ocasional (menos de 10 horas/semana)",
    "Employed full time (30+ hours/week)": "Empleo a tiempo completo (30 o más horas/semana)",
    "Employed part time (10-30 hours/week)": "Empleo a tiempo parcial (10 a 30 horas/semana)",
    "Employment or settlement centre": "Centro de empleo o de asentamiento",
    "Family Sponsored": "Patrocinado por la familia",
    "Health issues": "Problemas de salud",
    "Health reasons": "Razones de salud",
    "High school diploma or equivalent": "Diploma de escuela secundaria o equivalente",
    "Household responsibilities": "Responsabilidades del hogar",
    "Household work / Caregiver": "Trabajo doméstico / Cuidador",
    "I agree": "Acepto",
    "I didn't have a work permit": "No tenía permiso de trabajo",
    "I directly moved to Sault": "Me mudé directamente a Sault",
    "I disagree": "No acepto",
    "Immigrant (permanent resident)": "Inmigrante (residente permanente)",
    "Immigration issues": "Problemas de inmigración",
    "In Canada": "En Canadá",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Indígena (Primeras Naciones, Métis, Inuit/Inuk)",
    "International Student": "Estudiante internacional",
    "Internship / volunteer experience": "Pasantía / experiencia de voluntariado",
    "Lack of Canadian work experience": "Falta de experiencia laboral canadiense",
    "Lack of skills for available jobs": "Falta de habilidades para los empleos disponibles",
    "Language barriers": "Barreras lingüísticas",
    "Language support": "Apoyo lingüístico",
    "Limited job opportunities in preferred sector": "Oportunidades de empleo limitadas en el sector preferido",
    "Limited knowledge of local job market": "Conocimiento limitado del mercado laboral local",
    "Limited mentorship and job-matching support": "Apoyo limitado de mentoría y de conexión con empleos",
    "Limited professional network": "Red profesional limitada",
    "Limited suitable jobs": "Empleos adecuados limitados",
    "Local job boards": "Portales de empleo locales",
    "Local job market information": "Información sobre el mercado laboral local",
    "Local training or certification": "Formación o certificación local",
    "Low wages": "Salarios bajos",
    "Man": "Hombre",
    "Manitoba": "Manitoba",
    "Mentorship support": "Apoyo de mentoría",
    "Networking support": "Apoyo para establecer contactos",
    "New Brunswick": "Nuevo Brunswick",
    "Newfoundland and Labrador": "Terranova y Labrador",
    "No": "No",
    "Non-Canadian work experience not recognized": "Experiencia laboral no canadiense no reconocida",
    "Non-binary person or other gender": "Persona no binaria u otro género",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Residente no permanente (p. ej., permiso de trabajo, permiso de estudio, solicitante de asilo)",
    "None of the above (do not select any other options)": "Ninguna de las anteriores (no seleccione ninguna otra opción)",
    "Northwest Territories": "Territorios del Noroeste",
    "Not qualified for available jobs": "No calificado para los empleos disponibles",
    "Nova Scotia": "Nueva Escocia",
    "Nunavut": "Nunavut",
    "On temporary leave from a job (e.g., maternity/parental leave)": "En licencia temporal de un empleo (p. ej., licencia de maternidad o parental)",
    "Other": "Otro",
    "Other parts of Ontario": "Otras partes de Ontario",
    "Outside Canada": "Fuera de Canadá",
    "Outside of Canada": "Fuera de Canadá",
    "Outside of Ontario but within Canada": "Fuera de Ontario pero dentro de Canadá",
    "Personal contacts": "Contactos personales",
    "Post-graduate degree (e.g., Master's)": "Posgrado (p. ej., maestría)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Posgrado (p. ej., maestría, doctorado, M.D.)",
    "Primary school": "Escuela primaria",
    "Prince Edward Island": "Isla del Príncipe Eduardo",
    "Professional network": "Red profesional",
    "Protected Person": "Persona protegida",
    "Quebec": "Quebec",
    "Recognition of non-Canadian work experience": "Reconocimiento de la experiencia laboral no canadiense",
    "Refugee": "Refugiado",
    "Refugee Claimant": "Solicitante de asilo",
    "Resume/interview support": "Apoyo con el currículum y las entrevistas",
    "Retired": "Jubilado",
    "Saskatchewan": "Saskatchewan",
    "Self-employed": "Trabajador autónomo",
    "Skills-to-job matching platform": "Plataforma de conexión entre habilidades y empleos",
    "Social media (e.g., LinkedIn)": "Redes sociales (p. ej., LinkedIn)",
    "Student or recent graduate": "Estudiante o recién graduado",
    "Temporary Foreign Worker": "Trabajador extranjero temporal",
    "Temporary Resident Permit Holder": "Titular de un permiso de residencia temporal",
    "Training recommendations": "Recomendaciones de formación",
    "Unable to work": "Incapaz de trabajar",
    "Undergraduate degree": "Título de grado (licenciatura)",
    "Unemployed and actively looking for work": "Desempleado y buscando trabajo activamente",
    "Unemployed and not looking for work": "Desempleado y sin buscar trabajo",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Minoría visible (p. ej., surasiático, chino, negro)",
    "Woman": "Mujer",
    "Yes": "Sí",
    "Yukon": "Yukón",
    "Didn't look for job": "No busqué trabajo",
  },
  def: {
    "Family Sponsored": "Inmigró porque un familiar que ya estaba en Canadá lo patrocinó.",
    "Economic Immigrant": "Inmigró a través de un programa de trabajadores calificados o de negocios (p. ej., Entrada Exprés, Programa de Candidatos Provinciales).",
    "Refugee": "Vino a Canadá para protegerse de un peligro en su país de origen.",
    "Temporary Foreign Worker": "En Canadá con un permiso de trabajo vinculado a un empleador o un permiso de trabajo abierto.",
    "Refugee Claimant": "Ha solicitado protección como refugiado en Canadá y está esperando una decisión.",
    "Protected Person": "Canadá ya ha aceptado que usted necesita protección (estatus de refugiado/persona protegida aprobado).",
    "Temporary Resident Permit Holder": "Tiene un permiso especial para permanecer temporalmente cuando normalmente no estaría permitido.",
    "Canadian degree or training": "Completó un título o programa de formación en Canadá.",
    "Canadian work experience": "Ha trabajado para un empleador en Canadá.",
    "Employment or settlement centre": "Recibió ayuda de una organización que apoya a quienes buscan empleo o a los recién llegados (p. ej., Sault Community Career Center).",
    "Internship / volunteer experience": "Obtuvo experiencia laboral a través de una pasantía no remunerada, una colocación de corta duración o voluntariado.",
    "Local job boards": "Usó sitios web o anuncios que publican empleos en su zona (p. ej., el portal de empleo de AWIC).",
    "Personal contacts": "Recibió ayuda o información sobre empleos de familiares, amigos o personas que conoce personalmente.",
    "Professional network": "Usó contactos de su campo profesional, como colegas o mentores.",
    "Recognition of non-Canadian work experience": "Su experiencia laboral obtenida fuera de Canadá fue aceptada.",
    "Caregiving responsibilities": "Debe cuidar de niños o de familiares mayores que dependen de usted.",
    "Credentials not recognized": "Su educación, título o licencia obtenida fuera de Canadá no es aceptada por los empleadores canadienses.",
    "Discrimination of any kind": "Fue tratado injustamente por su raza, etnia, religión, género, acento, edad u otras características personales.",
    "Health issues": "Tiene problemas de salud física o mental que dificultan encontrar o conservar un empleo.",
    "Household responsibilities": "Debe encargarse de las tareas del hogar (cocinar, limpiar, administrar la casa).",
    "Lack of Canadian work experience": "Los empleadores piden experiencia laboral en Canadá, que usted aún no tiene.",
    "Lack of skills for available jobs": "Los empleos disponibles en su zona requieren habilidades o formación que usted no tiene actualmente.",
    "Language barriers": "Sus conocimientos de inglés (o francés) dificultan encontrar trabajo o superar las entrevistas.",
    "Limited job opportunities in preferred sector": "Hay pocos empleos en su campo o sector en su zona.",
    "Limited knowledge of local job market": "No está seguro de cómo encontrar empleo, qué empleadores están contratando o cómo funciona la contratación en su zona.",
    "Limited mentorship and job-matching support": "No tiene acceso a mentores ni a servicios que lo conecten con empleos adecuados.",
    "Limited professional network": "Conoce a pocas personas en su campo que puedan compartir oportunidades, referencias o consejos.",
    "Non-Canadian work experience not recognized": "Su experiencia laboral obtenida fuera de Canadá no es aceptada ni valorada por los empleadores canadienses.",
    "Childcare support": "Necesita ayuda con el cuidado de sus hijos para poder trabajar.",
    "Credential recognition support": "Necesita ayuda para que se acepten su educación o sus cualificaciones profesionales obtenidas fuera de Canadá.",
    "Language support": "Necesita ayuda para mejorar sus conocimientos de inglés (o francés).",
    "Local job market information": "Necesita información sobre qué empleadores están contratando, qué empleos hay disponibles y qué habilidades se demandan en su zona.",
    "Local training or certification": "Necesita formación o certificación ofrecida en su zona para calificar para los empleos disponibles.",
    "Mentorship support": "Necesita ponerse en contacto con personas con experiencia en su campo.",
    "Networking support": "Necesita ayuda para conocer a empleadores y profesionales.",
    "Resume/interview support": "Necesita ayuda para preparar su currículum, su carta de presentación o para practicar entrevistas de trabajo.",
    "Skills-to-job matching platform": "Necesita un servicio o herramienta que relacione sus habilidades con ofertas de empleo adecuadas.",
    "Training recommendations": "Necesita sugerencias sobre qué formación o cursos tomar para mejorar sus posibilidades de conseguir empleo.",
    "Doesn’t need employment income": "No necesita trabajar porque tiene otras fuentes de ingresos o apoyo financiero.",
    "Health reasons": "Tiene problemas de salud física o mental que dificultan encontrar o conservar un empleo.",
    "Immigration issues": "Su estatus migratorio o sus documentos (p. ej., permiso de trabajo, trámite de residencia permanente) le impiden trabajar.",
    "Limited suitable jobs": "Hay pocos empleos en su zona que coincidan con sus habilidades, experiencia o preferencias.",
    "Low wages": "Los empleos disponibles pagan muy poco como para que trabajar le valga la pena.",
    "Not qualified for available jobs": "Los empleos disponibles en su zona requieren educación, habilidades o certificaciones que usted no tiene actualmente.",
  },
  ui: {
    "% complete": " % completado",
    "Back to home": "Volver al inicio",
    "Back": "Atrás",
    "Definition:": "Definición:",
    "Email address": "Correo electrónico",
    "Finish to become a Survey Champion": "Termine para convertirse en Campeón de la Encuesta",
    "Five $50 local gift cards drawn monthly": "Cinco tarjetas de regalo locales de $50 sorteadas cada mes",
    "Go back": "Atrás",
    "Home": "Inicio",
    "Next 5 skills": "5 habilidades siguientes",
    "Next question": "Pregunta siguiente",
    "No matches": "Sin resultados",
    "Not sure": "No estoy seguro",
    "One moment.": "Un momento.",
    "Previous question": "Pregunta anterior",
    "Saving your response…": "Guardando su respuesta…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "Ocurrió un problema al conectar con el servidor. Sus respuestas siguen guardadas en este dispositivo; inténtelo de nuevo.",
    "Submit": "Enviar",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Gracias por su tiempo y su respuesta. Hizo una gran contribución al desarrollo de la comunidad.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Gracias — su respuesta ha sido registrada. No es necesario que la complete de nuevo.",
    "Try again": "Intentar de nuevo",
    "We couldn't save your response": "No pudimos guardar su respuesta",
    "Yes, enter me in the gift-card draw": "Sí, inscríbame en el sorteo de tarjetas de regalo",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Abrió un enlace de invitación personal, por lo que su participación puede registrarse con fines de recordatorio. Sus respuestas se mantienen confidenciales y se analizan de forma anonimizada.",
    "You're a Survey Champion": "Usted es un Campeón de la Encuesta",
    "You've already completed this survey": "Ya ha completado esta encuesta",
    "Your responses are anonymous.": "Sus respuestas son anónimas.",
    "more — keep typing to narrow": "más — siga escribiendo para acotar",
    "Search or select a language": "Busque o seleccione un idioma",
    "Type to search countries…": "Escriba para buscar un país…",
    "Type to search areas of study…": "Escriba para buscar un área de estudio…",
    "Type to search occupations…": "Escriba para buscar una ocupación…",
    "Type to search…": "Escriba para buscar…",
    "Select one…": "Seleccione una opción…",
    "1 · Lowest": "1 · más bajo",
    "5 · Highest": "5 · más alto",
    "Thank you for your interest.": "Gracias por su interés.",
    "Unfortunately you are not eligible to participate in the survey.": "Lamentablemente, no es elegible para participar en la encuesta.",
    "Thank you for starting the survey.": "Gracias por comenzar la encuesta.",
    "Unfortunately we cannot proceed without your consent.": "Lamentablemente, no podemos continuar sin su consentimiento.",
  },
};
