// DRAFT Finnish (fi) — pending fluent review. Keyed to exact source strings.
module.exports = {
  q: {
    language: "Valitse kieli jatkaaksesi",
    consent: "Vahvista, että olet vähintään 18-vuotias ja osallistut tähän kyselyyn vapaaehtoisesti.",
    eligible: "Muutitko Pohjois-Ontarioon asumaan syyskuun 2021 jälkeen?",
    moved_from: "Mistä muutit?",
    province: "Valitse provinssi, josta muutit",
    country_moved_from: "Valitse maa, josta muutit",
    gender: "Mikä on sukupuolesi?",
    age_group: "Mikä on ikäryhmäsi?",
    identity_groups: "Kuulutko johonkin seuraavista ryhmistä? Valitse kaikki sopivat.",
    immigration_category: "Valitse maahanmuuttoluokka",
    non_permanent_category: "Valitse ei-pysyvän asukkaan luokka",
    non_permanent_other: "Täsmennä",
    recent_credential: "Mikä on viimeisin suorittamasi tutkinto?",
    program_name: "Mikä oli pääasiallinen opintoalasi?",
    program_name_other: "Kirjoita pääasiallinen opintoalasi",
    program_location: "Missä suoritit tämän ohjelman?",
    highest_education: "Onko tämä ohjelma korkein koulutustasosi?",
    highest_credential: "Mikä on korkein koulutustasosi?",
    highest_program_name: "Mikä oli korkeimman koulutustasosi pääasiallinen opintoala?",
    highest_program_name_other: "Kirjoita korkeimman koulutustasosi pääasiallinen opintoala",
    current_program: "Mikä on nykyinen opinto-ohjelmasi?",
    current_program_name: "Mikä on pääasiallinen opintoalasi?",
    current_program_name_other: "Kirjoita pääasiallinen opintoalasi",
    employed_before: "Olitko töissä Kanadassa ennen Sault Ste. Marieen muuttoa?",
    previous_job_title: "Mikä oli viimeisin ammattisi ennen Sault Ste. Marieen muuttoa?",
    home_emp_before: "Olitko töissä kotimaassasi ennen Kanadaan tuloa?",
    home_country_job: "Mikä oli viimeisin ammattisi kotimaassasi?",
    employment_status: "Mikä seuraavista kuvaa parhaiten nykyistä työtilannettasi?",
    current_job_title: "Mikä on nykyisen työsi nimike?",
    intended_job: "Onko nykyinen työsi se, jota aioit tehdä?",
    intended_job_title: "Mikä on tavoittelemasi työn nimike?",
    job_search_help: "Mitkä seuraavista olivat hyödyllisiä työnhaussasi Pohjois-Ontariossa / Sault Ste. Mariessa? Valitse kaikki sopivat.",
    job_search_other: "Täsmennä",
    work_barriers: "Valitse kaikki sopivat esteet",
    work_barriers_other: "Täsmennä",
    work_support: "Millainen tuki auttaisi sinua saamaan haluamasi työn? Valitse kaikki sopivat.",
    work_support_other: "Täsmennä",
    unemployed_intended_job: "Mikä on tavoittelemasi työn nimike?",
    unemployed_barrier_gate: "Oletko kohdannut esteitä etsiessäsi työtä Sault Ste. Mariessa?",
    unemployment_reasons: "Valitse kaikki sopivat esteet",
    unemployment_reasons_other: "Täsmennä",
    not_looking_reasons: "Miksi et etsi työtä?",
    not_looking_other: "Täsmennä",
    student_working: "Oletko tällä hetkellä töissä?",
    student_current_job: "Mikä on nykyisen työsi nimike?",
    student_job_relevant: "Liittyykö nykyinen työsi nykyiseen opinto-ohjelmaasi?",
    student_job_help: "Mitkä seuraavista olivat hyödyllisiä työnhaussasi Pohjois-Ontariossa / Sault Ste. Mariessa? Valitse kaikki sopivat.",
    student_job_help_other: "Täsmennä",
    student_barrier_gate: "Oletko kohdannut esteitä etsiessäsi työtä Sault Ste. Mariessa?",
    student_barriers: "Valitse kaikki sopivat esteet",
    student_barriers_other: "Täsmennä",
    student_support: "Millainen tuki auttaisi sinua saamaan haluamasi työn? Valitse kaikki sopivat.",
    student_support_other: "Täsmennä",
    planned_intended_job: "Mikä on valmistumisen jälkeen tavoittelemasi työn nimike?",
    skills: "Miten arvioisit tasosi kussakin seuraavista taidoista?",
    gift_card_draw: "Haluatko osallistua lahjakorttiarvontaan? (Vain palkintotarkoituksiin)",
    "work_barrier.a": "Onko olemassa este, joka estää sinua tekemästä kokoaikatyötä?",
    "work_barrier.b": "Onko olemassa este, joka estää sinua saamasta haluamaasi työtä?",
    "work_barrier.c": "Onko olemassa este, joka estää sinua tekemästä kokoaikatyötä ja haluamaasi työtä?",
    "work_barrier.d": "Onko olemassa este, joka estää sinua saamasta kokoaikaista työtä?",
    "work_barrier.e": "Onko olemassa este, joka estää sinua tekemästä haluamaasi työtä?",
  },
  help: {
    skills: "1 = matalin, 2 = matala, 3 = kohtalainen, 4 = korkea, 5 = korkein, 0 = en ole varma",
  },
  o: {
    "85 or older": "85 tai vanhempi",
    "Advanced Diploma": "Ylempi diplomi",
    "Alberta": "Alberta",
    "Apprenticeship": "Oppisopimuskoulutus",
    "British Columbia": "Brittiläinen Kolumbia",
    "Canadian degree or training": "Kanadalainen tutkinto tai koulutus",
    "Canadian work experience": "Kanadalainen työkokemus",
    "Caregiving responsibilities": "Hoivavastuut",
    "Childcare support": "Lastenhoidon tuki",
    "College certificate": "College-todistus",
    "Credential recognition support": "Tuki tutkintojen tunnustamiseen",
    "Credentials not recognized": "Tutkintoja ei tunnusteta",
    "Diploma": "Diplomi",
    "Discrimination of any kind": "Minkä tahansa tyyppinen syrjintä",
    "Doesn’t need employment income": "Ei tarvitse työtuloja",
    "Economic Immigrant": "Taloudellinen maahanmuuttaja",
    "Employed casual (less than 10 hours/week)": "Satunnainen työ (alle 10 tuntia/viikko)",
    "Employed full time (30+ hours/week)": "Kokoaikatyö (30+ tuntia/viikko)",
    "Employed part time (10-30 hours/week)": "Osa-aikatyö (10-30 tuntia/viikko)",
    "Employment or settlement centre": "Työllisyys- tai kotoutumiskeskus",
    "Family Sponsored": "Perheen sponsoroima",
    "Health issues": "Terveysongelmat",
    "Health reasons": "Terveydelliset syyt",
    "High school diploma or equivalent": "Lukion päättötodistus tai vastaava",
    "Household responsibilities": "Kotitalouden vastuut",
    "Household work / Caregiver": "Kotityö / Hoitaja",
    "I agree": "Hyväksyn",
    "I didn't have a work permit": "Minulla ei ollut työlupaa",
    "I directly moved to Sault": "Muutin suoraan Saultiin",
    "I disagree": "En hyväksy",
    "Immigrant (permanent resident)": "Maahanmuuttaja (pysyvä asukas)",
    "Immigration issues": "Maahanmuutto-ongelmat",
    "In Canada": "Kanadassa",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Alkuperäiskansa (First Nations, Métis, Inuit/Inuk)",
    "International Student": "Kansainvälinen opiskelija",
    "Internship / volunteer experience": "Harjoittelu / vapaaehtoiskokemus",
    "Lack of Canadian work experience": "Kanadalaisen työkokemuksen puute",
    "Lack of skills for available jobs": "Taitojen puute tarjolla oleviin työpaikkoihin",
    "Language barriers": "Kielimuurit",
    "Language support": "Kielituki",
    "Limited job opportunities in preferred sector": "Rajalliset työmahdollisuudet halutulla alalla",
    "Limited knowledge of local job market": "Rajallinen tietämys paikallisista työmarkkinoista",
    "Limited mentorship and job-matching support": "Rajallinen mentorointi- ja työnvälitystuki",
    "Limited professional network": "Rajallinen ammatillinen verkosto",
    "Limited suitable jobs": "Rajallisesti sopivia työpaikkoja",
    "Local job boards": "Paikalliset työpaikkailmoitukset",
    "Local job market information": "Tietoa paikallisista työmarkkinoista",
    "Local training or certification": "Paikallinen koulutus tai sertifiointi",
    "Low wages": "Matalat palkat",
    "Man": "Mies",
    "Manitoba": "Manitoba",
    "Mentorship support": "Mentorointituki",
    "Networking support": "Verkostoitumistuki",
    "New Brunswick": "New Brunswick",
    "Newfoundland and Labrador": "Newfoundland ja Labrador",
    "No": "Ei",
    "Non-Canadian work experience not recognized": "Ei-kanadalaista työkokemusta ei tunnusteta",
    "Non-binary person or other gender": "Muunsukupuolinen henkilö tai muu sukupuoli",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Ei-pysyvä asukas (esim. työlupa, opiskelulupa, turvapaikanhakija)",
    "None of the above (do not select any other options)": "Ei mikään edellä mainituista (älä valitse muita vaihtoehtoja)",
    "Northwest Territories": "Luoteisterritoriot",
    "Not qualified for available jobs": "Ei pätevyyttä tarjolla oleviin työpaikkoihin",
    "Nova Scotia": "Nova Scotia",
    "Nunavut": "Nunavut",
    "On temporary leave from a job (e.g., maternity/parental leave)": "Väliaikaisella vapaalla työstä (esim. äitiys- tai vanhempainvapaa)",
    "Other": "Muu",
    "Other parts of Ontario": "Muut osat Ontariota",
    "Outside Canada": "Kanadan ulkopuolella",
    "Outside of Canada": "Kanadan ulkopuolelta",
    "Outside of Ontario but within Canada": "Ontarion ulkopuolelta mutta Kanadasta",
    "Personal contacts": "Henkilökohtaiset kontaktit",
    "Post-graduate degree (e.g., Master's)": "Jatkotutkinto (esim. maisteri)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Jatkotutkinto (esim. maisteri, tohtori, M.D.)",
    "Primary school": "Peruskoulu",
    "Prince Edward Island": "Prinssi Edwardin saari",
    "Professional network": "Ammatillinen verkosto",
    "Protected Person": "Suojeltu henkilö",
    "Quebec": "Quebec",
    "Recognition of non-Canadian work experience": "Ei-kanadalaisen työkokemuksen tunnustaminen",
    "Refugee": "Pakolainen",
    "Refugee Claimant": "Turvapaikanhakija",
    "Resume/interview support": "Tuki ansioluetteloon ja haastatteluihin",
    "Retired": "Eläkkeellä",
    "Saskatchewan": "Saskatchewan",
    "Self-employed": "Itsenäinen ammatinharjoittaja",
    "Skills-to-job matching platform": "Taitojen ja työpaikkojen yhdistämisalusta",
    "Social media (e.g., LinkedIn)": "Sosiaalinen media (esim. LinkedIn)",
    "Student or recent graduate": "Opiskelija tai vastavalmistunut",
    "Temporary Foreign Worker": "Tilapäinen ulkomainen työntekijä",
    "Temporary Resident Permit Holder": "Tilapäisen oleskeluluvan haltija",
    "Training recommendations": "Koulutussuositukset",
    "Unable to work": "Työkyvytön",
    "Undergraduate degree": "Kandidaatin tutkinto",
    "Unemployed and actively looking for work": "Työtön ja aktiivisesti työtä etsivä",
    "Unemployed and not looking for work": "Työtön eikä etsi työtä",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Näkyvä vähemmistö (esim. eteläaasialainen, kiinalainen, musta)",
    "Woman": "Nainen",
    "Yes": "Kyllä",
    "Yukon": "Yukon",
  },
  def: {
    "Family Sponsored": "Muutit maahan, koska Kanadassa jo oleva perheenjäsen sponsoroi sinua.",
    "Economic Immigrant": "Muutit maahan ammattitaitoisten työntekijöiden tai yrittäjien ohjelman kautta (esim. Express Entry, Provincial Nominee).",
    "Refugee": "Tulit Kanadaan suojaan kotimaasi vaaralta.",
    "Temporary Foreign Worker": "Kanadassa työnantajaan sidotulla työluvalla tai avoimella työluvalla.",
    "Refugee Claimant": "Olet hakenut Kanadalta pakolaissuojelua ja odotat päätöstä.",
    "Protected Person": "Kanada on jo hyväksynyt, että tarvitset suojelua (hyväksytty pakolais-/suojeluasema).",
    "Temporary Resident Permit Holder": "Sinulla on erityislupa jäädä tilapäisesti, kun se ei normaalisti olisi sallittua.",
    "Canadian degree or training": "Olet suorittanut tutkinnon tai koulutusohjelman Kanadassa.",
    "Canadian work experience": "Olet työskennellyt työnantajalle Kanadassa.",
    "Employment or settlement centre": "Sait apua järjestöltä, joka tukee työnhakijoita tai maahanmuuttajia (esim. Sault Community Career Center).",
    "Internship / volunteer experience": "Hankit työkokemusta palkattoman harjoittelun, lyhytaikaisen työjakson tai vapaaehtoistyön kautta.",
    "Local job boards": "Käytit verkkosivustoja tai ilmoituksia, joissa mainostetaan alueesi työpaikkoja (esim. AWIC:n työpaikkailmoitukset).",
    "Personal contacts": "Sait apua tai työvinkkejä perheeltä, ystäviltä tai henkilökohtaisesti tuntemiltasi ihmisiltä.",
    "Professional network": "Käytit oman alasi kontakteja, kuten kollegoita tai mentoreita.",
    "Recognition of non-Canadian work experience": "Kanadan ulkopuolella hankittu työkokemuksesi hyväksyttiin.",
    "Caregiving responsibilities": "Sinun on huolehdittava lapsista tai iäkkäistä perheenjäsenistä, jotka ovat riippuvaisia sinusta.",
    "Credentials not recognized": "Kanadan ulkopuolella hankittua koulutustasi, tutkintoasi tai lupaasi eivät kanadalaiset työnantajat hyväksy.",
    "Discrimination of any kind": "Sinua kohdeltiin epäoikeudenmukaisesti rotusi, etnisen taustasi, uskontosi, sukupuolesi, aksenttisi, ikäsi tai muiden henkilökohtaisten ominaisuuksien vuoksi.",
    "Health issues": "Sinulla on fyysisiä tai mielenterveydellisiä ongelmia, jotka vaikeuttavat työn löytämistä tai säilyttämistä.",
    "Household responsibilities": "Sinun on hoidettava kotitaloustyöt (ruoanlaitto, siivous, kodin pyörittäminen).",
    "Lack of Canadian work experience": "Työnantajat vaativat työkokemusta Kanadasta, jota sinulla ei vielä ole.",
    "Lack of skills for available jobs": "Alueesi tarjolla olevat työpaikat vaativat taitoja tai koulutusta, joita sinulla ei tällä hetkellä ole.",
    "Language barriers": "Englannin (tai ranskan) taitosi vaikeuttaa työn löytämistä tai haastatteluista läpi pääsemistä.",
    "Limited job opportunities in preferred sector": "Alueellasi on vähän työpaikkoja omalla alallasi tai toimialallasi.",
    "Limited knowledge of local job market": "Et ole varma, miten löytää töitä, ketkä työnantajat rekrytoivat tai miten rekrytointi alueellasi toimii.",
    "Limited mentorship and job-matching support": "Sinulla ei ole pääsyä mentoreihin tai palveluihin, jotka yhdistäisivät sinut sopiviin työpaikkoihin.",
    "Limited professional network": "Tunnet vain harvoja alasi ihmisiä, jotka voisivat jakaa työvinkkejä, suosituksia tai neuvoja.",
    "Non-Canadian work experience not recognized": "Kanadan ulkopuolella hankittua työkokemustasi eivät kanadalaiset työnantajat hyväksy tai arvosta.",
    "Childcare support": "Tarvitset apua lastesi hoitoon, jotta voit työskennellä.",
    "Credential recognition support": "Tarvitset apua saadaksesi Kanadan ulkopuolella hankitun koulutuksesi tai ammatilliset pätevyytesi hyväksytyiksi.",
    "Language support": "Tarvitset apua englannin (tai ranskan) taitosi parantamiseen.",
    "Local job market information": "Tarvitset tietoa siitä, ketkä työnantajat rekrytoivat, mitä työpaikkoja on tarjolla ja mitä taitoja alueellasi kysytään.",
    "Local training or certification": "Tarvitset alueellasi tarjottavaa koulutusta tai sertifiointia päteäksesi tarjolla oleviin työpaikkoihin.",
    "Mentorship support": "Tarvitset yhteyden oman alasi kokeneisiin ihmisiin.",
    "Networking support": "Tarvitset apua työnantajien ja ammattilaisten tapaamiseen.",
    "Resume/interview support": "Tarvitset apua ansioluettelosi ja hakemuskirjeesi laatimiseen tai haastatteluihin harjoitteluun.",
    "Skills-to-job matching platform": "Tarvitset palvelun tai työkalun, joka yhdistää taitosi sopiviin avoimiin työpaikkoihin.",
    "Training recommendations": "Tarvitset ehdotuksia siitä, mitä koulutusta tai kursseja kannattaisi suorittaa työnsaantimahdollisuuksiesi parantamiseksi.",
    "Doesn’t need employment income": "Sinun ei tarvitse työskennellä, koska sinulla on muita tulonlähteitä tai taloudellista tukea.",
    "Health reasons": "Sinulla on fyysisiä tai mielenterveydellisiä ongelmia, jotka vaikeuttavat työn löytämistä tai säilyttämistä.",
    "Immigration issues": "Maahanmuuttostatuksesi tai asiakirjasi (esim. työlupa, pysyvän oleskeluluvan käsittely) estävät sinua työskentelemästä.",
    "Limited suitable jobs": "Alueellasi on vähän työpaikkoja, jotka vastaavat taitojasi, kokemustasi tai toiveitasi.",
    "Low wages": "Tarjolla olevat työpaikat maksavat liian vähän, jotta työnteko olisi sinulle kannattavaa.",
    "Not qualified for available jobs": "Alueesi tarjolla olevat työpaikat vaativat koulutusta, taitoja tai sertifikaatteja, joita sinulla ei tällä hetkellä ole.",
  },
  ui: {
    "% complete": " % valmis",
    "Back to home": "Takaisin etusivulle",
    "Back": "Takaisin",
    "Consent is required to continue": "Jatkaminen edellyttää suostumusta",
    "Definition:": "Määritelmä:",
    "Email address": "Sähköpostiosoite",
    "Finish to become a Survey Champion": "Viimeistele tullaksesi kyselyn mestariksi",
    "Five $50 local gift cards drawn monthly": "Viisi 50 $ paikallista lahjakorttia arvotaan kuukausittain",
    "Go back": "Takaisin",
    "Go home": "Etusivulle",
    "Halfway there": "Puolivälissä",
    "Home": "Etusivu",
    "Next 5 skills": "Seuraavat 5 taitoa",
    "Next question": "Seuraava kysymys",
    "No matches": "Ei tuloksia",
    "Not sure": "En ole varma",
    "One moment.": "Hetki.",
    "Previous question": "Edellinen kysymys",
    "Saving your response…": "Tallennetaan vastaustasi…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "Palvelimeen yhdistämisessä tapahtui virhe. Vastauksesi ovat yhä tallessa tällä laitteella — yritä uudelleen.",
    "Submit": "Lähetä",
    "Thank you for sharing your experience.": "Kiitos, että jaoit kokemuksesi.",
    "Thank you for your time and response": "Kiitos ajastasi ja vastauksestasi",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Kiitos ajastasi ja vastauksestasi. Annoit suuren panoksen yhteisön kehittämiseen.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Kiitos — vastauksesi on tallennettu. Sitä ei tarvitse täyttää uudelleen.",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "Osallistuaksesi sinun on oltava vähintään 18-vuotias ja suostuttava osallistumaan. Jos haluat jatkaa, voit palata takaisin ja muuttaa vastaustasi.",
    "Try again": "Yritä uudelleen",
    "We couldn't save your response": "Emme voineet tallentaa vastaustasi",
    "Yes, enter me in the gift-card draw": "Kyllä, ilmoita minut lahjakorttiarvontaan",
    "You made a great contribution to the development of the community": "Annoit suuren panoksen yhteisön kehittämiseen",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Avasit henkilökohtaisen kutsulinkin, joten suorituksesi voidaan kirjata muistutuksia varten. Vastauksesi pidetään luottamuksellisina ja analysoidaan tunnistamattomassa muodossa.",
    "You're a Survey Champion": "Olet kyselyn mestari",
    "You've already completed this survey": "Olet jo täyttänyt tämän kyselyn",
    "Your responses are anonymous.": "Vastauksesi ovat nimettömiä.",
    "more — keep typing to narrow": "lisää — jatka kirjoittamista rajataksesi",
    "Search or select a language": "Hae tai valitse kieli",
    "Type to search countries…": "Kirjoita hakeaksesi maata…",
    "Type to search areas of study…": "Kirjoita hakeaksesi opintoalaa…",
    "Type to search occupations…": "Kirjoita hakeaksesi ammattia…",
    "Type to search…": "Kirjoita hakeaksesi…",
    "Select one…": "Valitse vaihtoehto…",
    "1 · Lowest": "1 · matalin",
    "5 · Highest": "5 · korkein",
  },
};
