// DRAFT French (fr) — pending fluent + ethics review. Keyed to exact source strings.
// Recovered from the shipped dictionary so French is rebuildable from a map like
// every other language (it originally had none).
module.exports = {
  q: {
    "language": "Sélectionnez une langue pour continuer",
    "consent": "Veuillez confirmer que vous avez au moins 18 ans et que vous acceptez de participer volontairement à ce sondage.",
    "eligible": "Avez-vous déménagé dans le Nord de l'Ontario après septembre 2021 pour y vivre ?",
    "moved_from": "D'où avez-vous déménagé ?",
    "province": "Veuillez sélectionner la province d'où vous avez déménagé",
    "country_moved_from": "Veuillez sélectionner le pays d'où vous avez déménagé",
    "gender": "Quel est votre genre ?",
    "age_group": "Quel est votre groupe d'âge ?",
    "identity_groups": "Vous identifiez-vous à l'un des groupes suivants ? Sélectionnez tout ce qui s'applique.",
    "immigration_category": "Sélectionnez votre catégorie d'immigration",
    "non_permanent_category": "Sélectionnez votre catégorie de résident non permanent",
    "non_permanent_other": "Veuillez préciser",
    "recent_credential": "Quel est le diplôme le plus récent que vous avez obtenu ?",
    "program_name": "Quel était votre principal domaine d'études ?",
    "program_name_other": "Veuillez saisir votre principal domaine d'études",
    "program_location": "Où avez-vous suivi ce programme ?",
    "highest_education": "Ce programme correspond-il à votre plus haut niveau d'études ?",
    "highest_credential": "Quel est votre plus haut niveau d'études ?",
    "highest_program_name": "Pour votre plus haut niveau d'études, quel était votre principal domaine d'études ?",
    "highest_program_name_other": "Veuillez saisir votre principal domaine d'études pour votre plus haut niveau d'études",
    "current_program": "Quel est votre programme d'études actuel ?",
    "current_program_name": "Quel est votre principal domaine d'études ?",
    "current_program_name_other": "Veuillez saisir votre principal domaine d'études",
    "employed_before": "Occupiez-vous un emploi au Canada avant de déménager à Sault Ste. Marie ?",
    "previous_job_title": "Quelle était votre dernière profession avant de déménager à Sault Ste. Marie ?",
    "home_emp_before": "Occupiez-vous un emploi dans votre pays d'origine avant de venir au Canada ?",
    "home_country_job": "Quelle était votre dernière profession dans votre pays d'origine ?",
    "employment_status": "Parmi les énoncés suivants, lequel décrit le mieux votre situation d'emploi actuelle ?",
    "current_job_title": "Quel est l'intitulé de votre emploi actuel ?",
    "intended_job": "Votre emploi actuel est-il celui que vous souhaitiez exercer ?",
    "intended_job_title": "Quel est l'intitulé de l'emploi que vous souhaitez exercer ?",
    "job_search_help": "Parmi les éléments suivants, lesquels vous ont été utiles dans votre recherche d'emploi dans le Nord de l'Ontario / à Sault Ste. Marie ? Sélectionnez tout ce qui s'applique.",
    "job_search_other": "Veuillez préciser",
    "work_barriers": "Sélectionnez tous les obstacles qui s'appliquent",
    "work_barriers_other": "Veuillez préciser",
    "work_support": "Quel type de soutien vous aiderait à obtenir l'emploi que vous souhaitez ? Sélectionnez tout ce qui s'applique.",
    "work_support_other": "Veuillez préciser",
    "unemployed_intended_job": "Quel est l'intitulé de l'emploi que vous souhaitez exercer ?",
    "unemployed_barrier_gate": "Avez-vous rencontré des obstacles dans votre recherche d'emploi à Sault Ste. Marie ?",
    "unemployment_reasons": "Sélectionnez tous les obstacles qui s'appliquent",
    "unemployment_reasons_other": "Veuillez préciser",
    "not_looking_reasons": "Pourquoi ne cherchez-vous pas d'emploi ?",
    "not_looking_other": "Veuillez préciser",
    "student_working": "Travaillez-vous actuellement ?",
    "student_current_job": "Quel est l'intitulé de votre emploi actuel ?",
    "student_job_relevant": "Votre emploi actuel est-il en lien avec votre programme d'études actuel ?",
    "student_job_help": "Parmi les éléments suivants, lesquels vous ont été utiles dans votre recherche d'emploi dans le Nord de l'Ontario / à Sault Ste. Marie ? Sélectionnez tout ce qui s'applique.",
    "student_job_help_other": "Veuillez préciser",
    "student_barrier_gate": "Avez-vous rencontré des obstacles dans votre recherche d'emploi à Sault Ste. Marie ?",
    "student_barriers": "Sélectionnez tous les obstacles qui s'appliquent",
    "student_barriers_other": "Veuillez préciser",
    "student_support": "Quel type de soutien vous aiderait à obtenir l'emploi que vous souhaitez ? Sélectionnez tout ce qui s'applique.",
    "student_support_other": "Veuillez préciser",
    "planned_intended_job": "Quel est l'intitulé de l'emploi que vous souhaitez exercer après l'obtention de votre diplôme ?",
    "skills": "Comment évalueriez-vous votre niveau pour chacune des compétences suivantes ?",
    "gift_card_draw": "Souhaitez-vous participer au tirage de cartes-cadeaux ? (À des fins de prix uniquement)",
    "work_barrier.a": "Y a-t-il un obstacle qui vous empêche de travailler à temps plein ?",
    "work_barrier.b": "Y a-t-il un obstacle qui vous empêche d'obtenir l'emploi que vous souhaitez ?",
    "work_barrier.c": "Y a-t-il un obstacle qui vous empêche de travailler à temps plein et d'exercer l'emploi que vous souhaitez ?",
    "work_barrier.d": "Y a-t-il un obstacle qui vous empêche d'obtenir un emploi à temps plein ?",
    "work_barrier.e": "Y a-t-il un obstacle qui vous empêche d'exercer l'emploi que vous souhaitez ?",
  },
  help: {
    "skills": "1 = le plus bas, 2 = bas, 3 = modéré, 4 = élevé, 5 = le plus élevé, 0 = incertain",
  },
  o: {
    "I agree": "J'accepte",
    "I disagree": "Je refuse",
    "Yes": "Oui",
    "No": "Non",
    "Other parts of Ontario": "D'autres régions de l'Ontario",
    "Outside of Ontario but within Canada": "À l'extérieur de l'Ontario mais au Canada",
    "Outside of Canada": "À l'extérieur du Canada",
    "Alberta": "Alberta",
    "British Columbia": "Colombie-Britannique",
    "Manitoba": "Manitoba",
    "New Brunswick": "Nouveau-Brunswick",
    "Newfoundland and Labrador": "Terre-Neuve-et-Labrador",
    "Northwest Territories": "Territoires du Nord-Ouest",
    "Nova Scotia": "Nouvelle-Écosse",
    "Nunavut": "Nunavut",
    "Prince Edward Island": "Île-du-Prince-Édouard",
    "Quebec": "Québec",
    "Saskatchewan": "Saskatchewan",
    "Yukon": "Yukon",
    "Woman": "Femme",
    "Man": "Homme",
    "Non-binary person or other gender": "Personne non binaire ou autre genre",
    "18-24": "18-24",
    "25-34": "25-34",
    "35-44": "35-44",
    "45-54": "45-54",
    "55-64": "55-64",
    "65-74": "65-74",
    "75-84": "75-84",
    "85 or older": "85 ans ou plus",
    "Immigrant (permanent resident)": "Immigrant (résident permanent)",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Autochtone (Premières Nations, Métis, Inuit/Inuk)",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Résident non permanent (p. ex. permis de travail, permis d'études, demandeur d'asile)",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Minorité visible (p. ex. Sud-Asiatique, Chinois, Noir)",
    "None of the above (do not select any other options)": "Aucune de ces réponses (ne sélectionnez aucune autre option)",
    "Economic Immigrant": "Immigrant économique",
    "Family Sponsored": "Parrainé par la famille",
    "Refugee": "Réfugié",
    "International Student": "Étudiant international",
    "Protected Person": "Personne protégée",
    "Refugee Claimant": "Demandeur d'asile",
    "Temporary Foreign Worker": "Travailleur étranger temporaire",
    "Temporary Resident Permit Holder": "Titulaire d'un permis de séjour temporaire",
    "Other": "Autre",
    "Primary school": "École primaire",
    "High school diploma or equivalent": "Diplôme d'études secondaires ou équivalent",
    "Apprenticeship": "Apprentissage",
    "College certificate": "Certificat collégial",
    "Diploma": "Diplôme",
    "Advanced Diploma": "Diplôme avancé",
    "Undergraduate degree": "Diplôme de premier cycle",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Diplôme d'études supérieures (p. ex. maîtrise, doctorat, M.D.)",
    "In Canada": "Au Canada",
    "Outside Canada": "À l'extérieur du Canada",
    "Post-graduate degree (e.g., Master's)": "Diplôme d'études supérieures (p. ex. maîtrise)",
    "I directly moved to Sault": "J'ai déménagé directement à Sault",
    "I didn't have a work permit": "Je n'avais pas de permis de travail",
    "Employed casual (less than 10 hours/week)": "Emploi occasionnel (moins de 10 heures/semaine)",
    "Employed full time (30+ hours/week)": "Emploi à temps plein (30 heures et plus/semaine)",
    "Employed part time (10-30 hours/week)": "Emploi à temps partiel (10 à 30 heures/semaine)",
    "Household work / Caregiver": "Travail domestique / Aidant",
    "On temporary leave from a job (e.g., maternity/parental leave)": "En congé temporaire d'un emploi (p. ex. congé de maternité ou parental)",
    "Retired": "Retraité",
    "Self-employed": "Travailleur autonome",
    "Student or recent graduate": "Étudiant ou diplômé récent",
    "Unable to work": "Incapable de travailler",
    "Unemployed and actively looking for work": "Sans emploi et à la recherche active d'un emploi",
    "Unemployed and not looking for work": "Sans emploi et ne cherchant pas d'emploi",
    "Canadian degree or training": "Diplôme ou formation canadienne",
    "Canadian work experience": "Expérience de travail canadienne",
    "Employment or settlement centre": "Centre d'emploi ou d'établissement",
    "Internship / volunteer experience": "Stage / expérience de bénévolat",
    "Local job boards": "Babillards d'emplois locaux",
    "Personal contacts": "Contacts personnels",
    "Professional network": "Réseau professionnel",
    "Recognition of non-Canadian work experience": "Reconnaissance de l'expérience de travail non canadienne",
    "Social media (e.g., LinkedIn)": "Médias sociaux (p. ex. LinkedIn)",
    "Caregiving responsibilities": "Responsabilités d'aidant",
    "Credentials not recognized": "Titres de compétence non reconnus",
    "Discrimination of any kind": "Discrimination de toute nature",
    "Health issues": "Problèmes de santé",
    "Household responsibilities": "Responsabilités familiales",
    "Lack of Canadian work experience": "Manque d'expérience de travail canadienne",
    "Lack of skills for available jobs": "Manque de compétences pour les emplois disponibles",
    "Language barriers": "Barrières linguistiques",
    "Limited job opportunities in preferred sector": "Possibilités d'emploi limitées dans le secteur souhaité",
    "Limited knowledge of local job market": "Connaissance limitée du marché du travail local",
    "Limited mentorship and job-matching support": "Soutien limité en mentorat et en jumelage d'emplois",
    "Limited professional network": "Réseau professionnel limité",
    "Childcare support": "Aide à la garde d'enfants",
    "Credential recognition support": "Soutien à la reconnaissance des titres de compétence",
    "Language support": "Soutien linguistique",
    "Local job market information": "Information sur le marché du travail local",
    "Local training or certification": "Formation ou certification locale",
    "Mentorship support": "Soutien en mentorat",
    "Networking support": "Soutien au réseautage",
    "Resume/interview support": "Soutien pour le CV et les entrevues",
    "Skills-to-job matching platform": "Plateforme de jumelage compétences-emplois",
    "Training recommendations": "Recommandations de formation",
    "Non-Canadian work experience not recognized": "Expérience de travail non canadienne non reconnue",
    "Doesn’t need employment income": "N'a pas besoin de revenu d'emploi",
    "Health reasons": "Raisons de santé",
    "Immigration issues": "Problèmes d'immigration",
    "Limited suitable jobs": "Emplois convenables limités",
    "Low wages": "Bas salaires",
    "Not qualified for available jobs": "Non qualifié pour les emplois disponibles",
  },
  def: {
    "Family Sponsored": "Vous avez immigré parce qu'un membre de votre famille déjà au Canada vous a parrainé.",
    "Economic Immigrant": "Vous avez immigré dans le cadre d'un programme de travailleurs qualifiés ou d'affaires (p. ex. Entrée express, Programme des candidats des provinces).",
    "Refugee": "Vous êtes venu au Canada pour être protégé d'un danger dans votre pays d'origine.",
    "Temporary Foreign Worker": "Au Canada avec un permis de travail lié à un employeur ou un permis de travail ouvert.",
    "Refugee Claimant": "Vous avez demandé l'asile au Canada et attendez une décision.",
    "Protected Person": "Le Canada a déjà reconnu que vous avez besoin de protection (statut de réfugié ou de personne protégée approuvé).",
    "Temporary Resident Permit Holder": "Vous détenez un permis spécial vous permettant de rester temporairement alors que ce ne serait normalement pas autorisé.",
    "Canadian degree or training": "Vous avez obtenu un diplôme ou suivi une formation au Canada.",
    "Canadian work experience": "Vous avez travaillé pour un employeur au Canada.",
    "Employment or settlement centre": "Vous avez reçu l'aide d'un organisme qui soutient les chercheurs d'emploi ou les nouveaux arrivants (p. ex. Sault Community Career Center).",
    "Internship / volunteer experience": "Vous avez acquis de l'expérience de travail grâce à un stage non rémunéré, à un placement de courte durée ou à du bénévolat.",
    "Local job boards": "Vous avez utilisé des sites Web ou des affichages qui annoncent des emplois dans votre région (p. ex. le babillard d'emplois AWIC).",
    "Personal contacts": "Vous avez obtenu de l'aide ou des pistes d'emploi de votre famille, de vos amis ou de personnes que vous connaissez personnellement.",
    "Professional network": "Vous avez utilisé des contacts de votre domaine professionnel, comme des collègues ou des mentors.",
    "Recognition of non-Canadian work experience": "Votre expérience de travail acquise à l'extérieur du Canada a été acceptée.",
    "Caregiving responsibilities": "Vous devez prendre soin d'enfants ou de membres âgés de votre famille qui dépendent de vous.",
    "Credentials not recognized": "Votre formation, votre diplôme ou votre permis obtenu à l'extérieur du Canada n'est pas accepté par les employeurs canadiens.",
    "Discrimination of any kind": "Vous avez été traité injustement en raison de votre race, de votre origine ethnique, de votre religion, de votre genre, de votre accent, de votre âge ou d'autres caractéristiques personnelles.",
    "Health issues": "Vous avez des problèmes de santé physique ou mentale qui rendent plus difficile de trouver ou de garder un emploi.",
    "Household responsibilities": "Vous devez gérer les tâches ménagères (cuisine, ménage, gestion du foyer).",
    "Lack of Canadian work experience": "Les employeurs exigent une expérience de travail au Canada, que vous n'avez pas encore.",
    "Lack of skills for available jobs": "Les emplois disponibles dans votre région exigent des compétences ou une formation que vous n'avez pas actuellement.",
    "Language barriers": "Vos compétences en anglais (ou en français) rendent plus difficile de trouver du travail ou de réussir les entrevues.",
    "Limited job opportunities in preferred sector": "Il y a peu d'emplois dans votre domaine ou votre secteur dans votre région.",
    "Limited knowledge of local job market": "Vous ne savez pas trop comment trouver un emploi, quels employeurs embauchent ou comment fonctionne l'embauche dans votre région.",
    "Limited mentorship and job-matching support": "Vous n'avez pas accès à des mentors ou à des services qui vous mettent en contact avec des emplois convenables.",
    "Limited professional network": "Vous connaissez peu de personnes dans votre domaine qui pourraient partager des pistes d'emploi, des références ou des conseils.",
    "Non-Canadian work experience not recognized": "Votre expérience de travail acquise à l'extérieur du Canada n'est pas acceptée ni valorisée par les employeurs canadiens.",
    "Childcare support": "Vous avez besoin d'aide pour la garde de vos enfants afin de pouvoir travailler.",
    "Credential recognition support": "Vous avez besoin d'aide pour faire reconnaître votre formation ou vos qualifications professionnelles obtenues à l'extérieur du Canada.",
    "Language support": "Vous avez besoin d'aide pour améliorer vos compétences en anglais (ou en français).",
    "Local job market information": "Vous avez besoin d'information sur les employeurs qui embauchent, les emplois disponibles et les compétences recherchées dans votre région.",
    "Local training or certification": "Vous avez besoin d'une formation ou d'une certification offerte dans votre région pour vous qualifier aux emplois disponibles.",
    "Mentorship support": "Vous avez besoin d'être mis en contact avec des personnes expérimentées de votre domaine.",
    "Networking support": "Vous avez besoin d'aide pour rencontrer des employeurs et des professionnels.",
    "Resume/interview support": "Vous avez besoin d'aide pour préparer votre CV, votre lettre de présentation ou pour vous exercer aux entrevues.",
    "Skills-to-job matching platform": "Vous avez besoin d'un service ou d'un outil qui associe vos compétences à des offres d'emploi convenables.",
    "Training recommendations": "Vous avez besoin de suggestions sur les formations ou les cours à suivre pour améliorer vos chances d'obtenir un emploi.",
    "Doesn’t need employment income": "Vous n'avez pas besoin de travailler parce que vous avez d'autres sources de revenu ou un soutien financier.",
    "Health reasons": "Vous avez des problèmes de santé physique ou mentale qui rendent plus difficile de trouver ou de garder un emploi.",
    "Immigration issues": "Votre statut d'immigration ou vos documents (p. ex. permis de travail, traitement de la résidence permanente) vous empêchent de travailler.",
    "Limited suitable jobs": "Il y a peu d'emplois dans votre région qui correspondent à vos compétences, à votre expérience ou à vos préférences.",
    "Low wages": "Les emplois disponibles paient trop peu pour que travailler en vaille la peine pour vous.",
    "Not qualified for available jobs": "Les emplois disponibles dans votre région exigent une formation, des compétences ou des certifications que vous n'avez pas actuellement.",
  },
  ui: {
    "Search or select a language": "Rechercher ou sélectionner une langue",
    "Type to search countries…": "Tapez pour rechercher un pays…",
    "Type to search areas of study…": "Tapez pour rechercher un domaine d'études…",
    "Type to search occupations…": "Tapez pour rechercher une profession…",
    "1 · Lowest": "1 · le plus bas",
    "5 · Highest": "5 · le plus élevé",
    "Type to search…": "Tapez pour rechercher…",
    "Select one…": "Sélectionnez une option…",
    "% complete": " % complété",
    "Finish to become a Survey Champion": "Terminez pour devenir un champion du sondage",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Vous avez ouvert un lien d'invitation personnel; votre participation peut donc être enregistrée à des fins de rappel. Vos réponses demeurent confidentielles et sont analysées de façon anonymisée.",
    "Your responses are anonymous.": "Vos réponses sont anonymes.",
    "Previous question": "Question précédente",
    "Next question": "Question suivante",
    "Next 5 skills": "5 compétences suivantes",
    "Back": "Retour",
    "Submit": "Soumettre",
    "Definition:": "Définition :",
    "No matches": "Aucun résultat",
    "more — keep typing to narrow": "de plus — continuez à taper pour affiner",
    "Not sure": "Incertain",
    "Yes, enter me in the gift-card draw": "Oui, inscrivez-moi au tirage de cartes-cadeaux",
    "Five $50 local gift cards drawn monthly": "Cinq cartes-cadeaux locales de 50 $ tirées chaque mois",
    "Email address": "Adresse courriel",
    "Consent is required to continue": "Le consentement est requis pour continuer",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "Pour participer, vous devez avoir au moins 18 ans et accepter de participer. Si vous souhaitez continuer, vous pouvez revenir en arrière et modifier votre réponse.",
    "Go back": "Retour",
    "Home": "Accueil",
    "You've already completed this survey": "Vous avez déjà rempli ce sondage",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Merci — votre réponse a été enregistrée. Il n'est pas nécessaire de la remplir à nouveau.",
    "Saving your response…": "Enregistrement de votre réponse…",
    "One moment.": "Un instant.",
    "You're a Survey Champion": "Vous êtes un champion du sondage",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Merci de votre temps et de votre réponse. Vous avez grandement contribué au développement de la communauté.",
    "Back to home": "Retour à l'accueil",
    "We couldn't save your response": "Nous n'avons pas pu enregistrer votre réponse",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "Une erreur s'est produite lors de la connexion au serveur. Vos réponses sont toujours enregistrées sur cet appareil — veuillez réessayer.",
    "Try again": "Réessayer",
    "Thank you for your interest.": "Merci de votre intérêt.",
    "Unfortunately you are not eligible to participate in the survey.": "Malheureusement, vous n'êtes pas admissible à participer à ce sondage.",
  },
};
