// DRAFT Gujarati (gu) — ⚠ MACHINE-QUALITY DRAFT. Requires native-speaker review
// before release. Keyed to exact source strings.
module.exports = {
  q: {
    language: "ચાલુ રાખવા માટે ભાષા પસંદ કરો",
    consent: "કૃપા કરીને પુષ્ટિ કરો કે તમે ઓછામાં ઓછા 18 વર્ષના છો અને સ્વેચ્છાએ આ સર્વેક્ષણમાં ભાગ લેવા સંમત છો.",
    eligible: "શું તમે સપ્ટેમ્બર 2021 પછી રહેવા માટે ઉત્તરી ઓન્ટારિયો આવ્યા હતા?",
    moved_from: "તમે ક્યાંથી આવ્યા છો?",
    province: "કૃપા કરીને તે પ્રાંત પસંદ કરો જ્યાંથી તમે આવ્યા છો",
    country_moved_from: "કૃપા કરીને તે દેશ પસંદ કરો જ્યાંથી તમે આવ્યા છો",
    gender: "તમારું લિંગ શું છે?",
    age_group: "તમારું વય જૂથ શું છે?",
    identity_groups: "શું તમે નીચેનામાંથી કોઈ જૂથ સાથે ઓળખ ધરાવો છો? લાગુ પડતા બધા વિકલ્પો પસંદ કરો.",
    immigration_category: "ઇમિગ્રેશન શ્રેણી પસંદ કરો",
    non_permanent_category: "બિન-કાયમી નિવાસી શ્રેણી પસંદ કરો",
    non_permanent_other: "કૃપા કરીને સ્પષ્ટ કરો",
    recent_credential: "તમે સૌથી તાજેતરમાં કઈ શૈક્ષણિક લાયકાત પૂર્ણ કરી છે?",
    program_name: "તમારા અભ્યાસનું મુખ્ય ક્ષેત્ર શું હતું?",
    program_name_other: "તમારા અભ્યાસનું મુખ્ય ક્ષેત્ર લખો",
    program_location: "તમે આ કાર્યક્રમ ક્યાં પૂર્ણ કર્યો?",
    highest_education: "શું આ કાર્યક્રમ તમારું શિક્ષણનું સર્વોચ્ચ સ્તર છે?",
    highest_credential: "તમારું શિક્ષણનું સર્વોચ્ચ સ્તર શું છે?",
    highest_program_name: "તમારા શિક્ષણના સર્વોચ્ચ સ્તર માટે, તમારા અભ્યાસનું મુખ્ય ક્ષેત્ર શું હતું?",
    highest_program_name_other: "તમારા શિક્ષણના સર્વોચ્ચ સ્તર માટે અભ્યાસનું મુખ્ય ક્ષેત્ર લખો",
    current_program: "તમારો વર્તમાન અભ્યાસ કાર્યક્રમ શું છે?",
    current_program_name: "તમારા અભ્યાસનું મુખ્ય ક્ષેત્ર શું છે?",
    current_program_name_other: "તમારા અભ્યાસનું મુખ્ય ક્ષેત્ર લખો",
    employed_before: "શું તમે સોલ્ટ સ્ટે. મેરી આવતા પહેલા કેનેડામાં નોકરી કરતા હતા?",
    previous_job_title: "સોલ્ટ સ્ટે. મેરી આવતા પહેલા તમારો છેલ્લો વ્યવસાય શું હતો?",
    home_emp_before: "શું તમે કેનેડા આવતા પહેલા તમારા વતન દેશમાં નોકરી કરતા હતા?",
    home_country_job: "તમારા વતન દેશમાં તમારો છેલ્લો વ્યવસાય શું હતો?",
    employment_status: "નીચેનામાંથી કયું તમારી વર્તમાન રોજગાર સ્થિતિનું શ્રેષ્ઠ વર્ણન કરે છે?",
    current_job_title: "તમારી વર્તમાન નોકરીનું પદનામ શું છે?",
    intended_job: "શું તમારી વર્તમાન નોકરી એ જ છે જે તમે કરવા માંગતા હતા?",
    intended_job_title: "તમે જે નોકરી કરવા માંગો છો તેનું પદનામ શું છે?",
    job_search_help: "ઉત્તરી ઓન્ટારિયો / સોલ્ટ સ્ટે. મેરીમાં તમારી નોકરીની શોધમાં નીચેનામાંથી કયા ઉપયોગી હતા? લાગુ પડતા બધા વિકલ્પો પસંદ કરો.",
    job_search_other: "કૃપા કરીને સ્પષ્ટ કરો",
    work_barriers: "લાગુ પડતા બધા અવરોધો પસંદ કરો",
    work_barriers_other: "કૃપા કરીને સ્પષ્ટ કરો",
    work_support: "કયા પ્રકારની સહાય તમને ઇચ્છિત નોકરી મેળવવામાં મદદ કરશે? લાગુ પડતા બધા વિકલ્પો પસંદ કરો.",
    work_support_other: "કૃપા કરીને સ્પષ્ટ કરો",
    unemployed_intended_job: "તમે જે નોકરી કરવા માંગો છો તેનું પદનામ શું છે?",
    unemployed_barrier_gate: "શું સોલ્ટ સ્ટે. મેરીમાં કામ શોધતી વખતે તમને કોઈ અવરોધનો સામનો કરવો પડ્યો?",
    unemployment_reasons: "લાગુ પડતા બધા અવરોધો પસંદ કરો",
    unemployment_reasons_other: "કૃપા કરીને સ્પષ્ટ કરો",
    not_looking_reasons: "તમે કામ કેમ શોધી રહ્યા નથી?",
    not_looking_other: "કૃપા કરીને સ્પષ્ટ કરો",
    student_working: "શું તમે હાલમાં કામ કરી રહ્યા છો?",
    student_current_job: "તમારી વર્તમાન નોકરીનું પદનામ શું છે?",
    student_job_relevant: "શું તમારી વર્તમાન નોકરી તમારા વર્તમાન અભ્યાસ કાર્યક્રમ સાથે સંબંધિત છે?",
    student_job_help: "ઉત્તરી ઓન્ટારિયો / સોલ્ટ સ્ટે. મેરીમાં તમારી નોકરીની શોધમાં નીચેનામાંથી કયા ઉપયોગી હતા? લાગુ પડતા બધા વિકલ્પો પસંદ કરો.",
    student_job_help_other: "કૃપા કરીને સ્પષ્ટ કરો",
    student_barrier_gate: "શું સોલ્ટ સ્ટે. મેરીમાં નોકરી શોધતી વખતે તમને કોઈ અવરોધનો સામનો કરવો પડ્યો?",
    student_barriers: "લાગુ પડતા બધા અવરોધો પસંદ કરો",
    student_barriers_other: "કૃપા કરીને સ્પષ્ટ કરો",
    student_support: "કયા પ્રકારની સહાય તમને ઇચ્છિત નોકરી મેળવવામાં મદદ કરશે? લાગુ પડતા બધા વિકલ્પો પસંદ કરો.",
    student_support_other: "કૃપા કરીને સ્પષ્ટ કરો",
    planned_intended_job: "સ્નાતક થયા પછી તમે જે નોકરી કરવા માંગો છો તેનું પદનામ શું છે?",
    skills: "તમે નીચેની દરેક કુશળતા માટે તમારા સ્તરનું મૂલ્યાંકન કેવી રીતે કરશો?",
    gift_card_draw: "શું તમે ગિફ્ટ કાર્ડ ડ્રોમાં ભાગ લેવા માંગો છો? (માત્ર ઇનામના હેતુ માટે)",
    "work_barrier.a": "શું કોઈ અવરોધ છે જે તમને પૂર્ણ સમય કામ કરતા રોકે છે?",
    "work_barrier.b": "શું કોઈ અવરોધ છે જે તમને ઇચ્છિત નોકરી મેળવતા રોકે છે?",
    "work_barrier.c": "શું કોઈ અવરોધ છે જે તમને પૂર્ણ સમય કામ કરતા અને ઇચ્છિત નોકરી કરતા રોકે છે?",
    "work_barrier.d": "શું કોઈ અવરોધ છે જે તમને પૂર્ણ સમયની નોકરી મેળવતા રોકે છે?",
    "work_barrier.e": "શું કોઈ અવરોધ છે જે તમને ઇચ્છિત નોકરી કરતા રોકે છે?",
  },
  help: {
    skills: "1 = સૌથી ઓછું, 2 = ઓછું, 3 = મધ્યમ, 4 = ઊંચું, 5 = સૌથી ઊંચું, 0 = ખાતરી નથી",
  },
  o: {
    "85 or older": "85 કે તેથી વધુ",
    "Advanced Diploma": "અદ્યતન ડિપ્લોમા",
    "Alberta": "આલ્બર્ટા",
    "Apprenticeship": "એપ્રેન્ટિસશિપ",
    "British Columbia": "બ્રિટિશ કોલંબિયા",
    "Canadian degree or training": "કેનેડિયન ડિગ્રી અથવા તાલીમ",
    "Canadian work experience": "કેનેડિયન કામનો અનુભવ",
    "Caregiving responsibilities": "સંભાળની જવાબદારીઓ",
    "Childcare support": "બાળ સંભાળ સહાય",
    "College certificate": "કોલેજ પ્રમાણપત્ર",
    "Credential recognition support": "લાયકાત માન્યતા સહાય",
    "Credentials not recognized": "લાયકાતો માન્ય નથી",
    "Diploma": "ડિપ્લોમા",
    "Discrimination of any kind": "કોઈપણ પ્રકારનો ભેદભાવ",
    "Doesn’t need employment income": "રોજગાર આવકની જરૂર નથી",
    "Economic Immigrant": "આર્થિક ઇમિગ્રન્ટ",
    "Employed casual (less than 10 hours/week)": "પ્રાસંગિક રોજગાર (અઠવાડિયે 10 કલાકથી ઓછું)",
    "Employed full time (30+ hours/week)": "પૂર્ણ સમયનો રોજગાર (અઠવાડિયે 30+ કલાક)",
    "Employed part time (10-30 hours/week)": "અંશકાલિક રોજગાર (અઠવાડિયે 10-30 કલાક)",
    "Employment or settlement centre": "રોજગાર અથવા વસાહત કેન્દ્ર",
    "Family Sponsored": "કુટુંબ દ્વારા પ્રાયોજિત",
    "Health issues": "આરોગ્ય સમસ્યાઓ",
    "Health reasons": "આરોગ્યના કારણો",
    "High school diploma or equivalent": "હાઈ સ્કૂલ ડિપ્લોમા અથવા સમકક્ષ",
    "Household responsibilities": "ઘરેલું જવાબદારીઓ",
    "Household work / Caregiver": "ઘરકામ / સંભાળ રાખનાર",
    "I agree": "હું સંમત છું",
    "I didn't have a work permit": "મારી પાસે વર્ક પરમિટ ન હતી",
    "I directly moved to Sault": "હું સીધો સોલ્ટ આવ્યો",
    "I disagree": "હું સંમત નથી",
    "Immigrant (permanent resident)": "ઇમિગ્રન્ટ (કાયમી નિવાસી)",
    "Immigration issues": "ઇમિગ્રેશન સમસ્યાઓ",
    "In Canada": "કેનેડામાં",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "સ્વદેશી (ફર્સ્ટ નેશન્સ, મેટિસ, ઇનુઇટ/ઇનુક)",
    "International Student": "આંતરરાષ્ટ્રીય વિદ્યાર્થી",
    "Internship / volunteer experience": "ઇન્ટર્નશિપ / સ્વયંસેવક અનુભવ",
    "Lack of Canadian work experience": "કેનેડિયન કામના અનુભવનો અભાવ",
    "Lack of skills for available jobs": "ઉપલબ્ધ નોકરીઓ માટે કુશળતાનો અભાવ",
    "Language barriers": "ભાષાકીય અવરોધો",
    "Language support": "ભાષા સહાય",
    "Limited job opportunities in preferred sector": "પસંદગીના ક્ષેત્રમાં મર્યાદિત નોકરીની તકો",
    "Limited knowledge of local job market": "સ્થાનિક નોકરી બજારનું મર્યાદિત જ્ઞાન",
    "Limited mentorship and job-matching support": "મર્યાદિત માર્ગદર્શન અને નોકરી-મેળ સહાય",
    "Limited professional network": "મર્યાદિત વ્યાવસાયિક નેટવર્ક",
    "Limited suitable jobs": "મર્યાદિત યોગ્ય નોકરીઓ",
    "Local job boards": "સ્થાનિક જોબ બોર્ડ",
    "Local job market information": "સ્થાનિક નોકરી બજારની માહિતી",
    "Local training or certification": "સ્થાનિક તાલીમ અથવા પ્રમાણપત્ર",
    "Low wages": "ઓછું વેતન",
    "Man": "પુરુષ",
    "Manitoba": "મેનિટોબા",
    "Mentorship support": "માર્ગદર્શન સહાય",
    "Networking support": "નેટવર્કિંગ સહાય",
    "New Brunswick": "ન્યુ બ્રન્સવિક",
    "Newfoundland and Labrador": "ન્યુફાઉન્ડલેન્ડ અને લેબ્રાડોર",
    "No": "ના",
    "Non-Canadian work experience not recognized": "બિન-કેનેડિયન કામનો અનુભવ માન્ય નથી",
    "Non-binary person or other gender": "બિન-દ્વિસંગી વ્યક્તિ અથવા અન્ય લિંગ",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "બિન-કાયમી નિવાસી (દા.ત., વર્ક પરમિટ, સ્ટડી પરમિટ, શરણાર્થી દાવેદાર)",
    "None of the above (do not select any other options)": "ઉપરોક્તમાંથી કોઈ નહીં (અન્ય કોઈ વિકલ્પ પસંદ ન કરો)",
    "Northwest Territories": "નોર્થવેસ્ટ ટેરિટરીઝ",
    "Not qualified for available jobs": "ઉપલબ્ધ નોકરીઓ માટે લાયક નથી",
    "Nova Scotia": "નોવા સ્કોશિયા",
    "Nunavut": "નુનાવુત",
    "On temporary leave from a job (e.g., maternity/parental leave)": "નોકરીમાંથી કામચલાઉ રજા પર (દા.ત., પ્રસૂતિ/વાલી રજા)",
    "Other": "અન્ય",
    "Other parts of Ontario": "ઓન્ટારિયોના અન્ય ભાગો",
    "Outside Canada": "કેનેડાની બહાર",
    "Outside of Canada": "કેનેડાની બહાર",
    "Outside of Ontario but within Canada": "ઓન્ટારિયોની બહાર પરંતુ કેનેડાની અંદર",
    "Personal contacts": "વ્યક્તિગત સંપર્કો",
    "Post-graduate degree (e.g., Master's)": "અનુસ્નાતક ડિગ્રી (દા.ત., માસ્ટર્સ)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "અનુસ્નાતક ડિગ્રી (દા.ત., માસ્ટર્સ, પીએચડી, એમડી)",
    "Primary school": "પ્રાથમિક શાળા",
    "Prince Edward Island": "પ્રિન્સ એડવર્ડ આઇલેન્ડ",
    "Professional network": "વ્યાવસાયિક નેટવર્ક",
    "Protected Person": "સંરક્ષિત વ્યક્તિ",
    "Quebec": "ક્વિબેક",
    "Recognition of non-Canadian work experience": "બિન-કેનેડિયન કામના અનુભવની માન્યતા",
    "Refugee": "શરણાર્થી",
    "Refugee Claimant": "શરણાર્થી દાવેદાર",
    "Resume/interview support": "રિઝ્યુમે/ઇન્ટરવ્યુ સહાય",
    "Retired": "નિવૃત્ત",
    "Saskatchewan": "સાસ્કાચેવન",
    "Self-employed": "સ્વ-રોજગાર",
    "Skills-to-job matching platform": "કુશળતા-થી-નોકરી મેળ પ્લેટફોર્મ",
    "Social media (e.g., LinkedIn)": "સોશિયલ મીડિયા (દા.ત., લિંક્ડઇન)",
    "Student or recent graduate": "વિદ્યાર્થી અથવા તાજેતરના સ્નાતક",
    "Temporary Foreign Worker": "કામચલાઉ વિદેશી કામદાર",
    "Temporary Resident Permit Holder": "કામચલાઉ નિવાસી પરમિટ ધારક",
    "Training recommendations": "તાલીમ ભલામણો",
    "Unable to work": "કામ કરવામાં અસમર્થ",
    "Undergraduate degree": "સ્નાતક ડિગ્રી",
    "Unemployed and actively looking for work": "બેરોજગાર અને સક્રિય રીતે કામ શોધી રહ્યા છે",
    "Unemployed and not looking for work": "બેરોજગાર અને કામ શોધી રહ્યા નથી",
    "Visible minority (e.g., South Asian, Chinese, Black)": "દૃશ્યમાન લઘુમતી (દા.ત., દક્ષિણ એશિયન, ચીની, અશ્વેત)",
    "Woman": "સ્ત્રી",
    "Yes": "હા",
    "Yukon": "યુકોન",
  },
  def: {
    "Family Sponsored": "તમે ઇમિગ્રેશન કર્યું કારણ કે કેનેડામાં પહેલેથી હાજર કુટુંબના સભ્યએ તમને પ્રાયોજિત કર્યા.",
    "Economic Immigrant": "તમે કુશળ-કામદાર અથવા વ્યવસાય કાર્યક્રમ દ્વારા ઇમિગ્રેશન કર્યું (દા.ત., એક્સપ્રેસ એન્ટ્રી, પ્રોવિન્શિયલ નોમિની).",
    "Refugee": "તમે તમારા વતન દેશમાં જોખમથી રક્ષણ માટે કેનેડા આવ્યા.",
    "Temporary Foreign Worker": "એમ્પ્લોયર સાથે જોડાયેલ વર્ક પરમિટ અથવા ખુલ્લી વર્ક પરમિટ પર કેનેડામાં.",
    "Refugee Claimant": "તમે કેનેડા પાસે શરણાર્થી રક્ષણ માંગ્યું છે અને નિર્ણયની રાહ જોઈ રહ્યા છો.",
    "Protected Person": "કેનેડાએ પહેલેથી સ્વીકાર્યું છે કે તમને રક્ષણની જરૂર છે (મંજૂર શરણાર્થી/સંરક્ષિત દરજ્જો).",
    "Temporary Resident Permit Holder": "તમારી પાસે કામચલાઉ રહેવા માટે વિશેષ પરમિટ છે જ્યારે સામાન્ય રીતે તેની મંજૂરી ન હોય.",
    "Employment or settlement agency": "એક સંસ્થા જે લોકોને કામ શોધવામાં મદદ કરે છે, અથવા નવા આવનારાઓને કેનેડામાં વસવામાં મદદ કરે છે.",
    "Recognition of experience": "એક એમ્પ્લોયર જે તમે અગાઉ મેળવેલા કામના અનુભવને સ્વીકારે અને મૂલ્ય આપે છે.",
    "Networking events": "એવા કાર્યક્રમો જ્યાં તમે નોકરીના સંપર્કો બનાવવા માટે તમારા ક્ષેત્રના લોકોને મળો છો.",
    "Lack of local experience": "તમે હજુ સુધી કેનેડા અથવા આ વિસ્તારમાં કામ કર્યું નથી, જે એમ્પ્લોયરો ઘણીવાર માંગે છે.",
    "Lack of Canadian experience": "તમે હજુ સુધી કેનેડા અથવા આ વિસ્તારમાં કામ કર્યું નથી, જે એમ્પ્લોયરો ઘણીવાર માંગે છે.",
    "Qualifications not recognized": "અન્ય દેશમાંથી તમારું શિક્ષણ, લાઇસન્સ અથવા અનુભવ અહીં સ્વીકારવામાં આવતો નથી.",
    "Credential recognition issue": "અન્ય દેશમાંથી તમારું શિક્ષણ, લાઇસન્સ અથવા અનુભવ અહીં સ્વીકારવામાં આવતો નથી.",
    "Experience not recognized": "અન્ય દેશમાંથી તમારું શિક્ષણ, લાઇસન્સ અથવા અનુભવ અહીં સ્વીકારવામાં આવતો નથી.",
    "Immigration restrictions": "તમારી પરમિટ અથવા દરજ્જાની શરતો તમે કરી શકો તે કામ અથવા કલાકોને મર્યાદિત કરે છે.",
    "Immigration status": "તમારી પરમિટ અથવા દરજ્જાની શરતો તમે કરી શકો તે કામ અથવા કલાકોને મર્યાદિત કરે છે.",
    "Skills mismatch": "તમારી કુશળતા સ્થાનિક રીતે ઉપલબ્ધ નોકરીઓ સાથે મેળ ખાતી નથી.",
    "Limited network": "તમે એવા ઘણા લોકોને ઓળખતા નથી જે તમને નોકરીઓ સાથે જોડી શકે.",
    "Credential recognition": "કેનેડામાં તમારા વિદેશી શિક્ષણ અથવા લાઇસન્સને માન્યતા અપાવવામાં મદદ.",
    "Job matching": "એક સેવા જે તમને યોગ્ય નોકરીની તકો સાથે જોડે છે.",
    "Training matching": "એક સેવા જે તમને યોગ્ય તાલીમ કાર્યક્રમો સાથે જોડે છે.",
  },
  ui: {
    "% complete": "% પૂર્ણ",
    "Back to home": "હોમ પર પાછા જાઓ",
    "Back": "પાછળ",
    "Consent is required to continue": "ચાલુ રાખવા માટે સંમતિ જરૂરી છે",
    "Definition:": "વ્યાખ્યા:",
    "Email address": "ઇમેઇલ સરનામું",
    "Finish to become a Survey Champion": "સર્વેક્ષણ ચેમ્પિયન બનવા માટે પૂર્ણ કરો",
    "Five $50 local gift cards drawn monthly": "દર મહિને $50 ના પાંચ સ્થાનિક ગિફ્ટ કાર્ડ ડ્રો કરવામાં આવે છે",
    "Go back": "પાછા જાઓ",
    "Go home": "હોમ પર જાઓ",
    "Halfway there": "અડધો રસ્તો પૂર્ણ",
    "Home": "હોમ",
    "Next 5 skills": "આગામી 5 કુશળતા",
    "Next question": "આગળનો પ્રશ્ન",
    "No matches": "કોઈ મેળ નથી",
    "Not sure": "ખાતરી નથી",
    "One moment.": "એક ક્ષણ.",
    "Previous question": "પાછલો પ્રશ્ન",
    "Saving your response…": "તમારો પ્રતિસાદ સાચવવામાં આવી રહ્યો છે…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "સર્વર સાથે જોડાવામાં સમસ્યા આવી. તમારા જવાબો હજુ પણ આ ઉપકરણ પર સાચવેલા છે — કૃપા કરીને ફરી પ્રયાસ કરો.",
    "Submit": "સબમિટ કરો",
    "Thank you for sharing your experience.": "તમારો અનુભવ શેર કરવા બદલ આભાર.",
    "Thank you for your time and response": "તમારા સમય અને પ્રતિસાદ બદલ આભાર",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "તમારા સમય અને પ્રતિસાદ બદલ આભાર. તમે સમુદાયના વિકાસમાં મોટું યોગદાન આપ્યું.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "આભાર — તમારો પ્રતિસાદ નોંધવામાં આવ્યો છે. તેને ફરીથી ભરવાની જરૂર નથી.",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "ભાગ લેવા માટે, તમારી ઉંમર ઓછામાં ઓછી 18 વર્ષ હોવી જોઈએ અને તમારે ભાગ લેવા સંમત થવું જોઈએ. જો તમે ચાલુ રાખવા માંગતા હો, તો તમે પાછા જઈને તમારો જવાબ બદલી શકો છો.",
    "Try again": "ફરી પ્રયાસ કરો",
    "We couldn't save your response": "અમે તમારો પ્રતિસાદ સાચવી શક્યા નહીં",
    "Yes, enter me in the gift-card draw": "હા, મને ગિફ્ટ કાર્ડ ડ્રોમાં સામેલ કરો",
    "You made a great contribution to the development of the community": "તમે સમુદાયના વિકાસમાં મોટું યોગદાન આપ્યું",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "તમે વ્યક્તિગત આમંત્રણ લિંક ખોલી છે, તેથી રિમાઇન્ડરના હેતુ માટે તમારું પૂર્ણ થવું નોંધાઈ શકે છે. તમારા પ્રતિસાદો ગોપનીય રાખવામાં આવે છે અને ઓળખ-રહિત સ્વરૂપમાં વિશ્લેષણ કરવામાં આવે છે.",
    "You're a Survey Champion": "તમે સર્વેક્ષણ ચેમ્પિયન છો",
    "You've already completed this survey": "તમે પહેલેથી જ આ સર્વેક્ષણ પૂર્ણ કરી લીધું છે",
    "Your responses are anonymous.": "તમારા પ્રતિસાદો અનામી છે.",
    "more — keep typing to narrow": "વધુ — સંકુચિત કરવા માટે ટાઇપ કરતા રહો",
    "Search or select a language": "ભાષા શોધો અથવા પસંદ કરો",
    "Type to search countries…": "દેશ શોધવા માટે ટાઇપ કરો…",
    "Type to search areas of study…": "અભ્યાસ ક્ષેત્ર શોધવા માટે ટાઇપ કરો…",
    "Type to search occupations…": "વ્યવસાય શોધવા માટે ટાઇપ કરો…",
    "Type to search…": "શોધવા માટે ટાઇપ કરો…",
    "Select one…": "એક પસંદ કરો…",
    "1 · Lowest": "1 · સૌથી ઓછું",
    "5 · Highest": "5 · સૌથી ઊંચું",
  },
};
