// DRAFT Hindi (hi) — ⚠ MACHINE-QUALITY DRAFT. Requires native-speaker review
// before release. Keyed to exact source strings.
module.exports = {
  q: {
    language: "जारी रखने के लिए भाषा चुनें",
    consent: "कृपया पुष्टि करें कि आप कम से कम 18 वर्ष के हैं और स्वेच्छा से इस सर्वेक्षण में भाग लेने के लिए सहमत हैं।",
    eligible: "क्या आप सितंबर 2021 के बाद रहने के लिए उत्तरी ओंटारियो आए थे?",
    moved_from: "आप कहाँ से आए हैं?",
    province: "कृपया वह प्रांत चुनें जहाँ से आप आए हैं",
    country_moved_from: "कृपया वह देश चुनें जहाँ से आप आए हैं",
    gender: "आपका लिंग क्या है?",
    age_group: "आपका आयु वर्ग क्या है?",
    identity_groups: "क्या आप निम्नलिखित में से किसी समूह से पहचान रखते हैं? सभी लागू विकल्प चुनें।",
    immigration_category: "आप्रवासन श्रेणी चुनें",
    non_permanent_category: "गैर-स्थायी निवासी श्रेणी चुनें",
    non_permanent_other: "कृपया निर्दिष्ट करें",
    recent_credential: "आपने सबसे हाल ही में कौन सी शैक्षणिक योग्यता पूरी की है?",
    program_name: "आपके अध्ययन का मुख्य क्षेत्र क्या था?",
    program_name_other: "अपने अध्ययन का मुख्य क्षेत्र लिखें",
    program_location: "आपने यह कार्यक्रम कहाँ पूरा किया?",
    highest_education: "क्या यह कार्यक्रम आपकी शिक्षा का उच्चतम स्तर है?",
    highest_credential: "आपकी शिक्षा का उच्चतम स्तर क्या है?",
    highest_program_name: "अपनी शिक्षा के उच्चतम स्तर के लिए, आपके अध्ययन का मुख्य क्षेत्र क्या था?",
    highest_program_name_other: "अपनी शिक्षा के उच्चतम स्तर के लिए अध्ययन का मुख्य क्षेत्र लिखें",
    current_program: "आपका वर्तमान अध्ययन कार्यक्रम क्या है?",
    current_program_name: "आपके अध्ययन का मुख्य क्षेत्र क्या है?",
    current_program_name_other: "अपने अध्ययन का मुख्य क्षेत्र लिखें",
    employed_before: "क्या आप सॉल्ट स्टे. मैरी आने से पहले कनाडा में कार्यरत थे?",
    previous_job_title: "सॉल्ट स्टे. मैरी आने से पहले आपका अंतिम व्यवसाय क्या था?",
    home_emp_before: "क्या आप कनाडा आने से पहले अपने गृह देश में कार्यरत थे?",
    home_country_job: "आपके गृह देश में आपका अंतिम व्यवसाय क्या था?",
    employment_status: "निम्नलिखित में से कौन सा आपकी वर्तमान रोजगार स्थिति का सबसे अच्छा वर्णन करता है?",
    current_job_title: "आपकी वर्तमान नौकरी का पदनाम क्या है?",
    intended_job: "क्या आपकी वर्तमान नौकरी वही है जो आप करना चाहते थे?",
    intended_job_title: "आप जो नौकरी करना चाहते हैं उसका पदनाम क्या है?",
    job_search_help: "उत्तरी ओंटारियो / सॉल्ट स्टे. मैरी में आपकी नौकरी खोज में निम्नलिखित में से कौन उपयोगी थे? सभी लागू विकल्प चुनें।",
    job_search_other: "कृपया निर्दिष्ट करें",
    work_barriers: "सभी लागू बाधाएँ चुनें",
    work_barriers_other: "कृपया निर्दिष्ट करें",
    work_support: "किस प्रकार की सहायता आपको मनचाही नौकरी पाने में मदद करेगी? सभी लागू विकल्प चुनें।",
    work_support_other: "कृपया निर्दिष्ट करें",
    unemployed_intended_job: "आप जो नौकरी करना चाहते हैं उसका पदनाम क्या है?",
    unemployed_barrier_gate: "क्या सॉल्ट स्टे. मैरी में काम की तलाश करते समय आपको किसी बाधा का सामना करना पड़ा?",
    unemployment_reasons: "सभी लागू बाधाएँ चुनें",
    unemployment_reasons_other: "कृपया निर्दिष्ट करें",
    not_looking_reasons: "आप काम क्यों नहीं खोज रहे हैं?",
    not_looking_other: "कृपया निर्दिष्ट करें",
    student_working: "क्या आप वर्तमान में काम कर रहे हैं?",
    student_current_job: "आपकी वर्तमान नौकरी का पदनाम क्या है?",
    student_job_relevant: "क्या आपकी वर्तमान नौकरी आपके वर्तमान अध्ययन कार्यक्रम से संबंधित है?",
    student_job_help: "उत्तरी ओंटारियो / सॉल्ट स्टे. मैरी में आपकी नौकरी खोज में निम्नलिखित में से कौन उपयोगी थे? सभी लागू विकल्प चुनें।",
    student_job_help_other: "कृपया निर्दिष्ट करें",
    student_barrier_gate: "क्या सॉल्ट स्टे. मैरी में नौकरी की तलाश करते समय आपको किसी बाधा का सामना करना पड़ा?",
    student_barriers: "सभी लागू बाधाएँ चुनें",
    student_barriers_other: "कृपया निर्दिष्ट करें",
    student_support: "किस प्रकार की सहायता आपको मनचाही नौकरी पाने में मदद करेगी? सभी लागू विकल्प चुनें।",
    student_support_other: "कृपया निर्दिष्ट करें",
    planned_intended_job: "स्नातक होने के बाद आप जो नौकरी करना चाहते हैं उसका पदनाम क्या है?",
    skills: "आप निम्नलिखित प्रत्येक कौशल के लिए अपने स्तर का मूल्यांकन कैसे करेंगे?",
    gift_card_draw: "क्या आप उपहार कार्ड ड्रॉ में भाग लेना चाहते हैं? (केवल पुरस्कार उद्देश्यों के लिए)",
    "work_barrier.a": "क्या कोई बाधा है जो आपको पूर्णकालिक काम करने से रोकती है?",
    "work_barrier.b": "क्या कोई बाधा है जो आपको मनचाही नौकरी पाने से रोकती है?",
    "work_barrier.c": "क्या कोई बाधा है जो आपको पूर्णकालिक काम करने और मनचाही नौकरी करने से रोकती है?",
    "work_barrier.d": "क्या कोई बाधा है जो आपको पूर्णकालिक नौकरी पाने से रोकती है?",
    "work_barrier.e": "क्या कोई बाधा है जो आपको मनचाही नौकरी करने से रोकती है?",
  },
  help: {
    skills: "1 = सबसे कम, 2 = कम, 3 = मध्यम, 4 = उच्च, 5 = सबसे अधिक, 0 = निश्चित नहीं",
  },
  o: {
    "85 or older": "85 या उससे अधिक",
    "Advanced Diploma": "उन्नत डिप्लोमा",
    "Alberta": "अल्बर्टा",
    "Apprenticeship": "प्रशिक्षुता",
    "British Columbia": "ब्रिटिश कोलंबिया",
    "Canadian degree or training": "कनाडाई डिग्री या प्रशिक्षण",
    "Canadian work experience": "कनाडाई कार्य अनुभव",
    "Caregiving responsibilities": "देखभाल की जिम्मेदारियाँ",
    "Childcare support": "बाल देखभाल सहायता",
    "College certificate": "कॉलेज प्रमाणपत्र",
    "Credential recognition support": "योग्यता मान्यता सहायता",
    "Credentials not recognized": "योग्यताएँ मान्यता प्राप्त नहीं",
    "Diploma": "डिप्लोमा",
    "Discrimination of any kind": "किसी भी प्रकार का भेदभाव",
    "Doesn’t need employment income": "रोजगार आय की आवश्यकता नहीं",
    "Economic Immigrant": "आर्थिक आप्रवासी",
    "Employed casual (less than 10 hours/week)": "अनियमित रोजगार (10 घंटे/सप्ताह से कम)",
    "Employed full time (30+ hours/week)": "पूर्णकालिक रोजगार (30+ घंटे/सप्ताह)",
    "Employed part time (10-30 hours/week)": "अंशकालिक रोजगार (10-30 घंटे/सप्ताह)",
    "Employment or settlement centre": "रोजगार या बसावट केंद्र",
    "Family Sponsored": "परिवार द्वारा प्रायोजित",
    "Health issues": "स्वास्थ्य समस्याएँ",
    "Health reasons": "स्वास्थ्य कारण",
    "High school diploma or equivalent": "हाई स्कूल डिप्लोमा या समकक्ष",
    "Household responsibilities": "घरेलू जिम्मेदारियाँ",
    "Household work / Caregiver": "घरेलू कार्य / देखभालकर्ता",
    "I agree": "मैं सहमत हूँ",
    "I didn't have a work permit": "मेरे पास कार्य परमिट नहीं था",
    "I directly moved to Sault": "मैं सीधे सॉल्ट आया",
    "I disagree": "मैं सहमत नहीं हूँ",
    "Immigrant (permanent resident)": "आप्रवासी (स्थायी निवासी)",
    "Immigration issues": "आप्रवासन संबंधी समस्याएँ",
    "In Canada": "कनाडा में",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "स्वदेशी (फर्स्ट नेशंस, मेटिस, इनुइट/इनुक)",
    "International Student": "अंतर्राष्ट्रीय छात्र",
    "Internship / volunteer experience": "इंटर्नशिप / स्वयंसेवी अनुभव",
    "Lack of Canadian work experience": "कनाडाई कार्य अनुभव की कमी",
    "Lack of skills for available jobs": "उपलब्ध नौकरियों के लिए कौशल की कमी",
    "Language barriers": "भाषा संबंधी बाधाएँ",
    "Language support": "भाषा सहायता",
    "Limited job opportunities in preferred sector": "पसंदीदा क्षेत्र में सीमित नौकरी के अवसर",
    "Limited knowledge of local job market": "स्थानीय नौकरी बाजार का सीमित ज्ञान",
    "Limited mentorship and job-matching support": "सीमित मार्गदर्शन और नौकरी-मिलान सहायता",
    "Limited professional network": "सीमित पेशेवर नेटवर्क",
    "Limited suitable jobs": "सीमित उपयुक्त नौकरियाँ",
    "Local job boards": "स्थानीय नौकरी बोर्ड",
    "Local job market information": "स्थानीय नौकरी बाजार की जानकारी",
    "Local training or certification": "स्थानीय प्रशिक्षण या प्रमाणन",
    "Low wages": "कम वेतन",
    "Man": "पुरुष",
    "Manitoba": "मैनिटोबा",
    "Mentorship support": "मार्गदर्शन सहायता",
    "Networking support": "नेटवर्किंग सहायता",
    "New Brunswick": "न्यू ब्रंसविक",
    "Newfoundland and Labrador": "न्यूफ़ाउंडलैंड और लैब्राडोर",
    "No": "नहीं",
    "Non-Canadian work experience not recognized": "गैर-कनाडाई कार्य अनुभव मान्यता प्राप्त नहीं",
    "Non-binary person or other gender": "गैर-द्विआधारी व्यक्ति या अन्य लिंग",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "गैर-स्थायी निवासी (जैसे, कार्य परमिट, अध्ययन परमिट, शरणार्थी आवेदक)",
    "None of the above (do not select any other options)": "उपरोक्त में से कोई नहीं (कोई अन्य विकल्प न चुनें)",
    "Northwest Territories": "नॉर्थवेस्ट टेरिटरीज़",
    "Not qualified for available jobs": "उपलब्ध नौकरियों के लिए योग्य नहीं",
    "Nova Scotia": "नोवा स्कोटिया",
    "Nunavut": "नुनावुत",
    "On temporary leave from a job (e.g., maternity/parental leave)": "नौकरी से अस्थायी अवकाश पर (जैसे, मातृत्व/अभिभावक अवकाश)",
    "Other": "अन्य",
    "Other parts of Ontario": "ओंटारियो के अन्य भाग",
    "Outside Canada": "कनाडा के बाहर",
    "Outside of Canada": "कनाडा के बाहर",
    "Outside of Ontario but within Canada": "ओंटारियो के बाहर लेकिन कनाडा के भीतर",
    "Personal contacts": "व्यक्तिगत संपर्क",
    "Post-graduate degree (e.g., Master's)": "स्नातकोत्तर डिग्री (जैसे, मास्टर्स)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "स्नातकोत्तर डिग्री (जैसे, मास्टर्स, पीएचडी, एमडी)",
    "Primary school": "प्राथमिक विद्यालय",
    "Prince Edward Island": "प्रिंस एडवर्ड आइलैंड",
    "Professional network": "पेशेवर नेटवर्क",
    "Protected Person": "संरक्षित व्यक्ति",
    "Quebec": "क्यूबेक",
    "Recognition of non-Canadian work experience": "गैर-कनाडाई कार्य अनुभव की मान्यता",
    "Refugee": "शरणार्थी",
    "Refugee Claimant": "शरणार्थी आवेदक",
    "Resume/interview support": "रिज्यूमे/साक्षात्कार सहायता",
    "Retired": "सेवानिवृत्त",
    "Saskatchewan": "सस्केचेवान",
    "Self-employed": "स्वरोजगार",
    "Skills-to-job matching platform": "कौशल-से-नौकरी मिलान मंच",
    "Social media (e.g., LinkedIn)": "सोशल मीडिया (जैसे, लिंक्डइन)",
    "Student or recent graduate": "छात्र या हाल ही में स्नातक",
    "Temporary Foreign Worker": "अस्थायी विदेशी कर्मचारी",
    "Temporary Resident Permit Holder": "अस्थायी निवासी परमिट धारक",
    "Training recommendations": "प्रशिक्षण सिफारिशें",
    "Unable to work": "काम करने में असमर्थ",
    "Undergraduate degree": "स्नातक डिग्री",
    "Unemployed and actively looking for work": "बेरोजगार और सक्रिय रूप से काम की तलाश में",
    "Unemployed and not looking for work": "बेरोजगार और काम की तलाश नहीं",
    "Visible minority (e.g., South Asian, Chinese, Black)": "दृश्यमान अल्पसंख्यक (जैसे, दक्षिण एशियाई, चीनी, अश्वेत)",
    "Woman": "महिला",
    "Yes": "हाँ",
    "Yukon": "युकोन",
  },
  def: {
    "Family Sponsored": "आपने आप्रवास किया क्योंकि कनाडा में पहले से मौजूद परिवार के किसी सदस्य ने आपको प्रायोजित किया।",
    "Economic Immigrant": "आपने कुशल-कर्मचारी या व्यवसाय कार्यक्रम (जैसे, एक्सप्रेस एंट्री, प्रोविंशियल नॉमिनी) के माध्यम से आप्रवास किया।",
    "Refugee": "आप अपने गृह देश में खतरे से सुरक्षा के लिए कनाडा आए।",
    "Temporary Foreign Worker": "किसी नियोक्ता से जुड़े कार्य परमिट या खुले कार्य परमिट पर कनाडा में।",
    "Refugee Claimant": "आपने कनाडा से शरणार्थी सुरक्षा माँगी है और निर्णय की प्रतीक्षा कर रहे हैं।",
    "Protected Person": "कनाडा ने पहले ही स्वीकार कर लिया है कि आपको सुरक्षा की आवश्यकता है (स्वीकृत शरणार्थी/संरक्षित स्थिति)।",
    "Temporary Resident Permit Holder": "आपके पास अस्थायी रूप से रहने के लिए विशेष परमिट है जब सामान्यतः इसकी अनुमति नहीं होती।",
    "Employment or settlement agency": "एक संगठन जो लोगों को काम खोजने में मदद करता है, या नए आगंतुकों को कनाडा में बसने में मदद करता है।",
    "Recognition of experience": "एक नियोक्ता जो आपके पहले प्राप्त कार्य अनुभव को स्वीकार और महत्व देता है।",
    "Networking events": "ऐसे आयोजन जहाँ आप नौकरी के संपर्क बनाने के लिए अपने क्षेत्र के लोगों से मिलते हैं।",
    "Lack of local experience": "आपने अभी तक कनाडा या इस क्षेत्र में काम नहीं किया है, जो नियोक्ता अक्सर माँगते हैं।",
    "Lack of Canadian experience": "आपने अभी तक कनाडा या इस क्षेत्र में काम नहीं किया है, जो नियोक्ता अक्सर माँगते हैं।",
    "Qualifications not recognized": "दूसरे देश से आपकी शिक्षा, लाइसेंस या अनुभव यहाँ स्वीकार नहीं किया जाता।",
    "Credential recognition issue": "दूसरे देश से आपकी शिक्षा, लाइसेंस या अनुभव यहाँ स्वीकार नहीं किया जाता।",
    "Experience not recognized": "दूसरे देश से आपकी शिक्षा, लाइसेंस या अनुभव यहाँ स्वीकार नहीं किया जाता।",
    "Immigration restrictions": "आपके परमिट या स्थिति की शर्तें उस काम या घंटों को सीमित करती हैं जो आप कर सकते हैं।",
    "Immigration status": "आपके परमिट या स्थिति की शर्तें उस काम या घंटों को सीमित करती हैं जो आप कर सकते हैं।",
    "Skills mismatch": "आपके कौशल स्थानीय रूप से उपलब्ध नौकरियों से मेल नहीं खाते।",
    "Limited network": "आप ऐसे बहुत से लोगों को नहीं जानते जो आपको नौकरियों से जोड़ सकें।",
    "Credential recognition": "कनाडा में आपकी विदेशी शिक्षा या लाइसेंस को स्वीकृत कराने में सहायता।",
    "Job matching": "एक सेवा जो आपको उपयुक्त नौकरी के अवसरों से जोड़ती है।",
    "Training matching": "एक सेवा जो आपको उपयुक्त प्रशिक्षण कार्यक्रमों से जोड़ती है।",
  },
  ui: {
    "% complete": "% पूर्ण",
    "Back to home": "होम पर वापस जाएँ",
    "Back": "वापस",
    "Consent is required to continue": "जारी रखने के लिए सहमति आवश्यक है",
    "Definition:": "परिभाषा:",
    "Email address": "ईमेल पता",
    "Finish to become a Survey Champion": "सर्वेक्षण चैंपियन बनने के लिए पूरा करें",
    "Five $50 local gift cards drawn monthly": "हर महीने $50 के पाँच स्थानीय उपहार कार्ड निकाले जाते हैं",
    "Go back": "वापस जाएँ",
    "Go home": "होम पर जाएँ",
    "Halfway there": "आधा रास्ता पूरा",
    "Home": "होम",
    "Next 5 skills": "अगले 5 कौशल",
    "Next question": "अगला प्रश्न",
    "No matches": "कोई मिलान नहीं",
    "Not sure": "निश्चित नहीं",
    "One moment.": "एक क्षण।",
    "Previous question": "पिछला प्रश्न",
    "Saving your response…": "आपकी प्रतिक्रिया सहेजी जा रही है…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "सर्वर से जुड़ने में कोई समस्या हुई। आपके उत्तर अभी भी इस डिवाइस पर सहेजे गए हैं — कृपया पुनः प्रयास करें।",
    "Submit": "जमा करें",
    "Thank you for sharing your experience.": "अपना अनुभव साझा करने के लिए धन्यवाद।",
    "Thank you for your time and response": "आपके समय और प्रतिक्रिया के लिए धन्यवाद",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "आपके समय और प्रतिक्रिया के लिए धन्यवाद। आपने समुदाय के विकास में बड़ा योगदान दिया।",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "धन्यवाद — आपकी प्रतिक्रिया दर्ज कर ली गई है। इसे दोबारा भरने की आवश्यकता नहीं है।",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "भाग लेने के लिए, आपकी आयु कम से कम 18 वर्ष होनी चाहिए और आपको भाग लेने के लिए सहमत होना चाहिए। यदि आप जारी रखना चाहते हैं, तो आप वापस जाकर अपना उत्तर बदल सकते हैं।",
    "Try again": "पुनः प्रयास करें",
    "We couldn't save your response": "हम आपकी प्रतिक्रिया सहेज नहीं सके",
    "Yes, enter me in the gift-card draw": "हाँ, मुझे उपहार कार्ड ड्रॉ में शामिल करें",
    "You made a great contribution to the development of the community": "आपने समुदाय के विकास में बड़ा योगदान दिया",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "आपने एक व्यक्तिगत निमंत्रण लिंक खोला है, इसलिए अनुस्मारक उद्देश्यों के लिए आपका पूरा होना दर्ज किया जा सकता है। आपकी प्रतिक्रियाएँ गोपनीय रखी जाती हैं और पहचान-रहित रूप में विश्लेषित की जाती हैं।",
    "You're a Survey Champion": "आप एक सर्वेक्षण चैंपियन हैं",
    "You've already completed this survey": "आप पहले ही यह सर्वेक्षण पूरा कर चुके हैं",
    "Your responses are anonymous.": "आपकी प्रतिक्रियाएँ गुमनाम हैं।",
    "more — keep typing to narrow": "और — सीमित करने के लिए टाइप करते रहें",
    "Search or select a language": "भाषा खोजें या चुनें",
    "Type to search countries…": "देश खोजने के लिए टाइप करें…",
    "Type to search areas of study…": "अध्ययन क्षेत्र खोजने के लिए टाइप करें…",
    "Type to search occupations…": "व्यवसाय खोजने के लिए टाइप करें…",
    "Type to search…": "खोजने के लिए टाइप करें…",
    "Select one…": "एक चुनें…",
    "1 · Lowest": "1 · सबसे कम",
    "5 · Highest": "5 · सबसे अधिक",
  },
};
