// DRAFT Italian (it) — pending fluent review. Keyed to exact source strings.
module.exports = {
  q: {
    language: "Seleziona una lingua per continuare",
    consent: "Conferma di avere almeno 18 anni e di accettare volontariamente di partecipare a questo sondaggio.",
    eligible: "Ti sei trasferito nel Nord dell'Ontario dopo settembre 2021 per viverci?",
    moved_from: "Da dove ti sei trasferito?",
    province: "Seleziona la provincia da cui ti sei trasferito",
    country_moved_from: "Seleziona il paese da cui ti sei trasferito",
    gender: "Qual è il tuo genere?",
    age_group: "Qual è la tua fascia d'età?",
    identity_groups: "Ti identifichi con uno dei seguenti gruppi? Seleziona tutte le opzioni pertinenti.",
    immigration_category: "Seleziona la categoria di immigrazione",
    non_permanent_category: "Seleziona la categoria di residente non permanente",
    non_permanent_other: "Specifica",
    recent_credential: "Qual è il titolo di studio più recente che hai conseguito?",
    program_name: "Qual era il tuo principale ambito di studio?",
    program_name_other: "Digita il tuo principale ambito di studio",
    program_location: "Dove hai completato questo programma?",
    highest_education: "Questo programma è il tuo livello di istruzione più alto?",
    highest_credential: "Qual è il tuo livello di istruzione più alto?",
    highest_program_name: "Per il tuo livello di istruzione più alto, qual era il tuo principale ambito di studio?",
    highest_program_name_other: "Digita il tuo principale ambito di studio per il tuo livello di istruzione più alto",
    current_program: "Qual è il tuo programma di studi attuale?",
    current_program_name: "Qual è il tuo principale ambito di studio?",
    current_program_name_other: "Digita il tuo principale ambito di studio",
    employed_before: "Eri occupato in Canada prima di trasferirti a Sault Ste. Marie?",
    previous_job_title: "Qual era la tua ultima occupazione prima di trasferirti a Sault Ste. Marie?",
    home_emp_before: "Eri occupato nel tuo paese d'origine prima di venire in Canada?",
    home_country_job: "Qual era la tua ultima occupazione nel tuo paese d'origine?",
    employment_status: "Quale delle seguenti opzioni descrive meglio la tua situazione lavorativa attuale?",
    current_job_title: "Qual è il titolo del tuo lavoro attuale?",
    intended_job: "Il tuo lavoro attuale è quello che intendevi svolgere?",
    intended_job_title: "Qual è il titolo del lavoro che intendi svolgere?",
    job_search_help: "Quali dei seguenti ti sono stati utili nella ricerca di lavoro nel Nord dell'Ontario / Sault Ste. Marie? Seleziona tutte le opzioni pertinenti.",
    job_search_other: "Specifica",
    work_barriers: "Seleziona tutte le barriere pertinenti",
    work_barriers_other: "Specifica",
    work_support: "Che tipo di supporto ti aiuterebbe a ottenere il lavoro che desideri? Seleziona tutte le opzioni pertinenti.",
    work_support_other: "Specifica",
    unemployed_intended_job: "Qual è il titolo del lavoro che intendi svolgere?",
    unemployed_barrier_gate: "Hai incontrato barriere durante la ricerca di lavoro a Sault Ste. Marie?",
    unemployment_reasons: "Seleziona tutte le barriere pertinenti",
    unemployment_reasons_other: "Specifica",
    not_looking_reasons: "Perché non stai cercando lavoro?",
    not_looking_other: "Specifica",
    student_working: "Attualmente stai lavorando?",
    student_current_job: "Qual è il titolo del tuo lavoro attuale?",
    student_job_relevant: "Il tuo lavoro attuale è pertinente al tuo programma di studi attuale?",
    student_job_help: "Quali dei seguenti ti sono stati utili nella ricerca di lavoro nel Nord dell'Ontario / Sault Ste. Marie? Seleziona tutte le opzioni pertinenti.",
    student_job_help_other: "Specifica",
    student_barrier_gate: "Hai incontrato barriere durante la ricerca di lavoro a Sault Ste. Marie?",
    student_barriers: "Seleziona tutte le barriere pertinenti",
    student_barriers_other: "Specifica",
    student_support: "Che tipo di supporto ti aiuterebbe a ottenere il lavoro che desideri? Seleziona tutte le opzioni pertinenti.",
    student_support_other: "Specifica",
    planned_intended_job: "Qual è il titolo del lavoro che intendi svolgere dopo la laurea?",
    skills: "Come valuteresti il tuo livello per ciascuna delle seguenti competenze?",
    gift_card_draw: "Vuoi partecipare all'estrazione delle carte regalo? (Solo a fini del premio)",
    "work_barrier.a": "C'è una barriera che ti impedisce di lavorare a tempo pieno?",
    "work_barrier.b": "C'è una barriera che ti impedisce di ottenere il lavoro che desideri?",
    "work_barrier.c": "C'è una barriera che ti impedisce di lavorare a tempo pieno e di svolgere il lavoro che desideri?",
    "work_barrier.d": "C'è una barriera che ti impedisce di ottenere un lavoro a tempo pieno?",
    "work_barrier.e": "C'è una barriera che ti impedisce di svolgere il lavoro che desideri?",
  },
  help: {
    skills: "1 = più basso, 2 = basso, 3 = moderato, 4 = alto, 5 = più alto, 0 = non so",
  },
  o: {
    "85 or older": "85 o più",
    "Advanced Diploma": "Diploma avanzato",
    "Alberta": "Alberta",
    "Apprenticeship": "Apprendistato",
    "British Columbia": "Columbia Britannica",
    "Canadian degree or training": "Titolo o formazione canadese",
    "Canadian work experience": "Esperienza lavorativa canadese",
    "Caregiving responsibilities": "Responsabilità di assistenza",
    "Childcare support": "Supporto per la cura dei bambini",
    "College certificate": "Certificato di college",
    "Credential recognition support": "Supporto per il riconoscimento dei titoli",
    "Credentials not recognized": "Titoli non riconosciuti",
    "Diploma": "Diploma",
    "Discrimination of any kind": "Discriminazione di qualsiasi tipo",
    "Doesn’t need employment income": "Non ha bisogno di reddito da lavoro",
    "Economic Immigrant": "Immigrato economico",
    "Employed casual (less than 10 hours/week)": "Lavoro occasionale (meno di 10 ore/settimana)",
    "Employed full time (30+ hours/week)": "Lavoro a tempo pieno (30 o più ore/settimana)",
    "Employed part time (10-30 hours/week)": "Lavoro part-time (10-30 ore/settimana)",
    "Employment or settlement centre": "Centro per l'impiego o l'integrazione",
    "Family Sponsored": "Sponsorizzato dalla famiglia",
    "Health issues": "Problemi di salute",
    "Health reasons": "Motivi di salute",
    "High school diploma or equivalent": "Diploma di scuola superiore o equivalente",
    "Household responsibilities": "Responsabilità domestiche",
    "Household work / Caregiver": "Lavoro domestico / Assistente",
    "I agree": "Accetto",
    "I didn't have a work permit": "Non avevo un permesso di lavoro",
    "I directly moved to Sault": "Mi sono trasferito direttamente a Sault",
    "I disagree": "Non accetto",
    "Immigrant (permanent resident)": "Immigrato (residente permanente)",
    "Immigration issues": "Problemi di immigrazione",
    "In Canada": "In Canada",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Indigeno (Prime Nazioni, Métis, Inuit/Inuk)",
    "International Student": "Studente internazionale",
    "Internship / volunteer experience": "Tirocinio / esperienza di volontariato",
    "Lack of Canadian work experience": "Mancanza di esperienza lavorativa canadese",
    "Lack of skills for available jobs": "Mancanza di competenze per i lavori disponibili",
    "Language barriers": "Barriere linguistiche",
    "Language support": "Supporto linguistico",
    "Limited job opportunities in preferred sector": "Opportunità di lavoro limitate nel settore preferito",
    "Limited knowledge of local job market": "Conoscenza limitata del mercato del lavoro locale",
    "Limited mentorship and job-matching support": "Supporto limitato di mentoring e di collocamento",
    "Limited professional network": "Rete professionale limitata",
    "Limited suitable jobs": "Lavori adeguati limitati",
    "Local job boards": "Bacheche di lavoro locali",
    "Local job market information": "Informazioni sul mercato del lavoro locale",
    "Local training or certification": "Formazione o certificazione locale",
    "Low wages": "Salari bassi",
    "Man": "Uomo",
    "Manitoba": "Manitoba",
    "Mentorship support": "Supporto di mentoring",
    "Networking support": "Supporto per il networking",
    "New Brunswick": "Nuovo Brunswick",
    "Newfoundland and Labrador": "Terranova e Labrador",
    "No": "No",
    "Non-Canadian work experience not recognized": "Esperienza lavorativa non canadese non riconosciuta",
    "Non-binary person or other gender": "Persona non binaria o altro genere",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Residente non permanente (ad es., permesso di lavoro, permesso di studio, richiedente asilo)",
    "None of the above (do not select any other options)": "Nessuna delle precedenti (non selezionare altre opzioni)",
    "Northwest Territories": "Territori del Nord-Ovest",
    "Not qualified for available jobs": "Non qualificato per i lavori disponibili",
    "Nova Scotia": "Nuova Scozia",
    "Nunavut": "Nunavut",
    "On temporary leave from a job (e.g., maternity/parental leave)": "In congedo temporaneo da un lavoro (ad es., congedo di maternità o parentale)",
    "Other": "Altro",
    "Other parts of Ontario": "Altre parti dell'Ontario",
    "Outside Canada": "Fuori dal Canada",
    "Outside of Canada": "Fuori dal Canada",
    "Outside of Ontario but within Canada": "Fuori dall'Ontario ma all'interno del Canada",
    "Personal contacts": "Contatti personali",
    "Post-graduate degree (e.g., Master's)": "Titolo post-laurea (ad es., master)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Titolo post-laurea (ad es., master, dottorato, M.D.)",
    "Primary school": "Scuola primaria",
    "Prince Edward Island": "Isola del Principe Edoardo",
    "Professional network": "Rete professionale",
    "Protected Person": "Persona protetta",
    "Quebec": "Quebec",
    "Recognition of non-Canadian work experience": "Riconoscimento dell'esperienza lavorativa non canadese",
    "Refugee": "Rifugiato",
    "Refugee Claimant": "Richiedente asilo",
    "Resume/interview support": "Supporto per curriculum e colloqui",
    "Retired": "Pensionato",
    "Saskatchewan": "Saskatchewan",
    "Self-employed": "Lavoratore autonomo",
    "Skills-to-job matching platform": "Piattaforma di abbinamento competenze-lavoro",
    "Social media (e.g., LinkedIn)": "Social media (ad es., LinkedIn)",
    "Student or recent graduate": "Studente o neolaureato",
    "Temporary Foreign Worker": "Lavoratore straniero temporaneo",
    "Temporary Resident Permit Holder": "Titolare di permesso di soggiorno temporaneo",
    "Training recommendations": "Raccomandazioni di formazione",
    "Unable to work": "Impossibilitato a lavorare",
    "Undergraduate degree": "Laurea triennale",
    "Unemployed and actively looking for work": "Disoccupato e attivamente in cerca di lavoro",
    "Unemployed and not looking for work": "Disoccupato e non in cerca di lavoro",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Minoranza visibile (ad es., sud-asiatica, cinese, nera)",
    "Woman": "Donna",
    "Yes": "Sì",
    "Yukon": "Yukon",
  },
  def: {
    "Family Sponsored": "Sei immigrato perché un familiare già presente in Canada ti ha sponsorizzato.",
    "Economic Immigrant": "Sei immigrato tramite un programma per lavoratori qualificati o imprenditori (ad es., Express Entry, Programma dei candidati provinciali).",
    "Refugee": "Sei venuto in Canada per proteggerti da un pericolo nel tuo paese d'origine.",
    "Temporary Foreign Worker": "In Canada con un permesso di lavoro legato a un datore di lavoro o un permesso di lavoro aperto.",
    "Refugee Claimant": "Hai chiesto protezione come rifugiato al Canada e sei in attesa di una decisione.",
    "Protected Person": "Il Canada ha già riconosciuto che hai bisogno di protezione (status di rifugiato/persona protetta approvato).",
    "Temporary Resident Permit Holder": "Possiedi un permesso speciale per rimanere temporaneamente quando normalmente non sarebbe consentito.",
    "Canadian degree or training": "Hai conseguito un titolo di studio o completato un programma di formazione in Canada.",
    "Canadian work experience": "Hai lavorato per un datore di lavoro in Canada.",
    "Employment or settlement centre": "Hai ricevuto aiuto da un'organizzazione che sostiene chi cerca lavoro o i nuovi arrivati (ad es., Sault Community Career Center).",
    "Internship / volunteer experience": "Hai acquisito esperienza lavorativa tramite un tirocinio non retribuito, un impiego di breve durata o volontariato.",
    "Local job boards": "Hai usato siti web o annunci che pubblicizzano lavori nella tua zona (ad es., la bacheca di lavoro AWIC).",
    "Personal contacts": "Hai ricevuto aiuto o segnalazioni di lavoro da familiari, amici o persone che conosci personalmente.",
    "Professional network": "Hai usato contatti del tuo settore professionale, come colleghi o mentori.",
    "Recognition of non-Canadian work experience": "La tua esperienza lavorativa acquisita fuori dal Canada è stata accettata.",
    "Caregiving responsibilities": "Devi occuparti di figli o familiari anziani che dipendono da te.",
    "Credentials not recognized": "La tua istruzione, il tuo titolo o la tua licenza ottenuti fuori dal Canada non sono accettati dai datori di lavoro canadesi.",
    "Discrimination of any kind": "Sei stato trattato ingiustamente a causa della tua etnia, religione, genere, accento, età o altre caratteristiche personali.",
    "Health issues": "Hai problemi di salute fisica o mentale che rendono più difficile trovare o mantenere un lavoro.",
    "Household responsibilities": "Devi gestire le faccende domestiche (cucinare, pulire, mandare avanti la casa).",
    "Lack of Canadian work experience": "I datori di lavoro chiedono esperienza lavorativa in Canada, che non hai ancora.",
    "Lack of skills for available jobs": "I lavori disponibili nella tua zona richiedono competenze o formazione che attualmente non possiedi.",
    "Language barriers": "Le tue competenze in inglese (o francese) rendono più difficile trovare lavoro o superare i colloqui.",
    "Limited job opportunities in preferred sector": "Ci sono pochi lavori nel tuo campo o settore nella tua zona.",
    "Limited knowledge of local job market": "Non sai bene come trovare lavoro, quali datori di lavoro stanno assumendo o come funzionano le assunzioni nella tua zona.",
    "Limited mentorship and job-matching support": "Non hai accesso a mentori o servizi che ti mettano in contatto con lavori adeguati.",
    "Limited professional network": "Conosci poche persone nel tuo campo che potrebbero segnalarti opportunità, referenze o consigli.",
    "Non-Canadian work experience not recognized": "La tua esperienza lavorativa acquisita fuori dal Canada non è accettata né valorizzata dai datori di lavoro canadesi.",
    "Childcare support": "Hai bisogno di aiuto per la cura dei tuoi figli così da poter lavorare.",
    "Credential recognition support": "Hai bisogno di aiuto per far accettare la tua istruzione o le tue qualifiche professionali ottenute fuori dal Canada.",
    "Language support": "Hai bisogno di aiuto per migliorare le tue competenze in inglese (o francese).",
    "Local job market information": "Hai bisogno di informazioni su quali datori di lavoro stanno assumendo, quali lavori sono disponibili e quali competenze sono richieste nella tua zona.",
    "Local training or certification": "Hai bisogno di formazione o certificazione offerta nella tua zona per qualificarti ai lavori disponibili.",
    "Mentorship support": "Hai bisogno di entrare in contatto con persone esperte del tuo settore.",
    "Networking support": "Hai bisogno di aiuto per incontrare datori di lavoro e professionisti.",
    "Resume/interview support": "Hai bisogno di aiuto per preparare il tuo curriculum, la lettera di presentazione o per esercitarti ai colloqui.",
    "Skills-to-job matching platform": "Hai bisogno di un servizio o strumento che abbini le tue competenze a offerte di lavoro adeguate.",
    "Training recommendations": "Hai bisogno di suggerimenti su quale formazione o corsi seguire per migliorare le tue possibilità di trovare lavoro.",
    "Doesn’t need employment income": "Non hai bisogno di lavorare perché hai altre fonti di reddito o sostegno finanziario.",
    "Health reasons": "Hai problemi di salute fisica o mentale che rendono più difficile trovare o mantenere un lavoro.",
    "Immigration issues": "Il tuo status di immigrazione o i tuoi documenti (ad es., permesso di lavoro, pratica di residenza permanente) ti impediscono di lavorare.",
    "Limited suitable jobs": "Ci sono pochi lavori nella tua zona che corrispondano alle tue competenze, esperienza o preferenze.",
    "Low wages": "I lavori disponibili pagano troppo poco perché per te valga la pena lavorare.",
    "Not qualified for available jobs": "I lavori disponibili nella tua zona richiedono istruzione, competenze o certificazioni che attualmente non possiedi.",
  },
  ui: {
    "% complete": " % completato",
    "Back to home": "Torna alla home",
    "Back": "Indietro",
    "Definition:": "Definizione:",
    "Email address": "Indirizzo email",
    "Finish to become a Survey Champion": "Completa per diventare un Campione del Sondaggio",
    "Five $50 local gift cards drawn monthly": "Cinque carte regalo locali da $50 estratte ogni mese",
    "Go back": "Indietro",
    "Home": "Home",
    "Next 5 skills": "5 competenze successive",
    "Next question": "Domanda successiva",
    "No matches": "Nessun risultato",
    "Not sure": "Non so",
    "One moment.": "Un momento.",
    "Previous question": "Domanda precedente",
    "Saving your response…": "Salvataggio della tua risposta…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "Si è verificato un problema nel raggiungere il server. Le tue risposte sono ancora salvate su questo dispositivo — riprova.",
    "Submit": "Invia",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Grazie per il tuo tempo e la tua risposta. Hai dato un grande contributo allo sviluppo della comunità.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Grazie — la tua risposta è stata registrata. Non è necessario compilarla di nuovo.",
    "Try again": "Riprova",
    "We couldn't save your response": "Non siamo riusciti a salvare la tua risposta",
    "Yes, enter me in the gift-card draw": "Sì, iscrivimi all'estrazione delle carte regalo",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Hai aperto un link di invito personale, quindi il tuo completamento potrebbe essere registrato a fini di promemoria. Le tue risposte sono mantenute riservate e analizzate in forma anonimizzata.",
    "You're a Survey Champion": "Sei un Campione del Sondaggio",
    "You've already completed this survey": "Hai già completato questo sondaggio",
    "Your responses are anonymous.": "Le tue risposte sono anonime.",
    "more — keep typing to narrow": "altri — continua a digitare per restringere",
    "Search or select a language": "Cerca o seleziona una lingua",
    "Type to search countries…": "Digita per cercare un paese…",
    "Type to search areas of study…": "Digita per cercare un ambito di studio…",
    "Type to search occupations…": "Digita per cercare una professione…",
    "Type to search…": "Digita per cercare…",
    "Select one…": "Seleziona un'opzione…",
    "1 · Lowest": "1 · più basso",
    "5 · Highest": "5 · più alto",
    "Thank you for your interest.": "Grazie per il tuo interesse.",
    "Unfortunately you are not eligible to participate in the survey.": "Purtroppo non sei idoneo a partecipare al sondaggio.",
    "Thank you for starting the survey.": "Grazie per aver iniziato il sondaggio.",
    "Unfortunately we cannot proceed without your consent.": "Purtroppo non possiamo procedere senza il tuo consenso.",
  },
};
