// DRAFT Kurdish — Kurmanji / Latin script (ku) — ⚠ MACHINE-QUALITY DRAFT.
// Requires native-speaker review before release.
//
// ⚠ DIALECT DECISION: this is KURMANJI (Latin script, left-to-right), matching the
// native name "Kurdî" shown in the language selector. If the Sault Kurdish community
// is primarily SORANI-speaking, this is the wrong variant — Sorani uses the Arabic
// script (کوردی) and is right-to-left, and would need both a different translation
// and RTL layout. Confirm with the community before release.
module.exports = {
  q: {
    language: "Zimanek hilbijêre ji bo berdewamkirinê",
    consent: "Ji kerema xwe piştrast bike ku tu bi kêmî 18 salî yî û bi dilxwazî razî yî ku beşdarî vê anketê bibî.",
    eligible: "Ma tu piştî Îlona 2021an ji bo jiyanê koçî Ontarioya Bakur kirî?",
    moved_from: "Tu ji ku derê koç kirî?",
    province: "Ji kerema xwe parêzgeha ku tu jê koç kirî hilbijêre",
    country_moved_from: "Ji kerema xwe welatê ku tu jê koç kirî hilbijêre",
    gender: "Zayenda te çi ye?",
    age_group: "Koma temenê te çi ye?",
    identity_groups: "Ma tu xwe bi yek ji van koman dinasî? Hemûyên ku li te tên hilbijêre.",
    immigration_category: "Kategoriya koçberiyê hilbijêre",
    non_permanent_category: "Kategoriya niştecîhê ne-daîmî hilbijêre",
    non_permanent_other: "Ji kerema xwe diyar bike",
    recent_credential: "Dawîn bawernameya perwerdehiyê ya ku te temam kiriye çi ye?",
    program_name: "Qada sereke ya xwendina te çi bû?",
    program_name_other: "Qada sereke ya xwendina xwe binivîse",
    program_location: "Te ev bername li ku derê temam kir?",
    highest_education: "Ma ev bername asta herî bilind a perwerdehiya te ye?",
    highest_credential: "Asta herî bilind a perwerdehiya te çi ye?",
    highest_program_name: "Ji bo asta herî bilind a perwerdehiya te, qada sereke ya xwendina te çi bû?",
    highest_program_name_other: "Ji bo asta herî bilind a perwerdehiya xwe qada sereke ya xwendinê binivîse",
    current_program: "Bernameya xwendina te ya niha çi ye?",
    current_program_name: "Qada sereke ya xwendina te çi ye?",
    current_program_name_other: "Qada sereke ya xwendina xwe binivîse",
    employed_before: "Ma berî ku koçî Sault Ste. Marie bikî li Kanadayê dixebitî?",
    previous_job_title: "Berî ku koçî Sault Ste. Marie bikî pîşeya te ya dawî çi bû?",
    home_emp_before: "Ma berî ku werî Kanadayê li welatê xwe dixebitî?",
    home_country_job: "Li welatê xwe pîşeya te ya dawî çi bû?",
    employment_status: "Kîjan ji van rewşa te ya xebatê ya niha baştir vedibêje?",
    current_job_title: "Navê karê te yê niha çi ye?",
    intended_job: "Ma karê te yê niha ew e ku te dixwest bikî?",
    intended_job_title: "Navê karê ku tu dixwazî bikî çi ye?",
    job_search_help: "Kîjan ji van di lêgerîna kar de li Ontarioya Bakur / Sault Ste. Marie ji te re bikêr bûn? Hemûyên ku li te tên hilbijêre.",
    job_search_other: "Ji kerema xwe diyar bike",
    work_barriers: "Hemû asteng ên ku li te tên hilbijêre",
    work_barriers_other: "Ji kerema xwe diyar bike",
    work_support: "Kîjan cure piştgirî dê ji te re bibe alîkar ku karê ku tu dixwazî bistînî? Hemûyên ku li te tên hilbijêre.",
    work_support_other: "Ji kerema xwe diyar bike",
    unemployed_intended_job: "Navê karê ku tu dixwazî bikî çi ye?",
    unemployed_barrier_gate: "Ma dema lêgerîna kar li Sault Ste. Marie tu rastî tu astengan hatî?",
    unemployment_reasons: "Hemû asteng ên ku li te tên hilbijêre",
    unemployment_reasons_other: "Ji kerema xwe diyar bike",
    not_looking_reasons: "Çima tu li kar nagerî?",
    not_looking_other: "Ji kerema xwe diyar bike",
    student_working: "Ma tu niha dixebitî?",
    student_current_job: "Navê karê te yê niha çi ye?",
    student_job_relevant: "Ma karê te yê niha bi bernameya xwendina te ya niha ve girêdayî ye?",
    student_job_help: "Kîjan ji van di lêgerîna kar de li Ontarioya Bakur / Sault Ste. Marie ji te re bikêr bûn? Hemûyên ku li te tên hilbijêre.",
    student_job_help_other: "Ji kerema xwe diyar bike",
    student_barrier_gate: "Ma dema lêgerîna kar li Sault Ste. Marie tu rastî tu astengan hatî?",
    student_barriers: "Hemû asteng ên ku li te tên hilbijêre",
    student_barriers_other: "Ji kerema xwe diyar bike",
    student_support: "Kîjan cure piştgirî dê ji te re bibe alîkar ku karê ku tu dixwazî bistînî? Hemûyên ku li te tên hilbijêre.",
    student_support_other: "Ji kerema xwe diyar bike",
    planned_intended_job: "Navê karê ku tu piştî mezûnbûnê dixwazî bikî çi ye?",
    skills: "Tu dê asta xwe ji bo her yek ji van jêhatîbûnan çawa binirxînî?",
    gift_card_draw: "Ma tu dixwazî beşdarî pêşbaziya qerta diyariyê bibî? (Tenê ji bo armanca xelatê)",
    "work_barrier.a": "Ma astengek heye ku nahêle tu bi tam-dem bixebitî?",
    "work_barrier.b": "Ma astengek heye ku nahêle tu karê ku dixwazî bistînî?",
    "work_barrier.c": "Ma astengek heye ku nahêle tu bi tam-dem bixebitî û karê ku dixwazî bikî?",
    "work_barrier.d": "Ma astengek heye ku nahêle tu karekî tam-dem bistînî?",
    "work_barrier.e": "Ma astengek heye ku nahêle tu karê ku dixwazî bikî?",
    "unemployed_support": "Kîjan cure piştgirî dê ji te re bibe alîkar ku karê ku tu dixwazî bistînî? Hemûyên ku li te tên hilbijêre.",
    "not_looking_intended_job": "Navê karê ku tu dixwazî bikî çi ye?",
    "not_looking_barrier_gate": "Ma dema lêgerîna kar li Sault Ste. Marie tu rastî tu astengan hatî?",
    "not_looking_barriers": "Hemû asteng ên ku li te tên hilbijêre",
    "not_looking_barriers_other": "Ji kerema xwe diyar bike",
    "not_looking_support": "Kîjan cure piştgirî dê di lêgerîna kar a paşerojê de alîkariya te bike? Hemû yên ku li gorî rewşê ne hilbijêre.",
    "not_looking_support_other": "Ji kerema xwe diyar bike",
    "not_looking_expect_look": "Ma tu hêvî dikî ku di 12 mehên bên de dest bi lêgerîna kar bikî?",
  },
  help: {
    skills: "1 = herî kêm, 2 = kêm, 3 = navîn, 4 = bilind, 5 = herî bilind, 0 = ne diyar",
  },
  o: {
    "85 or older": "85 an mezintir",
    "Advanced Diploma": "Dîplomaya pêşketî",
    "Alberta": "Alberta",
    "Apprenticeship": "Şagirtî",
    "British Columbia": "Kolombiyaya Brîtanî",
    "Canadian degree or training": "Bawername an perwerdehiya Kanadayî",
    "Canadian work experience": "Ezmûna xebata Kanadayî",
    "Caregiving responsibilities": "Berpirsiyariyên lênêrînê",
    "Childcare support": "Piştgiriya lênêrîna zarokan",
    "College certificate": "Sertîfîkaya kolejê",
    "Credential recognition support": "Piştgiriya naskirina bawernameyan",
    "Credentials not recognized": "Bawername nayên naskirin",
    "Diploma": "Dîploma",
    "Discrimination of any kind": "Cudakariya her cureyî",
    "Doesn’t need employment income": "Hewceyî dahata xebatê nake",
    "Economic Immigrant": "Koçberê aborî",
    "Employed casual (less than 10 hours/week)": "Xebata demkî (kêmtir ji 10 saetan/hefte)",
    "Employed full time (30+ hours/week)": "Xebata tam-dem (30+ saet/hefte)",
    "Employed part time (10-30 hours/week)": "Xebata nîv-dem (10-30 saet/hefte)",
    "Employment or settlement centre": "Navenda xebatê an bicihbûnê",
    "Family Sponsored": "Ji aliyê malbatê ve piştgirîkirî",
    "Health issues": "Pirsgirêkên tenduristiyê",
    "Health reasons": "Sedemên tenduristiyê",
    "High school diploma or equivalent": "Dîplomaya dibistana amadeyî an hevta",
    "Household responsibilities": "Berpirsiyariyên malê",
    "Household work / Caregiver": "Karê malê / Lênêr",
    "I agree": "Ez razî me",
    "I didn't have a work permit": "Destûrnameya xebatê min tunebû",
    "I directly moved to Sault": "Ez rasterast koçî Sault kirim",
    "I disagree": "Ez ne razî me",
    "Immigrant (permanent resident)": "Koçber (niştecîhê daîmî)",
    "Immigration issues": "Pirsgirêkên koçberiyê",
    "In Canada": "Li Kanadayê",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Xwecihî (First Nations, Métis, Inuit/Inuk)",
    "International Student": "Xwendekarê navneteweyî",
    "Internship / volunteer experience": "Stajyerî / ezmûna dilxwazî",
    "Lack of Canadian work experience": "Kêmasiya ezmûna xebata Kanadayî",
    "Lack of skills for available jobs": "Kêmasiya jêhatîbûnê ji bo karên berdest",
    "Language barriers": "Astengên ziman",
    "Language support": "Piştgiriya ziman",
    "Limited job opportunities in preferred sector": "Derfetên kar ên sînordar di sektora tercîhkirî de",
    "Limited knowledge of local job market": "Zanîna sînordar a bazara kar a herêmî",
    "Limited mentorship and job-matching support": "Piştgiriya sînordar a rêberî û lihevanîna kar",
    "Limited professional network": "Torê pîşeyî yê sînordar",
    "Limited suitable jobs": "Karên guncav ên sînordar",
    "Local job boards": "Panoyên kar ên herêmî",
    "Local job market information": "Agahiyên bazara kar a herêmî",
    "Local training or certification": "Perwerdehî an sertîfîkasyona herêmî",
    "Low wages": "Meaşên kêm",
    "Man": "Mêr",
    "Manitoba": "Manitoba",
    "Mentorship support": "Piştgiriya rêberiyê",
    "Networking support": "Piştgiriya torê",
    "New Brunswick": "New Brunswick",
    "Newfoundland and Labrador": "Newfoundland û Labrador",
    "No": "Na",
    "Non-Canadian work experience not recognized": "Ezmûna xebata ne-Kanadayî nayê naskirin",
    "Non-binary person or other gender": "Kesê ne-dudimensiyonî an zayenda din",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Niştecîhê ne-daîmî (mînak, destûrnameya xebatê, destûrnameya xwendinê, daxwazkerê penaberiyê)",
    "None of the above (do not select any other options)": "Tu ji van (tu vebijarkên din hilnebijêre)",
    "Northwest Territories": "Herêmên Bakur-Rojava",
    "Not qualified for available jobs": "Ji bo karên berdest ne jêhatî",
    "Nova Scotia": "Nova Scotia",
    "Nunavut": "Nunavut",
    "On temporary leave from a job (e.g., maternity/parental leave)": "Di betlaneya demkî ya ji karekî de (mînak, betlaneya zayînê/dêûbavtiyê)",
    "Other": "Yên din",
    "Other parts of Ontario": "Beşên din ên Ontario",
    "Outside Canada": "Li derveyî Kanadayê",
    "Outside of Canada": "Li derveyî Kanadayê",
    "Outside of Ontario but within Canada": "Li derveyî Ontario lê li hundirê Kanadayê",
    "Personal contacts": "Têkiliyên kesane",
    "Post-graduate degree (e.g., Master's)": "Bawernameya piştî-mezûniyetê (mînak, Master)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Bawernameya piştî-mezûniyetê (mînak, Master, PhD, MD)",
    "Primary school": "Dibistana seretayî",
    "Prince Edward Island": "Girava Prince Edward",
    "Professional network": "Torê pîşeyî",
    "Protected Person": "Kesê parastî",
    "Quebec": "Quebec",
    "Recognition of non-Canadian work experience": "Naskirina ezmûna xebata ne-Kanadayî",
    "Refugee": "Penaber",
    "Refugee Claimant": "Daxwazkerê penaberiyê",
    "Resume/interview support": "Piştgiriya CV/hevpeyivînê",
    "Retired": "Teqawît",
    "Saskatchewan": "Saskatchewan",
    "Self-employed": "Xwe-xebitî",
    "Skills-to-job matching platform": "Platforma lihevanîna jêhatîbûn-kar",
    "Social media (e.g., LinkedIn)": "Medyaya civakî (mînak, LinkedIn)",
    "Student or recent graduate": "Xwendekar an mezûnê nû",
    "Temporary Foreign Worker": "Karkerê biyanî yê demkî",
    "Temporary Resident Permit Holder": "Xwedanê destûrnameya niştecîhbûna demkî",
    "Training recommendations": "Pêşniyarên perwerdehiyê",
    "Unable to work": "Nikare bixebite",
    "Undergraduate degree": "Bawernameya lîsansê",
    "Unemployed and actively looking for work": "Bêkar û bi awayekî çalak li kar digere",
    "Unemployed and not looking for work": "Bêkar û li kar nagere",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Hindikahiya xuya (mînak, Asyaya Başûr, Çînî, Reş)",
    "Woman": "Jin",
    "Yes": "Erê",
    "Yukon": "Yukon",
    "Didn't look for job": "Min li kar negeriya",
  },
  def: {
    "Family Sponsored": "Te koç kir ji ber ku endamekî malbatê yê ku jixwe li Kanadayê bû piştgirî da te.",
    "Economic Immigrant": "Te bi rêya bernameyeke karkerên jêhatî an karsaziyê koç kir (mînak, Express Entry, Provincial Nominee).",
    "Refugee": "Tu ji bo parastinê ji xetereya li welatê xwe hatî Kanadayê.",
    "Temporary Foreign Worker": "Li Kanadayê bi destûrnameyeke xebatê ya girêdayî kardêrekî an destûrnameyeke xebatê ya vekirî.",
    "Refugee Claimant": "Te ji Kanadayê parastina penaberiyê xwestiye û li benda biryarê yî.",
    "Protected Person": "Kanada jixwe qebûl kiriye ku tu hewceyî parastinê yî (statuya penaber/kesê parastî ya pejirandî).",
    "Temporary Resident Permit Holder": "Destûrnameyeke taybet a te heye ku bi demkî bimînî dema ku bi gelemperî nayê destûrdan.",
    "Canadian degree or training": "Te li Kanadayê bawernameyek an bernameyeke perwerdehiyê temam kiriye.",
    "Canadian work experience": "Te li Kanadayê ji bo kardêrekî xebitiye.",
    "Employment or settlement centre": "Te ji rêxistineke ku piştgiriyê dide kesên li kar digerin an nûhatiyan alîkarî wergirt (mînak, Sault Community Career Center).",
    "Internship / volunteer experience": "Te bi rêya stajyeriya bêpere, xebateke kurt-demî an dilxwaziyê ezmûna xebatê bi dest xist.",
    "Local job boards": "Te malper an îlanên ku karên herêma te reklam dikin bikar anî (mînak, panoya karan a AWIC).",
    "Personal contacts": "Te ji malbatê, hevalan an kesên ku bi kesane nas dikî alîkarî an agahiyên kar wergirt.",
    "Professional network": "Te têkiliyên qada xebata xwe, wek hevkar an rêberan, bikar anî.",
    "Recognition of non-Canadian work experience": "Ezmûna xebata te ya li derveyî Kanadayê hatî qebûlkirin.",
    "Caregiving responsibilities": "Divê tu li zarok an endamên malbatê yên pîr ên ku bi te ve girêdayî ne binêrî.",
    "Credentials not recognized": "Perwerdehî, bawername an lîsansa te ya ji derveyî Kanadayê ji aliyê kardêrên Kanadayî ve nayê qebûlkirin.",
    "Discrimination of any kind": "Ji ber nijad, etnîsîte, ol, zayend, devok, temen an taybetmendiyên din ên kesane bi te re neheqî hat kirin.",
    "Health issues": "Pirsgirêkên tenduristiya laşî an derûnî yên te hene ku dîtin an parastina karekî dijwartir dikin.",
    "Household responsibilities": "Divê tu karên malê (xwarinçêkirin, paqijkirin, birêvebirina malê) bi rê ve bibî.",
    "Lack of Canadian work experience": "Kardêr ezmûna xebatê ya li Kanadayê dixwazin, ku hîn a te tune.",
    "Lack of skills for available jobs": "Karên berdest ên li herêma te jêhatîbûn an perwerdehiyeke dixwazin ku niha a te tune.",
    "Language barriers": "Zanîna te ya Îngilîzî (an Fransî) dîtina kar an derbasbûna hevpeyivînan dijwartir dike.",
    "Limited job opportunities in preferred sector": "Li herêma te di qad an sektora te de karên kêm hene.",
    "Limited knowledge of local job market": "Tu ne piştrast î ka çawa kar bibînî, kîjan kardêr kar didin, an li herêma te kardan çawa dimeşe.",
    "Limited mentorship and job-matching support": "Gihîştina te bi rêberan an xizmetên ku te bi karên guncav ve girê didin tune.",
    "Limited professional network": "Tu kêm kesan di qada xwe de nas dikî ku dikarin agahiyên kar, referans an şîretan parve bikin.",
    "Non-Canadian work experience not recognized": "Ezmûna xebata te ya li derveyî Kanadayê ji aliyê kardêrên Kanadayî ve nayê qebûlkirin an qîmet nayê dayîn.",
    "Childcare support": "Ji bo ku tu bikarî bixebitî, hewceyî alîkariya lênêrîna zarokên xwe yî.",
    "Credential recognition support": "Hewceyî alîkariyê yî da ku perwerdehî an jêhatîbûnên te yên pîşeyî yên ji derveyî Kanadayê werin qebûlkirin.",
    "Language support": "Hewceyî alîkariyê yî da ku zanîna xwe ya Îngilîzî (an Fransî) baştir bikî.",
    "Local job market information": "Hewceyî agahiyan î derbarê kîjan kardêran kar didin, kîjan kar hene, û li herêma te kîjan jêhatîbûn tên xwestin.",
    "Local training or certification": "Hewceyî perwerdehî an sertîfîkasyona ku li herêma te tê pêşkêşkirin î da ku ji bo karên berdest bibî jêhatî.",
    "Mentorship support": "Hewceyî têkiliyê bi kesên bi ezmûn ên qada xwe re yî.",
    "Networking support": "Hewceyî alîkariyê yî da ku bi kardêr û pisporan re bicivî.",
    "Resume/interview support": "Hewceyî alîkariyê yî ji bo amadekirina CV, nameya nasînê an ceribandina hevpeyivînan.",
    "Skills-to-job matching platform": "Hewceyî xizmet an amûrekê yî ku jêhatîbûnên te bi derfetên kar ên guncav re li hev tîne.",
    "Training recommendations": "Hewceyî pêşniyaran î ka kîjan perwerdehî an kursan bigirî da ku şansên te yên dîtina kar zêde bibin.",
    "Doesn’t need employment income": "Hewceyî xebatê nakî ji ber ku çavkaniyên din ên dahatê an piştgiriya darayî a te heye.",
    "Health reasons": "Pirsgirêkên tenduristiya laşî an derûnî yên te hene ku dîtin an parastina karekî dijwartir dikin.",
    "Immigration issues": "Statuya te ya koçberiyê an belgeyên te (mînak, destûrnameya xebatê, pêvajoya niştecîhbûna daîmî) nahêlin tu bixebitî.",
    "Limited suitable jobs": "Li herêma te karên ku bi jêhatîbûn, ezmûn an tercîhên te re li hev bikin kêm in.",
    "Low wages": "Karên berdest ew qas kêm didin ku xebat ji bo te nayê hesibandin.",
    "Not qualified for available jobs": "Karên berdest ên li herêma te perwerdehî, jêhatîbûn an sertîfîkasyonên dixwazin ku niha a te tune.",
  },
  ui: {
    "% complete": "% temam",
    "Back to home": "Vegere malperê",
    "Back": "Vegere",
    "Definition:": "Pênase:",
    "Email address": "Navnîşana e-nameyê",
    "Finish to become a Survey Champion": "Temam bike da ku bibî Şampiyonê Anketê",
    "Five $50 local gift cards drawn monthly": "Her meh pênc qertên diyariyê yên herêmî yên 50 $ têne kişandin",
    "Go back": "Vegere",
    "Home": "Malper",
    "Next 5 skills": "5 jêhatîbûnên din",
    "Next question": "Pirsa din",
    "No matches": "Encam tune",
    "Not sure": "Ne diyar",
    "One moment.": "Kêliyek.",
    "Previous question": "Pirsa berê",
    "Saving your response…": "Bersiva te tê tomarkirin…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "Di gihîştina serverê de çewtiyek çêbû. Bersivên te hîn jî li ser vê amûrê hatine tomarkirin — ji kerema xwe dîsa biceribîne.",
    "Submit": "Bişîne",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Spas ji bo dema te û bersiva te. Te beşdariyeke mezin di pêşkeftina civakê de kir.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Spas — bersiva te hatiye tomarkirin. Pêwîst nake ku dîsa were dagirtin.",
    "Try again": "Dîsa biceribîne",
    "We couldn't save your response": "Me nikarîbû bersiva te tomar bike",
    "Yes, enter me in the gift-card draw": "Erê, min têxe pêşbaziya qerta diyariyê",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Te girêdaneke vexwendinê ya kesane vekir, ji ber vê yekê temamkirina te dikare ji bo armancên bîranînê were tomarkirin. Bersivên te veşartî têne parastin û bi awayekî nenaskirî têne analîzkirin.",
    "You're a Survey Champion": "Tu Şampiyonê Anketê yî",
    "You've already completed this survey": "Te jixwe ev anket temam kiriye",
    "Your responses are anonymous.": "Bersivên te nenas in.",
    "more — keep typing to narrow": "zêdetir — berdewam binivîse da ku teng bikî",
    "Search or select a language": "Zimanek bigere an hilbijêre",
    "Type to search countries…": "Binivîse da ku welatan bigerî…",
    "Type to search areas of study…": "Binivîse da ku qadên xwendinê bigerî…",
    "Type to search occupations…": "Binivîse da ku pîşeyan bigerî…",
    "Type to search…": "Binivîse da ku bigerî…",
    "Select one…": "Yekê hilbijêre…",
    "1 · Lowest": "1 · herî kêm",
    "5 · Highest": "5 · herî bilind",
    "Thank you for your interest.": "Spas ji bo eleqeya te.",
    "Unfortunately you are not eligible to participate in the survey.": "Mixabin, tu ne mafdar î ku beşdarî vê anketê bibî.",
    "Thank you for starting the survey.": "Spas ji bo destpêkirina anketê.",
    "Unfortunately we cannot proceed without your consent.": "Mixabin, em nikarin bêyî razîbûna te bidomînin.",
  },
};
