// DRAFT Punjabi (pa, Gurmukhi) — ⚠ MACHINE-QUALITY DRAFT. Requires native-speaker
// review before release. Keyed to exact source strings.
module.exports = {
  q: {
    language: "ਜਾਰੀ ਰੱਖਣ ਲਈ ਇੱਕ ਭਾਸ਼ਾ ਚੁਣੋ",
    consent: "ਕਿਰਪਾ ਕਰਕੇ ਪੁਸ਼ਟੀ ਕਰੋ ਕਿ ਤੁਸੀਂ ਘੱਟੋ-ਘੱਟ 18 ਸਾਲ ਦੇ ਹੋ ਅਤੇ ਸਵੈ-ਇੱਛਾ ਨਾਲ ਇਸ ਸਰਵੇਖਣ ਵਿੱਚ ਭਾਗ ਲੈਣ ਲਈ ਸਹਿਮਤ ਹੋ।",
    eligible: "ਕੀ ਤੁਸੀਂ ਸਤੰਬਰ 2021 ਤੋਂ ਬਾਅਦ ਰਹਿਣ ਲਈ ਉੱਤਰੀ ਓਨਟਾਰੀਓ ਆਏ ਸੀ?",
    moved_from: "ਤੁਸੀਂ ਕਿੱਥੋਂ ਆਏ ਹੋ?",
    province: "ਕਿਰਪਾ ਕਰਕੇ ਉਹ ਸੂਬਾ ਚੁਣੋ ਜਿੱਥੋਂ ਤੁਸੀਂ ਆਏ ਹੋ",
    country_moved_from: "ਕਿਰਪਾ ਕਰਕੇ ਉਹ ਦੇਸ਼ ਚੁਣੋ ਜਿੱਥੋਂ ਤੁਸੀਂ ਆਏ ਹੋ",
    gender: "ਤੁਹਾਡਾ ਲਿੰਗ ਕੀ ਹੈ?",
    age_group: "ਤੁਹਾਡਾ ਉਮਰ ਸਮੂਹ ਕੀ ਹੈ?",
    identity_groups: "ਕੀ ਤੁਸੀਂ ਹੇਠ ਲਿਖੇ ਕਿਸੇ ਸਮੂਹ ਨਾਲ ਪਛਾਣ ਰੱਖਦੇ ਹੋ? ਸਾਰੇ ਲਾਗੂ ਵਿਕਲਪ ਚੁਣੋ।",
    immigration_category: "ਇਮੀਗ੍ਰੇਸ਼ਨ ਸ਼੍ਰੇਣੀ ਚੁਣੋ",
    non_permanent_category: "ਗੈਰ-ਸਥਾਈ ਨਿਵਾਸੀ ਸ਼੍ਰੇਣੀ ਚੁਣੋ",
    non_permanent_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    recent_credential: "ਤੁਸੀਂ ਸਭ ਤੋਂ ਹਾਲ ਹੀ ਵਿੱਚ ਕਿਹੜੀ ਵਿੱਦਿਅਕ ਯੋਗਤਾ ਪੂਰੀ ਕੀਤੀ ਹੈ?",
    program_name: "ਤੁਹਾਡੀ ਪੜ੍ਹਾਈ ਦਾ ਮੁੱਖ ਖੇਤਰ ਕੀ ਸੀ?",
    program_name_other: "ਆਪਣੀ ਪੜ੍ਹਾਈ ਦਾ ਮੁੱਖ ਖੇਤਰ ਲਿਖੋ",
    program_location: "ਤੁਸੀਂ ਇਹ ਪ੍ਰੋਗਰਾਮ ਕਿੱਥੇ ਪੂਰਾ ਕੀਤਾ?",
    highest_education: "ਕੀ ਇਹ ਪ੍ਰੋਗਰਾਮ ਤੁਹਾਡੀ ਸਿੱਖਿਆ ਦਾ ਸਭ ਤੋਂ ਉੱਚਾ ਪੱਧਰ ਹੈ?",
    highest_credential: "ਤੁਹਾਡੀ ਸਿੱਖਿਆ ਦਾ ਸਭ ਤੋਂ ਉੱਚਾ ਪੱਧਰ ਕੀ ਹੈ?",
    highest_program_name: "ਆਪਣੀ ਸਿੱਖਿਆ ਦੇ ਸਭ ਤੋਂ ਉੱਚੇ ਪੱਧਰ ਲਈ, ਤੁਹਾਡੀ ਪੜ੍ਹਾਈ ਦਾ ਮੁੱਖ ਖੇਤਰ ਕੀ ਸੀ?",
    highest_program_name_other: "ਆਪਣੀ ਸਿੱਖਿਆ ਦੇ ਸਭ ਤੋਂ ਉੱਚੇ ਪੱਧਰ ਲਈ ਪੜ੍ਹਾਈ ਦਾ ਮੁੱਖ ਖੇਤਰ ਲਿਖੋ",
    current_program: "ਤੁਹਾਡਾ ਮੌਜੂਦਾ ਪੜ੍ਹਾਈ ਪ੍ਰੋਗਰਾਮ ਕੀ ਹੈ?",
    current_program_name: "ਤੁਹਾਡੀ ਪੜ੍ਹਾਈ ਦਾ ਮੁੱਖ ਖੇਤਰ ਕੀ ਹੈ?",
    current_program_name_other: "ਆਪਣੀ ਪੜ੍ਹਾਈ ਦਾ ਮੁੱਖ ਖੇਤਰ ਲਿਖੋ",
    employed_before: "ਕੀ ਤੁਸੀਂ ਸੌਲਟ ਸਟੇ. ਮੈਰੀ ਆਉਣ ਤੋਂ ਪਹਿਲਾਂ ਕੈਨੇਡਾ ਵਿੱਚ ਨੌਕਰੀ ਕਰਦੇ ਸੀ?",
    previous_job_title: "ਸੌਲਟ ਸਟੇ. ਮੈਰੀ ਆਉਣ ਤੋਂ ਪਹਿਲਾਂ ਤੁਹਾਡਾ ਆਖਰੀ ਕਿੱਤਾ ਕੀ ਸੀ?",
    home_emp_before: "ਕੀ ਤੁਸੀਂ ਕੈਨੇਡਾ ਆਉਣ ਤੋਂ ਪਹਿਲਾਂ ਆਪਣੇ ਜੱਦੀ ਦੇਸ਼ ਵਿੱਚ ਨੌਕਰੀ ਕਰਦੇ ਸੀ?",
    home_country_job: "ਤੁਹਾਡੇ ਜੱਦੀ ਦੇਸ਼ ਵਿੱਚ ਤੁਹਾਡਾ ਆਖਰੀ ਕਿੱਤਾ ਕੀ ਸੀ?",
    employment_status: "ਹੇਠ ਲਿਖਿਆਂ ਵਿੱਚੋਂ ਕਿਹੜਾ ਤੁਹਾਡੀ ਮੌਜੂਦਾ ਰੁਜ਼ਗਾਰ ਸਥਿਤੀ ਦਾ ਸਭ ਤੋਂ ਵਧੀਆ ਵਰਣਨ ਕਰਦਾ ਹੈ?",
    current_job_title: "ਤੁਹਾਡੀ ਮੌਜੂਦਾ ਨੌਕਰੀ ਦਾ ਅਹੁਦਾ ਕੀ ਹੈ?",
    intended_job: "ਕੀ ਤੁਹਾਡੀ ਮੌਜੂਦਾ ਨੌਕਰੀ ਉਹੀ ਹੈ ਜੋ ਤੁਸੀਂ ਕਰਨਾ ਚਾਹੁੰਦੇ ਸੀ?",
    intended_job_title: "ਤੁਸੀਂ ਜੋ ਨੌਕਰੀ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ ਉਸਦਾ ਅਹੁਦਾ ਕੀ ਹੈ?",
    job_search_help: "ਉੱਤਰੀ ਓਨਟਾਰੀਓ / ਸੌਲਟ ਸਟੇ. ਮੈਰੀ ਵਿੱਚ ਤੁਹਾਡੀ ਨੌਕਰੀ ਦੀ ਭਾਲ ਵਿੱਚ ਹੇਠ ਲਿਖਿਆਂ ਵਿੱਚੋਂ ਕਿਹੜੇ ਲਾਭਦਾਇਕ ਸਨ? ਸਾਰੇ ਲਾਗੂ ਵਿਕਲਪ ਚੁਣੋ।",
    job_search_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    work_barriers: "ਸਾਰੀਆਂ ਲਾਗੂ ਰੁਕਾਵਟਾਂ ਚੁਣੋ",
    work_barriers_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    work_support: "ਕਿਸ ਕਿਸਮ ਦੀ ਸਹਾਇਤਾ ਤੁਹਾਨੂੰ ਮਨਚਾਹੀ ਨੌਕਰੀ ਲੈਣ ਵਿੱਚ ਮਦਦ ਕਰੇਗੀ? ਸਾਰੇ ਲਾਗੂ ਵਿਕਲਪ ਚੁਣੋ।",
    work_support_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    unemployed_intended_job: "ਤੁਸੀਂ ਜੋ ਨੌਕਰੀ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ ਉਸਦਾ ਅਹੁਦਾ ਕੀ ਹੈ?",
    unemployed_barrier_gate: "ਕੀ ਸੌਲਟ ਸਟੇ. ਮੈਰੀ ਵਿੱਚ ਕੰਮ ਲੱਭਣ ਵੇਲੇ ਤੁਹਾਨੂੰ ਕਿਸੇ ਰੁਕਾਵਟ ਦਾ ਸਾਹਮਣਾ ਕਰਨਾ ਪਿਆ?",
    unemployment_reasons: "ਸਾਰੀਆਂ ਲਾਗੂ ਰੁਕਾਵਟਾਂ ਚੁਣੋ",
    unemployment_reasons_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    not_looking_reasons: "ਤੁਸੀਂ ਕੰਮ ਕਿਉਂ ਨਹੀਂ ਲੱਭ ਰਹੇ?",
    not_looking_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    student_working: "ਕੀ ਤੁਸੀਂ ਇਸ ਵੇਲੇ ਕੰਮ ਕਰ ਰਹੇ ਹੋ?",
    student_current_job: "ਤੁਹਾਡੀ ਮੌਜੂਦਾ ਨੌਕਰੀ ਦਾ ਅਹੁਦਾ ਕੀ ਹੈ?",
    student_job_relevant: "ਕੀ ਤੁਹਾਡੀ ਮੌਜੂਦਾ ਨੌਕਰੀ ਤੁਹਾਡੇ ਮੌਜੂਦਾ ਪੜ੍ਹਾਈ ਪ੍ਰੋਗਰਾਮ ਨਾਲ ਸੰਬੰਧਿਤ ਹੈ?",
    student_job_help: "ਉੱਤਰੀ ਓਨਟਾਰੀਓ / ਸੌਲਟ ਸਟੇ. ਮੈਰੀ ਵਿੱਚ ਤੁਹਾਡੀ ਨੌਕਰੀ ਦੀ ਭਾਲ ਵਿੱਚ ਹੇਠ ਲਿਖਿਆਂ ਵਿੱਚੋਂ ਕਿਹੜੇ ਲਾਭਦਾਇਕ ਸਨ? ਸਾਰੇ ਲਾਗੂ ਵਿਕਲਪ ਚੁਣੋ।",
    student_job_help_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    student_barrier_gate: "ਕੀ ਸੌਲਟ ਸਟੇ. ਮੈਰੀ ਵਿੱਚ ਨੌਕਰੀ ਲੱਭਣ ਵੇਲੇ ਤੁਹਾਨੂੰ ਕਿਸੇ ਰੁਕਾਵਟ ਦਾ ਸਾਹਮਣਾ ਕਰਨਾ ਪਿਆ?",
    student_barriers: "ਸਾਰੀਆਂ ਲਾਗੂ ਰੁਕਾਵਟਾਂ ਚੁਣੋ",
    student_barriers_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    student_support: "ਕਿਸ ਕਿਸਮ ਦੀ ਸਹਾਇਤਾ ਤੁਹਾਨੂੰ ਮਨਚਾਹੀ ਨੌਕਰੀ ਲੈਣ ਵਿੱਚ ਮਦਦ ਕਰੇਗੀ? ਸਾਰੇ ਲਾਗੂ ਵਿਕਲਪ ਚੁਣੋ।",
    student_support_other: "ਕਿਰਪਾ ਕਰਕੇ ਦੱਸੋ",
    planned_intended_job: "ਗ੍ਰੈਜੂਏਸ਼ਨ ਤੋਂ ਬਾਅਦ ਤੁਸੀਂ ਜੋ ਨੌਕਰੀ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ ਉਸਦਾ ਅਹੁਦਾ ਕੀ ਹੈ?",
    skills: "ਤੁਸੀਂ ਹੇਠ ਲਿਖੇ ਹਰੇਕ ਹੁਨਰ ਲਈ ਆਪਣੇ ਪੱਧਰ ਦਾ ਮੁਲਾਂਕਣ ਕਿਵੇਂ ਕਰੋਗੇ?",
    gift_card_draw: "ਕੀ ਤੁਸੀਂ ਗਿਫਟ ਕਾਰਡ ਡਰਾਅ ਵਿੱਚ ਭਾਗ ਲੈਣਾ ਚਾਹੁੰਦੇ ਹੋ? (ਸਿਰਫ਼ ਇਨਾਮ ਦੇ ਉਦੇਸ਼ਾਂ ਲਈ)",
    "work_barrier.a": "ਕੀ ਕੋਈ ਰੁਕਾਵਟ ਹੈ ਜੋ ਤੁਹਾਨੂੰ ਪੂਰਾ ਸਮਾਂ ਕੰਮ ਕਰਨ ਤੋਂ ਰੋਕਦੀ ਹੈ?",
    "work_barrier.b": "ਕੀ ਕੋਈ ਰੁਕਾਵਟ ਹੈ ਜੋ ਤੁਹਾਨੂੰ ਮਨਚਾਹੀ ਨੌਕਰੀ ਲੈਣ ਤੋਂ ਰੋਕਦੀ ਹੈ?",
    "work_barrier.c": "ਕੀ ਕੋਈ ਰੁਕਾਵਟ ਹੈ ਜੋ ਤੁਹਾਨੂੰ ਪੂਰਾ ਸਮਾਂ ਕੰਮ ਕਰਨ ਅਤੇ ਮਨਚਾਹੀ ਨੌਕਰੀ ਕਰਨ ਤੋਂ ਰੋਕਦੀ ਹੈ?",
    "work_barrier.d": "ਕੀ ਕੋਈ ਰੁਕਾਵਟ ਹੈ ਜੋ ਤੁਹਾਨੂੰ ਪੂਰੇ ਸਮੇਂ ਦੀ ਨੌਕਰੀ ਲੈਣ ਤੋਂ ਰੋਕਦੀ ਹੈ?",
    "work_barrier.e": "ਕੀ ਕੋਈ ਰੁਕਾਵਟ ਹੈ ਜੋ ਤੁਹਾਨੂੰ ਮਨਚਾਹੀ ਨੌਕਰੀ ਕਰਨ ਤੋਂ ਰੋਕਦੀ ਹੈ?",
  },
  help: {
    skills: "1 = ਸਭ ਤੋਂ ਘੱਟ, 2 = ਘੱਟ, 3 = ਦਰਮਿਆਨਾ, 4 = ਉੱਚਾ, 5 = ਸਭ ਤੋਂ ਉੱਚਾ, 0 = ਯਕੀਨ ਨਹੀਂ",
  },
  o: {
    "85 or older": "85 ਜਾਂ ਵੱਧ",
    "Advanced Diploma": "ਉੱਨਤ ਡਿਪਲੋਮਾ",
    "Alberta": "ਅਲਬਰਟਾ",
    "Apprenticeship": "ਸਿਖਲਾਈ (ਅਪ੍ਰੈਂਟਿਸਸ਼ਿਪ)",
    "British Columbia": "ਬ੍ਰਿਟਿਸ਼ ਕੋਲੰਬੀਆ",
    "Canadian degree or training": "ਕੈਨੇਡੀਅਨ ਡਿਗਰੀ ਜਾਂ ਸਿਖਲਾਈ",
    "Canadian work experience": "ਕੈਨੇਡੀਅਨ ਕੰਮ ਦਾ ਤਜਰਬਾ",
    "Caregiving responsibilities": "ਦੇਖਭਾਲ ਦੀਆਂ ਜ਼ਿੰਮੇਵਾਰੀਆਂ",
    "Childcare support": "ਬਾਲ ਦੇਖਭਾਲ ਸਹਾਇਤਾ",
    "College certificate": "ਕਾਲਜ ਸਰਟੀਫਿਕੇਟ",
    "Credential recognition support": "ਯੋਗਤਾ ਮਾਨਤਾ ਸਹਾਇਤਾ",
    "Credentials not recognized": "ਯੋਗਤਾਵਾਂ ਮਾਨਤਾ ਪ੍ਰਾਪਤ ਨਹੀਂ",
    "Diploma": "ਡਿਪਲੋਮਾ",
    "Discrimination of any kind": "ਕਿਸੇ ਵੀ ਕਿਸਮ ਦਾ ਵਿਤਕਰਾ",
    "Doesn’t need employment income": "ਰੁਜ਼ਗਾਰ ਆਮਦਨ ਦੀ ਲੋੜ ਨਹੀਂ",
    "Economic Immigrant": "ਆਰਥਿਕ ਪ੍ਰਵਾਸੀ",
    "Employed casual (less than 10 hours/week)": "ਆਰਜ਼ੀ ਰੁਜ਼ਗਾਰ (ਹਫ਼ਤੇ ਵਿੱਚ 10 ਘੰਟਿਆਂ ਤੋਂ ਘੱਟ)",
    "Employed full time (30+ hours/week)": "ਪੂਰੇ ਸਮੇਂ ਦਾ ਰੁਜ਼ਗਾਰ (ਹਫ਼ਤੇ ਵਿੱਚ 30+ ਘੰਟੇ)",
    "Employed part time (10-30 hours/week)": "ਅੱਧੇ ਸਮੇਂ ਦਾ ਰੁਜ਼ਗਾਰ (ਹਫ਼ਤੇ ਵਿੱਚ 10-30 ਘੰਟੇ)",
    "Employment or settlement centre": "ਰੁਜ਼ਗਾਰ ਜਾਂ ਵਸੇਬਾ ਕੇਂਦਰ",
    "Family Sponsored": "ਪਰਿਵਾਰ ਦੁਆਰਾ ਸਪਾਂਸਰ",
    "Health issues": "ਸਿਹਤ ਸਮੱਸਿਆਵਾਂ",
    "Health reasons": "ਸਿਹਤ ਕਾਰਨ",
    "High school diploma or equivalent": "ਹਾਈ ਸਕੂਲ ਡਿਪਲੋਮਾ ਜਾਂ ਬਰਾਬਰ",
    "Household responsibilities": "ਘਰੇਲੂ ਜ਼ਿੰਮੇਵਾਰੀਆਂ",
    "Household work / Caregiver": "ਘਰੇਲੂ ਕੰਮ / ਦੇਖਭਾਲ ਕਰਨ ਵਾਲਾ",
    "I agree": "ਮੈਂ ਸਹਿਮਤ ਹਾਂ",
    "I didn't have a work permit": "ਮੇਰੇ ਕੋਲ ਵਰਕ ਪਰਮਿਟ ਨਹੀਂ ਸੀ",
    "I directly moved to Sault": "ਮੈਂ ਸਿੱਧਾ ਸੌਲਟ ਆਇਆ",
    "I disagree": "ਮੈਂ ਸਹਿਮਤ ਨਹੀਂ ਹਾਂ",
    "Immigrant (permanent resident)": "ਪ੍ਰਵਾਸੀ (ਸਥਾਈ ਨਿਵਾਸੀ)",
    "Immigration issues": "ਇਮੀਗ੍ਰੇਸ਼ਨ ਸਮੱਸਿਆਵਾਂ",
    "In Canada": "ਕੈਨੇਡਾ ਵਿੱਚ",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "ਮੂਲ ਨਿਵਾਸੀ (ਫਸਟ ਨੇਸ਼ਨਜ਼, ਮੈਟਿਸ, ਇਨੂਇਟ/ਇਨੁਕ)",
    "International Student": "ਅੰਤਰਰਾਸ਼ਟਰੀ ਵਿਦਿਆਰਥੀ",
    "Internship / volunteer experience": "ਇੰਟਰਨਸ਼ਿਪ / ਸਵੈ-ਸੇਵੀ ਤਜਰਬਾ",
    "Lack of Canadian work experience": "ਕੈਨੇਡੀਅਨ ਕੰਮ ਦੇ ਤਜਰਬੇ ਦੀ ਘਾਟ",
    "Lack of skills for available jobs": "ਉਪਲਬਧ ਨੌਕਰੀਆਂ ਲਈ ਹੁਨਰ ਦੀ ਘਾਟ",
    "Language barriers": "ਭਾਸ਼ਾਈ ਰੁਕਾਵਟਾਂ",
    "Language support": "ਭਾਸ਼ਾ ਸਹਾਇਤਾ",
    "Limited job opportunities in preferred sector": "ਪਸੰਦੀਦਾ ਖੇਤਰ ਵਿੱਚ ਸੀਮਤ ਨੌਕਰੀ ਦੇ ਮੌਕੇ",
    "Limited knowledge of local job market": "ਸਥਾਨਕ ਨੌਕਰੀ ਬਾਜ਼ਾਰ ਦੀ ਸੀਮਤ ਜਾਣਕਾਰੀ",
    "Limited mentorship and job-matching support": "ਸੀਮਤ ਮਾਰਗਦਰਸ਼ਨ ਅਤੇ ਨੌਕਰੀ-ਮਿਲਾਨ ਸਹਾਇਤਾ",
    "Limited professional network": "ਸੀਮਤ ਪੇਸ਼ੇਵਰ ਨੈੱਟਵਰਕ",
    "Limited suitable jobs": "ਸੀਮਤ ਢੁਕਵੀਆਂ ਨੌਕਰੀਆਂ",
    "Local job boards": "ਸਥਾਨਕ ਨੌਕਰੀ ਬੋਰਡ",
    "Local job market information": "ਸਥਾਨਕ ਨੌਕਰੀ ਬਾਜ਼ਾਰ ਦੀ ਜਾਣਕਾਰੀ",
    "Local training or certification": "ਸਥਾਨਕ ਸਿਖਲਾਈ ਜਾਂ ਪ੍ਰਮਾਣੀਕਰਨ",
    "Low wages": "ਘੱਟ ਤਨਖਾਹ",
    "Man": "ਪੁਰਸ਼",
    "Manitoba": "ਮੈਨੀਟੋਬਾ",
    "Mentorship support": "ਮਾਰਗਦਰਸ਼ਨ ਸਹਾਇਤਾ",
    "Networking support": "ਨੈੱਟਵਰਕਿੰਗ ਸਹਾਇਤਾ",
    "New Brunswick": "ਨਿਊ ਬਰੰਜ਼ਵਿਕ",
    "Newfoundland and Labrador": "ਨਿਊਫਾਊਂਡਲੈਂਡ ਅਤੇ ਲੈਬਰਾਡੋਰ",
    "No": "ਨਹੀਂ",
    "Non-Canadian work experience not recognized": "ਗੈਰ-ਕੈਨੇਡੀਅਨ ਕੰਮ ਦਾ ਤਜਰਬਾ ਮਾਨਤਾ ਪ੍ਰਾਪਤ ਨਹੀਂ",
    "Non-binary person or other gender": "ਗੈਰ-ਬਾਈਨਰੀ ਵਿਅਕਤੀ ਜਾਂ ਹੋਰ ਲਿੰਗ",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "ਗੈਰ-ਸਥਾਈ ਨਿਵਾਸੀ (ਜਿਵੇਂ, ਵਰਕ ਪਰਮਿਟ, ਸਟੱਡੀ ਪਰਮਿਟ, ਸ਼ਰਨਾਰਥੀ ਦਾਅਵੇਦਾਰ)",
    "None of the above (do not select any other options)": "ਉਪਰੋਕਤ ਵਿੱਚੋਂ ਕੋਈ ਨਹੀਂ (ਕੋਈ ਹੋਰ ਵਿਕਲਪ ਨਾ ਚੁਣੋ)",
    "Northwest Territories": "ਨਾਰਥਵੈਸਟ ਟੈਰੀਟਰੀਜ਼",
    "Not qualified for available jobs": "ਉਪਲਬਧ ਨੌਕਰੀਆਂ ਲਈ ਯੋਗ ਨਹੀਂ",
    "Nova Scotia": "ਨੋਵਾ ਸਕੋਸ਼ੀਆ",
    "Nunavut": "ਨੁਨਾਵੁਤ",
    "On temporary leave from a job (e.g., maternity/parental leave)": "ਨੌਕਰੀ ਤੋਂ ਆਰਜ਼ੀ ਛੁੱਟੀ 'ਤੇ (ਜਿਵੇਂ, ਜਣੇਪਾ/ਮਾਪਿਆਂ ਦੀ ਛੁੱਟੀ)",
    "Other": "ਹੋਰ",
    "Other parts of Ontario": "ਓਨਟਾਰੀਓ ਦੇ ਹੋਰ ਹਿੱਸੇ",
    "Outside Canada": "ਕੈਨੇਡਾ ਤੋਂ ਬਾਹਰ",
    "Outside of Canada": "ਕੈਨੇਡਾ ਤੋਂ ਬਾਹਰ",
    "Outside of Ontario but within Canada": "ਓਨਟਾਰੀਓ ਤੋਂ ਬਾਹਰ ਪਰ ਕੈਨੇਡਾ ਦੇ ਅੰਦਰ",
    "Personal contacts": "ਨਿੱਜੀ ਸੰਪਰਕ",
    "Post-graduate degree (e.g., Master's)": "ਪੋਸਟ-ਗ੍ਰੈਜੂਏਟ ਡਿਗਰੀ (ਜਿਵੇਂ, ਮਾਸਟਰਜ਼)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "ਪੋਸਟ-ਗ੍ਰੈਜੂਏਟ ਡਿਗਰੀ (ਜਿਵੇਂ, ਮਾਸਟਰਜ਼, ਪੀਐਚਡੀ, ਐਮਡੀ)",
    "Primary school": "ਪ੍ਰਾਇਮਰੀ ਸਕੂਲ",
    "Prince Edward Island": "ਪ੍ਰਿੰਸ ਐਡਵਰਡ ਆਈਲੈਂਡ",
    "Professional network": "ਪੇਸ਼ੇਵਰ ਨੈੱਟਵਰਕ",
    "Protected Person": "ਸੁਰੱਖਿਅਤ ਵਿਅਕਤੀ",
    "Quebec": "ਕਿਊਬੈਕ",
    "Recognition of non-Canadian work experience": "ਗੈਰ-ਕੈਨੇਡੀਅਨ ਕੰਮ ਦੇ ਤਜਰਬੇ ਦੀ ਮਾਨਤਾ",
    "Refugee": "ਸ਼ਰਨਾਰਥੀ",
    "Refugee Claimant": "ਸ਼ਰਨਾਰਥੀ ਦਾਅਵੇਦਾਰ",
    "Resume/interview support": "ਰੈਜ਼ਿਊਮੇ/ਇੰਟਰਵਿਊ ਸਹਾਇਤਾ",
    "Retired": "ਸੇਵਾਮੁਕਤ",
    "Saskatchewan": "ਸਸਕੈਚਵਨ",
    "Self-employed": "ਸਵੈ-ਰੁਜ਼ਗਾਰ",
    "Skills-to-job matching platform": "ਹੁਨਰ-ਤੋਂ-ਨੌਕਰੀ ਮਿਲਾਨ ਪਲੇਟਫਾਰਮ",
    "Social media (e.g., LinkedIn)": "ਸੋਸ਼ਲ ਮੀਡੀਆ (ਜਿਵੇਂ, ਲਿੰਕਡਇਨ)",
    "Student or recent graduate": "ਵਿਦਿਆਰਥੀ ਜਾਂ ਹਾਲ ਹੀ ਦਾ ਗ੍ਰੈਜੂਏਟ",
    "Temporary Foreign Worker": "ਆਰਜ਼ੀ ਵਿਦੇਸ਼ੀ ਕਾਮਾ",
    "Temporary Resident Permit Holder": "ਆਰਜ਼ੀ ਨਿਵਾਸੀ ਪਰਮਿਟ ਧਾਰਕ",
    "Training recommendations": "ਸਿਖਲਾਈ ਸਿਫ਼ਾਰਸ਼ਾਂ",
    "Unable to work": "ਕੰਮ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ",
    "Undergraduate degree": "ਅੰਡਰਗ੍ਰੈਜੂਏਟ ਡਿਗਰੀ",
    "Unemployed and actively looking for work": "ਬੇਰੁਜ਼ਗਾਰ ਅਤੇ ਸਰਗਰਮੀ ਨਾਲ ਕੰਮ ਲੱਭ ਰਿਹਾ",
    "Unemployed and not looking for work": "ਬੇਰੁਜ਼ਗਾਰ ਅਤੇ ਕੰਮ ਨਹੀਂ ਲੱਭ ਰਿਹਾ",
    "Visible minority (e.g., South Asian, Chinese, Black)": "ਦਿਸਣਯੋਗ ਘੱਟਗਿਣਤੀ (ਜਿਵੇਂ, ਦੱਖਣੀ ਏਸ਼ੀਆਈ, ਚੀਨੀ, ਕਾਲੇ)",
    "Woman": "ਔਰਤ",
    "Yes": "ਹਾਂ",
    "Yukon": "ਯੂਕੋਨ",
  },
  def: {
    "Family Sponsored": "ਤੁਸੀਂ ਪ੍ਰਵਾਸ ਕੀਤਾ ਕਿਉਂਕਿ ਕੈਨੇਡਾ ਵਿੱਚ ਪਹਿਲਾਂ ਤੋਂ ਮੌਜੂਦ ਪਰਿਵਾਰਕ ਮੈਂਬਰ ਨੇ ਤੁਹਾਨੂੰ ਸਪਾਂਸਰ ਕੀਤਾ।",
    "Economic Immigrant": "ਤੁਸੀਂ ਹੁਨਰਮੰਦ-ਕਾਮੇ ਜਾਂ ਕਾਰੋਬਾਰੀ ਪ੍ਰੋਗਰਾਮ ਰਾਹੀਂ ਪ੍ਰਵਾਸ ਕੀਤਾ (ਜਿਵੇਂ, ਐਕਸਪ੍ਰੈਸ ਐਂਟਰੀ, ਪ੍ਰੋਵਿੰਸ਼ੀਅਲ ਨਾਮਿਨੀ)।",
    "Refugee": "ਤੁਸੀਂ ਆਪਣੇ ਜੱਦੀ ਦੇਸ਼ ਵਿੱਚ ਖ਼ਤਰੇ ਤੋਂ ਸੁਰੱਖਿਆ ਲਈ ਕੈਨੇਡਾ ਆਏ।",
    "Temporary Foreign Worker": "ਕਿਸੇ ਮਾਲਕ ਨਾਲ ਜੁੜੇ ਵਰਕ ਪਰਮਿਟ ਜਾਂ ਖੁੱਲ੍ਹੇ ਵਰਕ ਪਰਮਿਟ 'ਤੇ ਕੈਨੇਡਾ ਵਿੱਚ।",
    "Refugee Claimant": "ਤੁਸੀਂ ਕੈਨੇਡਾ ਤੋਂ ਸ਼ਰਨਾਰਥੀ ਸੁਰੱਖਿਆ ਮੰਗੀ ਹੈ ਅਤੇ ਫ਼ੈਸਲੇ ਦੀ ਉਡੀਕ ਕਰ ਰਹੇ ਹੋ।",
    "Protected Person": "ਕੈਨੇਡਾ ਨੇ ਪਹਿਲਾਂ ਹੀ ਸਵੀਕਾਰ ਕਰ ਲਿਆ ਹੈ ਕਿ ਤੁਹਾਨੂੰ ਸੁਰੱਖਿਆ ਦੀ ਲੋੜ ਹੈ (ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਸ਼ਰਨਾਰਥੀ/ਸੁਰੱਖਿਅਤ ਦਰਜਾ)।",
    "Temporary Resident Permit Holder": "ਤੁਹਾਡੇ ਕੋਲ ਆਰਜ਼ੀ ਤੌਰ 'ਤੇ ਰਹਿਣ ਲਈ ਵਿਸ਼ੇਸ਼ ਪਰਮਿਟ ਹੈ ਜਦੋਂ ਆਮ ਤੌਰ 'ਤੇ ਇਸਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਹੁੰਦੀ।",
    "Canadian degree or training": "ਤੁਸੀਂ ਕੈਨੇਡਾ ਵਿੱਚ ਕੋਈ ਡਿਗਰੀ ਜਾਂ ਸਿਖਲਾਈ ਪ੍ਰੋਗਰਾਮ ਪੂਰਾ ਕੀਤਾ ਹੈ।",
    "Canadian work experience": "ਤੁਸੀਂ ਕੈਨੇਡਾ ਵਿੱਚ ਕਿਸੇ ਮਾਲਕ ਲਈ ਕੰਮ ਕੀਤਾ ਹੈ।",
    "Employment or settlement centre": "ਤੁਹਾਨੂੰ ਅਜਿਹੀ ਸੰਸਥਾ ਤੋਂ ਮਦਦ ਮਿਲੀ ਜੋ ਨੌਕਰੀ ਲੱਭਣ ਵਾਲਿਆਂ ਜਾਂ ਨਵੇਂ ਆਏ ਲੋਕਾਂ ਦੀ ਸਹਾਇਤਾ ਕਰਦੀ ਹੈ (ਜਿਵੇਂ, Sault Community Career Center)।",
    "Internship / volunteer experience": "ਤੁਸੀਂ ਬਿਨਾਂ ਤਨਖਾਹ ਵਾਲੀ ਇੰਟਰਨਸ਼ਿਪ, ਥੋੜ੍ਹੇ ਸਮੇਂ ਦੀ ਨਿਯੁਕਤੀ ਜਾਂ ਸਵੈ-ਸੇਵਾ ਰਾਹੀਂ ਕੰਮ ਦਾ ਤਜਰਬਾ ਹਾਸਲ ਕੀਤਾ।",
    "Local job boards": "ਤੁਸੀਂ ਅਜਿਹੀਆਂ ਵੈੱਬਸਾਈਟਾਂ ਜਾਂ ਇਸ਼ਤਿਹਾਰਾਂ ਦੀ ਵਰਤੋਂ ਕੀਤੀ ਜੋ ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਨੌਕਰੀਆਂ ਦੀ ਜਾਣਕਾਰੀ ਦਿੰਦੀਆਂ ਹਨ (ਜਿਵੇਂ, AWIC ਜੌਬ ਬੋਰਡ)।",
    "Personal contacts": "ਤੁਹਾਨੂੰ ਪਰਿਵਾਰ, ਦੋਸਤਾਂ ਜਾਂ ਨਿੱਜੀ ਤੌਰ 'ਤੇ ਜਾਣਨ ਵਾਲੇ ਲੋਕਾਂ ਤੋਂ ਮਦਦ ਜਾਂ ਨੌਕਰੀ ਦੀ ਜਾਣਕਾਰੀ ਮਿਲੀ।",
    "Professional network": "ਤੁਸੀਂ ਆਪਣੇ ਕੰਮ ਦੇ ਖੇਤਰ ਦੇ ਸੰਪਰਕਾਂ, ਜਿਵੇਂ ਸਹਿਕਰਮੀਆਂ ਜਾਂ ਮਾਰਗਦਰਸ਼ਕਾਂ ਦੀ ਵਰਤੋਂ ਕੀਤੀ।",
    "Recognition of non-Canadian work experience": "ਕੈਨੇਡਾ ਤੋਂ ਬਾਹਰ ਹਾਸਲ ਕੀਤਾ ਤੁਹਾਡਾ ਕੰਮ ਦਾ ਤਜਰਬਾ ਸਵੀਕਾਰ ਕੀਤਾ ਗਿਆ।",
    "Caregiving responsibilities": "ਤੁਹਾਨੂੰ ਉਹਨਾਂ ਬੱਚਿਆਂ ਜਾਂ ਬਜ਼ੁਰਗ ਪਰਿਵਾਰਕ ਮੈਂਬਰਾਂ ਦੀ ਦੇਖਭਾਲ ਕਰਨੀ ਪੈਂਦੀ ਹੈ ਜੋ ਤੁਹਾਡੇ 'ਤੇ ਨਿਰਭਰ ਹਨ।",
    "Credentials not recognized": "ਕੈਨੇਡਾ ਤੋਂ ਬਾਹਰ ਦੀ ਤੁਹਾਡੀ ਸਿੱਖਿਆ, ਡਿਗਰੀ ਜਾਂ ਲਾਇਸੰਸ ਕੈਨੇਡੀਅਨ ਮਾਲਕਾਂ ਵੱਲੋਂ ਸਵੀਕਾਰ ਨਹੀਂ ਕੀਤਾ ਜਾਂਦਾ।",
    "Discrimination of any kind": "ਤੁਹਾਡੇ ਨਾਲ ਤੁਹਾਡੀ ਨਸਲ, ਜਾਤੀ, ਧਰਮ, ਲਿੰਗ, ਲਹਿਜੇ, ਉਮਰ ਜਾਂ ਹੋਰ ਨਿੱਜੀ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਕਾਰਨ ਬੇਇਨਸਾਫ਼ੀ ਹੋਈ।",
    "Health issues": "ਤੁਹਾਨੂੰ ਸਰੀਰਕ ਜਾਂ ਮਾਨਸਿਕ ਸਿਹਤ ਸਮੱਸਿਆਵਾਂ ਹਨ ਜਿਸ ਕਾਰਨ ਨੌਕਰੀ ਲੱਭਣੀ ਜਾਂ ਰੱਖਣੀ ਔਖੀ ਹੋ ਜਾਂਦੀ ਹੈ।",
    "Household responsibilities": "ਤੁਹਾਨੂੰ ਘਰੇਲੂ ਕੰਮ (ਖਾਣਾ ਬਣਾਉਣਾ, ਸਫ਼ਾਈ, ਘਰ ਚਲਾਉਣਾ) ਸੰਭਾਲਣੇ ਪੈਂਦੇ ਹਨ।",
    "Lack of Canadian work experience": "ਮਾਲਕ ਕੈਨੇਡਾ ਵਿੱਚ ਕੰਮ ਦਾ ਤਜਰਬਾ ਮੰਗਦੇ ਹਨ, ਜੋ ਤੁਹਾਡੇ ਕੋਲ ਅਜੇ ਨਹੀਂ ਹੈ।",
    "Lack of skills for available jobs": "ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਉਪਲਬਧ ਨੌਕਰੀਆਂ ਲਈ ਅਜਿਹੇ ਹੁਨਰ ਜਾਂ ਸਿਖਲਾਈ ਚਾਹੀਦੀ ਹੈ ਜੋ ਤੁਹਾਡੇ ਕੋਲ ਇਸ ਵੇਲੇ ਨਹੀਂ ਹਨ।",
    "Language barriers": "ਤੁਹਾਡੀ ਅੰਗਰੇਜ਼ੀ (ਜਾਂ ਫ਼੍ਰੈਂਚ) ਦੀ ਮੁਹਾਰਤ ਕਾਰਨ ਕੰਮ ਲੱਭਣਾ ਜਾਂ ਇੰਟਰਵਿਊ ਪਾਸ ਕਰਨੀ ਔਖੀ ਹੋ ਜਾਂਦੀ ਹੈ।",
    "Limited job opportunities in preferred sector": "ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਤੁਹਾਡੇ ਖੇਤਰ ਜਾਂ ਉਦਯੋਗ ਵਿੱਚ ਬਹੁਤ ਘੱਟ ਨੌਕਰੀਆਂ ਹਨ।",
    "Limited knowledge of local job market": "ਤੁਹਾਨੂੰ ਪੱਕਾ ਪਤਾ ਨਹੀਂ ਕਿ ਨੌਕਰੀ ਕਿਵੇਂ ਲੱਭਣੀ ਹੈ, ਕਿਹੜੇ ਮਾਲਕ ਭਰਤੀ ਕਰ ਰਹੇ ਹਨ, ਜਾਂ ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਭਰਤੀ ਕਿਵੇਂ ਹੁੰਦੀ ਹੈ।",
    "Limited mentorship and job-matching support": "ਤੁਹਾਡੇ ਕੋਲ ਅਜਿਹੇ ਮਾਰਗਦਰਸ਼ਕਾਂ ਜਾਂ ਸੇਵਾਵਾਂ ਤੱਕ ਪਹੁੰਚ ਨਹੀਂ ਜੋ ਤੁਹਾਨੂੰ ਢੁਕਵੀਆਂ ਨੌਕਰੀਆਂ ਨਾਲ ਜੋੜਨ।",
    "Limited professional network": "ਤੁਸੀਂ ਆਪਣੇ ਖੇਤਰ ਵਿੱਚ ਅਜਿਹੇ ਘੱਟ ਲੋਕਾਂ ਨੂੰ ਜਾਣਦੇ ਹੋ ਜੋ ਨੌਕਰੀ ਦੀ ਜਾਣਕਾਰੀ, ਸਿਫ਼ਾਰਸ਼ ਜਾਂ ਸਲਾਹ ਦੇ ਸਕਣ।",
    "Non-Canadian work experience not recognized": "ਕੈਨੇਡਾ ਤੋਂ ਬਾਹਰ ਹਾਸਲ ਕੀਤਾ ਤੁਹਾਡਾ ਕੰਮ ਦਾ ਤਜਰਬਾ ਕੈਨੇਡੀਅਨ ਮਾਲਕਾਂ ਵੱਲੋਂ ਸਵੀਕਾਰ ਜਾਂ ਕਦਰ ਨਹੀਂ ਕੀਤਾ ਜਾਂਦਾ।",
    "Childcare support": "ਕੰਮ ਕਰ ਸਕਣ ਲਈ ਤੁਹਾਨੂੰ ਆਪਣੇ ਬੱਚਿਆਂ ਦੀ ਦੇਖਭਾਲ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।",
    "Credential recognition support": "ਕੈਨੇਡਾ ਤੋਂ ਬਾਹਰ ਦੀ ਆਪਣੀ ਸਿੱਖਿਆ ਜਾਂ ਪੇਸ਼ੇਵਰ ਯੋਗਤਾਵਾਂ ਨੂੰ ਸਵੀਕਾਰ ਕਰਵਾਉਣ ਲਈ ਤੁਹਾਨੂੰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।",
    "Language support": "ਤੁਹਾਨੂੰ ਆਪਣੀ ਅੰਗਰੇਜ਼ੀ (ਜਾਂ ਫ਼੍ਰੈਂਚ) ਸੁਧਾਰਨ ਲਈ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।",
    "Local job market information": "ਤੁਹਾਨੂੰ ਜਾਣਕਾਰੀ ਚਾਹੀਦੀ ਹੈ ਕਿ ਕਿਹੜੇ ਮਾਲਕ ਭਰਤੀ ਕਰ ਰਹੇ ਹਨ, ਕਿਹੜੀਆਂ ਨੌਕਰੀਆਂ ਉਪਲਬਧ ਹਨ ਅਤੇ ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਕਿਹੜੇ ਹੁਨਰਾਂ ਦੀ ਮੰਗ ਹੈ।",
    "Local training or certification": "ਉਪਲਬਧ ਨੌਕਰੀਆਂ ਲਈ ਯੋਗ ਬਣਨ ਵਾਸਤੇ ਤੁਹਾਨੂੰ ਆਪਣੇ ਖੇਤਰ ਵਿੱਚ ਦਿੱਤੀ ਜਾਂਦੀ ਸਿਖਲਾਈ ਜਾਂ ਪ੍ਰਮਾਣੀਕਰਨ ਚਾਹੀਦਾ ਹੈ।",
    "Mentorship support": "ਤੁਹਾਨੂੰ ਆਪਣੇ ਖੇਤਰ ਦੇ ਤਜਰਬੇਕਾਰ ਲੋਕਾਂ ਨਾਲ ਸੰਪਰਕ ਚਾਹੀਦਾ ਹੈ।",
    "Networking support": "ਤੁਹਾਨੂੰ ਮਾਲਕਾਂ ਅਤੇ ਪੇਸ਼ੇਵਰਾਂ ਨੂੰ ਮਿਲਣ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।",
    "Resume/interview support": "ਤੁਹਾਨੂੰ ਆਪਣਾ ਰੈਜ਼ਿਊਮੇ, ਕਵਰ ਲੈਟਰ ਤਿਆਰ ਕਰਨ ਜਾਂ ਇੰਟਰਵਿਊ ਦਾ ਅਭਿਆਸ ਕਰਨ ਵਿੱਚ ਮਦਦ ਚਾਹੀਦੀ ਹੈ।",
    "Skills-to-job matching platform": "ਤੁਹਾਨੂੰ ਅਜਿਹੀ ਸੇਵਾ ਜਾਂ ਸਾਧਨ ਚਾਹੀਦਾ ਹੈ ਜੋ ਤੁਹਾਡੇ ਹੁਨਰਾਂ ਨੂੰ ਢੁਕਵੀਆਂ ਨੌਕਰੀਆਂ ਨਾਲ ਮਿਲਾਏ।",
    "Training recommendations": "ਤੁਹਾਨੂੰ ਸੁਝਾਅ ਚਾਹੀਦੇ ਹਨ ਕਿ ਨੌਕਰੀ ਮਿਲਣ ਦੀ ਸੰਭਾਵਨਾ ਵਧਾਉਣ ਲਈ ਕਿਹੜੀ ਸਿਖਲਾਈ ਜਾਂ ਕੋਰਸ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ।",
    "Doesn’t need employment income": "ਤੁਹਾਨੂੰ ਕੰਮ ਕਰਨ ਦੀ ਲੋੜ ਨਹੀਂ ਕਿਉਂਕਿ ਤੁਹਾਡੇ ਕੋਲ ਆਮਦਨ ਦੇ ਹੋਰ ਸਰੋਤ ਜਾਂ ਵਿੱਤੀ ਸਹਾਇਤਾ ਹੈ।",
    "Health reasons": "ਤੁਹਾਨੂੰ ਸਰੀਰਕ ਜਾਂ ਮਾਨਸਿਕ ਸਿਹਤ ਸਮੱਸਿਆਵਾਂ ਹਨ ਜਿਸ ਕਾਰਨ ਨੌਕਰੀ ਲੱਭਣੀ ਜਾਂ ਰੱਖਣੀ ਔਖੀ ਹੋ ਜਾਂਦੀ ਹੈ।",
    "Immigration issues": "ਤੁਹਾਡਾ ਇਮੀਗ੍ਰੇਸ਼ਨ ਦਰਜਾ ਜਾਂ ਦਸਤਾਵੇਜ਼ (ਜਿਵੇਂ, ਵਰਕ ਪਰਮਿਟ, ਪੀਆਰ ਦੀ ਪ੍ਰਕਿਰਿਆ) ਤੁਹਾਨੂੰ ਕੰਮ ਕਰਨ ਤੋਂ ਰੋਕਦੇ ਹਨ।",
    "Limited suitable jobs": "ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਅਜਿਹੀਆਂ ਬਹੁਤ ਘੱਟ ਨੌਕਰੀਆਂ ਹਨ ਜੋ ਤੁਹਾਡੇ ਹੁਨਰਾਂ, ਤਜਰਬੇ ਜਾਂ ਪਸੰਦ ਨਾਲ ਮੇਲ ਖਾਂਦੀਆਂ ਹੋਣ।",
    "Low wages": "ਉਪਲਬਧ ਨੌਕਰੀਆਂ ਇੰਨੀ ਘੱਟ ਤਨਖਾਹ ਦਿੰਦੀਆਂ ਹਨ ਕਿ ਤੁਹਾਡੇ ਲਈ ਕੰਮ ਕਰਨਾ ਲਾਹੇਵੰਦ ਨਹੀਂ ਰਹਿੰਦਾ।",
    "Not qualified for available jobs": "ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਉਪਲਬਧ ਨੌਕਰੀਆਂ ਲਈ ਅਜਿਹੀ ਸਿੱਖਿਆ, ਹੁਨਰ ਜਾਂ ਪ੍ਰਮਾਣੀਕਰਨ ਚਾਹੀਦਾ ਹੈ ਜੋ ਤੁਹਾਡੇ ਕੋਲ ਇਸ ਵੇਲੇ ਨਹੀਂ ਹੈ।",
  },
  ui: {
    "% complete": "% ਪੂਰਾ",
    "Back to home": "ਹੋਮ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    "Back": "ਵਾਪਸ",
    "Consent is required to continue": "ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਹਿਮਤੀ ਲੋੜੀਂਦੀ ਹੈ",
    "Definition:": "ਪਰਿਭਾਸ਼ਾ:",
    "Email address": "ਈਮੇਲ ਪਤਾ",
    "Finish to become a Survey Champion": "ਸਰਵੇਖਣ ਚੈਂਪੀਅਨ ਬਣਨ ਲਈ ਪੂਰਾ ਕਰੋ",
    "Five $50 local gift cards drawn monthly": "ਹਰ ਮਹੀਨੇ $50 ਦੇ ਪੰਜ ਸਥਾਨਕ ਗਿਫਟ ਕਾਰਡ ਕੱਢੇ ਜਾਂਦੇ ਹਨ",
    "Go back": "ਵਾਪਸ ਜਾਓ",
    "Go home": "ਹੋਮ 'ਤੇ ਜਾਓ",
    "Home": "ਹੋਮ",
    "Next 5 skills": "ਅਗਲੇ 5 ਹੁਨਰ",
    "Next question": "ਅਗਲਾ ਸਵਾਲ",
    "No matches": "ਕੋਈ ਮੇਲ ਨਹੀਂ",
    "Not sure": "ਯਕੀਨ ਨਹੀਂ",
    "One moment.": "ਇੱਕ ਪਲ।",
    "Previous question": "ਪਿਛਲਾ ਸਵਾਲ",
    "Saving your response…": "ਤੁਹਾਡਾ ਜਵਾਬ ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "ਸਰਵਰ ਨਾਲ ਜੁੜਨ ਵਿੱਚ ਕੋਈ ਸਮੱਸਿਆ ਆਈ। ਤੁਹਾਡੇ ਜਵਾਬ ਅਜੇ ਵੀ ਇਸ ਡਿਵਾਈਸ 'ਤੇ ਸੰਭਾਲੇ ਹੋਏ ਹਨ — ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Submit": "ਜਮ੍ਹਾਂ ਕਰੋ",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "ਤੁਹਾਡੇ ਸਮੇਂ ਅਤੇ ਜਵਾਬ ਲਈ ਧੰਨਵਾਦ। ਤੁਸੀਂ ਭਾਈਚਾਰੇ ਦੇ ਵਿਕਾਸ ਵਿੱਚ ਵੱਡਾ ਯੋਗਦਾਨ ਪਾਇਆ।",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "ਧੰਨਵਾਦ — ਤੁਹਾਡਾ ਜਵਾਬ ਦਰਜ ਕਰ ਲਿਆ ਗਿਆ ਹੈ। ਇਸਨੂੰ ਦੁਬਾਰਾ ਭਰਨ ਦੀ ਲੋੜ ਨਹੀਂ।",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "ਭਾਗ ਲੈਣ ਲਈ, ਤੁਹਾਡੀ ਉਮਰ ਘੱਟੋ-ਘੱਟ 18 ਸਾਲ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ ਅਤੇ ਤੁਹਾਨੂੰ ਭਾਗ ਲੈਣ ਲਈ ਸਹਿਮਤ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ। ਜੇ ਤੁਸੀਂ ਜਾਰੀ ਰੱਖਣਾ ਚਾਹੁੰਦੇ ਹੋ, ਤਾਂ ਤੁਸੀਂ ਵਾਪਸ ਜਾ ਕੇ ਆਪਣਾ ਜਵਾਬ ਬਦਲ ਸਕਦੇ ਹੋ।",
    "Try again": "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    "We couldn't save your response": "ਅਸੀਂ ਤੁਹਾਡਾ ਜਵਾਬ ਸੰਭਾਲ ਨਹੀਂ ਸਕੇ",
    "Yes, enter me in the gift-card draw": "ਹਾਂ, ਮੈਨੂੰ ਗਿਫਟ ਕਾਰਡ ਡਰਾਅ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "ਤੁਸੀਂ ਇੱਕ ਨਿੱਜੀ ਸੱਦਾ ਲਿੰਕ ਖੋਲ੍ਹਿਆ ਹੈ, ਇਸ ਲਈ ਯਾਦ-ਦਹਾਨੀ ਦੇ ਉਦੇਸ਼ਾਂ ਲਈ ਤੁਹਾਡਾ ਪੂਰਾ ਕਰਨਾ ਦਰਜ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ। ਤੁਹਾਡੇ ਜਵਾਬ ਗੁਪਤ ਰੱਖੇ ਜਾਂਦੇ ਹਨ ਅਤੇ ਪਛਾਣ-ਰਹਿਤ ਰੂਪ ਵਿੱਚ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤੇ ਜਾਂਦੇ ਹਨ।",
    "You're a Survey Champion": "ਤੁਸੀਂ ਇੱਕ ਸਰਵੇਖਣ ਚੈਂਪੀਅਨ ਹੋ",
    "You've already completed this survey": "ਤੁਸੀਂ ਪਹਿਲਾਂ ਹੀ ਇਹ ਸਰਵੇਖਣ ਪੂਰਾ ਕਰ ਚੁੱਕੇ ਹੋ",
    "Your responses are anonymous.": "ਤੁਹਾਡੇ ਜਵਾਬ ਗੁਮਨਾਮ ਹਨ।",
    "more — keep typing to narrow": "ਹੋਰ — ਸੀਮਤ ਕਰਨ ਲਈ ਟਾਈਪ ਕਰਦੇ ਰਹੋ",
    "Search or select a language": "ਭਾਸ਼ਾ ਖੋਜੋ ਜਾਂ ਚੁਣੋ",
    "Type to search countries…": "ਦੇਸ਼ ਖੋਜਣ ਲਈ ਟਾਈਪ ਕਰੋ…",
    "Type to search areas of study…": "ਪੜ੍ਹਾਈ ਦੇ ਖੇਤਰ ਖੋਜਣ ਲਈ ਟਾਈਪ ਕਰੋ…",
    "Type to search occupations…": "ਕਿੱਤੇ ਖੋਜਣ ਲਈ ਟਾਈਪ ਕਰੋ…",
    "Type to search…": "ਖੋਜਣ ਲਈ ਟਾਈਪ ਕਰੋ…",
    "Select one…": "ਇੱਕ ਚੁਣੋ…",
    "1 · Lowest": "1 · ਸਭ ਤੋਂ ਘੱਟ",
    "5 · Highest": "5 · ਸਭ ਤੋਂ ਉੱਚਾ",
    "Thank you for your interest.": "ਤੁਹਾਡੀ ਦਿਲਚਸਪੀ ਲਈ ਧੰਨਵਾਦ।",
    "Unfortunately you are not eligible to participate in the survey.": "ਬਦਕਿਸਮਤੀ ਨਾਲ, ਤੁਸੀਂ ਇਸ ਸਰਵੇਖਣ ਵਿੱਚ ਭਾਗ ਲੈਣ ਦੇ ਯੋਗ ਨਹੀਂ ਹੋ।",
  },
};
