// DRAFT Polish (pl) — pending fluent review. Keyed to exact source strings.
module.exports = {
  q: {
    language: "Wybierz język, aby kontynuować",
    consent: "Potwierdź, że masz co najmniej 18 lat i dobrowolnie zgadzasz się na udział w tej ankiecie.",
    eligible: "Czy przeprowadziłeś się do północnego Ontario po wrześniu 2021 roku, aby tu mieszkać?",
    moved_from: "Skąd się przeprowadziłeś?",
    province: "Wybierz prowincję, z której się przeprowadziłeś",
    country_moved_from: "Wybierz kraj, z którego się przeprowadziłeś",
    gender: "Jaka jest Twoja płeć?",
    age_group: "Jaka jest Twoja grupa wiekowa?",
    identity_groups: "Czy identyfikujesz się z którąkolwiek z poniższych grup? Zaznacz wszystkie, które pasują.",
    immigration_category: "Wybierz kategorię imigracyjną",
    non_permanent_category: "Wybierz kategorię rezydenta niestałego",
    non_permanent_other: "Proszę określić",
    recent_credential: "Jakie jest najnowsze uzyskane przez Ciebie wykształcenie?",
    program_name: "Jaki był Twój główny kierunek studiów?",
    program_name_other: "Wpisz swój główny kierunek studiów",
    program_location: "Gdzie ukończyłeś ten program?",
    highest_education: "Czy ten program to Twój najwyższy poziom wykształcenia?",
    highest_credential: "Jaki jest Twój najwyższy poziom wykształcenia?",
    highest_program_name: "Jaki był Twój główny kierunek studiów dla najwyższego poziomu wykształcenia?",
    highest_program_name_other: "Wpisz swój główny kierunek studiów dla najwyższego poziomu wykształcenia",
    current_program: "Jaki jest Twój obecny program studiów?",
    current_program_name: "Jaki jest Twój główny kierunek studiów?",
    current_program_name_other: "Wpisz swój główny kierunek studiów",
    employed_before: "Czy pracowałeś w Kanadzie przed przeprowadzką do Sault Ste. Marie?",
    previous_job_title: "Jaki był Twój ostatni zawód przed przeprowadzką do Sault Ste. Marie?",
    home_emp_before: "Czy pracowałeś w swoim kraju pochodzenia przed przyjazdem do Kanady?",
    home_country_job: "Jaki był Twój ostatni zawód w kraju pochodzenia?",
    employment_status: "Które z poniższych najlepiej opisuje Twoją obecną sytuację zawodową?",
    current_job_title: "Jaka jest nazwa Twojego obecnego stanowiska?",
    intended_job: "Czy Twoja obecna praca jest tą, którą zamierzałeś wykonywać?",
    intended_job_title: "Jaka jest nazwa stanowiska, które zamierzasz wykonywać?",
    job_search_help: "Które z poniższych okazały się przydatne w poszukiwaniu pracy w północnym Ontario / Sault Ste. Marie? Zaznacz wszystkie, które pasują.",
    job_search_other: "Proszę określić",
    work_barriers: "Zaznacz wszystkie pasujące przeszkody",
    work_barriers_other: "Proszę określić",
    work_support: "Jaki rodzaj wsparcia pomógłby Ci zdobyć wymarzoną pracę? Zaznacz wszystkie, które pasują.",
    work_support_other: "Proszę określić",
    unemployed_intended_job: "Jaka jest nazwa stanowiska, które zamierzasz wykonywać?",
    unemployed_barrier_gate: "Czy napotkałeś jakieś przeszkody podczas poszukiwania pracy w Sault Ste. Marie?",
    unemployment_reasons: "Zaznacz wszystkie pasujące przeszkody",
    unemployment_reasons_other: "Proszę określić",
    not_looking_reasons: "Dlaczego nie szukasz pracy?",
    not_looking_other: "Proszę określić",
    student_working: "Czy obecnie pracujesz?",
    student_current_job: "Jaka jest nazwa Twojego obecnego stanowiska?",
    student_job_relevant: "Czy Twoja obecna praca jest związana z Twoim obecnym programem studiów?",
    student_job_help: "Które z poniższych okazały się przydatne w poszukiwaniu pracy w północnym Ontario / Sault Ste. Marie? Zaznacz wszystkie, które pasują.",
    student_job_help_other: "Proszę określić",
    student_barrier_gate: "Czy napotkałeś jakieś przeszkody podczas poszukiwania pracy w Sault Ste. Marie?",
    student_barriers: "Zaznacz wszystkie pasujące przeszkody",
    student_barriers_other: "Proszę określić",
    student_support: "Jaki rodzaj wsparcia pomógłby Ci zdobyć wymarzoną pracę? Zaznacz wszystkie, które pasują.",
    student_support_other: "Proszę określić",
    planned_intended_job: "Jaka jest nazwa stanowiska, które zamierzasz wykonywać po ukończeniu studiów?",
    skills: "Jak oceniłbyś swój poziom dla każdej z poniższych umiejętności?",
    gift_card_draw: "Czy chcesz wziąć udział w losowaniu kart podarunkowych? (Wyłącznie do celów nagrody)",
    "work_barrier.a": "Czy istnieje przeszkoda uniemożliwiająca Ci pracę w pełnym wymiarze godzin?",
    "work_barrier.b": "Czy istnieje przeszkoda uniemożliwiająca Ci zdobycie wymarzonej pracy?",
    "work_barrier.c": "Czy istnieje przeszkoda uniemożliwiająca Ci pracę w pełnym wymiarze godzin i wykonywanie wymarzonej pracy?",
    "work_barrier.d": "Czy istnieje przeszkoda uniemożliwiająca Ci zdobycie pracy w pełnym wymiarze godzin?",
    "work_barrier.e": "Czy istnieje przeszkoda uniemożliwiająca Ci wykonywanie wymarzonej pracy?",
    "unemployed_support": "Jaki rodzaj wsparcia pomógłby Ci zdobyć wymarzoną pracę? Zaznacz wszystkie, które pasują.",
    "not_looking_intended_job": "Jaka jest nazwa stanowiska, które zamierzasz wykonywać?",
    "not_looking_barrier_gate": "Czy napotkałeś jakieś przeszkody podczas poszukiwania pracy w Sault Ste. Marie?",
    "not_looking_barriers": "Zaznacz wszystkie pasujące przeszkody",
    "not_looking_barriers_other": "Proszę określić",
    "not_looking_support": "Jaki rodzaj wsparcia pomógłby w Twoim przyszłym poszukiwaniu pracy? Zaznacz wszystkie pasujące odpowiedzi.",
    "not_looking_support_other": "Proszę określić",
    "not_looking_expect_look": "Czy spodziewasz się, że zaczniesz szukać pracy w ciągu najbliższych 12 miesięcy?",
  },
  help: {
    skills: "1 = najniższy, 2 = niski, 3 = umiarkowany, 4 = wysoki, 5 = najwyższy, 0 = nie jestem pewien",
  },
  o: {
    "85 or older": "85 lub więcej",
    "Advanced Diploma": "Dyplom zaawansowany",
    "Alberta": "Alberta",
    "Apprenticeship": "Praktyka zawodowa",
    "British Columbia": "Kolumbia Brytyjska",
    "Canadian degree or training": "Kanadyjski dyplom lub szkolenie",
    "Canadian work experience": "Kanadyjskie doświadczenie zawodowe",
    "Caregiving responsibilities": "Obowiązki opiekuńcze",
    "Childcare support": "Wsparcie w opiece nad dziećmi",
    "College certificate": "Certyfikat college'u",
    "Credential recognition support": "Wsparcie w uznawaniu kwalifikacji",
    "Credentials not recognized": "Kwalifikacje nieuznane",
    "Diploma": "Dyplom",
    "Discrimination of any kind": "Dyskryminacja jakiegokolwiek rodzaju",
    "Doesn’t need employment income": "Nie potrzebuje dochodu z pracy",
    "Economic Immigrant": "Imigrant ekonomiczny",
    "Employed casual (less than 10 hours/week)": "Praca dorywcza (mniej niż 10 godzin/tydzień)",
    "Employed full time (30+ hours/week)": "Praca w pełnym wymiarze (30+ godzin/tydzień)",
    "Employed part time (10-30 hours/week)": "Praca w niepełnym wymiarze (10-30 godzin/tydzień)",
    "Employment or settlement centre": "Centrum zatrudnienia lub osiedlenia",
    "Family Sponsored": "Sponsorowany przez rodzinę",
    "Health issues": "Problemy zdrowotne",
    "Health reasons": "Powody zdrowotne",
    "High school diploma or equivalent": "Świadectwo ukończenia szkoły średniej lub równoważne",
    "Household responsibilities": "Obowiązki domowe",
    "Household work / Caregiver": "Praca w gospodarstwie domowym / Opiekun",
    "I agree": "Zgadzam się",
    "I didn't have a work permit": "Nie miałem pozwolenia na pracę",
    "I directly moved to Sault": "Przeprowadziłem się bezpośrednio do Sault",
    "I disagree": "Nie zgadzam się",
    "Immigrant (permanent resident)": "Imigrant (stały rezydent)",
    "Immigration issues": "Problemy imigracyjne",
    "In Canada": "W Kanadzie",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Rdzenny mieszkaniec (Pierwsze Narody, Métis, Inuit/Inuk)",
    "International Student": "Student zagraniczny",
    "Internship / volunteer experience": "Staż / doświadczenie wolontariackie",
    "Lack of Canadian work experience": "Brak kanadyjskiego doświadczenia zawodowego",
    "Lack of skills for available jobs": "Brak umiejętności do dostępnych stanowisk",
    "Language barriers": "Bariery językowe",
    "Language support": "Wsparcie językowe",
    "Limited job opportunities in preferred sector": "Ograniczone możliwości zatrudnienia w preferowanym sektorze",
    "Limited knowledge of local job market": "Ograniczona znajomość lokalnego rynku pracy",
    "Limited mentorship and job-matching support": "Ograniczone wsparcie mentorskie i w dopasowywaniu pracy",
    "Limited professional network": "Ograniczona sieć zawodowa",
    "Limited suitable jobs": "Ograniczona liczba odpowiednich stanowisk",
    "Local job boards": "Lokalne tablice ogłoszeń o pracy",
    "Local job market information": "Informacje o lokalnym rynku pracy",
    "Local training or certification": "Lokalne szkolenia lub certyfikacja",
    "Low wages": "Niskie płace",
    "Man": "Mężczyzna",
    "Manitoba": "Manitoba",
    "Mentorship support": "Wsparcie mentorskie",
    "Networking support": "Wsparcie w budowaniu kontaktów",
    "New Brunswick": "Nowy Brunszwik",
    "Newfoundland and Labrador": "Nowa Fundlandia i Labrador",
    "No": "Nie",
    "Non-Canadian work experience not recognized": "Niekanadyjskie doświadczenie zawodowe nieuznane",
    "Non-binary person or other gender": "Osoba niebinarna lub inna płeć",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Rezydent niestały (np. pozwolenie na pracę, pozwolenie na studia, osoba ubiegająca się o azyl)",
    "None of the above (do not select any other options)": "Żadne z powyższych (nie wybieraj innych opcji)",
    "Northwest Territories": "Terytoria Północno-Zachodnie",
    "Not qualified for available jobs": "Brak kwalifikacji do dostępnych stanowisk",
    "Nova Scotia": "Nowa Szkocja",
    "Nunavut": "Nunavut",
    "On temporary leave from a job (e.g., maternity/parental leave)": "Na tymczasowym urlopie od pracy (np. urlop macierzyński lub rodzicielski)",
    "Other": "Inne",
    "Other parts of Ontario": "Inne części Ontario",
    "Outside Canada": "Poza Kanadą",
    "Outside of Canada": "Poza Kanadą",
    "Outside of Ontario but within Canada": "Poza Ontario, ale w Kanadzie",
    "Personal contacts": "Kontakty osobiste",
    "Post-graduate degree (e.g., Master's)": "Studia podyplomowe (np. magisterskie)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Studia podyplomowe (np. magisterskie, doktorat, M.D.)",
    "Primary school": "Szkoła podstawowa",
    "Prince Edward Island": "Wyspa Księcia Edwarda",
    "Professional network": "Sieć zawodowa",
    "Protected Person": "Osoba objęta ochroną",
    "Quebec": "Quebec",
    "Recognition of non-Canadian work experience": "Uznanie niekanadyjskiego doświadczenia zawodowego",
    "Refugee": "Uchodźca",
    "Refugee Claimant": "Osoba ubiegająca się o azyl",
    "Resume/interview support": "Wsparcie w zakresie CV i rozmów kwalifikacyjnych",
    "Retired": "Emeryt",
    "Saskatchewan": "Saskatchewan",
    "Self-employed": "Samozatrudniony",
    "Skills-to-job matching platform": "Platforma dopasowująca umiejętności do pracy",
    "Social media (e.g., LinkedIn)": "Media społecznościowe (np. LinkedIn)",
    "Student or recent graduate": "Student lub niedawny absolwent",
    "Temporary Foreign Worker": "Tymczasowy pracownik zagraniczny",
    "Temporary Resident Permit Holder": "Posiadacz tymczasowego zezwolenia na pobyt",
    "Training recommendations": "Rekomendacje szkoleniowe",
    "Unable to work": "Niezdolny do pracy",
    "Undergraduate degree": "Studia licencjackie",
    "Unemployed and actively looking for work": "Bezrobotny i aktywnie poszukujący pracy",
    "Unemployed and not looking for work": "Bezrobotny i nieposzukujący pracy",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Mniejszość widoczna (np. Azjaci Południowi, Chińczycy, osoby czarnoskóre)",
    "Woman": "Kobieta",
    "Yes": "Tak",
    "Yukon": "Jukon",
    "Didn't look for job": "Nie szukałem pracy",
  },
  def: {
    "Family Sponsored": "Wyemigrowałeś, ponieważ członek rodziny przebywający już w Kanadzie Cię sponsorował.",
    "Economic Immigrant": "Wyemigrowałeś w ramach programu dla wykwalifikowanych pracowników lub przedsiębiorców (np. Express Entry, Program Nominacji Prowincjonalnych).",
    "Refugee": "Przyjechałeś do Kanady, aby chronić się przed niebezpieczeństwem w kraju pochodzenia.",
    "Temporary Foreign Worker": "W Kanadzie z pozwoleniem na pracę powiązanym z pracodawcą lub otwartym pozwoleniem na pracę.",
    "Refugee Claimant": "Złożyłeś w Kanadzie wniosek o ochronę jako uchodźca i czekasz na decyzję.",
    "Protected Person": "Kanada już uznała, że potrzebujesz ochrony (zatwierdzony status uchodźcy/osoby chronionej).",
    "Temporary Resident Permit Holder": "Posiadasz specjalne zezwolenie na tymczasowy pobyt, gdy normalnie nie byłoby to dozwolone.",
    "Canadian degree or training": "Ukończyłeś studia lub program szkoleniowy w Kanadzie.",
    "Canadian work experience": "Pracowałeś dla pracodawcy w Kanadzie.",
    "Employment or settlement centre": "Otrzymałeś pomoc od organizacji wspierającej osoby poszukujące pracy lub nowo przybyłych (np. Sault Community Career Center).",
    "Internship / volunteer experience": "Zdobyłeś doświadczenie zawodowe poprzez bezpłatny staż, krótkoterminową praktykę lub wolontariat.",
    "Local job boards": "Korzystałeś ze stron internetowych lub ogłoszeń o pracy w Twojej okolicy (np. tablica ogłoszeń AWIC).",
    "Personal contacts": "Otrzymałeś pomoc lub informacje o pracy od rodziny, przyjaciół lub osób, które znasz osobiście.",
    "Professional network": "Korzystałeś z kontaktów ze swojej branży, takich jak współpracownicy czy mentorzy.",
    "Recognition of non-Canadian work experience": "Twoje doświadczenie zawodowe zdobyte poza Kanadą zostało uznane.",
    "Caregiving responsibilities": "Musisz opiekować się dziećmi lub starszymi członkami rodziny, którzy są od Ciebie zależni.",
    "Credentials not recognized": "Twoje wykształcenie, dyplom lub licencja zdobyte poza Kanadą nie są akceptowane przez kanadyjskich pracodawców.",
    "Discrimination of any kind": "Zostałeś potraktowany niesprawiedliwie ze względu na rasę, pochodzenie etniczne, religię, płeć, akcent, wiek lub inne cechy osobiste.",
    "Health issues": "Masz problemy ze zdrowiem fizycznym lub psychicznym, które utrudniają znalezienie lub utrzymanie pracy.",
    "Household responsibilities": "Musisz zajmować się obowiązkami domowymi (gotowanie, sprzątanie, prowadzenie domu).",
    "Lack of Canadian work experience": "Pracodawcy wymagają doświadczenia zawodowego w Kanadzie, którego jeszcze nie masz.",
    "Lack of skills for available jobs": "Dostępne w Twojej okolicy stanowiska wymagają umiejętności lub szkolenia, których obecnie nie masz.",
    "Language barriers": "Twoja znajomość angielskiego (lub francuskiego) utrudnia znalezienie pracy lub przejście rozmów kwalifikacyjnych.",
    "Limited job opportunities in preferred sector": "W Twojej okolicy jest niewiele ofert pracy w Twojej dziedzinie lub branży.",
    "Limited knowledge of local job market": "Nie wiesz dokładnie, jak szukać pracy, którzy pracodawcy zatrudniają ani jak wygląda rekrutacja w Twojej okolicy.",
    "Limited mentorship and job-matching support": "Nie masz dostępu do mentorów ani usług, które łączyłyby Cię z odpowiednimi ofertami pracy.",
    "Limited professional network": "Znasz niewiele osób w swojej dziedzinie, które mogłyby przekazać Ci oferty, referencje lub rady.",
    "Non-Canadian work experience not recognized": "Twoje doświadczenie zawodowe zdobyte poza Kanadą nie jest akceptowane ani doceniane przez kanadyjskich pracodawców.",
    "Childcare support": "Potrzebujesz pomocy w opiece nad dziećmi, abyś mógł pracować.",
    "Credential recognition support": "Potrzebujesz pomocy w uznaniu Twojego wykształcenia lub kwalifikacji zawodowych zdobytych poza Kanadą.",
    "Language support": "Potrzebujesz pomocy w poprawie znajomości angielskiego (lub francuskiego).",
    "Local job market information": "Potrzebujesz informacji o tym, którzy pracodawcy zatrudniają, jakie oferty są dostępne i jakie umiejętności są poszukiwane w Twojej okolicy.",
    "Local training or certification": "Potrzebujesz szkolenia lub certyfikacji oferowanej w Twojej okolicy, aby kwalifikować się na dostępne stanowiska.",
    "Mentorship support": "Potrzebujesz kontaktu z doświadczonymi osobami ze swojej dziedziny.",
    "Networking support": "Potrzebujesz pomocy w poznawaniu pracodawców i specjalistów.",
    "Resume/interview support": "Potrzebujesz pomocy w przygotowaniu CV, listu motywacyjnego lub w ćwiczeniu rozmów kwalifikacyjnych.",
    "Skills-to-job matching platform": "Potrzebujesz usługi lub narzędzia, które dopasuje Twoje umiejętności do odpowiednich ofert pracy.",
    "Training recommendations": "Potrzebujesz sugestii, jakie szkolenia lub kursy podjąć, aby zwiększyć swoje szanse na znalezienie pracy.",
    "Doesn’t need employment income": "Nie musisz pracować, ponieważ masz inne źródła dochodu lub wsparcie finansowe.",
    "Health reasons": "Masz problemy ze zdrowiem fizycznym lub psychicznym, które utrudniają znalezienie lub utrzymanie pracy.",
    "Immigration issues": "Twój status imigracyjny lub dokumenty (np. pozwolenie na pracę, rozpatrywanie wniosku o pobyt stały) uniemożliwiają Ci pracę.",
    "Limited suitable jobs": "W Twojej okolicy jest niewiele ofert pracy odpowiadających Twoim umiejętnościom, doświadczeniu lub preferencjom.",
    "Low wages": "Dostępne oferty pracy oferują zbyt niskie wynagrodzenie, aby praca była dla Ciebie opłacalna.",
    "Not qualified for available jobs": "Dostępne w Twojej okolicy stanowiska wymagają wykształcenia, umiejętności lub certyfikatów, których obecnie nie masz.",
  },
  ui: {
    "% complete": " % ukończono",
    "Back to home": "Powrót do strony głównej",
    "Back": "Wstecz",
    "Definition:": "Definicja:",
    "Email address": "Adres e-mail",
    "Finish to become a Survey Champion": "Ukończ, aby zostać Mistrzem Ankiety",
    "Five $50 local gift cards drawn monthly": "Pięć lokalnych kart podarunkowych o wartości 50 $ losowanych co miesiąc",
    "Go back": "Wstecz",
    "Home": "Strona główna",
    "Next 5 skills": "Następne 5 umiejętności",
    "Next question": "Następne pytanie",
    "No matches": "Brak wyników",
    "Not sure": "Nie jestem pewien",
    "One moment.": "Chwileczkę.",
    "Previous question": "Poprzednie pytanie",
    "Saving your response…": "Zapisywanie Twojej odpowiedzi…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "Wystąpił problem z połączeniem z serwerem. Twoje odpowiedzi są nadal zapisane na tym urządzeniu — spróbuj ponownie.",
    "Submit": "Wyślij",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Dziękujemy za poświęcony czas i odpowiedź. Wniosłeś ogromny wkład w rozwój społeczności.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Dziękujemy — Twoja odpowiedź została zapisana. Nie musisz wypełniać jej ponownie.",
    "Try again": "Spróbuj ponownie",
    "We couldn't save your response": "Nie udało się zapisać Twojej odpowiedzi",
    "Yes, enter me in the gift-card draw": "Tak, zapisz mnie do losowania kart podarunkowych",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Otworzyłeś osobisty link z zaproszeniem, więc Twoje ukończenie może zostać zarejestrowane w celach przypomnienia. Twoje odpowiedzi są traktowane poufnie i analizowane w formie zanonimizowanej.",
    "You're a Survey Champion": "Jesteś Mistrzem Ankiety",
    "You've already completed this survey": "Już ukończyłeś tę ankietę",
    "Your responses are anonymous.": "Twoje odpowiedzi są anonimowe.",
    "more — keep typing to narrow": "więcej — kontynuuj pisanie, aby zawęzić",
    "Search or select a language": "Wyszukaj lub wybierz język",
    "Type to search countries…": "Wpisz, aby wyszukać kraj…",
    "Type to search areas of study…": "Wpisz, aby wyszukać kierunek studiów…",
    "Type to search occupations…": "Wpisz, aby wyszukać zawód…",
    "Type to search…": "Wpisz, aby wyszukać…",
    "Select one…": "Wybierz jedną opcję…",
    "1 · Lowest": "1 · najniższy",
    "5 · Highest": "5 · najwyższy",
    "Thank you for your interest.": "Dziękujemy za zainteresowanie.",
    "Unfortunately you are not eligible to participate in the survey.": "Niestety nie kwalifikujesz się do udziału w ankiecie.",
    "Thank you for starting the survey.": "Dziękujemy za rozpoczęcie ankiety.",
    "Unfortunately we cannot proceed without your consent.": "Niestety nie możemy kontynuować bez Twojej zgody.",
    "Note: This information will be used only for the prize draw and will not be linked to your survey responses.": "Uwaga: te informacje zostaną wykorzystane wyłącznie do losowania nagród i nie będą powiązane z Twoimi odpowiedziami w ankiecie.",
    "Listen": "Posłuchaj",
  },
};
