// DRAFT Portuguese (pt) — pending fluent review. Keyed to exact source strings.
module.exports = {
  q: {
    language: "Selecione um idioma para continuar",
    consent: "Confirme que tem pelo menos 18 anos e que concorda em participar voluntariamente nesta pesquisa.",
    eligible: "Você se mudou para o norte de Ontário depois de setembro de 2021 para morar?",
    moved_from: "De onde você se mudou?",
    province: "Selecione a província de onde você se mudou",
    country_moved_from: "Selecione o país de onde você se mudou",
    gender: "Qual é o seu gênero?",
    age_group: "Qual é a sua faixa etária?",
    identity_groups: "Você se identifica com algum dos seguintes grupos? Selecione todas as opções aplicáveis.",
    immigration_category: "Selecione a categoria de imigração",
    non_permanent_category: "Selecione a categoria de residente não permanente",
    non_permanent_other: "Especifique",
    recent_credential: "Qual é a credencial educacional mais recente que você concluiu?",
    program_name: "Qual foi a sua principal área de estudo?",
    program_name_other: "Digite a sua principal área de estudo",
    program_location: "Onde você concluiu este programa?",
    highest_education: "Este programa corresponde ao seu nível mais alto de escolaridade?",
    highest_credential: "Qual é o seu nível mais alto de escolaridade?",
    highest_program_name: "Para o seu nível mais alto de escolaridade, qual foi a sua principal área de estudo?",
    highest_program_name_other: "Digite a sua principal área de estudo para o seu nível mais alto de escolaridade",
    current_program: "Qual é o seu programa de estudos atual?",
    current_program_name: "Qual é a sua principal área de estudo?",
    current_program_name_other: "Digite a sua principal área de estudo",
    employed_before: "Você estava empregado no Canadá antes de se mudar para Sault Ste. Marie?",
    previous_job_title: "Qual era a sua última ocupação antes de se mudar para Sault Ste. Marie?",
    home_emp_before: "Você estava empregado no seu país de origem antes de vir para o Canadá?",
    home_country_job: "Qual era a sua última ocupação no seu país de origem?",
    employment_status: "Qual das opções a seguir descreve melhor a sua situação de emprego atual?",
    current_job_title: "Qual é o título do seu emprego atual?",
    intended_job: "O seu emprego atual é aquele que você pretendia ter?",
    intended_job_title: "Qual é o título do emprego que você pretende ter?",
    job_search_help: "Quais dos seguintes foram úteis na sua busca de emprego no norte de Ontário / Sault Ste. Marie? Selecione todas as opções aplicáveis.",
    job_search_other: "Especifique",
    work_barriers: "Selecione todas as barreiras aplicáveis",
    work_barriers_other: "Especifique",
    work_support: "Que tipo de apoio ajudaria você a conseguir o emprego que deseja? Selecione todas as opções aplicáveis.",
    work_support_other: "Especifique",
    unemployed_intended_job: "Qual é o título do emprego que você pretende ter?",
    unemployed_barrier_gate: "Você enfrentou alguma barreira ao procurar trabalho em Sault Ste. Marie?",
    unemployment_reasons: "Selecione todas as barreiras aplicáveis",
    unemployment_reasons_other: "Especifique",
    not_looking_reasons: "Por que você não está procurando trabalho?",
    not_looking_other: "Especifique",
    student_working: "Você está trabalhando atualmente?",
    student_current_job: "Qual é o título do seu emprego atual?",
    student_job_relevant: "O seu emprego atual está relacionado ao seu programa de estudos atual?",
    student_job_help: "Quais dos seguintes foram úteis na sua busca de emprego no norte de Ontário / Sault Ste. Marie? Selecione todas as opções aplicáveis.",
    student_job_help_other: "Especifique",
    student_barrier_gate: "Você enfrentou alguma barreira ao procurar emprego em Sault Ste. Marie?",
    student_barriers: "Selecione todas as barreiras aplicáveis",
    student_barriers_other: "Especifique",
    student_support: "Que tipo de apoio ajudaria você a conseguir o emprego que deseja? Selecione todas as opções aplicáveis.",
    student_support_other: "Especifique",
    planned_intended_job: "Qual é o título do emprego que você pretende ter após a formatura?",
    skills: "Como você avaliaria o seu nível em cada uma das seguintes competências?",
    gift_card_draw: "Você deseja participar do sorteio de cartões-presente? (Apenas para fins de premiação)",
    "work_barrier.a": "Existe alguma barreira que impede você de trabalhar em tempo integral?",
    "work_barrier.b": "Existe alguma barreira que impede você de conseguir o emprego que deseja?",
    "work_barrier.c": "Existe alguma barreira que impede você de trabalhar em tempo integral e de exercer o emprego que deseja?",
    "work_barrier.d": "Existe alguma barreira que impede você de conseguir um emprego em tempo integral?",
    "work_barrier.e": "Existe alguma barreira que impede você de exercer o emprego que deseja?",
  },
  help: {
    skills: "1 = mais baixo, 2 = baixo, 3 = moderado, 4 = alto, 5 = mais alto, 0 = não tenho certeza",
  },
  o: {
    "85 or older": "85 ou mais",
    "Advanced Diploma": "Diploma avançado",
    "Alberta": "Alberta",
    "Apprenticeship": "Aprendizagem",
    "British Columbia": "Colúmbia Britânica",
    "Canadian degree or training": "Diploma ou formação canadense",
    "Canadian work experience": "Experiência de trabalho canadense",
    "Caregiving responsibilities": "Responsabilidades de cuidado",
    "Childcare support": "Apoio para o cuidado de crianças",
    "College certificate": "Certificado de college",
    "Credential recognition support": "Apoio para o reconhecimento de credenciais",
    "Credentials not recognized": "Credenciais não reconhecidas",
    "Diploma": "Diploma",
    "Discrimination of any kind": "Discriminação de qualquer tipo",
    "Doesn’t need employment income": "Não precisa de renda de trabalho",
    "Economic Immigrant": "Imigrante econômico",
    "Employed casual (less than 10 hours/week)": "Emprego ocasional (menos de 10 horas/semana)",
    "Employed full time (30+ hours/week)": "Emprego em tempo integral (30 horas ou mais/semana)",
    "Employed part time (10-30 hours/week)": "Emprego em meio período (10 a 30 horas/semana)",
    "Employment or settlement centre": "Centro de emprego ou de assentamento",
    "Family Sponsored": "Patrocinado pela família",
    "Health issues": "Problemas de saúde",
    "Health reasons": "Motivos de saúde",
    "High school diploma or equivalent": "Diploma de ensino médio ou equivalente",
    "Household responsibilities": "Responsabilidades domésticas",
    "Household work / Caregiver": "Trabalho doméstico / Cuidador",
    "I agree": "Concordo",
    "I didn't have a work permit": "Eu não tinha permissão de trabalho",
    "I directly moved to Sault": "Mudei-me diretamente para Sault",
    "I disagree": "Não concordo",
    "Immigrant (permanent resident)": "Imigrante (residente permanente)",
    "Immigration issues": "Problemas de imigração",
    "In Canada": "No Canadá",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Indígena (Primeiras Nações, Métis, Inuit/Inuk)",
    "International Student": "Estudante internacional",
    "Internship / volunteer experience": "Estágio / experiência de voluntariado",
    "Lack of Canadian work experience": "Falta de experiência de trabalho canadense",
    "Lack of skills for available jobs": "Falta de competências para os empregos disponíveis",
    "Language barriers": "Barreiras linguísticas",
    "Language support": "Apoio linguístico",
    "Limited job opportunities in preferred sector": "Oportunidades de emprego limitadas no setor preferido",
    "Limited knowledge of local job market": "Conhecimento limitado do mercado de trabalho local",
    "Limited mentorship and job-matching support": "Apoio limitado de mentoria e de conexão com empregos",
    "Limited professional network": "Rede profissional limitada",
    "Limited suitable jobs": "Empregos adequados limitados",
    "Local job boards": "Portais de emprego locais",
    "Local job market information": "Informações sobre o mercado de trabalho local",
    "Local training or certification": "Formação ou certificação local",
    "Low wages": "Salários baixos",
    "Man": "Homem",
    "Manitoba": "Manitoba",
    "Mentorship support": "Apoio de mentoria",
    "Networking support": "Apoio para networking",
    "New Brunswick": "Nova Brunswick",
    "Newfoundland and Labrador": "Terra Nova e Labrador",
    "No": "Não",
    "Non-Canadian work experience not recognized": "Experiência de trabalho não canadense não reconhecida",
    "Non-binary person or other gender": "Pessoa não binária ou outro gênero",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Residente não permanente (p. ex., permissão de trabalho, permissão de estudo, requerente de refúgio)",
    "None of the above (do not select any other options)": "Nenhuma das anteriores (não selecione nenhuma outra opção)",
    "Northwest Territories": "Territórios do Noroeste",
    "Not qualified for available jobs": "Não qualificado para os empregos disponíveis",
    "Nova Scotia": "Nova Escócia",
    "Nunavut": "Nunavut",
    "On temporary leave from a job (e.g., maternity/parental leave)": "Em licença temporária de um emprego (p. ex., licença-maternidade ou parental)",
    "Other": "Outro",
    "Other parts of Ontario": "Outras partes de Ontário",
    "Outside Canada": "Fora do Canadá",
    "Outside of Canada": "Fora do Canadá",
    "Outside of Ontario but within Canada": "Fora de Ontário, mas dentro do Canadá",
    "Personal contacts": "Contatos pessoais",
    "Post-graduate degree (e.g., Master's)": "Pós-graduação (p. ex., mestrado)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Pós-graduação (p. ex., mestrado, doutorado, M.D.)",
    "Primary school": "Escola primária",
    "Prince Edward Island": "Ilha do Príncipe Eduardo",
    "Professional network": "Rede profissional",
    "Protected Person": "Pessoa protegida",
    "Quebec": "Quebec",
    "Recognition of non-Canadian work experience": "Reconhecimento da experiência de trabalho não canadense",
    "Refugee": "Refugiado",
    "Refugee Claimant": "Requerente de refúgio",
    "Resume/interview support": "Apoio com currículo e entrevistas",
    "Retired": "Aposentado",
    "Saskatchewan": "Saskatchewan",
    "Self-employed": "Autônomo",
    "Skills-to-job matching platform": "Plataforma de conexão entre competências e empregos",
    "Social media (e.g., LinkedIn)": "Redes sociais (p. ex., LinkedIn)",
    "Student or recent graduate": "Estudante ou recém-formado",
    "Temporary Foreign Worker": "Trabalhador estrangeiro temporário",
    "Temporary Resident Permit Holder": "Titular de permissão de residência temporária",
    "Training recommendations": "Recomendações de formação",
    "Unable to work": "Incapaz de trabalhar",
    "Undergraduate degree": "Diploma de graduação",
    "Unemployed and actively looking for work": "Desempregado e procurando trabalho ativamente",
    "Unemployed and not looking for work": "Desempregado e sem procurar trabalho",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Minoria visível (p. ex., sul-asiático, chinês, negro)",
    "Woman": "Mulher",
    "Yes": "Sim",
    "Yukon": "Yukon",
  },
  def: {
    "Family Sponsored": "Você imigrou porque um familiar que já estava no Canadá o patrocinou.",
    "Economic Immigrant": "Você imigrou por meio de um programa de trabalhadores qualificados ou de negócios (p. ex., Entrada Expressa, Programa de Candidatos Provinciais).",
    "Refugee": "Você veio ao Canadá para se proteger de um perigo no seu país de origem.",
    "Temporary Foreign Worker": "No Canadá com uma permissão de trabalho vinculada a um empregador ou uma permissão de trabalho aberta.",
    "Refugee Claimant": "Você pediu proteção como refugiado ao Canadá e está aguardando uma decisão.",
    "Protected Person": "O Canadá já aceitou que você precisa de proteção (status de refugiado/pessoa protegida aprovado).",
    "Temporary Resident Permit Holder": "Você tem uma permissão especial para permanecer temporariamente quando normalmente não seria permitido.",
    "Canadian degree or training": "Você concluiu um diploma ou programa de formação no Canadá.",
    "Canadian work experience": "Você trabalhou para um empregador no Canadá.",
    "Employment or settlement centre": "Você recebeu ajuda de uma organização que apoia quem procura emprego ou os recém-chegados (p. ex., Sault Community Career Center).",
    "Internship / volunteer experience": "Você adquiriu experiência de trabalho por meio de um estágio não remunerado, uma colocação de curta duração ou voluntariado.",
    "Local job boards": "Você usou sites ou anúncios que divulgam empregos na sua região (p. ex., o quadro de vagas da AWIC).",
    "Personal contacts": "Você recebeu ajuda ou indicações de emprego de familiares, amigos ou pessoas que conhece pessoalmente.",
    "Professional network": "Você usou contatos da sua área profissional, como colegas ou mentores.",
    "Recognition of non-Canadian work experience": "Sua experiência de trabalho obtida fora do Canadá foi aceita.",
    "Caregiving responsibilities": "Você precisa cuidar de crianças ou familiares idosos que dependem de você.",
    "Credentials not recognized": "Sua formação, diploma ou licença obtida fora do Canadá não é aceita pelos empregadores canadenses.",
    "Discrimination of any kind": "Você foi tratado injustamente por causa da sua raça, etnia, religião, gênero, sotaque, idade ou outras características pessoais.",
    "Health issues": "Você tem problemas de saúde física ou mental que dificultam encontrar ou manter um emprego.",
    "Household responsibilities": "Você precisa cuidar das tarefas domésticas (cozinhar, limpar, administrar a casa).",
    "Lack of Canadian work experience": "Os empregadores pedem experiência de trabalho no Canadá, que você ainda não tem.",
    "Lack of skills for available jobs": "Os empregos disponíveis na sua região exigem competências ou formação que você não tem atualmente.",
    "Language barriers": "Seus conhecimentos de inglês (ou francês) dificultam encontrar trabalho ou passar em entrevistas.",
    "Limited job opportunities in preferred sector": "Há poucos empregos na sua área ou setor na sua região.",
    "Limited knowledge of local job market": "Você não sabe bem como encontrar empregos, quais empregadores estão contratando ou como funciona a contratação na sua região.",
    "Limited mentorship and job-matching support": "Você não tem acesso a mentores ou serviços que o conectem a empregos adequados.",
    "Limited professional network": "Você conhece poucas pessoas na sua área que possam compartilhar oportunidades, indicações ou conselhos.",
    "Non-Canadian work experience not recognized": "Sua experiência de trabalho obtida fora do Canadá não é aceita nem valorizada pelos empregadores canadenses.",
    "Childcare support": "Você precisa de ajuda com o cuidado dos seus filhos para poder trabalhar.",
    "Credential recognition support": "Você precisa de ajuda para que sua formação ou qualificações profissionais obtidas fora do Canadá sejam aceitas.",
    "Language support": "Você precisa de ajuda para melhorar seus conhecimentos de inglês (ou francês).",
    "Local job market information": "Você precisa de informações sobre quais empregadores estão contratando, quais vagas existem e quais competências são procuradas na sua região.",
    "Local training or certification": "Você precisa de formação ou certificação oferecida na sua região para se qualificar para as vagas disponíveis.",
    "Mentorship support": "Você precisa de contato com pessoas experientes da sua área.",
    "Networking support": "Você precisa de ajuda para conhecer empregadores e profissionais.",
    "Resume/interview support": "Você precisa de ajuda para preparar seu currículo, sua carta de apresentação ou para praticar entrevistas de emprego.",
    "Skills-to-job matching platform": "Você precisa de um serviço ou ferramenta que relacione suas competências a vagas adequadas.",
    "Training recommendations": "Você precisa de sugestões sobre qual formação ou curso fazer para melhorar suas chances de conseguir um emprego.",
    "Doesn’t need employment income": "Você não precisa trabalhar porque tem outras fontes de renda ou apoio financeiro.",
    "Health reasons": "Você tem problemas de saúde física ou mental que dificultam encontrar ou manter um emprego.",
    "Immigration issues": "Seu status de imigração ou seus documentos (p. ex., permissão de trabalho, processamento da residência permanente) impedem você de trabalhar.",
    "Limited suitable jobs": "Há poucos empregos na sua região que correspondam às suas competências, experiência ou preferências.",
    "Low wages": "Os empregos disponíveis pagam pouco demais para que trabalhar valha a pena para você.",
    "Not qualified for available jobs": "Os empregos disponíveis na sua região exigem formação, competências ou certificações que você não tem atualmente.",
  },
  ui: {
    "% complete": " % concluído",
    "Back to home": "Voltar ao início",
    "Back": "Voltar",
    "Definition:": "Definição:",
    "Email address": "Endereço de e-mail",
    "Finish to become a Survey Champion": "Termine para se tornar um Campeão da Pesquisa",
    "Five $50 local gift cards drawn monthly": "Cinco cartões-presente locais de $50 sorteados mensalmente",
    "Go back": "Voltar",
    "Home": "Início",
    "Next 5 skills": "Próximas 5 competências",
    "Next question": "Próxima pergunta",
    "No matches": "Nenhum resultado",
    "Not sure": "Não tenho certeza",
    "One moment.": "Um momento.",
    "Previous question": "Pergunta anterior",
    "Saving your response…": "Salvando a sua resposta…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "Ocorreu um problema ao conectar com o servidor. As suas respostas continuam salvas neste dispositivo — tente novamente.",
    "Submit": "Enviar",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Obrigado pelo seu tempo e pela sua resposta. Você fez uma grande contribuição para o desenvolvimento da comunidade.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Obrigado — a sua resposta foi registrada. Não é necessário preenchê-la novamente.",
    "Try again": "Tentar novamente",
    "We couldn't save your response": "Não conseguimos salvar a sua resposta",
    "Yes, enter me in the gift-card draw": "Sim, inscreva-me no sorteio de cartões-presente",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Você abriu um link de convite pessoal, portanto a sua participação pode ser registrada para fins de lembrete. As suas respostas são mantidas confidenciais e analisadas de forma anonimizada.",
    "You're a Survey Champion": "Você é um Campeão da Pesquisa",
    "You've already completed this survey": "Você já concluiu esta pesquisa",
    "Your responses are anonymous.": "As suas respostas são anônimas.",
    "more — keep typing to narrow": "mais — continue digitando para refinar",
    "Search or select a language": "Pesquise ou selecione um idioma",
    "Type to search countries…": "Digite para pesquisar um país…",
    "Type to search areas of study…": "Digite para pesquisar uma área de estudo…",
    "Type to search occupations…": "Digite para pesquisar uma ocupação…",
    "Type to search…": "Digite para pesquisar…",
    "Select one…": "Selecione uma opção…",
    "1 · Lowest": "1 · mais baixo",
    "5 · Highest": "5 · mais alto",
    "Thank you for your interest.": "Obrigado pelo seu interesse.",
    "Unfortunately you are not eligible to participate in the survey.": "Infelizmente, você não é elegível para participar da pesquisa.",
    "Thank you for starting the survey.": "Obrigado por iniciar a pesquisa.",
    "Unfortunately we cannot proceed without your consent.": "Infelizmente, não podemos continuar sem o seu consentimento.",
  },
};
