// DRAFT Tamil (ta) — ⚠ MACHINE-QUALITY DRAFT. Requires native-speaker review
// before release. Keyed to exact source strings.
module.exports = {
  q: {
    language: "தொடர ஒரு மொழியைத் தேர்ந்தெடுக்கவும்",
    consent: "நீங்கள் குறைந்தது 18 வயதுடையவர் என்பதையும், இந்த ஆய்வில் தன்னார்வமாகப் பங்கேற்க ஒப்புக்கொள்கிறீர்கள் என்பதையும் உறுதிப்படுத்தவும்.",
    eligible: "நீங்கள் செப்டம்பர் 2021 க்குப் பிறகு வாழ்வதற்காக வட ஒன்டாரியோவுக்கு குடிபெயர்ந்தீர்களா?",
    moved_from: "நீங்கள் எங்கிருந்து குடிபெயர்ந்தீர்கள்?",
    province: "நீங்கள் குடிபெயர்ந்த மாகாணத்தைத் தேர்ந்தெடுக்கவும்",
    country_moved_from: "நீங்கள் குடிபெயர்ந்த நாட்டைத் தேர்ந்தெடுக்கவும்",
    gender: "உங்கள் பாலினம் என்ன?",
    age_group: "உங்கள் வயதுக் குழு என்ன?",
    identity_groups: "பின்வரும் குழுக்களில் ஏதேனும் ஒன்றுடன் உங்களை அடையாளப்படுத்திக் கொள்கிறீர்களா? பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்.",
    immigration_category: "குடியேற்றப் பிரிவைத் தேர்ந்தெடுக்கவும்",
    non_permanent_category: "நிரந்தரமற்ற குடியிருப்பாளர் பிரிவைத் தேர்ந்தெடுக்கவும்",
    non_permanent_other: "தயவுசெய்து குறிப்பிடவும்",
    recent_credential: "நீங்கள் மிக சமீபத்தில் முடித்த கல்வித் தகுதி என்ன?",
    program_name: "உங்கள் முக்கிய படிப்புத் துறை என்ன?",
    program_name_other: "உங்கள் முக்கிய படிப்புத் துறையை உள்ளிடவும்",
    program_location: "இந்தத் திட்டத்தை எங்கே முடித்தீர்கள்?",
    highest_education: "இந்தத் திட்டம் உங்கள் மிக உயர்ந்த கல்வி நிலையா?",
    highest_credential: "உங்கள் மிக உயர்ந்த கல்வி நிலை என்ன?",
    highest_program_name: "உங்கள் மிக உயர்ந்த கல்வி நிலைக்கு, உங்கள் முக்கிய படிப்புத் துறை என்ன?",
    highest_program_name_other: "உங்கள் மிக உயர்ந்த கல்வி நிலைக்கான முக்கிய படிப்புத் துறையை உள்ளிடவும்",
    current_program: "உங்கள் தற்போதைய படிப்புத் திட்டம் என்ன?",
    current_program_name: "உங்கள் முக்கிய படிப்புத் துறை என்ன?",
    current_program_name_other: "உங்கள் முக்கிய படிப்புத் துறையை உள்ளிடவும்",
    employed_before: "சோல்ட் ஸ்டெ. மேரிக்கு குடிபெயர்வதற்கு முன்பு நீங்கள் கனடாவில் வேலை செய்தீர்களா?",
    previous_job_title: "சோல்ட் ஸ்டெ. மேரிக்கு குடிபெயர்வதற்கு முன்பு உங்கள் கடைசி தொழில் என்ன?",
    home_emp_before: "கனடாவுக்கு வருவதற்கு முன்பு உங்கள் சொந்த நாட்டில் வேலை செய்தீர்களா?",
    home_country_job: "உங்கள் சொந்த நாட்டில் உங்கள் கடைசி தொழில் என்ன?",
    employment_status: "பின்வருவனவற்றில் எது உங்கள் தற்போதைய வேலை நிலையை சிறப்பாக விவரிக்கிறது?",
    current_job_title: "உங்கள் தற்போதைய வேலையின் பதவி என்ன?",
    intended_job: "உங்கள் தற்போதைய வேலை நீங்கள் செய்ய விரும்பியதுதானா?",
    intended_job_title: "நீங்கள் செய்ய விரும்பும் வேலையின் பதவி என்ன?",
    job_search_help: "வட ஒன்டாரியோ / சோல்ட் ஸ்டெ. மேரியில் உங்கள் வேலைத் தேடலில் பின்வருவனவற்றில் எவை பயனுள்ளதாக இருந்தன? பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்.",
    job_search_other: "தயவுசெய்து குறிப்பிடவும்",
    work_barriers: "பொருந்தும் அனைத்துத் தடைகளையும் தேர்ந்தெடுக்கவும்",
    work_barriers_other: "தயவுசெய்து குறிப்பிடவும்",
    work_support: "எந்த வகையான ஆதரவு நீங்கள் விரும்பும் வேலையைப் பெற உதவும்? பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்.",
    work_support_other: "தயவுசெய்து குறிப்பிடவும்",
    unemployed_intended_job: "நீங்கள் செய்ய விரும்பும் வேலையின் பதவி என்ன?",
    unemployed_barrier_gate: "சோல்ட் ஸ்டெ. மேரியில் வேலை தேடும்போது ஏதேனும் தடைகளை எதிர்கொண்டீர்களா?",
    unemployment_reasons: "பொருந்தும் அனைத்துத் தடைகளையும் தேர்ந்தெடுக்கவும்",
    unemployment_reasons_other: "தயவுசெய்து குறிப்பிடவும்",
    not_looking_reasons: "நீங்கள் ஏன் வேலை தேடவில்லை?",
    not_looking_other: "தயவுசெய்து குறிப்பிடவும்",
    student_working: "நீங்கள் தற்போது வேலை செய்கிறீர்களா?",
    student_current_job: "உங்கள் தற்போதைய வேலையின் பதவி என்ன?",
    student_job_relevant: "உங்கள் தற்போதைய வேலை உங்கள் தற்போதைய படிப்புத் திட்டத்துடன் தொடர்புடையதா?",
    student_job_help: "வட ஒன்டாரியோ / சோல்ட் ஸ்டெ. மேரியில் உங்கள் வேலைத் தேடலில் பின்வருவனவற்றில் எவை பயனுள்ளதாக இருந்தன? பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்.",
    student_job_help_other: "தயவுசெய்து குறிப்பிடவும்",
    student_barrier_gate: "சோல்ட் ஸ்டெ. மேரியில் வேலை தேடும்போது ஏதேனும் தடைகளை எதிர்கொண்டீர்களா?",
    student_barriers: "பொருந்தும் அனைத்துத் தடைகளையும் தேர்ந்தெடுக்கவும்",
    student_barriers_other: "தயவுசெய்து குறிப்பிடவும்",
    student_support: "எந்த வகையான ஆதரவு நீங்கள் விரும்பும் வேலையைப் பெற உதவும்? பொருந்தும் அனைத்தையும் தேர்ந்தெடுக்கவும்.",
    student_support_other: "தயவுசெய்து குறிப்பிடவும்",
    planned_intended_job: "பட்டம் பெற்ற பிறகு நீங்கள் செய்ய விரும்பும் வேலையின் பதவி என்ன?",
    skills: "பின்வரும் ஒவ்வொரு திறனுக்கும் உங்கள் நிலையை எவ்வாறு மதிப்பிடுவீர்கள்?",
    gift_card_draw: "பரிசு அட்டை குலுக்கலில் பங்கேற்க விரும்புகிறீர்களா? (பரிசு நோக்கங்களுக்காக மட்டும்)",
    "work_barrier.a": "முழுநேரமாக வேலை செய்வதைத் தடுக்கும் ஏதேனும் தடை உள்ளதா?",
    "work_barrier.b": "நீங்கள் விரும்பும் வேலையைப் பெறுவதைத் தடுக்கும் ஏதேனும் தடை உள்ளதா?",
    "work_barrier.c": "முழுநேரமாக வேலை செய்வதையும் நீங்கள் விரும்பும் வேலையைச் செய்வதையும் தடுக்கும் ஏதேனும் தடை உள்ளதா?",
    "work_barrier.d": "முழுநேர வேலையைப் பெறுவதைத் தடுக்கும் ஏதேனும் தடை உள்ளதா?",
    "work_barrier.e": "நீங்கள் விரும்பும் வேலையைச் செய்வதைத் தடுக்கும் ஏதேனும் தடை உள்ளதா?",
  },
  help: {
    skills: "1 = மிகக் குறைவு, 2 = குறைவு, 3 = மிதமான, 4 = அதிகம், 5 = மிக அதிகம், 0 = உறுதியாகத் தெரியவில்லை",
  },
  o: {
    "85 or older": "85 அல்லது அதற்கு மேல்",
    "Advanced Diploma": "மேம்பட்ட டிப்ளோமா",
    "Alberta": "ஆல்பர்ட்டா",
    "Apprenticeship": "பயிற்சி (அப்ரண்டிஸ்ஷிப்)",
    "British Columbia": "பிரிட்டிஷ் கொலம்பியா",
    "Canadian degree or training": "கனேடியப் பட்டம் அல்லது பயிற்சி",
    "Canadian work experience": "கனேடிய வேலை அனுபவம்",
    "Caregiving responsibilities": "பராமரிப்புப் பொறுப்புகள்",
    "Childcare support": "குழந்தை பராமரிப்பு ஆதரவு",
    "College certificate": "கல்லூரிச் சான்றிதழ்",
    "Credential recognition support": "தகுதி அங்கீகார ஆதரவு",
    "Credentials not recognized": "தகுதிகள் அங்கீகரிக்கப்படவில்லை",
    "Diploma": "டிப்ளோமா",
    "Discrimination of any kind": "எந்தவிதமான பாகுபாடும்",
    "Doesn’t need employment income": "வேலை வருமானம் தேவையில்லை",
    "Economic Immigrant": "பொருளாதாரக் குடியேறி",
    "Employed casual (less than 10 hours/week)": "தற்காலிக வேலை (வாரத்திற்கு 10 மணிநேரத்திற்கும் குறைவு)",
    "Employed full time (30+ hours/week)": "முழுநேர வேலை (வாரத்திற்கு 30+ மணிநேரம்)",
    "Employed part time (10-30 hours/week)": "பகுதிநேர வேலை (வாரத்திற்கு 10-30 மணிநேரம்)",
    "Employment or settlement centre": "வேலைவாய்ப்பு அல்லது குடியேற்ற மையம்",
    "Family Sponsored": "குடும்பத்தால் நிதியுதவி பெற்றவர்",
    "Health issues": "உடல்நலப் பிரச்சினைகள்",
    "Health reasons": "உடல்நலக் காரணங்கள்",
    "High school diploma or equivalent": "உயர்நிலைப் பள்ளி டிப்ளோமா அல்லது சமமானது",
    "Household responsibilities": "வீட்டுப் பொறுப்புகள்",
    "Household work / Caregiver": "வீட்டு வேலை / பராமரிப்பாளர்",
    "I agree": "நான் ஒப்புக்கொள்கிறேன்",
    "I didn't have a work permit": "என்னிடம் வேலை அனுமதி இல்லை",
    "I directly moved to Sault": "நான் நேரடியாக சோல்ட்டுக்கு குடிபெயர்ந்தேன்",
    "I disagree": "நான் ஒப்புக்கொள்ளவில்லை",
    "Immigrant (permanent resident)": "குடியேறி (நிரந்தரக் குடியிருப்பாளர்)",
    "Immigration issues": "குடியேற்றப் பிரச்சினைகள்",
    "In Canada": "கனடாவில்",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "பழங்குடி (ஃபர்ஸ்ட் நேஷன்ஸ், மேட்டிஸ், இனுயிட்/இனுக்)",
    "International Student": "சர்வதேச மாணவர்",
    "Internship / volunteer experience": "பயிற்சி / தன்னார்வ அனுபவம்",
    "Lack of Canadian work experience": "கனேடிய வேலை அனுபவமின்மை",
    "Lack of skills for available jobs": "கிடைக்கும் வேலைகளுக்கான திறன்களின் பற்றாக்குறை",
    "Language barriers": "மொழித் தடைகள்",
    "Language support": "மொழி ஆதரவு",
    "Limited job opportunities in preferred sector": "விருப்பமான துறையில் குறைவான வேலை வாய்ப்புகள்",
    "Limited knowledge of local job market": "உள்ளூர் வேலைச் சந்தை பற்றிய குறைவான அறிவு",
    "Limited mentorship and job-matching support": "குறைவான வழிகாட்டல் மற்றும் வேலை-பொருத்த ஆதரவு",
    "Limited professional network": "குறைவான தொழில்முறை வலையமைப்பு",
    "Limited suitable jobs": "குறைவான பொருத்தமான வேலைகள்",
    "Local job boards": "உள்ளூர் வேலை அறிவிப்புப் பலகைகள்",
    "Local job market information": "உள்ளூர் வேலைச் சந்தைத் தகவல்",
    "Local training or certification": "உள்ளூர் பயிற்சி அல்லது சான்றிதழ்",
    "Low wages": "குறைந்த ஊதியம்",
    "Man": "ஆண்",
    "Manitoba": "மனிடோபா",
    "Mentorship support": "வழிகாட்டல் ஆதரவு",
    "Networking support": "வலையமைப்பு ஆதரவு",
    "New Brunswick": "நியூ ப்ரன்ஸ்விக்",
    "Newfoundland and Labrador": "நியூஃபவுண்ட்லாந்து மற்றும் லாப்ரடோர்",
    "No": "இல்லை",
    "Non-Canadian work experience not recognized": "கனேடியமல்லாத வேலை அனுபவம் அங்கீகரிக்கப்படவில்லை",
    "Non-binary person or other gender": "இருபாலரல்லாத நபர் அல்லது பிற பாலினம்",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "நிரந்தரமற்ற குடியிருப்பாளர் (எ.கா., வேலை அனுமதி, படிப்பு அனுமதி, அகதி கோரிக்கையாளர்)",
    "None of the above (do not select any other options)": "மேற்கண்ட எதுவும் இல்லை (வேறு எந்த விருப்பத்தையும் தேர்ந்தெடுக்க வேண்டாம்)",
    "Northwest Territories": "வடமேற்குப் பிரதேசங்கள்",
    "Not qualified for available jobs": "கிடைக்கும் வேலைகளுக்குத் தகுதியில்லை",
    "Nova Scotia": "நோவா ஸ்கோஷியா",
    "Nunavut": "நுனாவுட்",
    "On temporary leave from a job (e.g., maternity/parental leave)": "வேலையிலிருந்து தற்காலிக விடுப்பில் (எ.கா., மகப்பேறு/பெற்றோர் விடுப்பு)",
    "Other": "மற்றவை",
    "Other parts of Ontario": "ஒன்டாரியோவின் பிற பகுதிகள்",
    "Outside Canada": "கனடாவுக்கு வெளியே",
    "Outside of Canada": "கனடாவுக்கு வெளியே",
    "Outside of Ontario but within Canada": "ஒன்டாரியோவுக்கு வெளியே ஆனால் கனடாவுக்குள்",
    "Personal contacts": "தனிப்பட்ட தொடர்புகள்",
    "Post-graduate degree (e.g., Master's)": "முதுகலைப் பட்டம் (எ.கா., முதுநிலை)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "முதுகலைப் பட்டம் (எ.கா., முதுநிலை, முனைவர், MD)",
    "Primary school": "தொடக்கப் பள்ளி",
    "Prince Edward Island": "பிரின்ஸ் எட்வர்ட் தீவு",
    "Professional network": "தொழில்முறை வலையமைப்பு",
    "Protected Person": "பாதுகாக்கப்பட்ட நபர்",
    "Quebec": "கியூபெக்",
    "Recognition of non-Canadian work experience": "கனேடியமல்லாத வேலை அனுபவத்தின் அங்கீகாரம்",
    "Refugee": "அகதி",
    "Refugee Claimant": "அகதி கோரிக்கையாளர்",
    "Resume/interview support": "விண்ணப்பம்/நேர்காணல் ஆதரவு",
    "Retired": "ஓய்வு பெற்றவர்",
    "Saskatchewan": "சஸ்காட்செவான்",
    "Self-employed": "சுயதொழில்",
    "Skills-to-job matching platform": "திறன்-வேலை பொருத்த தளம்",
    "Social media (e.g., LinkedIn)": "சமூக ஊடகம் (எ.கா., லிங்க்ட்இன்)",
    "Student or recent graduate": "மாணவர் அல்லது சமீபத்தில் பட்டம் பெற்றவர்",
    "Temporary Foreign Worker": "தற்காலிக வெளிநாட்டுத் தொழிலாளர்",
    "Temporary Resident Permit Holder": "தற்காலிகக் குடியிருப்பு அனுமதி வைத்திருப்பவர்",
    "Training recommendations": "பயிற்சிப் பரிந்துரைகள்",
    "Unable to work": "வேலை செய்ய இயலாதவர்",
    "Undergraduate degree": "இளங்கலைப் பட்டம்",
    "Unemployed and actively looking for work": "வேலையற்றவர் மற்றும் தீவிரமாக வேலை தேடுகிறார்",
    "Unemployed and not looking for work": "வேலையற்றவர் மற்றும் வேலை தேடவில்லை",
    "Visible minority (e.g., South Asian, Chinese, Black)": "தெரியும் சிறுபான்மையினர் (எ.கா., தென்னாசியர், சீனர், கறுப்பினத்தவர்)",
    "Woman": "பெண்",
    "Yes": "ஆம்",
    "Yukon": "யூகான்",
  },
  def: {
    "Family Sponsored": "கனடாவில் ஏற்கனவே உள்ள குடும்ப உறுப்பினர் உங்களுக்கு நிதியுதவி அளித்ததால் நீங்கள் குடியேறினீர்கள்.",
    "Economic Immigrant": "திறமையான தொழிலாளர் அல்லது வணிகத் திட்டம் மூலம் நீங்கள் குடியேறினீர்கள் (எ.கா., எக்ஸ்பிரஸ் என்ட்ரி, மாகாண நியமனத் திட்டம்).",
    "Refugee": "உங்கள் சொந்த நாட்டில் உள்ள ஆபத்திலிருந்து பாதுகாப்புக்காக நீங்கள் கனடா வந்தீர்கள்.",
    "Temporary Foreign Worker": "ஒரு முதலாளியுடன் இணைக்கப்பட்ட வேலை அனுமதி அல்லது திறந்த வேலை அனுமதியில் கனடாவில்.",
    "Refugee Claimant": "நீங்கள் கனடாவிடம் அகதி பாதுகாப்பு கோரியுள்ளீர்கள், முடிவுக்காகக் காத்திருக்கிறீர்கள்.",
    "Protected Person": "உங்களுக்குப் பாதுகாப்பு தேவை என்பதை கனடா ஏற்கனவே ஏற்றுக்கொண்டுள்ளது (அங்கீகரிக்கப்பட்ட அகதி/பாதுகாக்கப்பட்ட நிலை).",
    "Temporary Resident Permit Holder": "பொதுவாக அனுமதிக்கப்படாத நிலையில் தற்காலிகமாகத் தங்குவதற்கு உங்களிடம் சிறப்பு அனுமதி உள்ளது.",
    "Employment or settlement agency": "மக்கள் வேலை கண்டுபிடிக்க உதவும் அல்லது புதிதாக வந்தவர்களை கனடாவில் குடியேற உதவும் ஒரு அமைப்பு.",
    "Recognition of experience": "நீங்கள் முன்பு பெற்ற வேலை அனுபவத்தை ஏற்று மதிக்கும் ஒரு முதலாளி.",
    "Networking events": "வேலைத் தொடர்புகளை உருவாக்க உங்கள் துறையைச் சேர்ந்தவர்களைச் சந்திக்கும் நிகழ்வுகள்.",
    "Lack of local experience": "முதலாளிகள் அடிக்கடி கேட்கும் கனடாவிலோ இப்பகுதியிலோ நீங்கள் இன்னும் வேலை செய்யவில்லை.",
    "Lack of Canadian experience": "முதலாளிகள் அடிக்கடி கேட்கும் கனடாவிலோ இப்பகுதியிலோ நீங்கள் இன்னும் வேலை செய்யவில்லை.",
    "Qualifications not recognized": "மற்றொரு நாட்டிலிருந்து உங்கள் கல்வி, உரிமம் அல்லது அனுபவம் இங்கு ஏற்கப்படவில்லை.",
    "Credential recognition issue": "மற்றொரு நாட்டிலிருந்து உங்கள் கல்வி, உரிமம் அல்லது அனுபவம் இங்கு ஏற்கப்படவில்லை.",
    "Experience not recognized": "மற்றொரு நாட்டிலிருந்து உங்கள் கல்வி, உரிமம் அல்லது அனுபவம் இங்கு ஏற்கப்படவில்லை.",
    "Immigration restrictions": "உங்கள் அனுமதி அல்லது நிலையின் நிபந்தனைகள் நீங்கள் செய்யக்கூடிய வேலை அல்லது மணிநேரங்களைக் கட்டுப்படுத்துகின்றன.",
    "Immigration status": "உங்கள் அனுமதி அல்லது நிலையின் நிபந்தனைகள் நீங்கள் செய்யக்கூடிய வேலை அல்லது மணிநேரங்களைக் கட்டுப்படுத்துகின்றன.",
    "Skills mismatch": "உங்கள் திறன்கள் உள்ளூரில் கிடைக்கும் வேலைகளுடன் பொருந்தவில்லை.",
    "Limited network": "உங்களை வேலைகளுடன் இணைக்கக்கூடிய பலரை நீங்கள் அறிந்திருக்கவில்லை.",
    "Credential recognition": "உங்கள் வெளிநாட்டுக் கல்வி அல்லது உரிமத்தை கனடாவில் அங்கீகரிக்க உதவி.",
    "Job matching": "பொருத்தமான வேலை வாய்ப்புகளுடன் உங்களை இணைக்கும் ஒரு சேவை.",
    "Training matching": "பொருத்தமான பயிற்சித் திட்டங்களுடன் உங்களை இணைக்கும் ஒரு சேவை.",
  },
  ui: {
    "% complete": "% முடிந்தது",
    "Back to home": "முகப்புக்குத் திரும்பு",
    "Back": "பின்",
    "Consent is required to continue": "தொடர ஒப்புதல் தேவை",
    "Definition:": "வரையறை:",
    "Email address": "மின்னஞ்சல் முகவரி",
    "Finish to become a Survey Champion": "ஆய்வு சாம்பியன் ஆக முடிக்கவும்",
    "Five $50 local gift cards drawn monthly": "மாதந்தோறும் $50 மதிப்புள்ள ஐந்து உள்ளூர் பரிசு அட்டைகள் குலுக்கப்படுகின்றன",
    "Go back": "பின் செல்",
    "Go home": "முகப்புக்குச் செல்",
    "Halfway there": "பாதி தூரம்",
    "Home": "முகப்பு",
    "Next 5 skills": "அடுத்த 5 திறன்கள்",
    "Next question": "அடுத்த கேள்வி",
    "No matches": "பொருத்தம் இல்லை",
    "Not sure": "உறுதியாகத் தெரியவில்லை",
    "One moment.": "ஒரு நிமிடம்.",
    "Previous question": "முந்தைய கேள்வி",
    "Saving your response…": "உங்கள் பதில் சேமிக்கப்படுகிறது…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "சேவையகத்தை அணுகுவதில் சிக்கல் ஏற்பட்டது. உங்கள் பதில்கள் இன்னும் இந்தச் சாதனத்தில் சேமிக்கப்பட்டுள்ளன — மீண்டும் முயற்சிக்கவும்.",
    "Submit": "சமர்ப்பி",
    "Thank you for sharing your experience.": "உங்கள் அனுபவத்தைப் பகிர்ந்தமைக்கு நன்றி.",
    "Thank you for your time and response": "உங்கள் நேரத்திற்கும் பதிலுக்கும் நன்றி",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "உங்கள் நேரத்திற்கும் பதிலுக்கும் நன்றி. சமூகத்தின் வளர்ச்சிக்கு நீங்கள் பெரும் பங்களிப்பு செய்தீர்கள்.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "நன்றி — உங்கள் பதில் பதிவு செய்யப்பட்டுள்ளது. மீண்டும் நிரப்ப வேண்டியதில்லை.",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "பங்கேற்க, உங்களுக்கு குறைந்தது 18 வயது இருக்க வேண்டும் மற்றும் பங்கேற்க ஒப்புக்கொள்ள வேண்டும். தொடர விரும்பினால், பின் சென்று உங்கள் பதிலை மாற்றலாம்.",
    "Try again": "மீண்டும் முயற்சிக்கவும்",
    "We couldn't save your response": "உங்கள் பதிலைச் சேமிக்க முடியவில்லை",
    "Yes, enter me in the gift-card draw": "ஆம், பரிசு அட்டை குலுக்கலில் என்னைச் சேர்க்கவும்",
    "You made a great contribution to the development of the community": "சமூகத்தின் வளர்ச்சிக்கு நீங்கள் பெரும் பங்களிப்பு செய்தீர்கள்",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "நீங்கள் தனிப்பட்ட அழைப்பு இணைப்பைத் திறந்துள்ளீர்கள், எனவே நினைவூட்டல் நோக்கங்களுக்காக உங்கள் நிறைவு பதிவு செய்யப்படலாம். உங்கள் பதில்கள் ரகசியமாக வைக்கப்பட்டு அடையாளம் நீக்கப்பட்ட வடிவில் பகுப்பாய்வு செய்யப்படுகின்றன.",
    "You're a Survey Champion": "நீங்கள் ஒரு ஆய்வு சாம்பியன்",
    "You've already completed this survey": "நீங்கள் ஏற்கனவே இந்த ஆய்வை முடித்துவிட்டீர்கள்",
    "Your responses are anonymous.": "உங்கள் பதில்கள் அநாமதேயமானவை.",
    "more — keep typing to narrow": "மேலும் — சுருக்க தொடர்ந்து தட்டச்சு செய்யவும்",
    "Search or select a language": "மொழியைத் தேடவும் அல்லது தேர்ந்தெடுக்கவும்",
    "Type to search countries…": "நாட்டைத் தேட தட்டச்சு செய்யவும்…",
    "Type to search areas of study…": "படிப்புத் துறையைத் தேட தட்டச்சு செய்யவும்…",
    "Type to search occupations…": "தொழிலைத் தேட தட்டச்சு செய்யவும்…",
    "Type to search…": "தேட தட்டச்சு செய்யவும்…",
    "Select one…": "ஒன்றைத் தேர்ந்தெடுக்கவும்…",
    "1 · Lowest": "1 · மிகக் குறைவு",
    "5 · Highest": "5 · மிக அதிகம்",
  },
};
