// DRAFT Tagalog (tl) — pending fluent review. Keyed to exact source strings.
module.exports = {
  q: {
    language: "Pumili ng wika upang magpatuloy",
    consent: "Pakikumpirma na ikaw ay hindi bababa sa 18 taong gulang at kusang-loob na sumasang-ayon na lumahok sa survey na ito.",
    eligible: "Lumipat ka ba sa Northern Ontario pagkatapos ng Setyembre 2021 upang manirahan?",
    moved_from: "Saan ka lumipat mula?",
    province: "Pakipili ang lalawigan kung saan ka lumipat mula",
    country_moved_from: "Pakipili ang bansa kung saan ka lumipat mula",
    gender: "Ano ang iyong kasarian?",
    age_group: "Ano ang iyong pangkat ng edad?",
    identity_groups: "Nakikilala mo ba ang iyong sarili sa alinman sa mga sumusunod na grupo? Piliin lahat ng naaangkop.",
    immigration_category: "Pumili ng kategorya ng imigrasyon",
    non_permanent_category: "Pumili ng kategorya ng hindi permanenteng residente",
    non_permanent_other: "Pakitukoy",
    recent_credential: "Ano ang pinakahuling natapos mong kwalipikasyong pang-edukasyon?",
    program_name: "Ano ang iyong pangunahing larangan ng pag-aaral?",
    program_name_other: "I-type ang iyong pangunahing larangan ng pag-aaral",
    program_location: "Saan mo natapos ang programang ito?",
    highest_education: "Ang programang ito ba ang iyong pinakamataas na antas ng edukasyon?",
    highest_credential: "Ano ang iyong pinakamataas na antas ng edukasyon?",
    highest_program_name: "Para sa iyong pinakamataas na antas ng edukasyon, ano ang iyong pangunahing larangan ng pag-aaral?",
    highest_program_name_other: "I-type ang iyong pangunahing larangan ng pag-aaral para sa iyong pinakamataas na antas ng edukasyon",
    current_program: "Ano ang iyong kasalukuyang programa ng pag-aaral?",
    current_program_name: "Ano ang iyong pangunahing larangan ng pag-aaral?",
    current_program_name_other: "I-type ang iyong pangunahing larangan ng pag-aaral",
    employed_before: "May trabaho ka ba sa Canada bago lumipat sa Sault Ste. Marie?",
    previous_job_title: "Ano ang iyong huling trabaho bago lumipat sa Sault Ste. Marie?",
    home_emp_before: "May trabaho ka ba sa iyong bansang pinagmulan bago pumunta sa Canada?",
    home_country_job: "Ano ang iyong huling trabaho sa iyong bansang pinagmulan?",
    employment_status: "Alin sa mga sumusunod ang pinakamahusay na naglalarawan sa iyong kasalukuyang katayuan sa trabaho?",
    current_job_title: "Ano ang titulo ng iyong kasalukuyang trabaho?",
    intended_job: "Ang iyong kasalukuyang trabaho ba ang siyang balak mong gawin?",
    intended_job_title: "Ano ang titulo ng trabahong balak mong gawin?",
    job_search_help: "Alin sa mga sumusunod ang nakatulong sa iyong paghahanap ng trabaho sa Northern Ontario / Sault Ste. Marie? Piliin lahat ng naaangkop.",
    job_search_other: "Pakitukoy",
    work_barriers: "Piliin lahat ng naaangkop na hadlang",
    work_barriers_other: "Pakitukoy",
    work_support: "Anong uri ng suporta ang makakatulong sa iyo na makuha ang trabahong gusto mo? Piliin lahat ng naaangkop.",
    work_support_other: "Pakitukoy",
    unemployed_intended_job: "Ano ang titulo ng trabahong balak mong gawin?",
    unemployed_barrier_gate: "Nakaranas ka ba ng anumang hadlang habang naghahanap ng trabaho sa Sault Ste. Marie?",
    unemployment_reasons: "Piliin lahat ng naaangkop na hadlang",
    unemployment_reasons_other: "Pakitukoy",
    not_looking_reasons: "Bakit hindi ka naghahanap ng trabaho?",
    not_looking_other: "Pakitukoy",
    student_working: "Nagtatrabaho ka ba sa kasalukuyan?",
    student_current_job: "Ano ang titulo ng iyong kasalukuyang trabaho?",
    student_job_relevant: "May kaugnayan ba ang iyong kasalukuyang trabaho sa iyong kasalukuyang programa ng pag-aaral?",
    student_job_help: "Alin sa mga sumusunod ang nakatulong sa iyong paghahanap ng trabaho sa Northern Ontario / Sault Ste. Marie? Piliin lahat ng naaangkop.",
    student_job_help_other: "Pakitukoy",
    student_barrier_gate: "Nakaranas ka ba ng anumang hadlang habang naghahanap ng trabaho sa Sault Ste. Marie?",
    student_barriers: "Piliin lahat ng naaangkop na hadlang",
    student_barriers_other: "Pakitukoy",
    student_support: "Anong uri ng suporta ang makakatulong sa iyo na makuha ang trabahong gusto mo? Piliin lahat ng naaangkop.",
    student_support_other: "Pakitukoy",
    planned_intended_job: "Ano ang titulo ng trabahong balak mong gawin pagkatapos ng pagtatapos?",
    skills: "Paano mo iraranggo ang iyong antas sa bawat isa sa mga sumusunod na kasanayan?",
    gift_card_draw: "Gusto mo bang lumahok sa gift card draw? (Para sa layunin ng premyo lamang)",
    "work_barrier.a": "May hadlang ba na pumipigil sa iyong magtrabaho nang full time?",
    "work_barrier.b": "May hadlang ba na pumipigil sa iyong makuha ang trabahong gusto mo?",
    "work_barrier.c": "May hadlang ba na pumipigil sa iyong magtrabaho nang full time at gawin ang trabahong gusto mo?",
    "work_barrier.d": "May hadlang ba na pumipigil sa iyong makakuha ng full time na trabaho?",
    "work_barrier.e": "May hadlang ba na pumipigil sa iyong gawin ang trabahong gusto mo?",
  },
  help: {
    skills: "1 = pinakamababa, 2 = mababa, 3 = katamtaman, 4 = mataas, 5 = pinakamataas, 0 = hindi sigurado",
  },
  o: {
    "85 or older": "85 o mas matanda",
    "Advanced Diploma": "Advanced Diploma",
    "Alberta": "Alberta",
    "Apprenticeship": "Apprenticeship",
    "British Columbia": "British Columbia",
    "Canadian degree or training": "Canadian na digri o pagsasanay",
    "Canadian work experience": "Karanasan sa trabaho sa Canada",
    "Caregiving responsibilities": "Mga responsibilidad sa pag-aalaga",
    "Childcare support": "Suporta sa pag-aalaga ng bata",
    "College certificate": "Sertipiko ng kolehiyo",
    "Credential recognition support": "Suporta sa pagkilala ng kredensyal",
    "Credentials not recognized": "Hindi kinikilalang mga kredensyal",
    "Diploma": "Diploma",
    "Discrimination of any kind": "Diskriminasyon ng anumang uri",
    "Doesn’t need employment income": "Hindi kailangan ng kita mula sa trabaho",
    "Economic Immigrant": "Economic Immigrant",
    "Employed casual (less than 10 hours/week)": "Casual na trabaho (mas mababa sa 10 oras/linggo)",
    "Employed full time (30+ hours/week)": "Full time na trabaho (30+ oras/linggo)",
    "Employed part time (10-30 hours/week)": "Part time na trabaho (10-30 oras/linggo)",
    "Employment or settlement centre": "Sentro ng trabaho o settlement",
    "Family Sponsored": "Isponsor ng pamilya",
    "Health issues": "Mga problema sa kalusugan",
    "Health reasons": "Mga dahilang pangkalusugan",
    "High school diploma or equivalent": "High school diploma o katumbas",
    "Household responsibilities": "Mga responsibilidad sa bahay",
    "Household work / Caregiver": "Gawaing bahay / Tagapag-alaga",
    "I agree": "Sumasang-ayon ako",
    "I didn't have a work permit": "Wala akong work permit",
    "I directly moved to Sault": "Direkta akong lumipat sa Sault",
    "I disagree": "Hindi ako sumasang-ayon",
    "Immigrant (permanent resident)": "Imigrante (permanenteng residente)",
    "Immigration issues": "Mga isyu sa imigrasyon",
    "In Canada": "Sa Canada",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Katutubo (First Nations, Métis, Inuit/Inuk)",
    "International Student": "Internasyonal na mag-aaral",
    "Internship / volunteer experience": "Internship / karanasan sa boluntaryo",
    "Lack of Canadian work experience": "Kakulangan ng karanasan sa trabaho sa Canada",
    "Lack of skills for available jobs": "Kakulangan ng kasanayan para sa mga available na trabaho",
    "Language barriers": "Mga hadlang sa wika",
    "Language support": "Suporta sa wika",
    "Limited job opportunities in preferred sector": "Limitadong oportunidad sa trabaho sa nais na sektor",
    "Limited knowledge of local job market": "Limitadong kaalaman sa lokal na merkado ng trabaho",
    "Limited mentorship and job-matching support": "Limitadong suporta sa mentorship at job-matching",
    "Limited professional network": "Limitadong propesyonal na network",
    "Limited suitable jobs": "Limitadong angkop na trabaho",
    "Local job boards": "Mga lokal na job board",
    "Local job market information": "Impormasyon sa lokal na merkado ng trabaho",
    "Local training or certification": "Lokal na pagsasanay o sertipikasyon",
    "Low wages": "Mababang sahod",
    "Man": "Lalaki",
    "Manitoba": "Manitoba",
    "Mentorship support": "Suporta sa mentorship",
    "Networking support": "Suporta sa networking",
    "New Brunswick": "New Brunswick",
    "Newfoundland and Labrador": "Newfoundland at Labrador",
    "No": "Hindi",
    "Non-Canadian work experience not recognized": "Hindi kinikilala ang karanasan sa trabaho sa labas ng Canada",
    "Non-binary person or other gender": "Non-binary na tao o ibang kasarian",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Hindi permanenteng residente (hal., work permit, study permit, refugee claimant)",
    "None of the above (do not select any other options)": "Wala sa mga nabanggit (huwag pumili ng ibang opsyon)",
    "Northwest Territories": "Northwest Territories",
    "Not qualified for available jobs": "Hindi kwalipikado para sa mga available na trabaho",
    "Nova Scotia": "Nova Scotia",
    "Nunavut": "Nunavut",
    "On temporary leave from a job (e.g., maternity/parental leave)": "Nasa pansamantalang leave mula sa trabaho (hal., maternity/parental leave)",
    "Other": "Iba pa",
    "Other parts of Ontario": "Ibang bahagi ng Ontario",
    "Outside Canada": "Sa labas ng Canada",
    "Outside of Canada": "Sa labas ng Canada",
    "Outside of Ontario but within Canada": "Sa labas ng Ontario ngunit sa loob ng Canada",
    "Personal contacts": "Mga personal na kontak",
    "Post-graduate degree (e.g., Master's)": "Post-graduate na digri (hal., Master's)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Post-graduate na digri (hal., Master's, PhD, MD)",
    "Primary school": "Elementarya",
    "Prince Edward Island": "Prince Edward Island",
    "Professional network": "Propesyonal na network",
    "Protected Person": "Protektadong tao",
    "Quebec": "Quebec",
    "Recognition of non-Canadian work experience": "Pagkilala sa karanasan sa trabaho sa labas ng Canada",
    "Refugee": "Refugee",
    "Refugee Claimant": "Refugee Claimant",
    "Resume/interview support": "Suporta sa resume/interview",
    "Retired": "Retirado",
    "Saskatchewan": "Saskatchewan",
    "Self-employed": "Self-employed",
    "Skills-to-job matching platform": "Platform sa pagtutugma ng kasanayan at trabaho",
    "Social media (e.g., LinkedIn)": "Social media (hal., LinkedIn)",
    "Student or recent graduate": "Mag-aaral o kamakailang nagtapos",
    "Temporary Foreign Worker": "Temporary Foreign Worker",
    "Temporary Resident Permit Holder": "May hawak ng Temporary Resident Permit",
    "Training recommendations": "Mga rekomendasyon sa pagsasanay",
    "Unable to work": "Hindi makapagtrabaho",
    "Undergraduate degree": "Undergraduate na digri",
    "Unemployed and actively looking for work": "Walang trabaho at aktibong naghahanap ng trabaho",
    "Unemployed and not looking for work": "Walang trabaho at hindi naghahanap ng trabaho",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Visible minority (hal., South Asian, Chinese, Black)",
    "Woman": "Babae",
    "Yes": "Oo",
    "Yukon": "Yukon",
  },
  def: {
    "Family Sponsored": "Lumipat ka dahil isinponsor ka ng isang miyembro ng pamilya na nasa Canada na.",
    "Economic Immigrant": "Lumipat ka sa pamamagitan ng programa para sa skilled worker o negosyo (hal., Express Entry, Provincial Nominee).",
    "Refugee": "Pumunta ka sa Canada para sa proteksyon mula sa panganib sa iyong bansang pinagmulan.",
    "Temporary Foreign Worker": "Nasa Canada gamit ang work permit na nakatali sa isang employer o open work permit.",
    "Refugee Claimant": "Humingi ka ng proteksyon bilang refugee sa Canada at naghihintay ng desisyon.",
    "Protected Person": "Tinanggap na ng Canada na kailangan mo ng proteksyon (aprubadong refugee/protected status).",
    "Temporary Resident Permit Holder": "May hawak kang espesyal na permit upang manatili nang pansamantala kung kailan normal na hindi ito pinapayagan.",
    "Canadian degree or training": "Nakatapos ka ng digri o programa ng pagsasanay sa Canada.",
    "Canadian work experience": "Nagtrabaho ka para sa isang employer sa Canada.",
    "Employment or settlement centre": "Nakatanggap ka ng tulong mula sa organisasyong sumusuporta sa mga naghahanap ng trabaho o mga bagong dating (hal., Sault Community Career Center).",
    "Internship / volunteer experience": "Nakakuha ka ng karanasan sa trabaho sa pamamagitan ng walang bayad na internship, panandaliang placement, o boluntaryong gawain.",
    "Local job boards": "Gumamit ka ng mga website o anunsyo na naglalathala ng mga trabaho sa iyong lugar (hal., AWIC job board).",
    "Personal contacts": "Nakakuha ka ng tulong o impormasyon tungkol sa trabaho mula sa pamilya, mga kaibigan, o mga taong personal mong kilala.",
    "Professional network": "Gumamit ka ng mga koneksyon mula sa iyong larangan ng trabaho, tulad ng mga katrabaho o mentor.",
    "Recognition of non-Canadian work experience": "Tinanggap ang iyong karanasan sa trabaho na nakuha sa labas ng Canada.",
    "Caregiving responsibilities": "Kailangan mong mag-alaga ng mga bata o matatandang miyembro ng pamilya na umaasa sa iyo.",
    "Credentials not recognized": "Ang iyong edukasyon, digri, o lisensya mula sa labas ng Canada ay hindi tinatanggap ng mga employer sa Canada.",
    "Discrimination of any kind": "Hindi ka patas na trinato dahil sa iyong lahi, etnisidad, relihiyon, kasarian, punto ng pagsasalita, edad, o iba pang personal na katangian.",
    "Health issues": "May mga kondisyon ka sa pisikal o mental na kalusugan na nagpapahirap sa paghahanap o pagpapanatili ng trabaho.",
    "Household responsibilities": "Kailangan mong asikasuhin ang mga gawaing bahay (pagluluto, paglilinis, pagpapatakbo ng tahanan).",
    "Lack of Canadian work experience": "Humihingi ang mga employer ng karanasan sa trabaho sa Canada, na wala ka pa.",
    "Lack of skills for available jobs": "Ang mga trabahong available sa iyong lugar ay nangangailangan ng kasanayan o pagsasanay na wala ka sa kasalukuyan.",
    "Language barriers": "Ang iyong kakayahan sa Ingles (o Pranses) ay nagpapahirap sa paghahanap ng trabaho o pagpasa sa mga interbyu.",
    "Limited job opportunities in preferred sector": "Kakaunti ang mga trabaho sa iyong larangan o industriya sa iyong lugar.",
    "Limited knowledge of local job market": "Hindi ka sigurado kung paano maghanap ng trabaho, sinong employer ang kumukuha, o paano gumagana ang pagkuha sa iyong lugar.",
    "Limited mentorship and job-matching support": "Wala kang access sa mga mentor o serbisyong nag-uugnay sa iyo sa angkop na trabaho.",
    "Limited professional network": "Kakaunti ang kilala mong tao sa iyong larangan na maaaring magbahagi ng impormasyon sa trabaho, rekomendasyon, o payo.",
    "Non-Canadian work experience not recognized": "Ang iyong karanasan sa trabaho na nakuha sa labas ng Canada ay hindi tinatanggap o pinahahalagahan ng mga employer sa Canada.",
    "Childcare support": "Kailangan mo ng tulong sa pag-aalaga ng iyong mga anak upang makapagtrabaho ka.",
    "Credential recognition support": "Kailangan mo ng tulong upang matanggap ang iyong edukasyon o propesyonal na kwalipikasyon mula sa labas ng Canada.",
    "Language support": "Kailangan mo ng tulong upang mapabuti ang iyong kakayahan sa Ingles (o Pranses).",
    "Local job market information": "Kailangan mo ng impormasyon kung sinong employer ang kumukuha, anong trabaho ang available, at anong kasanayan ang hinahanap sa iyong lugar.",
    "Local training or certification": "Kailangan mo ng pagsasanay o sertipikasyon na inaalok sa iyong lugar upang maging kwalipikado sa mga available na trabaho.",
    "Mentorship support": "Kailangan mo ng koneksyon sa mga taong may karanasan sa iyong larangan.",
    "Networking support": "Kailangan mo ng tulong upang makilala ang mga employer at propesyonal.",
    "Resume/interview support": "Kailangan mo ng tulong sa paghahanda ng iyong resume, cover letter, o pagsasanay para sa mga interbyu.",
    "Skills-to-job matching platform": "Kailangan mo ng serbisyo o tool na nagtutugma ng iyong kasanayan sa angkop na bakanteng trabaho.",
    "Training recommendations": "Kailangan mo ng mga mungkahi kung anong pagsasanay o kurso ang kukunin upang mapabuti ang iyong pagkakataong makakuha ng trabaho.",
    "Doesn’t need employment income": "Hindi mo kailangang magtrabaho dahil may iba kang pinagkukunan ng kita o suportang pinansyal.",
    "Health reasons": "May mga kondisyon ka sa pisikal o mental na kalusugan na nagpapahirap sa paghahanap o pagpapanatili ng trabaho.",
    "Immigration issues": "Ang iyong katayuan sa imigrasyon o mga dokumento (hal., work permit, prosesong PR) ay pumipigil sa iyong magtrabaho.",
    "Limited suitable jobs": "Kakaunti ang mga trabaho sa iyong lugar na tumutugma sa iyong kasanayan, karanasan, o kagustuhan.",
    "Low wages": "Napakababa ng bayad ng mga available na trabaho para maging sulit ang pagtatrabaho para sa iyo.",
    "Not qualified for available jobs": "Ang mga trabahong available sa iyong lugar ay nangangailangan ng edukasyon, kasanayan, o sertipikasyon na wala ka sa kasalukuyan.",
  },
  ui: {
    "% complete": "% kumpleto",
    "Back to home": "Bumalik sa home",
    "Back": "Bumalik",
    "Consent is required to continue": "Kailangan ang pahintulot upang magpatuloy",
    "Definition:": "Kahulugan:",
    "Email address": "Email address",
    "Finish to become a Survey Champion": "Tapusin upang maging Survey Champion",
    "Five $50 local gift cards drawn monthly": "Limang $50 na lokal na gift card ang binubunot buwan-buwan",
    "Go back": "Bumalik",
    "Home": "Home",
    "Next 5 skills": "Susunod na 5 kasanayan",
    "Next question": "Susunod na tanong",
    "No matches": "Walang tugma",
    "Not sure": "Hindi sigurado",
    "One moment.": "Sandali lang.",
    "Previous question": "Nakaraang tanong",
    "Saving your response…": "Sine-save ang iyong sagot…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "May naganap na problema sa pagkonekta sa server. Naka-save pa rin ang iyong mga sagot sa device na ito — pakisubukang muli.",
    "Submit": "Isumite",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Salamat sa iyong oras at sagot. Malaki ang naiambag mo sa pag-unlad ng komunidad.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Salamat — naitala na ang iyong sagot. Hindi na kailangang sagutan itong muli.",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "Upang lumahok, kailangan mong hindi bababa sa 18 taong gulang at sumang-ayon na lumahok. Kung nais mong magpatuloy, maaari kang bumalik at baguhin ang iyong sagot.",
    "Try again": "Subukang muli",
    "We couldn't save your response": "Hindi namin na-save ang iyong sagot",
    "Yes, enter me in the gift-card draw": "Oo, isali ako sa gift-card draw",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Nagbukas ka ng personal na link ng imbitasyon, kaya maaaring maitala ang iyong pagkumpleto para sa layunin ng paalala. Ang iyong mga sagot ay pinananatiling kumpidensyal at sinusuri sa anyong hindi nakikilala ang pagkakakilanlan.",
    "You're a Survey Champion": "Ikaw ay isang Survey Champion",
    "You've already completed this survey": "Nakumpleto mo na ang survey na ito",
    "Your responses are anonymous.": "Ang iyong mga sagot ay anonymous.",
    "more — keep typing to narrow": "pa — magpatuloy sa pag-type upang paliitin",
    "Search or select a language": "Maghanap o pumili ng wika",
    "Type to search countries…": "Mag-type upang maghanap ng bansa…",
    "Type to search areas of study…": "Mag-type upang maghanap ng larangan ng pag-aaral…",
    "Type to search occupations…": "Mag-type upang maghanap ng trabaho…",
    "Type to search…": "Mag-type upang maghanap…",
    "Select one…": "Pumili ng isa…",
    "1 · Lowest": "1 · pinakamababa",
    "5 · Highest": "5 · pinakamataas",
    "Thank you for your interest.": "Salamat sa iyong interes.",
    "Unfortunately you are not eligible to participate in the survey.": "Sa kasamaang palad, hindi ka kwalipikadong lumahok sa survey.",
  },
};
