// DRAFT Ukrainian (uk) — pending fluent review. Keyed to exact source strings.
module.exports = {
  q: {
    language: "Виберіть мову, щоб продовжити",
    consent: "Підтвердіть, що вам щонайменше 18 років і ви добровільно погоджуєтеся взяти участь у цьому опитуванні.",
    eligible: "Чи переїхали ви до Північного Онтаріо після вересня 2021 року, щоб тут жити?",
    moved_from: "Звідки ви переїхали?",
    province: "Виберіть провінцію, з якої ви переїхали",
    country_moved_from: "Виберіть країну, з якої ви переїхали",
    gender: "Яка ваша стать?",
    age_group: "Яка ваша вікова група?",
    identity_groups: "Чи належите ви до будь-якої з наведених груп? Виберіть усе, що підходить.",
    immigration_category: "Виберіть імміграційну категорію",
    non_permanent_category: "Виберіть категорію тимчасового резидента",
    non_permanent_other: "Будь ласка, уточніть",
    recent_credential: "Який ваш останній здобутий освітній рівень?",
    program_name: "Яка була ваша основна галузь навчання?",
    program_name_other: "Введіть вашу основну галузь навчання",
    program_location: "Де ви завершили цю програму?",
    highest_education: "Чи є ця програма вашим найвищим рівнем освіти?",
    highest_credential: "Який ваш найвищий рівень освіти?",
    highest_program_name: "Яка була ваша основна галузь навчання для найвищого рівня освіти?",
    highest_program_name_other: "Введіть вашу основну галузь навчання для найвищого рівня освіти",
    current_program: "Яка ваша поточна навчальна програма?",
    current_program_name: "Яка ваша основна галузь навчання?",
    current_program_name_other: "Введіть вашу основну галузь навчання",
    employed_before: "Чи працювали ви в Канаді до переїзду в Су-Сент-Марі?",
    previous_job_title: "Ким ви працювали востаннє до переїзду в Су-Сент-Марі?",
    home_emp_before: "Чи працювали ви у своїй рідній країні до приїзду в Канаду?",
    home_country_job: "Ким ви працювали востаннє у своїй рідній країні?",
    employment_status: "Що з наведеного найкраще описує вашу поточну зайнятість?",
    current_job_title: "Яка назва вашої поточної посади?",
    intended_job: "Чи є ваша поточна робота тією, яку ви планували виконувати?",
    intended_job_title: "Яка назва посади, яку ви плануєте обіймати?",
    job_search_help: "Що з наведеного було корисним у пошуку роботи в Північному Онтаріо / Су-Сент-Марі? Виберіть усе, що підходить.",
    job_search_other: "Будь ласка, уточніть",
    work_barriers: "Виберіть усі перешкоди, що підходять",
    work_barriers_other: "Будь ласка, уточніть",
    work_support: "Який вид підтримки допоміг би вам отримати бажану роботу? Виберіть усе, що підходить.",
    work_support_other: "Будь ласка, уточніть",
    unemployed_intended_job: "Яка назва посади, яку ви плануєте обіймати?",
    unemployed_barrier_gate: "Чи стикалися ви з якимись перешкодами під час пошуку роботи в Су-Сент-Марі?",
    unemployment_reasons: "Виберіть усі перешкоди, що підходять",
    unemployment_reasons_other: "Будь ласка, уточніть",
    not_looking_reasons: "Чому ви не шукаєте роботу?",
    not_looking_other: "Будь ласка, уточніть",
    student_working: "Чи працюєте ви зараз?",
    student_current_job: "Яка назва вашої поточної посади?",
    student_job_relevant: "Чи пов'язана ваша поточна робота з вашою поточною навчальною програмою?",
    student_job_help: "Що з наведеного було корисним у пошуку роботи в Північному Онтаріо / Су-Сент-Марі? Виберіть усе, що підходить.",
    student_job_help_other: "Будь ласка, уточніть",
    student_barrier_gate: "Чи стикалися ви з якимись перешкодами під час пошуку роботи в Су-Сент-Марі?",
    student_barriers: "Виберіть усі перешкоди, що підходять",
    student_barriers_other: "Будь ласка, уточніть",
    student_support: "Який вид підтримки допоміг би вам отримати бажану роботу? Виберіть усе, що підходить.",
    student_support_other: "Будь ласка, уточніть",
    planned_intended_job: "Яка назва посади, яку ви плануєте обіймати після закінчення навчання?",
    skills: "Як би ви оцінили свій рівень для кожної з наведених навичок?",
    gift_card_draw: "Чи бажаєте ви взяти участь у розіграші подарункових карток? (Лише для цілей призу)",
    "work_barrier.a": "Чи є перешкода, яка заважає вам працювати повний робочий день?",
    "work_barrier.b": "Чи є перешкода, яка заважає вам отримати бажану роботу?",
    "work_barrier.c": "Чи є перешкода, яка заважає вам працювати повний робочий день і виконувати бажану роботу?",
    "work_barrier.d": "Чи є перешкода, яка заважає вам отримати роботу на повний робочий день?",
    "work_barrier.e": "Чи є перешкода, яка заважає вам виконувати бажану роботу?",
  },
  help: {
    skills: "1 = найнижчий, 2 = низький, 3 = помірний, 4 = високий, 5 = найвищий, 0 = не впевнений",
  },
  o: {
    "85 or older": "85 або старше",
    "Advanced Diploma": "Диплом підвищеного рівня",
    "Alberta": "Альберта",
    "Apprenticeship": "Професійне учнівство",
    "British Columbia": "Британська Колумбія",
    "Canadian degree or training": "Канадський диплом або навчання",
    "Canadian work experience": "Канадський досвід роботи",
    "Caregiving responsibilities": "Обов'язки з догляду",
    "Childcare support": "Підтримка з догляду за дітьми",
    "College certificate": "Сертифікат коледжу",
    "Credential recognition support": "Підтримка у визнанні кваліфікацій",
    "Credentials not recognized": "Кваліфікації не визнані",
    "Diploma": "Диплом",
    "Discrimination of any kind": "Дискримінація будь-якого виду",
    "Doesn’t need employment income": "Не потребує доходу від роботи",
    "Economic Immigrant": "Економічний іммігрант",
    "Employed casual (less than 10 hours/week)": "Тимчасова робота (менше 10 годин/тиждень)",
    "Employed full time (30+ hours/week)": "Повна зайнятість (30+ годин/тиждень)",
    "Employed part time (10-30 hours/week)": "Часткова зайнятість (10-30 годин/тиждень)",
    "Employment or settlement centre": "Центр працевлаштування або адаптації",
    "Family Sponsored": "Спонсорований родиною",
    "Health issues": "Проблеми зі здоров'ям",
    "Health reasons": "Причини зі здоров'ям",
    "High school diploma or equivalent": "Атестат про середню освіту або еквівалент",
    "Household responsibilities": "Домашні обов'язки",
    "Household work / Caregiver": "Домашня робота / Доглядальник",
    "I agree": "Я погоджуюсь",
    "I didn't have a work permit": "У мене не було дозволу на роботу",
    "I directly moved to Sault": "Я переїхав безпосередньо до Су",
    "I disagree": "Я не погоджуюсь",
    "Immigrant (permanent resident)": "Іммігрант (постійний резидент)",
    "Immigration issues": "Імміграційні проблеми",
    "In Canada": "У Канаді",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "Корінний народ (Перші нації, Метиси, Інуїти/Інук)",
    "International Student": "Іноземний студент",
    "Internship / volunteer experience": "Стажування / волонтерський досвід",
    "Lack of Canadian work experience": "Брак канадського досвіду роботи",
    "Lack of skills for available jobs": "Брак навичок для доступних вакансій",
    "Language barriers": "Мовні бар'єри",
    "Language support": "Мовна підтримка",
    "Limited job opportunities in preferred sector": "Обмежені можливості роботи в бажаному секторі",
    "Limited knowledge of local job market": "Обмежені знання місцевого ринку праці",
    "Limited mentorship and job-matching support": "Обмежена підтримка з менторства та підбору роботи",
    "Limited professional network": "Обмежена професійна мережа",
    "Limited suitable jobs": "Обмежена кількість відповідних вакансій",
    "Local job boards": "Місцеві дошки оголошень про роботу",
    "Local job market information": "Інформація про місцевий ринок праці",
    "Local training or certification": "Місцеве навчання або сертифікація",
    "Low wages": "Низька заробітна плата",
    "Man": "Чоловік",
    "Manitoba": "Манітоба",
    "Mentorship support": "Менторська підтримка",
    "Networking support": "Підтримка у налагодженні контактів",
    "New Brunswick": "Нью-Брансвік",
    "Newfoundland and Labrador": "Ньюфаундленд і Лабрадор",
    "No": "Ні",
    "Non-Canadian work experience not recognized": "Неканадський досвід роботи не визнано",
    "Non-binary person or other gender": "Небінарна особа або інша стать",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "Тимчасовий резидент (напр., дозвіл на роботу, дозвіл на навчання, шукач притулку)",
    "None of the above (do not select any other options)": "Жоден із перелічених (не вибирайте інші варіанти)",
    "Northwest Territories": "Північно-Західні території",
    "Not qualified for available jobs": "Немає кваліфікації для доступних вакансій",
    "Nova Scotia": "Нова Шотландія",
    "Nunavut": "Нунавут",
    "On temporary leave from a job (e.g., maternity/parental leave)": "У тимчасовій відпустці з роботи (напр., декретна або батьківська відпустка)",
    "Other": "Інше",
    "Other parts of Ontario": "Інші частини Онтаріо",
    "Outside Canada": "За межами Канади",
    "Outside of Canada": "За межами Канади",
    "Outside of Ontario but within Canada": "За межами Онтаріо, але в Канаді",
    "Personal contacts": "Особисті контакти",
    "Post-graduate degree (e.g., Master's)": "Післядипломна освіта (напр., магістр)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "Післядипломна освіта (напр., магістр, доктор філософії, M.D.)",
    "Primary school": "Початкова школа",
    "Prince Edward Island": "Острів Принца Едварда",
    "Professional network": "Професійна мережа",
    "Protected Person": "Особа під захистом",
    "Quebec": "Квебек",
    "Recognition of non-Canadian work experience": "Визнання неканадського досвіду роботи",
    "Refugee": "Біженець",
    "Refugee Claimant": "Шукач притулку",
    "Resume/interview support": "Підтримка з резюме та співбесід",
    "Retired": "На пенсії",
    "Saskatchewan": "Саскачеван",
    "Self-employed": "Самозайнятий",
    "Skills-to-job matching platform": "Платформа підбору роботи за навичками",
    "Social media (e.g., LinkedIn)": "Соціальні мережі (напр., LinkedIn)",
    "Student or recent graduate": "Студент або нещодавній випускник",
    "Temporary Foreign Worker": "Тимчасовий іноземний працівник",
    "Temporary Resident Permit Holder": "Власник тимчасового дозволу на проживання",
    "Training recommendations": "Рекомендації щодо навчання",
    "Unable to work": "Не здатний працювати",
    "Undergraduate degree": "Ступінь бакалавра",
    "Unemployed and actively looking for work": "Безробітний і активно шукає роботу",
    "Unemployed and not looking for work": "Безробітний і не шукає роботу",
    "Visible minority (e.g., South Asian, Chinese, Black)": "Видима меншина (напр., південноазіати, китайці, темношкірі)",
    "Woman": "Жінка",
    "Yes": "Так",
    "Yukon": "Юкон",
  },
  def: {
    "Family Sponsored": "Ви іммігрували, тому що член родини, який уже перебував у Канаді, вас спонсорував.",
    "Economic Immigrant": "Ви іммігрували за програмою для кваліфікованих працівників або підприємців (напр., Express Entry, Провінційна номінаційна програма).",
    "Refugee": "Ви приїхали до Канади для захисту від небезпеки у вашій рідній країні.",
    "Temporary Foreign Worker": "У Канаді за дозволом на роботу, прив'язаним до роботодавця, або за відкритим дозволом на роботу.",
    "Refugee Claimant": "Ви подали до Канади заяву про захист як біженець і очікуєте на рішення.",
    "Protected Person": "Канада вже визнала, що вам потрібен захист (затверджений статус біженця/особи під захистом).",
    "Temporary Resident Permit Holder": "Ви маєте спеціальний дозвіл на тимчасове перебування, коли зазвичай це не дозволялося б.",
    "Canadian degree or training": "Ви здобули диплом або пройшли навчальну програму в Канаді.",
    "Canadian work experience": "Ви працювали на роботодавця в Канаді.",
    "Employment or settlement centre": "Ви отримали допомогу від організації, яка підтримує тих, хто шукає роботу, або новоприбулих (напр., Sault Community Career Center).",
    "Internship / volunteer experience": "Ви здобули досвід роботи через неоплачуване стажування, короткострокову практику або волонтерство.",
    "Local job boards": "Ви користувалися вебсайтами або оголошеннями про роботу у вашому регіоні (напр., дошка вакансій AWIC).",
    "Personal contacts": "Ви отримали допомогу або інформацію про вакансії від родини, друзів чи людей, яких знаєте особисто.",
    "Professional network": "Ви користувалися контактами зі своєї професійної сфери, як-от колеги чи наставники.",
    "Recognition of non-Canadian work experience": "Ваш досвід роботи, здобутий за межами Канади, було визнано.",
    "Caregiving responsibilities": "Вам потрібно доглядати за дітьми або літніми членами родини, які залежать від вас.",
    "Credentials not recognized": "Ваша освіта, диплом або ліцензія, здобуті за межами Канади, не приймаються канадськими роботодавцями.",
    "Discrimination of any kind": "З вами повелися несправедливо через вашу расу, етнічність, релігію, стать, акцент, вік або інші особисті характеристики.",
    "Health issues": "У вас є проблеми з фізичним або психічним здоров'ям, які ускладнюють пошук чи збереження роботи.",
    "Household responsibilities": "Вам потрібно вести домашнє господарство (готувати, прибирати, керувати домом).",
    "Lack of Canadian work experience": "Роботодавці вимагають досвіду роботи в Канаді, якого у вас ще немає.",
    "Lack of skills for available jobs": "Доступні у вашому регіоні вакансії вимагають навичок або навчання, яких ви наразі не маєте.",
    "Language barriers": "Ваше володіння англійською (або французькою) ускладнює пошук роботи чи проходження співбесід.",
    "Limited job opportunities in preferred sector": "У вашому регіоні мало вакансій у вашій сфері чи галузі.",
    "Limited knowledge of local job market": "Ви не впевнені, як шукати роботу, які роботодавці наймають або як відбувається наймання у вашому регіоні.",
    "Limited mentorship and job-matching support": "У вас немає доступу до наставників чи послуг, які пов'язують вас із відповідними вакансіями.",
    "Limited professional network": "Ви знаєте небагато людей у своїй сфері, які могли б поділитися вакансіями, рекомендаціями чи порадами.",
    "Non-Canadian work experience not recognized": "Ваш досвід роботи, здобутий за межами Канади, не приймається і не цінується канадськими роботодавцями.",
    "Childcare support": "Вам потрібна допомога з доглядом за дітьми, щоб ви могли працювати.",
    "Credential recognition support": "Вам потрібна допомога, щоб вашу освіту або професійну кваліфікацію, здобуту за межами Канади, визнали.",
    "Language support": "Вам потрібна допомога у покращенні володіння англійською (або французькою).",
    "Local job market information": "Вам потрібна інформація про те, які роботодавці наймають, які вакансії доступні та які навички затребувані у вашому регіоні.",
    "Local training or certification": "Вам потрібне навчання або сертифікація, що пропонується у вашому регіоні, щоб відповідати вимогам доступних вакансій.",
    "Mentorship support": "Вам потрібен зв'язок із досвідченими людьми у вашій сфері.",
    "Networking support": "Вам потрібна допомога у знайомстві з роботодавцями та фахівцями.",
    "Resume/interview support": "Вам потрібна допомога у підготовці резюме, супровідного листа або у підготовці до співбесід.",
    "Skills-to-job matching platform": "Вам потрібна послуга чи інструмент, що зіставляє ваші навички з відповідними вакансіями.",
    "Training recommendations": "Вам потрібні поради щодо того, яке навчання чи курси пройти, щоб підвищити свої шанси знайти роботу.",
    "Doesn’t need employment income": "Вам не потрібно працювати, бо у вас є інші джерела доходу або фінансова підтримка.",
    "Health reasons": "У вас є проблеми з фізичним або психічним здоров'ям, які ускладнюють пошук чи збереження роботи.",
    "Immigration issues": "Ваш імміграційний статус або документи (напр., дозвіл на роботу, оформлення постійного проживання) не дозволяють вам працювати.",
    "Limited suitable jobs": "У вашому регіоні мало вакансій, які відповідають вашим навичкам, досвіду чи вподобанням.",
    "Low wages": "Доступні вакансії платять надто мало, щоб робота була для вас вигідною.",
    "Not qualified for available jobs": "Доступні у вашому регіоні вакансії вимагають освіти, навичок або сертифікатів, яких ви наразі не маєте.",
  },
  ui: {
    "% complete": " % завершено",
    "Back to home": "Повернутися на головну",
    "Back": "Назад",
    "Consent is required to continue": "Для продовження потрібна згода",
    "Definition:": "Визначення:",
    "Email address": "Адреса електронної пошти",
    "Finish to become a Survey Champion": "Завершіть, щоб стати Чемпіоном опитування",
    "Five $50 local gift cards drawn monthly": "П'ять місцевих подарункових карток на 50 $ розігруються щомісяця",
    "Go back": "Назад",
    "Go home": "На головну",
    "Home": "Головна",
    "Next 5 skills": "Наступні 5 навичок",
    "Next question": "Наступне запитання",
    "No matches": "Немає результатів",
    "Not sure": "Не впевнений",
    "One moment.": "Хвилинку.",
    "Previous question": "Попереднє запитання",
    "Saving your response…": "Збереження вашої відповіді…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "Виникла проблема зі з'єднанням із сервером. Ваші відповіді все ще збережені на цьому пристрої — спробуйте ще раз.",
    "Submit": "Надіслати",
    "Thank you for your time and response": "Дякуємо за ваш час і відповідь",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "Дякуємо за ваш час і відповідь. Ви зробили великий внесок у розвиток громади.",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "Дякуємо — вашу відповідь записано. Заповнювати її знову не потрібно.",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "Щоб взяти участь, вам має бути щонайменше 18 років і ви повинні погодитися на участь. Якщо бажаєте продовжити, ви можете повернутися та змінити свою відповідь.",
    "Try again": "Спробувати ще раз",
    "We couldn't save your response": "Не вдалося зберегти вашу відповідь",
    "Yes, enter me in the gift-card draw": "Так, зареєструйте мене в розіграші подарункових карток",
    "You made a great contribution to the development of the community": "Ви зробили великий внесок у розвиток громади",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "Ви відкрили персональне запрошення, тому ваше завершення може бути зафіксоване для нагадувань. Ваші відповіді зберігаються конфіденційно та аналізуються в знеособленому вигляді.",
    "You're a Survey Champion": "Ви Чемпіон опитування",
    "You've already completed this survey": "Ви вже пройшли це опитування",
    "Your responses are anonymous.": "Ваші відповіді анонімні.",
    "more — keep typing to narrow": "ще — продовжуйте вводити, щоб звузити",
    "Search or select a language": "Знайдіть або виберіть мову",
    "Type to search countries…": "Введіть, щоб знайти країну…",
    "Type to search areas of study…": "Введіть, щоб знайти галузь навчання…",
    "Type to search occupations…": "Введіть, щоб знайти професію…",
    "Type to search…": "Введіть для пошуку…",
    "Select one…": "Виберіть варіант…",
    "1 · Lowest": "1 · найнижчий",
    "5 · Highest": "5 · найвищий",
  },
};
