// DRAFT Urdu (ur) — ⚠ MACHINE-QUALITY DRAFT. Requires native-speaker review
// before release. RTL language — see the dir=rtl wiring in app.js.
module.exports = {
  q: {
    language: "جاری رکھنے کے لیے زبان منتخب کریں",
    consent: "براہ کرم تصدیق کریں کہ آپ کی عمر کم از کم 18 سال ہے اور آپ رضاکارانہ طور پر اس سروے میں حصہ لینے پر رضامند ہیں۔",
    eligible: "کیا آپ ستمبر 2021 کے بعد رہنے کے لیے شمالی اونٹاریو منتقل ہوئے؟",
    moved_from: "آپ کہاں سے منتقل ہوئے؟",
    province: "براہ کرم وہ صوبہ منتخب کریں جہاں سے آپ منتقل ہوئے",
    country_moved_from: "براہ کرم وہ ملک منتخب کریں جہاں سے آپ منتقل ہوئے",
    gender: "آپ کی جنس کیا ہے؟",
    age_group: "آپ کا عمر کا گروپ کیا ہے؟",
    identity_groups: "کیا آپ درج ذیل میں سے کسی گروپ سے تعلق رکھتے ہیں؟ تمام قابل اطلاق منتخب کریں۔",
    immigration_category: "امیگریشن کیٹیگری منتخب کریں",
    non_permanent_category: "غیر مستقل رہائشی کیٹیگری منتخب کریں",
    non_permanent_other: "براہ کرم وضاحت کریں",
    recent_credential: "آپ نے حال ہی میں کون سی تعلیمی قابلیت مکمل کی ہے؟",
    program_name: "آپ کا مطالعہ کا بنیادی شعبہ کیا تھا؟",
    program_name_other: "اپنے مطالعہ کا بنیادی شعبہ لکھیں",
    program_location: "آپ نے یہ پروگرام کہاں مکمل کیا؟",
    highest_education: "کیا یہ پروگرام آپ کی تعلیم کی اعلیٰ ترین سطح ہے؟",
    highest_credential: "آپ کی تعلیم کی اعلیٰ ترین سطح کیا ہے؟",
    highest_program_name: "اپنی تعلیم کی اعلیٰ ترین سطح کے لیے، آپ کا مطالعہ کا بنیادی شعبہ کیا تھا؟",
    highest_program_name_other: "اپنی تعلیم کی اعلیٰ ترین سطح کے لیے مطالعہ کا بنیادی شعبہ لکھیں",
    current_program: "آپ کا موجودہ تعلیمی پروگرام کیا ہے؟",
    current_program_name: "آپ کا مطالعہ کا بنیادی شعبہ کیا ہے؟",
    current_program_name_other: "اپنے مطالعہ کا بنیادی شعبہ لکھیں",
    employed_before: "کیا آپ سالٹ سٹی۔ میری منتقل ہونے سے پہلے کینیڈا میں ملازمت کرتے تھے؟",
    previous_job_title: "سالٹ سٹی۔ میری منتقل ہونے سے پہلے آپ کا آخری پیشہ کیا تھا؟",
    home_emp_before: "کیا آپ کینیڈا آنے سے پہلے اپنے آبائی ملک میں ملازمت کرتے تھے؟",
    home_country_job: "آپ کے آبائی ملک میں آپ کا آخری پیشہ کیا تھا؟",
    employment_status: "درج ذیل میں سے کون سا آپ کی موجودہ ملازمت کی حالت کو بہترین طور پر بیان کرتا ہے؟",
    current_job_title: "آپ کی موجودہ ملازمت کا عہدہ کیا ہے؟",
    intended_job: "کیا آپ کی موجودہ ملازمت وہی ہے جو آپ کرنا چاہتے تھے؟",
    intended_job_title: "آپ جو ملازمت کرنا چاہتے ہیں اس کا عہدہ کیا ہے؟",
    job_search_help: "شمالی اونٹاریو / سالٹ سٹی۔ میری میں آپ کی ملازمت کی تلاش میں درج ذیل میں سے کون سے مفید تھے؟ تمام قابل اطلاق منتخب کریں۔",
    job_search_other: "براہ کرم وضاحت کریں",
    work_barriers: "تمام قابل اطلاق رکاوٹیں منتخب کریں",
    work_barriers_other: "براہ کرم وضاحت کریں",
    work_support: "کس قسم کی مدد آپ کو مطلوبہ ملازمت حاصل کرنے میں مدد دے گی؟ تمام قابل اطلاق منتخب کریں۔",
    work_support_other: "براہ کرم وضاحت کریں",
    unemployed_intended_job: "آپ جو ملازمت کرنا چاہتے ہیں اس کا عہدہ کیا ہے؟",
    unemployed_barrier_gate: "کیا سالٹ سٹی۔ میری میں کام تلاش کرتے وقت آپ کو کسی رکاوٹ کا سامنا کرنا پڑا؟",
    unemployment_reasons: "تمام قابل اطلاق رکاوٹیں منتخب کریں",
    unemployment_reasons_other: "براہ کرم وضاحت کریں",
    not_looking_reasons: "آپ کام کیوں نہیں تلاش کر رہے؟",
    not_looking_other: "براہ کرم وضاحت کریں",
    student_working: "کیا آپ اس وقت کام کر رہے ہیں؟",
    student_current_job: "آپ کی موجودہ ملازمت کا عہدہ کیا ہے؟",
    student_job_relevant: "کیا آپ کی موجودہ ملازمت آپ کے موجودہ تعلیمی پروگرام سے متعلق ہے؟",
    student_job_help: "شمالی اونٹاریو / سالٹ سٹی۔ میری میں آپ کی ملازمت کی تلاش میں درج ذیل میں سے کون سے مفید تھے؟ تمام قابل اطلاق منتخب کریں۔",
    student_job_help_other: "براہ کرم وضاحت کریں",
    student_barrier_gate: "کیا سالٹ سٹی۔ میری میں ملازمت تلاش کرتے وقت آپ کو کسی رکاوٹ کا سامنا کرنا پڑا؟",
    student_barriers: "تمام قابل اطلاق رکاوٹیں منتخب کریں",
    student_barriers_other: "براہ کرم وضاحت کریں",
    student_support: "کس قسم کی مدد آپ کو مطلوبہ ملازمت حاصل کرنے میں مدد دے گی؟ تمام قابل اطلاق منتخب کریں۔",
    student_support_other: "براہ کرم وضاحت کریں",
    planned_intended_job: "گریجویشن کے بعد آپ جو ملازمت کرنا چاہتے ہیں اس کا عہدہ کیا ہے؟",
    skills: "آپ درج ذیل ہر مہارت کے لیے اپنی سطح کا اندازہ کیسے لگائیں گے؟",
    gift_card_draw: "کیا آپ گفٹ کارڈ ڈرا میں حصہ لینا چاہتے ہیں؟ (صرف انعامی مقاصد کے لیے)",
    "work_barrier.a": "کیا کوئی رکاوٹ ہے جو آپ کو کل وقتی کام کرنے سے روکتی ہے؟",
    "work_barrier.b": "کیا کوئی رکاوٹ ہے جو آپ کو مطلوبہ ملازمت حاصل کرنے سے روکتی ہے؟",
    "work_barrier.c": "کیا کوئی رکاوٹ ہے جو آپ کو کل وقتی کام کرنے اور مطلوبہ ملازمت کرنے سے روکتی ہے؟",
    "work_barrier.d": "کیا کوئی رکاوٹ ہے جو آپ کو کل وقتی ملازمت حاصل کرنے سے روکتی ہے؟",
    "work_barrier.e": "کیا کوئی رکاوٹ ہے جو آپ کو مطلوبہ ملازمت کرنے سے روکتی ہے؟",
  },
  help: {
    skills: "1 = سب سے کم، 2 = کم، 3 = درمیانہ، 4 = زیادہ، 5 = سب سے زیادہ، 0 = یقین نہیں",
  },
  o: {
    "85 or older": "85 یا اس سے زیادہ",
    "Advanced Diploma": "اعلیٰ ڈپلومہ",
    "Alberta": "البرٹا",
    "Apprenticeship": "اپرنٹس شپ",
    "British Columbia": "برٹش کولمبیا",
    "Canadian degree or training": "کینیڈین ڈگری یا تربیت",
    "Canadian work experience": "کینیڈین کام کا تجربہ",
    "Caregiving responsibilities": "دیکھ بھال کی ذمہ داریاں",
    "Childcare support": "بچوں کی دیکھ بھال کی مدد",
    "College certificate": "کالج سرٹیفکیٹ",
    "Credential recognition support": "قابلیت کی شناخت میں مدد",
    "Credentials not recognized": "قابلیتیں تسلیم شدہ نہیں",
    "Diploma": "ڈپلومہ",
    "Discrimination of any kind": "کسی بھی قسم کا امتیاز",
    "Doesn’t need employment income": "ملازمت کی آمدنی کی ضرورت نہیں",
    "Economic Immigrant": "معاشی تارک وطن",
    "Employed casual (less than 10 hours/week)": "عارضی ملازمت (ہفتے میں 10 گھنٹے سے کم)",
    "Employed full time (30+ hours/week)": "کل وقتی ملازمت (ہفتے میں 30+ گھنٹے)",
    "Employed part time (10-30 hours/week)": "جز وقتی ملازمت (ہفتے میں 10-30 گھنٹے)",
    "Employment or settlement centre": "روزگار یا آبادکاری مرکز",
    "Family Sponsored": "خاندان کی طرف سے اسپانسر شدہ",
    "Health issues": "صحت کے مسائل",
    "Health reasons": "صحت کی وجوہات",
    "High school diploma or equivalent": "ہائی اسکول ڈپلومہ یا مساوی",
    "Household responsibilities": "گھریلو ذمہ داریاں",
    "Household work / Caregiver": "گھریلو کام / دیکھ بھال کرنے والا",
    "I agree": "میں متفق ہوں",
    "I didn't have a work permit": "میرے پاس ورک پرمٹ نہیں تھا",
    "I directly moved to Sault": "میں براہ راست سالٹ منتقل ہوا",
    "I disagree": "میں متفق نہیں ہوں",
    "Immigrant (permanent resident)": "تارک وطن (مستقل رہائشی)",
    "Immigration issues": "امیگریشن کے مسائل",
    "In Canada": "کینیڈا میں",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "مقامی باشندے (فرسٹ نیشنز، میٹس، انوئٹ/انک)",
    "International Student": "بین الاقوامی طالب علم",
    "Internship / volunteer experience": "انٹرن شپ / رضاکارانہ تجربہ",
    "Lack of Canadian work experience": "کینیڈین کام کے تجربے کی کمی",
    "Lack of skills for available jobs": "دستیاب ملازمتوں کے لیے مہارت کی کمی",
    "Language barriers": "زبان کی رکاوٹیں",
    "Language support": "زبان کی مدد",
    "Limited job opportunities in preferred sector": "پسندیدہ شعبے میں محدود ملازمت کے مواقع",
    "Limited knowledge of local job market": "مقامی ملازمت کی منڈی کا محدود علم",
    "Limited mentorship and job-matching support": "محدود رہنمائی اور ملازمت کی مطابقت کی مدد",
    "Limited professional network": "محدود پیشہ ورانہ نیٹ ورک",
    "Limited suitable jobs": "محدود موزوں ملازمتیں",
    "Local job boards": "مقامی جاب بورڈز",
    "Local job market information": "مقامی ملازمت کی منڈی کی معلومات",
    "Local training or certification": "مقامی تربیت یا سرٹیفیکیشن",
    "Low wages": "کم اجرت",
    "Man": "مرد",
    "Manitoba": "مینیٹوبا",
    "Mentorship support": "رہنمائی کی مدد",
    "Networking support": "نیٹ ورکنگ کی مدد",
    "New Brunswick": "نیو برنزوک",
    "Newfoundland and Labrador": "نیو فاؤنڈ لینڈ اور لیبراڈور",
    "No": "نہیں",
    "Non-Canadian work experience not recognized": "غیر کینیڈین کام کا تجربہ تسلیم شدہ نہیں",
    "Non-binary person or other gender": "غیر بائنری شخص یا دیگر جنس",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "غیر مستقل رہائشی (مثلاً ورک پرمٹ، اسٹڈی پرمٹ، پناہ گزین درخواست گزار)",
    "None of the above (do not select any other options)": "مندرجہ بالا میں سے کوئی نہیں (کوئی اور آپشن منتخب نہ کریں)",
    "Northwest Territories": "شمال مغربی علاقے",
    "Not qualified for available jobs": "دستیاب ملازمتوں کے لیے اہل نہیں",
    "Nova Scotia": "نووا اسکوشیا",
    "Nunavut": "نوناوت",
    "On temporary leave from a job (e.g., maternity/parental leave)": "ملازمت سے عارضی چھٹی پر (مثلاً زچگی/والدین کی چھٹی)",
    "Other": "دیگر",
    "Other parts of Ontario": "اونٹاریو کے دیگر حصے",
    "Outside Canada": "کینیڈا سے باہر",
    "Outside of Canada": "کینیڈا سے باہر",
    "Outside of Ontario but within Canada": "اونٹاریو سے باہر لیکن کینیڈا کے اندر",
    "Personal contacts": "ذاتی رابطے",
    "Post-graduate degree (e.g., Master's)": "پوسٹ گریجویٹ ڈگری (مثلاً ماسٹرز)",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "پوسٹ گریجویٹ ڈگری (مثلاً ماسٹرز، پی ایچ ڈی، ایم ڈی)",
    "Primary school": "پرائمری اسکول",
    "Prince Edward Island": "پرنس ایڈورڈ آئی لینڈ",
    "Professional network": "پیشہ ورانہ نیٹ ورک",
    "Protected Person": "محفوظ شخص",
    "Quebec": "کیوبیک",
    "Recognition of non-Canadian work experience": "غیر کینیڈین کام کے تجربے کی شناخت",
    "Refugee": "پناہ گزین",
    "Refugee Claimant": "پناہ گزین درخواست گزار",
    "Resume/interview support": "ریزیومے/انٹرویو کی مدد",
    "Retired": "ریٹائرڈ",
    "Saskatchewan": "ساسکاچیوان",
    "Self-employed": "خود روزگار",
    "Skills-to-job matching platform": "مہارت سے ملازمت کی مطابقت کا پلیٹ فارم",
    "Social media (e.g., LinkedIn)": "سوشل میڈیا (مثلاً لنکڈان)",
    "Student or recent graduate": "طالب علم یا حالیہ گریجویٹ",
    "Temporary Foreign Worker": "عارضی غیر ملکی کارکن",
    "Temporary Resident Permit Holder": "عارضی رہائشی پرمٹ رکھنے والا",
    "Training recommendations": "تربیتی سفارشات",
    "Unable to work": "کام کرنے سے قاصر",
    "Undergraduate degree": "انڈر گریجویٹ ڈگری",
    "Unemployed and actively looking for work": "بے روزگار اور فعال طور پر کام کی تلاش میں",
    "Unemployed and not looking for work": "بے روزگار اور کام کی تلاش میں نہیں",
    "Visible minority (e.g., South Asian, Chinese, Black)": "نمایاں اقلیت (مثلاً جنوبی ایشیائی، چینی، سیاہ فام)",
    "Woman": "عورت",
    "Yes": "ہاں",
    "Yukon": "یوکون",
  },
  def: {
    "Family Sponsored": "آپ نے ہجرت کی کیونکہ کینیڈا میں پہلے سے موجود خاندان کے کسی فرد نے آپ کو اسپانسر کیا۔",
    "Economic Immigrant": "آپ نے ہنر مند کارکن یا کاروباری پروگرام کے ذریعے ہجرت کی (مثلاً Express Entry، صوبائی نامزدگی پروگرام)۔",
    "Refugee": "آپ اپنے آبائی ملک میں خطرے سے تحفظ کے لیے کینیڈا آئے۔",
    "Temporary Foreign Worker": "کسی آجر سے منسلک ورک پرمٹ یا کھلے ورک پرمٹ پر کینیڈا میں۔",
    "Refugee Claimant": "آپ نے کینیڈا سے پناہ گزین تحفظ کی درخواست دی ہے اور فیصلے کا انتظار کر رہے ہیں۔",
    "Protected Person": "کینیڈا نے پہلے ہی تسلیم کر لیا ہے کہ آپ کو تحفظ کی ضرورت ہے (منظور شدہ پناہ گزین/محفوظ حیثیت)۔",
    "Temporary Resident Permit Holder": "آپ کے پاس عارضی طور پر رہنے کا خصوصی پرمٹ ہے جب عام طور پر اجازت نہ ہو۔",
    "Canadian degree or training": "آپ نے کینیڈا میں کوئی ڈگری یا تربیتی پروگرام مکمل کیا ہے۔",
    "Canadian work experience": "آپ نے کینیڈا میں کسی آجر کے لیے کام کیا ہے۔",
    "Employment or settlement centre": "آپ کو ایسی تنظیم سے مدد ملی جو ملازمت کے متلاشیوں یا نئے آنے والوں کی معاونت کرتی ہے (مثلاً Sault Community Career Center)۔",
    "Internship / volunteer experience": "آپ نے بلامعاوضہ انٹرن شپ، قلیل مدتی تقرری یا رضاکارانہ کام کے ذریعے تجربہ حاصل کیا۔",
    "Local job boards": "آپ نے ایسی ویب سائٹس یا اشتہارات استعمال کیے جو آپ کے علاقے میں ملازمتوں کی تشہیر کرتے ہیں (مثلاً AWIC جاب بورڈ)۔",
    "Personal contacts": "آپ کو خاندان، دوستوں یا ذاتی طور پر جاننے والوں سے مدد یا ملازمت کی معلومات ملیں۔",
    "Professional network": "آپ نے اپنے شعبے کے رابطے استعمال کیے، جیسے ساتھی کارکن یا رہنما۔",
    "Recognition of non-Canadian work experience": "کینیڈا سے باہر حاصل کردہ آپ کا کام کا تجربہ تسلیم کیا گیا۔",
    "Caregiving responsibilities": "آپ کو ایسے بچوں یا بزرگ خاندانی افراد کی دیکھ بھال کرنی پڑتی ہے جو آپ پر انحصار کرتے ہیں۔",
    "Credentials not recognized": "کینیڈا سے باہر کی آپ کی تعلیم، ڈگری یا لائسنس کینیڈین آجروں کے ہاں قبول نہیں کیا جاتا۔",
    "Discrimination of any kind": "آپ کے ساتھ آپ کی نسل، نسلی پس منظر، مذہب، جنس، لہجے، عمر یا دیگر ذاتی خصوصیات کی وجہ سے ناانصافی ہوئی۔",
    "Health issues": "آپ کو جسمانی یا ذہنی صحت کے مسائل ہیں جن کی وجہ سے ملازمت ڈھونڈنا یا برقرار رکھنا مشکل ہو جاتا ہے۔",
    "Household responsibilities": "آپ کو گھریلو کام (کھانا پکانا، صفائی، گھر چلانا) سنبھالنے پڑتے ہیں۔",
    "Lack of Canadian work experience": "آجر کینیڈا میں کام کا تجربہ مانگتے ہیں، جو آپ کے پاس ابھی نہیں ہے۔",
    "Lack of skills for available jobs": "آپ کے علاقے میں دستیاب ملازمتوں کے لیے ایسی مہارتیں یا تربیت درکار ہے جو آپ کے پاس فی الحال نہیں۔",
    "Language barriers": "آپ کی انگریزی (یا فرانسیسی) کی مہارت کام ڈھونڈنا یا انٹرویو پاس کرنا مشکل بنا دیتی ہے۔",
    "Limited job opportunities in preferred sector": "آپ کے علاقے میں آپ کے شعبے یا صنعت میں بہت کم ملازمتیں ہیں۔",
    "Limited knowledge of local job market": "آپ کو یقین نہیں کہ ملازمت کیسے ڈھونڈی جائے، کون سے آجر بھرتی کر رہے ہیں، یا آپ کے علاقے میں بھرتی کیسے ہوتی ہے۔",
    "Limited mentorship and job-matching support": "آپ کو ایسے رہنماؤں یا خدمات تک رسائی نہیں جو آپ کو موزوں ملازمتوں سے جوڑیں۔",
    "Limited professional network": "آپ اپنے شعبے میں ایسے کم لوگوں کو جانتے ہیں جو ملازمت کی معلومات، سفارش یا مشورہ دے سکیں۔",
    "Non-Canadian work experience not recognized": "کینیڈا سے باہر حاصل کردہ آپ کا کام کا تجربہ کینیڈین آجر تسلیم یا قدر نہیں کرتے۔",
    "Childcare support": "کام کر سکنے کے لیے آپ کو اپنے بچوں کی دیکھ بھال میں مدد چاہیے۔",
    "Credential recognition support": "کینیڈا سے باہر کی اپنی تعلیم یا پیشہ ورانہ اہلیت کو تسلیم کروانے کے لیے آپ کو مدد چاہیے۔",
    "Language support": "آپ کو اپنی انگریزی (یا فرانسیسی) بہتر بنانے کے لیے مدد چاہیے۔",
    "Local job market information": "آپ کو معلومات چاہیے کہ کون سے آجر بھرتی کر رہے ہیں، کون سی ملازمتیں دستیاب ہیں، اور آپ کے علاقے میں کن مہارتوں کی مانگ ہے۔",
    "Local training or certification": "دستیاب ملازمتوں کے اہل ہونے کے لیے آپ کو اپنے علاقے میں دی جانے والی تربیت یا سرٹیفیکیشن چاہیے۔",
    "Mentorship support": "آپ کو اپنے شعبے کے تجربہ کار لوگوں سے رابطہ چاہیے۔",
    "Networking support": "آپ کو آجروں اور پیشہ ور افراد سے ملنے میں مدد چاہیے۔",
    "Resume/interview support": "آپ کو اپنا ریزیومے، کور لیٹر تیار کرنے یا انٹرویو کی مشق میں مدد چاہیے۔",
    "Skills-to-job matching platform": "آپ کو ایسی خدمت یا آلہ چاہیے جو آپ کی مہارتوں کو موزوں ملازمتوں سے ملائے۔",
    "Training recommendations": "آپ کو تجاویز چاہیے کہ ملازمت ملنے کے مواقع بہتر بنانے کے لیے کون سی تربیت یا کورس کریں۔",
    "Doesn’t need employment income": "آپ کو کام کرنے کی ضرورت نہیں کیونکہ آپ کے پاس آمدنی کے دیگر ذرائع یا مالی معاونت ہے۔",
    "Health reasons": "آپ کو جسمانی یا ذہنی صحت کے مسائل ہیں جن کی وجہ سے ملازمت ڈھونڈنا یا برقرار رکھنا مشکل ہو جاتا ہے۔",
    "Immigration issues": "آپ کی امیگریشن حیثیت یا دستاویزات (مثلاً ورک پرمٹ، پی آر کی کارروائی) آپ کو کام کرنے سے روکتی ہیں۔",
    "Limited suitable jobs": "آپ کے علاقے میں ایسی بہت کم ملازمتیں ہیں جو آپ کی مہارتوں، تجربے یا ترجیحات سے میل کھاتی ہوں۔",
    "Low wages": "دستیاب ملازمتیں اتنی کم اجرت دیتی ہیں کہ آپ کے لیے کام کرنا فائدہ مند نہیں رہتا۔",
    "Not qualified for available jobs": "آپ کے علاقے میں دستیاب ملازمتوں کے لیے ایسی تعلیم، مہارتیں یا سرٹیفیکیشن درکار ہیں جو آپ کے پاس فی الحال نہیں۔",
  },
  ui: {
    "% complete": "٪ مکمل",
    "Back to home": "ہوم پر واپس جائیں",
    "Back": "واپس",
    "Consent is required to continue": "جاری رکھنے کے لیے رضامندی ضروری ہے",
    "Definition:": "تعریف:",
    "Email address": "ای میل ایڈریس",
    "Finish to become a Survey Champion": "سروے چیمپئن بننے کے لیے مکمل کریں",
    "Five $50 local gift cards drawn monthly": "ہر ماہ 50 ڈالر کے پانچ مقامی گفٹ کارڈ نکالے جاتے ہیں",
    "Go back": "واپس جائیں",
    "Go home": "ہوم پر جائیں",
    "Home": "ہوم",
    "Next 5 skills": "اگلی 5 مہارتیں",
    "Next question": "اگلا سوال",
    "No matches": "کوئی نتیجہ نہیں",
    "Not sure": "یقین نہیں",
    "One moment.": "ایک لمحہ۔",
    "Previous question": "پچھلا سوال",
    "Saving your response…": "آپ کا جواب محفوظ کیا جا رہا ہے…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "سرور سے رابطے میں مسئلہ پیش آیا۔ آپ کے جوابات اب بھی اس ڈیوائس پر محفوظ ہیں — براہ کرم دوبارہ کوشش کریں۔",
    "Submit": "جمع کرائیں",
    "Thank you for your time and response": "آپ کے وقت اور جواب کے لیے شکریہ",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "آپ کے وقت اور جواب کے لیے شکریہ۔ آپ نے کمیونٹی کی ترقی میں بڑا حصہ ڈالا۔",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "شکریہ — آپ کا جواب ریکارڈ کر لیا گیا ہے۔ اسے دوبارہ بھرنے کی ضرورت نہیں۔",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "حصہ لینے کے لیے، آپ کی عمر کم از کم 18 سال ہونی چاہیے اور آپ کو شرکت پر رضامند ہونا چاہیے۔ اگر آپ جاری رکھنا چاہتے ہیں، تو آپ واپس جا کر اپنا جواب تبدیل کر سکتے ہیں۔",
    "Try again": "دوبارہ کوشش کریں",
    "We couldn't save your response": "ہم آپ کا جواب محفوظ نہیں کر سکے",
    "Yes, enter me in the gift-card draw": "ہاں، مجھے گفٹ کارڈ ڈرا میں شامل کریں",
    "You made a great contribution to the development of the community": "آپ نے کمیونٹی کی ترقی میں بڑا حصہ ڈالا",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "آپ نے ذاتی دعوتی لنک کھولا ہے، اس لیے یاد دہانی کے مقاصد کے لیے آپ کی تکمیل ریکارڈ کی جا سکتی ہے۔ آپ کے جوابات خفیہ رکھے جاتے ہیں اور شناخت کے بغیر تجزیہ کیے جاتے ہیں۔",
    "You're a Survey Champion": "آپ سروے چیمپئن ہیں",
    "You've already completed this survey": "آپ پہلے ہی یہ سروے مکمل کر چکے ہیں",
    "Your responses are anonymous.": "آپ کے جوابات گمنام ہیں۔",
    "more — keep typing to narrow": "مزید — محدود کرنے کے لیے ٹائپ کرتے رہیں",
    "Search or select a language": "زبان تلاش کریں یا منتخب کریں",
    "Type to search countries…": "ملک تلاش کرنے کے لیے ٹائپ کریں…",
    "Type to search areas of study…": "مطالعہ کا شعبہ تلاش کرنے کے لیے ٹائپ کریں…",
    "Type to search occupations…": "پیشہ تلاش کرنے کے لیے ٹائپ کریں…",
    "Type to search…": "تلاش کے لیے ٹائپ کریں…",
    "Select one…": "ایک منتخب کریں…",
    "1 · Lowest": "1 · سب سے کم",
    "5 · Highest": "5 · سب سے زیادہ",
  },
};
