// DRAFT Mandarin / Simplified Chinese (zh) — ⚠ MACHINE-QUALITY DRAFT. Requires
// native-speaker review before release. Keyed to exact source strings.
module.exports = {
  q: {
    language: "选择语言以继续",
    consent: "请确认您已年满18岁，并自愿同意参加本调查。",
    eligible: "您是否在2021年9月之后搬到安大略省北部居住？",
    moved_from: "您从哪里搬来？",
    province: "请选择您搬离的省份",
    country_moved_from: "请选择您搬离的国家",
    gender: "您的性别是什么？",
    age_group: "您的年龄段是什么？",
    identity_groups: "您认同以下任何群体吗？请选择所有适用项。",
    immigration_category: "选择移民类别",
    non_permanent_category: "选择非永久居民类别",
    non_permanent_other: "请说明",
    recent_credential: "您最近完成的学历是什么？",
    program_name: "您的主要学习领域是什么？",
    program_name_other: "请输入您的主要学习领域",
    program_location: "您在哪里完成这个课程？",
    highest_education: "这个课程是您的最高学历吗？",
    highest_credential: "您的最高学历是什么？",
    highest_program_name: "对于您的最高学历，您的主要学习领域是什么？",
    highest_program_name_other: "请输入您最高学历的主要学习领域",
    current_program: "您目前的学习课程是什么？",
    current_program_name: "您的主要学习领域是什么？",
    current_program_name_other: "请输入您的主要学习领域",
    employed_before: "在搬到苏圣玛丽之前，您在加拿大有工作吗？",
    previous_job_title: "在搬到苏圣玛丽之前，您最后的职业是什么？",
    home_emp_before: "在来加拿大之前，您在祖国有工作吗？",
    home_country_job: "您在祖国的最后一份职业是什么？",
    employment_status: "以下哪一项最能描述您目前的就业状况？",
    current_job_title: "您目前工作的职位名称是什么？",
    intended_job: "您目前的工作是您想要从事的工作吗？",
    intended_job_title: "您想要从事的工作职位名称是什么？",
    job_search_help: "在安大略省北部／苏圣玛丽求职过程中，以下哪些对您有帮助？请选择所有适用项。",
    job_search_other: "请说明",
    work_barriers: "请选择所有适用的障碍",
    work_barriers_other: "请说明",
    work_support: "哪种类型的支持能帮助您获得理想的工作？请选择所有适用项。",
    work_support_other: "请说明",
    unemployed_intended_job: "您想要从事的工作职位名称是什么？",
    unemployed_barrier_gate: "在苏圣玛丽找工作时，您是否遇到过任何障碍？",
    unemployment_reasons: "请选择所有适用的障碍",
    unemployment_reasons_other: "请说明",
    not_looking_reasons: "您为什么不找工作？",
    not_looking_other: "请说明",
    student_working: "您目前在工作吗？",
    student_current_job: "您目前工作的职位名称是什么？",
    student_job_relevant: "您目前的工作与您当前的学习课程相关吗？",
    student_job_help: "在安大略省北部／苏圣玛丽求职过程中，以下哪些对您有帮助？请选择所有适用项。",
    student_job_help_other: "请说明",
    student_barrier_gate: "在苏圣玛丽找工作时，您是否遇到过任何障碍？",
    student_barriers: "请选择所有适用的障碍",
    student_barriers_other: "请说明",
    student_support: "哪种类型的支持能帮助您获得理想的工作？请选择所有适用项。",
    student_support_other: "请说明",
    planned_intended_job: "毕业后您想从事的工作职位名称是什么？",
    skills: "您如何评价自己在以下每项技能上的水平？",
    gift_card_draw: "您想参加礼品卡抽奖吗？（仅用于奖品目的）",
    "work_barrier.a": "是否有障碍阻止您从事全职工作？",
    "work_barrier.b": "是否有障碍阻止您获得理想的工作？",
    "work_barrier.c": "是否有障碍阻止您从事全职工作以及您理想的工作？",
    "work_barrier.d": "是否有障碍阻止您获得一份全职工作？",
    "work_barrier.e": "是否有障碍阻止您从事理想的工作？",
  },
  help: {
    skills: "1 = 最低，2 = 低，3 = 中等，4 = 高，5 = 最高，0 = 不确定",
  },
  o: {
    "85 or older": "85岁或以上",
    "Advanced Diploma": "高级文凭",
    "Alberta": "艾伯塔省",
    "Apprenticeship": "学徒培训",
    "British Columbia": "不列颠哥伦比亚省",
    "Canadian degree or training": "加拿大学位或培训",
    "Canadian work experience": "加拿大工作经验",
    "Caregiving responsibilities": "照护责任",
    "Childcare support": "育儿支持",
    "College certificate": "学院证书",
    "Credential recognition support": "学历认证支持",
    "Credentials not recognized": "学历未获认可",
    "Diploma": "文凭",
    "Discrimination of any kind": "任何形式的歧视",
    "Doesn’t need employment income": "不需要工作收入",
    "Economic Immigrant": "经济类移民",
    "Employed casual (less than 10 hours/week)": "临时工作（每周少于10小时）",
    "Employed full time (30+ hours/week)": "全职工作（每周30小时以上）",
    "Employed part time (10-30 hours/week)": "兼职工作（每周10-30小时）",
    "Employment or settlement centre": "就业或安置中心",
    "Family Sponsored": "家庭担保",
    "Health issues": "健康问题",
    "Health reasons": "健康原因",
    "High school diploma or equivalent": "高中文凭或同等学历",
    "Household responsibilities": "家庭责任",
    "Household work / Caregiver": "家务／照护者",
    "I agree": "我同意",
    "I didn't have a work permit": "我没有工作许可",
    "I directly moved to Sault": "我直接搬到了苏圣玛丽",
    "I disagree": "我不同意",
    "Immigrant (permanent resident)": "移民（永久居民）",
    "Immigration issues": "移民问题",
    "In Canada": "在加拿大",
    "Indigenous (First Nations, Métis, Inuit/Inuk)": "原住民（第一民族、梅蒂斯人、因纽特人）",
    "International Student": "国际学生",
    "Internship / volunteer experience": "实习／志愿服务经验",
    "Lack of Canadian work experience": "缺乏加拿大工作经验",
    "Lack of skills for available jobs": "缺乏现有职位所需技能",
    "Language barriers": "语言障碍",
    "Language support": "语言支持",
    "Limited job opportunities in preferred sector": "理想行业的工作机会有限",
    "Limited knowledge of local job market": "对当地就业市场了解有限",
    "Limited mentorship and job-matching support": "导师指导和工作匹配支持有限",
    "Limited professional network": "职业人脉有限",
    "Limited suitable jobs": "合适的工作有限",
    "Local job boards": "本地招聘网站",
    "Local job market information": "本地就业市场信息",
    "Local training or certification": "本地培训或认证",
    "Low wages": "工资低",
    "Man": "男性",
    "Manitoba": "马尼托巴省",
    "Mentorship support": "导师指导支持",
    "Networking support": "人脉拓展支持",
    "New Brunswick": "新不伦瑞克省",
    "Newfoundland and Labrador": "纽芬兰与拉布拉多省",
    "No": "否",
    "Non-Canadian work experience not recognized": "非加拿大工作经验未获认可",
    "Non-binary person or other gender": "非二元性别者或其他性别",
    "Non-permanent resident (e.g., work permit, study permit, refugee claimant)": "非永久居民（如工作许可、学习许可、难民申请人）",
    "None of the above (do not select any other options)": "以上皆非（请勿选择其他选项）",
    "Northwest Territories": "西北地区",
    "Not qualified for available jobs": "不符合现有职位的资格",
    "Nova Scotia": "新斯科舍省",
    "Nunavut": "努纳武特地区",
    "On temporary leave from a job (e.g., maternity/parental leave)": "暂时休假中（如产假／育儿假）",
    "Other": "其他",
    "Other parts of Ontario": "安大略省其他地区",
    "Outside Canada": "加拿大境外",
    "Outside of Canada": "加拿大境外",
    "Outside of Ontario but within Canada": "安大略省以外但在加拿大境内",
    "Personal contacts": "个人人脉",
    "Post-graduate degree (e.g., Master's)": "研究生学位（如硕士）",
    "Post-graduate degree (e.g., Master's, PhD, MD)": "研究生学位（如硕士、博士、医学博士）",
    "Primary school": "小学",
    "Prince Edward Island": "爱德华王子岛省",
    "Professional network": "职业人脉",
    "Protected Person": "受保护人士",
    "Quebec": "魁北克省",
    "Recognition of non-Canadian work experience": "非加拿大工作经验的认可",
    "Refugee": "难民",
    "Refugee Claimant": "难民申请人",
    "Resume/interview support": "简历／面试支持",
    "Retired": "已退休",
    "Saskatchewan": "萨斯喀彻温省",
    "Self-employed": "自雇",
    "Skills-to-job matching platform": "技能与工作匹配平台",
    "Social media (e.g., LinkedIn)": "社交媒体（如领英）",
    "Student or recent graduate": "学生或应届毕业生",
    "Temporary Foreign Worker": "临时外国劳工",
    "Temporary Resident Permit Holder": "临时居民许可持有人",
    "Training recommendations": "培训建议",
    "Unable to work": "无法工作",
    "Undergraduate degree": "本科学位",
    "Unemployed and actively looking for work": "失业并积极求职",
    "Unemployed and not looking for work": "失业且不求职",
    "Visible minority (e.g., South Asian, Chinese, Black)": "可见少数族裔（如南亚裔、华裔、黑人）",
    "Woman": "女性",
    "Yes": "是",
    "Yukon": "育空地区",
  },
  def: {
    "Family Sponsored": "您移民是因为已在加拿大的家庭成员担保了您。",
    "Economic Immigrant": "您通过技术工人或商业项目移民（如快速通道、省提名计划）。",
    "Refugee": "您来到加拿大是为了躲避祖国的危险以寻求保护。",
    "Temporary Foreign Worker": "持有与雇主绑定的工作许可或开放式工作许可在加拿大。",
    "Refugee Claimant": "您已向加拿大申请难民保护，正在等待决定。",
    "Protected Person": "加拿大已经认定您需要保护（已批准的难民／受保护身份）。",
    "Temporary Resident Permit Holder": "您持有特殊许可，可在通常不被允许的情况下临时居留。",
    "Canadian degree or training": "您在加拿大完成了学位或培训课程。",
    "Canadian work experience": "您曾在加拿大为雇主工作过。",
    "Employment or settlement centre": "您得到了支持求职者或新移民的机构的帮助（如 Sault Community Career Center）。",
    "Internship / volunteer experience": "您通过无薪实习、短期工作安排或志愿服务获得了工作经验。",
    "Local job boards": "您使用了发布本地招聘信息的网站或公告（如 AWIC 招聘板）。",
    "Personal contacts": "您从家人、朋友或您个人认识的人那里获得了帮助或工作线索。",
    "Professional network": "您利用了本行业的人脉，例如同事或导师。",
    "Recognition of non-Canadian work experience": "您在加拿大境外获得的工作经验被认可了。",
    "Caregiving responsibilities": "您需要照顾依赖您的儿童或年长家人。",
    "Credentials not recognized": "您在加拿大境外获得的教育、学位或执照不被加拿大雇主认可。",
    "Discrimination of any kind": "您因种族、族裔、宗教、性别、口音、年龄或其他个人特征而受到不公平对待。",
    "Health issues": "您有身体或心理健康问题，使得找工作或保住工作更加困难。",
    "Household responsibilities": "您需要操持家务（做饭、打扫、管理家庭）。",
    "Lack of Canadian work experience": "雇主要求在加拿大的工作经验，而您尚未具备。",
    "Lack of skills for available jobs": "您所在地区的现有职位需要您目前不具备的技能或培训。",
    "Language barriers": "您的英语（或法语）水平使得找工作或通过面试更加困难。",
    "Limited job opportunities in preferred sector": "您所在地区在您的专业领域或行业中职位很少。",
    "Limited knowledge of local job market": "您不清楚如何找工作、哪些雇主在招聘，或您所在地区的招聘流程如何运作。",
    "Limited mentorship and job-matching support": "您无法获得能将您与合适职位对接的导师或服务。",
    "Limited professional network": "您在本行业认识的、能提供职位线索、推荐或建议的人很少。",
    "Non-Canadian work experience not recognized": "您在加拿大境外获得的工作经验不被加拿大雇主认可或重视。",
    "Childcare support": "您需要照顾孩子方面的帮助，以便能够工作。",
    "Credential recognition support": "您需要帮助，使您在加拿大境外获得的教育或专业资格获得认可。",
    "Language support": "您需要帮助提高英语（或法语）水平。",
    "Local job market information": "您需要了解哪些雇主在招聘、有哪些职位空缺，以及您所在地区需要哪些技能。",
    "Local training or certification": "您需要本地提供的培训或认证，以符合现有职位的要求。",
    "Mentorship support": "您需要与本行业的资深人士建立联系。",
    "Networking support": "您需要帮助去结识雇主和专业人士。",
    "Resume/interview support": "您需要帮助准备简历、求职信，或练习面试。",
    "Skills-to-job matching platform": "您需要能将您的技能与合适职位空缺相匹配的服务或工具。",
    "Training recommendations": "您需要关于参加哪些培训或课程的建议，以提高求职成功的机会。",
    "Doesn’t need employment income": "您不需要工作，因为您有其他收入来源或经济支持。",
    "Health reasons": "您有身体或心理健康问题，使得找工作或保住工作更加困难。",
    "Immigration issues": "您的移民身份或证件（如工作许可、永久居民申请处理中）使您无法工作。",
    "Limited suitable jobs": "您所在地区符合您技能、经验或意愿的职位很少。",
    "Low wages": "现有职位薪酬太低，对您来说工作并不划算。",
    "Not qualified for available jobs": "您所在地区的现有职位需要您目前不具备的教育、技能或认证。",
  },
  ui: {
    "% complete": "% 已完成",
    "Back to home": "返回首页",
    "Back": "返回",
    "Consent is required to continue": "需要同意才能继续",
    "Definition:": "定义：",
    "Email address": "电子邮件地址",
    "Finish to become a Survey Champion": "完成即可成为调查之星",
    "Five $50 local gift cards drawn monthly": "每月抽出五张50加元的本地礼品卡",
    "Go back": "返回",
    "Go home": "返回首页",
    "Halfway there": "已完成一半",
    "Home": "首页",
    "Next 5 skills": "下5项技能",
    "Next question": "下一题",
    "No matches": "无匹配结果",
    "Not sure": "不确定",
    "One moment.": "请稍候。",
    "Previous question": "上一题",
    "Saving your response…": "正在保存您的回答…",
    "Something went wrong reaching the server. Your answers are still saved on this device — please try again.": "连接服务器时出现问题。您的回答仍保存在此设备上——请重试。",
    "Submit": "提交",
    "Thank you for sharing your experience.": "感谢您分享您的经历。",
    "Thank you for your time and response": "感谢您的时间和回答",
    "Thank you for your time and response. You made a great contribution to the development of the community.": "感谢您的时间和回答。您为社区发展做出了重大贡献。",
    "Thank you — your response has been recorded. There's no need to fill it out again.": "谢谢——您的回答已记录。无需再次填写。",
    "To take part, you must be at least 18 years old and agree to participate. If you'd like to continue, you can go back and change your answer.": "参加本调查，您必须年满18岁并同意参与。如果您希望继续，可以返回并更改您的答案。",
    "Try again": "重试",
    "We couldn't save your response": "我们无法保存您的回答",
    "Yes, enter me in the gift-card draw": "是的，请让我参加礼品卡抽奖",
    "You made a great contribution to the development of the community": "您为社区发展做出了重大贡献",
    "You opened a personal invitation link, so your completion may be recorded for reminder purposes. Your responses are kept confidential and analyzed in de-identified form.": "您打开了个人邀请链接，因此您的完成情况可能会被记录以用于提醒。您的回答将被保密，并以去标识化的形式进行分析。",
    "You're a Survey Champion": "您是调查之星",
    "You've already completed this survey": "您已经完成了本调查",
    "Your responses are anonymous.": "您的回答是匿名的。",
    "more — keep typing to narrow": "更多——继续输入以缩小范围",
    "Search or select a language": "搜索或选择语言",
    "Type to search countries…": "输入以搜索国家…",
    "Type to search areas of study…": "输入以搜索学习领域…",
    "Type to search occupations…": "输入以搜索职业…",
    "Type to search…": "输入以搜索…",
    "Select one…": "请选择一项…",
    "1 · Lowest": "1 · 最低",
    "5 · Highest": "5 · 最高",
  },
};
